radio/src/gui/colorlcd/draw_functions.cpp

Change the animation so all the bars are shown at the start and then removed until empty.
Matches 212x64 B&W shutdown animation.

fix(color): Reverse direction of color shutdown animation.

---

radio/src/targets/taranis/board.h

This fix offset on batt measurement, fixing thereby the number of led on during charging

fix: inaccurate Batt measurement on T20

---

radio/src/gui/colorlcd/draw_functions.cpp
radio/src/sdcard.h

With this PR, by including a custom `shutdown.png` on SD card `\IMAGES` subfolder, a custom shutdown image will be displayed while powering off the radio.
Example video below uses following `shutdown.png`:
Result (click on image below to start video): 
[![Final video of fixing issues in your code in VS Code](https://img.youtube.com/vi/kNuXOPtfEqs/0.jpg)](https://www.youtube.com/watch?v=kNuXOPtfEqs)

feat(color): Show custom image during shutdown if present

---

radio/src/gui/colorlcd/model_telemetry.cpp

Fixes #4095 
- Limit width of number edit boxes for 'id' and 'instance' fields to prevent overlap.

fix(radio): Fix size of fields on sensor edit page for portrait layout

---

radio/src/CMakeLists.txt
radio/src/gui/128x64/gui.h
radio/src/gui/128x64/model_mix_edit.cpp
radio/src/gui/212x64/gui.h
radio/src/gui/212x64/model_mix_edit.cpp
radio/src/gui/colorlcd/menus.h
radio/src/gui/colorlcd/mixer_edit.cpp
radio/src/gui/colorlcd/mixer_edit_adv.cpp
radio/src/gui/colorlcd/model_mixes.cpp
radio/src/gui/common/stdlcd/model_mixes.cpp
radio/src/gui/gui_common.cpp
radio/src/lua/api_model.cpp
radio/src/mixer.cpp
radio/src/mixes.cpp
radio/src/mixes.h
radio/src/model_init.cpp
radio/src/opentx.cpp
radio/src/opentx.h
radio/src/storage/storage_common.cpp

fix: better iteration through mixers on display

---

radio/src/logs.cpp

fix: Deactivate logs and close log file if USB is connected

---

radio/src/targets/common/arm/stm32/stm32_adc.cpp

- fixes usage of 18 or more ADC channels
- enables clocks for DMAs used by the ADC

fix: ADC DMA clock enable and inhibit mask for internal channels

---

radio/src/gui/colorlcd/widgets/text.cpp
radio/src/translations.cpp
radio/src/translations.h
radio/src/translations/cn.h
radio/src/translations/cz.h
radio/src/translations/da.h
radio/src/translations/de.h
radio/src/translations/en.h
radio/src/translations/es.h
radio/src/translations/fi.h
radio/src/translations/fr.h
radio/src/translations/he.h
radio/src/translations/it.h
radio/src/translations/jp.h
radio/src/translations/nl.h
radio/src/translations/pl.h
radio/src/translations/pt.h
radio/src/translations/tw.h

Adds text alignment option for the text widget.
Here the results, as tested with TX16S simulator:
Translators, please double check the translation TR_ALIGNMENT - thanks!

feat(color): Add alignment option for text widget

---

radio/src/telemetry/flysky_ibus.cpp

Update code to populate single sensor GPS with Lat/Long together
Fixes #4062
Code is safe to be released with 2.9.1
This is for FlySky_IBUS protocol.
The original code was poulating GPS latitude and longitude in two instances of the "GPS" sensor. The bug fix asked to give them a different name (GLat.GLon), but the standard in many other protocols in EdgeTX is to have both in a single sensor.
It is displayed correctly in the UI and Widgets. Also the logs will inteact properly with goggle maps.
**Testing:**
Since i don't have that sensor, worked together with the bug reporter by providing firmware with the changes for him to test for me. After a few iteration, we got it right!!

fix(ibus): Separate lat long sensors merged to single GPS sensor

---

radio/src/globals.h
radio/src/haptic.cpp
radio/src/opentx.cpp
radio/src/opentx.h
radio/src/sbus.cpp
radio/src/targets/common/arm/stm32/bootloader/CMakeLists.txt
radio/src/targets/common/arm/stm32/bootloader/boot.cpp
radio/src/targets/common/arm/stm32/heartbeat_driver.cpp
radio/src/targets/common/arm/stm32/mixer_scheduler_driver.cpp
radio/src/targets/common/arm/stm32/stm32_timer.cpp
radio/src/targets/common/arm/stm32/timers_driver.cpp
radio/src/targets/common/arm/stm32/timers_driver.h
radio/src/targets/horus/board.cpp
radio/src/targets/horus/hal.h
radio/src/targets/nv14/board.cpp
radio/src/targets/nv14/hal.h
radio/src/targets/simu/CMakeLists.txt
radio/src/targets/simu/timers_driver.cpp
radio/src/targets/taranis/board.cpp
radio/src/targets/taranis/hal.h
radio/src/tasks/mixer_task.cpp

The microseconds timer introduced in #3957 is prone to some errors. This PR corrects these errors and uses a single timer instead of 2, thus removing the 2MHz timer.

feat: better microsecond timer

---

radio/src/boards/generic_stm32/module_ports.cpp
radio/src/targets/taranis/hal.h
radio/src/targets/taranis/lcd_driver_spi.cpp

Should fix missing bytes in CRSF telemetry stream.

fix: USART IRQ priority for external module

---

.github/workflows/actions.yml
.gitpod.yml
radio/src/CMakeLists.txt

This PR changes the Gitpod container image used as we need to use their base image.
See EdgeTX/build-edgetx#20
**Please note:** this PR is for testing only. It needs some edits before being merged. EdgeTX/build-edgetx#20 should be merged first.

fix: GitPod container image now needs their workspace image as base

---

radio/src/lua/api_model.cpp
radio/src/mixes.cpp

Fixes #4128 
Needs to be applied to 2.9 as well as main. Broken in PR #4008/#3999

fix(radio): Lua insertMix function not working

---

radio/src/inactivity_timer.cpp

Fixes splash not drawn even if requested for TPro V2 (and possibly others)

fix: splash screen on TProV2

---

radio/src/gui/colorlcd/radio_sdmanager.cpp

Progress bar was not tall enough so it got clipped.

fix(color): Clipped progress bar when flashing bootloader/module firmware

---

radio/src/FreeRTOSConfig.h
radio/src/rtos.h

This PR switches from FreeRTOS binary semaphores to mutexes. The main advantage is that it gives us `Priority Inheritance` (see [here](https://www.freertos.org/Real-time-embedded-RTOS-mutexes.html)).
`Priority Inheritance` should reduce lock contention when a mutex is locked from a lower priority task but needed by a higher priority task. This is done by temporarily raising the priority of the lower priority task to allow it to complete the current operation and release the mutex, thus giving way to the higher priority task to carry on.
This happens in the following cases:
- FatFs I/O mutex (`ioMutex`) is used from `UI (low prio)`, `Timer (mid prio)` and `Audio (high prio)` tasks.
- Mixer mutex is used from `UI (low prio)` and `Mixer (very high prio)` tasks.
- Audio mutex is used from `UI …

perf: Use FreeRTOS mutex instead of binary semaphore

---

radio/src/gui/128x64/model_setup.cpp
radio/src/gui/212x64/model_setup.cpp
radio/src/gui/colorlcd/module_setup.cpp
radio/src/hal/module_driver.h
radio/src/pulses/dsm2.cpp
radio/src/pulses/ppm.cpp
radio/src/pulses/ppm.h
radio/src/pulses/pulses.cpp
radio/src/pulses/pulses.h
radio/src/telemetry/mlink.cpp
radio/src/telemetry/mlink.h
radio/src/telemetry/spektrum.cpp
radio/src/telemetry/telemetry.cpp

In order to remove certain limitations and thus further generalise the modules' life cycle, it is necessary to notify the module driver on certain config changes in order to let it decide what is required to apply these changes.

refactor: notify module driver on config changes

---

radio/src/gui/128x64/radio_setup.cpp
radio/src/gui/212x64/radio_setup.cpp
radio/src/gui/colorlcd/radio_setup.cpp

fix(radio): Limit year range for RTC to prevent overflow

---

radio/src/thirdparty/libopenui/src/form.cpp
radio/src/thirdparty/libopenui/src/form.h

Fixes an obscure issue with input fields and page navigation.
Steps to reproduce issue:
- Navigate to Radio Settings, Hardware tab
- Use rotary encoder to select Battery calibration field
- Press Enter key to activate edit mode
- Press Page>, then Page<
The Battery meter range field is now selected in partial edit mode; but the rotary encoder does not change the value and the RTN key exits the page instead of exiting edit mode.

fix(color): Clear edit mode when page closes

---

radio/src/gui/colorlcd/radio_setup.cpp

Fixes:
- Edit range for switchesDelay property was set to -150ms - 850ms instead of 0ms to 1000ms
- Fix display for 0ms - was showing 00ms.

fix(color): Edit range and display value for switch play delay

---

radio/src/gui/colorlcd/radio_sdmanager.cpp

Fixes #938 
Option already exists on B&W radios.

feat(color): Add 'View Text' option for .lua files in SD manager

---

radio/src/gui/colorlcd/curveedit.cpp
radio/src/gui/colorlcd/gvar_numberedit.cpp
radio/src/gui/colorlcd/gvar_numberedit.h
radio/src/gui/colorlcd/output_edit.cpp
radio/src/gui/colorlcd/widget_settings.cpp

Fixes #826 
Set default value for:
- Widget - 'VALUE' option
- Curve - number of points
- Output - Min and Max fields

fix(color): Set default value for various number edit fields

---

radio/src/gui/colorlcd/themes/etx_lv_theme.cpp

Set height of number and text edit fields to 32 for UI consistency (was 34 high).
Fix vertical centering of text in edit field box.

chore(color): Set height of edit fields to match other UI elements

---

radio/src/cli.cpp

Mutex debug is not going to come back, but I (still ?) have a secret hope for the error counter to come back one day

chore: Cleanup obsolete ioMutex debug lines

---

radio/src/serial.cpp
radio/src/storage/storage_common.cpp
radio/src/targets/horus/board.cpp
radio/src/targets/nv14/board.cpp
radio/src/targets/taranis/board.cpp

fixes #3813
- removed forced default serial initialization of AUX1 for debug builds

fix: Correctly reflect state of AUX1 when DEBUG build

---

radio/src/io/frsky_firmware_update.h

As per issue reported by @pfeerick 
Will do for now, even if a more subtle approach might come later.
Simu tested ok

fix: Missing OTA option for newer Archer receivers

---

radio/src/gui/128x64/model_setup.cpp
radio/src/gui/212x64/model_setup.cpp
radio/src/hal/module_port.cpp
radio/src/hal/module_port.h
radio/src/pulses/modules_helpers.h
radio/src/pulses/multi.cpp
radio/src/pulses/multi.h
radio/src/pulses/pulses.cpp
radio/src/pulses/pulses.h
radio/src/pulses/pxx.cpp
radio/src/pulses/pxx.h
radio/src/pulses/pxx1.cpp
radio/src/serial.cpp
radio/src/targets/common/arm/CMakeLists.txt
radio/src/targets/common/arm/stm32/stm32_serial_driver.cpp
radio/src/targets/common/arm/stm32/stm32_softserial_driver.cpp
radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp
radio/src/targets/common/arm/stm32/stm32_usart_driver.h
radio/src/targets/simu/module_drivers.cpp
radio/src/telemetry/multi.cpp
radio/src/telemetry/multi.h
radio/src/telemetry/telemetry.cpp
radio/src/telemetry/telemetry.h
radio/src/tests/module_ports.cpp

This PR is meant to solve the issue caused by the shared S.PORT line between internal and external module on FrSky radios. The internal module on these radios take the S.PORT line in ownership when turned ON, and there is no way to turn it OFF.
Summary of Changes:
- Force release S.PORT owned by the external module when a PXX1 internal is turned ON.
- Re-Init external module (if powered ON) when a PXX1 internal module is turned OFF.
- MPM: automatically send "disable telemetry" if S.PORT is not owned by the MPM.
- PXX1 external module: automatically send "disable telemetry" if S.PORT is not owned by this module.
- Fixes to improve conflict detection between different drivers using the same pins (USART / timers).
*Please note*: In case an external module uses S.PORT both for TX and RX …

fix: Internal PXX exclusive S.PORT

---

radio/src/gui/128x64/radio_setup.cpp
radio/src/gui/212x64/radio_setup.cpp
radio/src/gui/colorlcd/radio_setup.cpp
radio/src/opentx.cpp

The model level setting for enabled features takes precedence over the radio level setting if the model setting is not 'Global'.
In this case the radio setting has no effect on the tab visibility which may lead to confusion.
This PR hides the enabled features toggle in radio settings if it is overridden in model settings and shows the model setting instead.

feat(radio): Show model level setting for 'Enabled Features' when altering radio level setting

---

radio/src/translations/de.h

fixes building German language firmware. Tested with TX16s and QX7
Thanks to @parkerEde for bringing this to attention and testing

fix(translation): German translation used non-existent `CENTER` on colorlcd

---

radio/src/gui/colorlcd/module_setup.cpp
radio/src/hal/module_port.cpp
radio/src/hal/module_port.h
radio/src/pulses/multi.cpp
radio/src/telemetry/multi.cpp

We should only consider whether or not the MPM has a working telemetry link.
Fixes an issue introduced in #3822 
Fixes #4197, resolves #1187

fix: MPM module status

---

radio/src/thirdparty/libopenui/src/bitmapbuffer.cpp

Fixes #860 
Use values of PRIMARY2 color instead of fixed white when inverting the rectangle.
Note: this will break if Gauge widget is ever changed to draw the bar background using a color other than PRIMARY2 (e.g. if the bar background color ever gets added as a widget option).

fix(color): Gauge invertRect assumed WHITE rather than PRIMARY2

---

radio/src/gui/colorlcd/menu_model.cpp
radio/src/gui/colorlcd/menu_model.h
radio/src/gui/colorlcd/menu_radio.cpp
radio/src/gui/colorlcd/menu_radio.h
radio/src/gui/colorlcd/model_select.cpp
radio/src/gui/colorlcd/model_select.h
radio/src/gui/colorlcd/tabsgroup.cpp
radio/src/gui/colorlcd/view_channels.cpp
radio/src/gui/colorlcd/view_channels.h
radio/src/gui/colorlcd/view_main.cpp

Allow SYS and MDL key navigation from within radio and model setup pages.
In the Radio Setup pages:
- MDL navigates to the Model Setup page
- Long press MDL navigates to Manage Models page
In the Model Setup pages:
- SYS navigates to the Radio Setup (TOOLS) page
- Long press SYS navigates to the Radio Setup (SETUP) page
- MDL navigates to the Channel Monitor (existing function)
- Long press MDL navigates to the Manage Models page
In the Channels Monitor page:
- MDL navigates to the Model Setup page
- Long press MDL navigates to the Manage Models page
- SYS navigates to the Radio Setup (TOOLS) page
- Long press SYS navigates to the Radio Setup (SETUP) page
In the Manage Model page:
- MDL navigates to the Model Setup page
- SYS navigates to the Radio Setup (TOOLS) page
- Long press SYS …

feat(color): Improved navigation with SYS and MDL keys

---

radio/src/gui/gui_common.cpp

Without this, a corrupted switch or pot configuration could lead to a crash.

fix: Enforce switch & pot ranges

---

radio/src/functions.cpp
radio/src/gui/colorlcd/radio_setup.cpp
radio/src/opentx.cpp
radio/src/thirdparty/libopenui/src/slider.cpp
radio/src/thirdparty/libopenui/src/slider.h

Fixes #4057 
Restrict the backlight value selected via the special function to lie between the user selected values for 'ON brightness' and 'OFF brightness' values.
When using a pot/slider to control the backlight the min value on the slider will be set to the 'OFF brightness' value, the max value will be 'ON brightness'. Values in between are scaled accordingly.
Tested on TX16S and EL18.
Note: If 'OFF brightness' is set to the lowest value in the settings UI then the inactivity timer will turn the LCD off. This is not true of the pot/sider value - the lowest value does not turn the LCD off.

fix(color): Scale SF backlight value to user selected min/max backlight values

---

radio/src/telemetry/mlink.cpp

fixes #4175
MLink delivers a true uplink LQI in percent.  
Changes:
- changed sensor name "RSSI" to "RQly" (which it really is)
- changed sensor unit to percent
- changed fixed subID 0 to MLink address
- changed value variable name to reflect its content

fix: change MLink sensor name for rx quality to RQly  

---

radio/src/gui/colorlcd/module_setup.cpp

Fixes #4187 
Delay the 'MPM Scanning' popup until the page has finished building.

fix(color): 'MPM Scanning' popup blocking hardware keys

---

radio/src/telemetry/mlink.cpp

- mlink.cpp: adress -> address

chore: Typo in mlink variable name

---

companion/src/mdichild.cpp

fix(cpn): Non-functional edit model button and context menu entry

---

radio/src/targets/common/arm/stm32/trainer_driver.cpp

Fixes #3634 
Power on/off of the external module is now in the module init/deinit code. Since trainer/sbus and trainer/ccpm are no modules,  power on/off is not handled for that mode of operation. Therefore, moduleSetPower calls were added to the init/deinit subroutines for trainer/sbus and trainer/cppm. There is also a fix in stop_trainer_module_sbus() where sbus_trainer_mod_st has to be set to nullptr after deiniztialization of the sbus port.
Tested on QX7-ACCESS with edgetx 2.9.1 with mode trainer/sbus (with SBUS data source and power pin voltage check) and with mode trainer/sbus (power pin voltage check only, I do not have a ccpm data source).

fix: Ext module not powered when using SBUS or CPPM trainer

---

radio/src/gui/colorlcd/mpm_settings.cpp
radio/src/io/multi_protolist.cpp
radio/src/storage/yaml/yaml_datastructs_funcs.cpp

fix(yaml): Do not limit to static MPM protocol definitions

---

radio/src/gui/colorlcd/theme_manager.cpp

Handle reading of colors from theme file where the color is in RGB(0x??, 0x??, 0x??) format.
Should be applied to 2.9 as well.

fix(color): Reading of RGB theme colors in hex format

---

radio/src/gui/colorlcd/special_functions.cpp

Fixes #4234
Fix validation check on parameter.

fix(color): 'Reset' SF does not show telemetry parameter when edited

---

radio/src/gui/colorlcd/widgets/value.cpp

Fixes value widget not triggering a refresh to change theme color when showing a telemetry sensor value and telemetry is lost. When the widget is in the top bar, it refreshed every 100ms (which is changing in pending PR IIRC), but not as a main view widget. 
Reported by a user on discord : https://discord.com/channels/761870396085108757/854744834698379274/1164226084762570862

fix(color): Value widget not refreshing when telem lost

---

radio/src/translations/tts_de.cpp

Fixes #4235 
- fixed use of  singular and plural in TIME tts
- removed "and" between hours and minutes (as is implemented for language EN) to make for shorter and more concise "TIME" speech messages

fix(tts): DE play value "TIME" wrong for 00:xx:xx hours

---

radio/src/storage/sdcard_yaml.cpp

Fixes a very old issue causing a copied model to be placed in the first free slot instead of its intended final position. The model headers were not updated either, so that the model name was not displayed properly.

fix(stdlcd): model copy

---

radio/src/translations/tts_de.cpp

handles DE language quirk for values of exactly 1 and 1.0 properly for all different scenarios:
- units: handles no unit, just singular unit (e.g. Volt), plural units (e.g. Sekunde, Sekunden) also for the odd DE exception to the rule (e.g. rad - "ein Radiant", not "eine" Radiant compared to "eine Stunde")
- fractions: handling special case 1.0
Note: there are also some minor issues with the DE sound pack which need fixing for km, dbm, rpm and mph to work properly. Code is prepared to handle those units and will work correctly as soon as the DE sound pack is updated. 
- km0.wav ("Kilometer") and dbm0.wav ("DBM") are missing
- rpm requires rpm0.wav ("Umdrehung pro Minute") and rpm1.wav ("Umdrehungen pro Minute")
- mph requires mph0.wav ("Meile pro Stunde") and mph1.wav ("Meilen pro Stunde") …

fix(tts): DE - value 1 representation ("eins", "eine", "ein") 

---

radio/src/MultiSubtypeDefs.h

add 9630 subtype under FX
Will resolve in part #4144

chore(mpm): Add FX/9630 subtype to static list

---

radio/src/gui/colorlcd/layouts/layout_factory_impl.cpp
radio/src/gui/colorlcd/layouts/layout_factory_impl.h
radio/src/gui/colorlcd/layouts/topbar_impl.cpp
radio/src/gui/colorlcd/widgets/radio_info.cpp
radio/src/gui/colorlcd/widgets/widgets_container_impl.h

- Remove top bar forced refresh of widgets, let widgets decide if refresh is needed (while retaining 100ms refresh interval)
- Adjust main view layout when options are changed instead of checking options repeatedly in the checkEvents function
- Adjust date time widget to only refresh when value changes

chore(color): Cleanup layout refresh logic.

---

radio/src/gui/colorlcd/preview_window.h
radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
radio/src/gui/colorlcd/themes/etx_lv_theme.h

After the libopenui refactor the theme editor preview no longer worked with screen elements defined entirely with LVGL styles (e.g. toggle switch and text button).
This PR cleans up the style management and fixes the theme preview to work correctly.

fix(color): Theme edit preview not working with LVGL styles

---

radio/src/CMakeLists.txt
radio/src/audio.cpp
radio/src/model_audio.cpp
radio/src/model_audio.h
radio/src/targets/common/arm/CMakeLists.txt
radio/src/tests/model_audio.cpp

Another victim of  the switch/ADC refactor PR.
Incorrect indexing of switches when looking for model specific audio file (e.g. SOUNDS/en/modelname folder).
Crashes simulator if model audio file exists.
Loads incorrect audio files on radio.

fix(color): Fix search for model specific audio files for switches.

---

cmake/FetchGtest.cmake

It seems that `googletest` generates `install`targets by default without a few tweaks.

fix(cpn): prevent googletest installation

---

radio/src/gui/colorlcd/hw_inputs.cpp
radio/src/gui/colorlcd/hw_inputs.h

Fix issue where main view does not update if a pot or slider state is changed in radio hardware.
The corresponding control is not added or removed from the main view when the state changes.

fix(color): Refresh main view if pots or sliders changed.

---

radio/src/gui/colorlcd/widget.cpp

Fixes the issue where long pressing on the radio info widget shows an empty menu.

fix(color): Don't display long press widget menu if no options

---

radio/src/targets/horus/bootloader/boot_menu.cpp
radio/src/targets/nv14/bootloader/boot_menu.cpp

Move the tick mark on the bootloader 'Write Firmware' screen to the left of the 'Version' string so it does not overlap the version text.

fix(color): Bootloader tick mark position.

---

radio/src/storage/sdcard_common.cpp

Fixes an issue where the radio may overwrite YAML files on the SD card after starting in emergency mode.
The data restored from the backup is only a partial copy of the last used radio and model data so this can result in settings being lost.

fix(radio): Don't update YAML files on SD card if radio in emergency mode

---

radio/src/gui/colorlcd/draw_functions.cpp
radio/src/gui/colorlcd/model_telemetry.cpp
radio/src/telemetry/spektrum.cpp
radio/src/telemetry/telemetry_sensors.cpp

Fixes #4170 
With data-types who are not plain 32bit numbers, like GPS, Text, DATE_TIME,  we have to populate the telemetry "value" with something that changes so that the "value" widget detects the change.  The trick is to populate the "value" with a hash of the GPS or DATE_TIME complex value. The actual value for GPS and DateTime are stored in different variables. 
The "value" widget was not displaying correctly DATE_TIME, fixed it (don't know why was moving the x coordinate -42 pixels!).
Change dateTime format to ISO 8601 date for color radios (YYYY-MM-DD HH:MM:SS).
NOTE: B&W was already this format (with 4 digits for year), and sensor log writing too... good for consistency.
NOT COMPILED FOR PRODUCTION: Updated Spektrun GPS testing code to change the values for GPS …

fix(color): Refreshing of GPS and DATE_TIME telemetry when using Value Widget

---

radio/src/gui/common/stdlcd/radio_trainer.cpp

It seems #3354 didn't take 212 screens into account.
Adds some padding on widescreen (212x64) B&W
Before:
After:
Before:
After:
@3djc Complaints? Concerns? Small furry animals? 😆

fix(bw): 212x64 trainer page text overlap

---

radio/src/MultiProtoDefs.h
radio/src/MultiSubtypeDefs.h

Pascal released MPM version 1.3.3.33. This updates the changes from 1.3.3.20 to 1.3.3.33 
Comparing files multi.txt-1.3.3.20 and  multi.txt-1.3.3.33
```
***** 1.3.3.20
49,KF606,KF606,MIG320
***** 1.3.3.33
49,KF606,KF606,MIG320,ZCZ50
*****
***** 1.3.3.20
58,FX,816,620
***** 1.3.3.33
58,FX,816,620,9630
*****
***** 1.3.3.20
70,DSM_RX,Multi,CPPM
***** 1.3.3.33
70,DSM_RX,Multi,CloneTX,EraseTX,CPPM
*****
***** 1.3.3.20
***** 1.3.3.33
94,Scorpio
```

chore: Update static MPM defs to 1.3.3.33

---

radio/src/storage/yaml/yaml_datastructs_funcs.cpp

Fixes #4230
When a custom mix script is used as a source input the value is stored as 'lua(x,y)' in the YAML file.
The ',' inside the brackets confuses the YAML parser and the value is not read back correctly.
This PR fixes the YAML parser to handle this case.

fix(radio): Custom mix script as SOURCE not parsed correctly

---

radio/src/opentx.cpp

Resolves #4018 for 2.9
Ports the following from #4027:
- Link startup and shutdown haptic triggers to state of hapticMode setting
- Include throttle LED fix
- Load settings on boot unless EM startup so haptic state can be loaded on boot

fix(color): No startup/shutdown haptic if haptic mode set to quiet

---

radio/src/mixer.cpp
radio/src/tests/mixer.cpp

This PR removes the distinction between following with respect to how delays are handled:
- a conditional mixer line (using a set of flight modes and/or conditional switch),
- a non-conditional one.
Fixes #4254

refactor(mixer): improve delays

---

radio/src/gui/colorlcd/preflight_checks.cpp

Fixes issue whereby toggle switches are shown as possible preflight check switches when in fact they are not tested for. This is already tested for on B&W, this brings colorlcd into line.

fix(color): Toggle switch not valid for preflight

---

radio/src/gui/colorlcd/themes/etx_lv_theme.cpp

Fix radio crash when editing a theme - missed in LVGL 8.3 upgrade.

fix(color): Crash in theme editor

---

companion/src/firmwares/eeprominterface.h
companion/src/firmwares/opentx/opentxinterface.cpp

Firmware is currently added in non-alphabetically order, and thus the Radio Type list in Companion settings is in a seemingly random wacky order... (i.e. the order stuff was added over time). I've manually gone through and changed the order firmware is registered, which puts them in a more rational order...
Before:
After:

feat(cpn): Radio Type sorted alphabetically

---

companion/src/logsdialog.cpp

- extends log viewer's x-axis time format to show milliseconds

feat(cpn): Extend Log Viewer x-axis time format to show milliseconds

---

companion/src/firmwares/generalsettings.cpp
companion/src/firmwares/generalsettings.h
companion/src/mdichild.cpp

When creating a new configuration in Companion the default calibration values do not work for the 6POS switches.
This PR sets better default values (taken from my TX16S) and fixes the values when loading a .etx file if they are set to the old default.
Fixes #4269

fix(cpn): Default calibration values for 6POS switch.

---

.github/workflows/macosx_cpn.yml

- Hopefully allow MacOS cpn to build on 2.9 branch by applying same XCode version switcheroo

chore(cpn): 2.9 Give SDL2 version of XCode it wants

---

radio/src/translations/cn.h
radio/src/translations/cz.h
radio/src/translations/da.h
radio/src/translations/de.h
radio/src/translations/en.h
radio/src/translations/es.h
radio/src/translations/fi.h
radio/src/translations/fr.h
radio/src/translations/he.h
radio/src/translations/it.h
radio/src/translations/jp.h
radio/src/translations/nl.h
radio/src/translations/pl.h
radio/src/translations/pt.h
radio/src/translations/ru.h
radio/src/translations/se.h
radio/src/translations/tw.h

Remove 'Range' value from strings so offsets are correct (missed in PR #4267).

fix(radio): Special/Global functions showing wrong function name

---

companion/src/modelslist.cpp

Fixes #4305
Fix format string so index value is correctly displayed.

fix(cpn): Model index missing in model list for B&W radios

---

radio/src/strhelpers.cpp

Resolves #2215
* on colorlcd, when showing the sources list, if GV has a name, show its index and its name, as opposed to just its index. 
This is just proof of concept... the code is still quite ugly... 
Before: 
After:
I'm pushing this to 2.9 as I want to piggyback and extend this on top of #2085, and also show names of LS when present.

feat(color): Show index and name (when set) for GVs in input source

---

companion/src/firmwares/modeldata.h
radio/src/storage/yaml/yaml_parser.cpp
radio/src/storage/yaml/yaml_tree_walker.cpp
radio/src/tests/model.cpp

- YAML output: escape double quotes `"` inside string elements

fix(yaml): properly escape double quotes

---

radio/src/gui/128x64/model_logical_switches.cpp
radio/src/gui/212x64/model_logical_switches.cpp
radio/src/gui/colorlcd/model_logical_switches.cpp

Fixes #4238
Limit V2 range to positive values, where function compares to |V1|.

fix(radio): Don't allow negative values for V2 on LS functions '|x|>y', '|x|<y' and '|dx|>=y'

---

radio/src/targets/common/arm/stm32/trainer_driver.cpp

Please note that this PR is explicitely targeted at `2.9`, as the `main` should be fixed with the more generic PR (see #4266)
Fixes #4324

fix: external module power for SBUS trainer

---

radio/src/gui/colorlcd/fm_matrix.cpp
radio/src/gui/colorlcd/model_usbjoystick.cpp
radio/src/gui/colorlcd/preflight_checks.cpp
radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
radio/src/thirdparty/libopenui/src/button_matrix.cpp

Make the button matrix controls more consistent with the rest of the UI.
- Set button height to 32
- Fill empty spots on last row with hidden buttons to make size consistent.
After:
Before:

fix(color): Button matrix styling

---

radio/src/inactivity_timer.cpp

On my TX16S and EL18 the backlight would not always turn off after inactivity and would randomly turn back on even if no input.
Fixed the code checking for activity on switches and analog inputs to not check the VBAT and RTC_BAT values.

fix(color): Backlight randomly turns back on when no user input.

---

radio/src/gui/colorlcd/model_inputs.cpp

Fixes #4315
Adding a new input with a gap before it to the last input would add the new to the wrong slot in the 'expos' data array.
Restarting the radio would rebuild the 'expos' array correctly.
This PR fixes ensures new inputs are added at the right spot (and cleans up the source file formatting).

fix(color): New inputs disappear until restart.

---

radio/src/gui/colorlcd/model_inputs.cpp

Fixes issue introduced in #4317 where the popup would not show all the possible values.

fix(color): New input popup not showing all empty inputs.

---

radio/src/gui/colorlcd/view_main_menu.cpp

PR #4320 introduced an issue where the quick menu does not close if the screen is tapped outside the quick menu area.

fix(color): Quick menu does not close properly.

---

radio/src/gui/colorlcd/view_main_menu.cpp

Fixes #4334 
Fix default scroll for quick menu.
Resize quick menu window if model has notes.
No model notes:
Has model notes:
Portrait layout has 9 slots so no resizing necessary.

fix(color): Incorrect scroll position on quick menu if model has notes

---

radio/src/gui/colorlcd/fullscreen_dialog.cpp
radio/src/gui/colorlcd/switch_warn_dialog.cpp
radio/src/targets/horus/libopenui_config.h
radio/src/targets/nv14/libopenui_config.h

Fix spacing and formatting of text on switch warning page.

fix(color): Formatting of text on controls warning dialog

---

radio/src/gui/colorlcd/preflight_checks.cpp

The switch section in the pre-flight check page would not update if one of the switches (except the last) was disabled or set as a toggle switch.

fix(color): Pre-flight check page does not always update.

---

radio/src/gui/colorlcd/screen_user_interface.cpp
radio/src/gui/colorlcd/topbar.cpp
radio/src/gui/colorlcd/topbar.h

Pressing the TELE button while editing top bar widgets opens a new copy of the screen setup page instead of returning to the previous one.
It then takes two presses of the RTN button to close back to the main view.

fix(color): `TELE` navigation issue when editing top bar widgets

---

radio/src/gui/colorlcd/widgets_setup.cpp
radio/src/gui/colorlcd/widgets_setup.h

When editing the widget layout, clicking on an empty widget slot shows a popup with a single 'Select widget' option. Clicking this opens the popup to select which widget to add.
This PR bypasses the 'Select widget' popup and goes straight to the list of widgets to choose from.

feat(color): Don't show popup when adding a widget to an empty slot.

---

radio/src/gui/colorlcd/radio_sdmanager.cpp

PR #4331 adjusted the positions of the text on the full screen dialog to better fit the switch warning text.
This affected the 'Flash Bootloader' dialog where the progress bar now overlaps the text.
This PR moves the progress bar to not cover the text.

fix(color): Progress bar position/size on firmware flasher dialog

---

radio/src/gui/colorlcd/page.cpp
radio/src/gui/colorlcd/tabsgroup.cpp
radio/src/thirdparty/libopenui/src/keyboard_base.cpp
radio/src/thirdparty/libopenui/src/keyboard_base.h
radio/src/thirdparty/libopenui/src/modal_window.cpp

When editing a text field, if the 'close' button on the keyboard (bottom left button) is pressed then both the keyboard and the page beneath are closed.
The LVGL keyboard sends a cancel event to both the keyboard and the text field being edited.

fix(color): Closing keyboard also closes underlying page.

---

radio/src/gui/colorlcd/LvglWrapper.cpp
radio/src/thirdparty/libopenui/src/keyboard_base.h
radio/src/thirdparty/libopenui/src/keyboard_number.cpp
radio/src/thirdparty/libopenui/src/keyboard_number.h
radio/src/thirdparty/libopenui/src/keyboard_text.cpp

Fixes #2425
Resolves #265
Adds shortcuts to the text keyboard using the hardware keys.
Short press:
- PG>/PGDN - move cursor right
- PG</PGUP - move cursor left
- SYS - cycle through keyboard layouts (alpha uppercase, alpha lowercase, numbers & symbols, numeric)
- TELE - change case of selected character (upper to lower or lower to upper)
- MDL - delete character to the left of the cursor (backspace)
Long press:
- PG>/PGDN - move cursor to the end of the input
- PG</PGUP - move cursor to the start of the input
- MDL - delete currently selected character
Long press SYS and TELE are available if there are other shortcuts that might be useful.

feat(color): Shortcut keys for text keyboard.

---

radio/src/gui/colorlcd/switchchoice.cpp
radio/src/gui/colorlcd/switchchoice.h
radio/src/thirdparty/libopenui/src/choice.cpp
radio/src/thirdparty/libopenui/src/choice.h

The new Switch Choice popup has some teething issues addressed in this PR:
- The 'Invert' button can be inadvertently activated while scrolling the list on the touch screen (phantom long press trigger).
- The 'ON' and 'ONE' options were not being filtered out when the list was inverted (showed as '0').

fix(color): Long press and filtering in new Switch Choice popup.

---

radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
radio/src/gui/colorlcd/view_text.cpp

Fixes the display of the checkbox on the pre-flight checklist page so it does not get clipped on the right and bottom.

fix(color): Clipping of checkbox on pre-flight checklist.

---

radio/src/gui/colorlcd/view_main_menu.cpp

On landscape layouts the quick menu was checking for model notes twice resulting in extra calls to the f_stat function.
Fixes: #4381

perf(color): Remove multiple checks for model notes in quick menu

---

radio/src/gui/colorlcd/model_flightmodes.cpp
radio/src/gui/colorlcd/model_gvars.cpp

When using the touch screen to select items on the GVAR list, the focus was not always being set to the touched line. In other cases two lines would end up showing as focused.
No idea why the GVAR list did this - the logic looks the same as on the FM list which does not show this problem.
Fixed by removing event bubbling and making the container objects not clickable.
~~TODO: this is probably a better way to handle these complex list buttons, so other views might need updating.~~
FM list updated with the same logic change.

fix(color): Incorrect focus selection in GVAR list

---

radio/src/gui/212x64/lcd.cpp
radio/src/gui/212x64/lcd.h
radio/src/targets/taranis/CMakeLists.txt
radio/src/targets/taranis/board.h
radio/src/targets/taranis/lcd_driver_spi.cpp

Removes unused build time option LCD_DUAL_BUFFER, that was historically implemented for B/W 212x64 pixel X9E and X9D+, but by default disabled.

chore: Remove unused LCD_DUAL_BUFFER

---

radio/src/gui/128x64/view_main.cpp

On radio with more than 4 trims (MT12, T20,..), obey trim value display settings for the first 4 trims (the others are not displaying values no matter the settings)

fix(bw128): Show first 4 trims when radio has > 4 trims

---

radio/src/lua/widgets.cpp

Fixes two issues:
- The 'Timer', 'TextSize' and 'String' options for Lua widgets were not being initialised so if no default value was supplied in the options table you would get random memory contents.
- The default value for a 'Timer' widget option was not being used.

fix(color): Initialisation of Lua widget options

---

radio/src/gui/colorlcd/curveedit.cpp
radio/src/gui/colorlcd/input_edit.cpp
radio/src/gui/colorlcd/input_edit.h
radio/src/gui/colorlcd/mixer_edit.cpp
radio/src/gui/colorlcd/mixer_edit.h

When editing a curve, moving any of the sticks will then attach that axis to the curve preview position and update the position as the stick is moved.
However if an input is edited first the curve preview becomes locked to the input source, and then in the curve edit page only this input source will move the preview position.
Also removes redundant (related) code in the mix editor.

fix(color): Wrong input could be used for updating curve preview

---

radio/src/gui/128x64/view_main.cpp
radio/src/gui/212x64/view_main.cpp

fix(b&w): Top left '!' warning always flashing on B&W simulators

---

radio/src/gui/colorlcd/layouts/trims.cpp

The marker bars on the color radio horizontal trim display work backwards compared to the B&W bars and the color vertical bar.
PR changes the color horizontal bar to match.
B&W:
Color:

fix(color): Trim display inconsistent with B&W

---

radio/src/targets/common/arm/stm32/stm32_ws2812.cpp

Fixes #4399
(bit order of data sent to WS2812 was LSB first, which is wrong)
Sends MSB first, as per WS2812 datasheet

fix(ws2812): Bit order of WS2812 data stream

---

radio/src/gui/colorlcd/radio_trainer.cpp

Resolves #4121 (remainder of) by switching string used, and moving the button around. 
@philmoz I'm open to suggestions/improvements if this can easily be made to look  nicer... focus was really just on making sure button was fully visible. Feel free to edit the PR if you wish.

chore(color): Change STR_CAL to STR_CALIBRATION on trainer page

---

radio/src/opentx.cpp

Default channel for RC cars is Steering, then Throttle. Match that

fix: default channel order should be ST

---

cmake/QtDefs.cmake

This should allow finding Qt5 without explicitly passing `-DCMAKE_PREFIX_PATH=$QT_DIR` in the `cmake` command line.

chore: improve finding Homebrew's Qt5 on macOS

---

radio/src/boards/generic_stm32/startup/startup_stm32f40_41xxx.s

F4 targets were failing to start the main firmware when exiting the bootloader.

fix(bw): Restart from bootloader on F4 targets

---

radio/src/gui/common/stdlcd/radio_sdmanager.cpp

Some bugs can stay hidden for years .....
Did a bit of housekeeping while I was at it
This fixes #4417

fix(bw): Uncleared reusable buffer in sdmanager

---

companion/src/simulation/telemetrysimu.cpp
companion/src/translations/companion_sv.ts

Fixes #4429 
Added translation for Run and Stop for the GPS simulator. 
Also added a text string for "Stop" in the TelemetrySimulator section in SE Qt translation file.

fix(cpn): Translation of GPS Run/Stop in telemetry simulator

---

radio/src/globals.h
radio/src/mixer.cpp
radio/src/opentx.h
radio/src/tests/gtests.h
radio/src/tests/mixer.cpp

Fixes #4361
The changes in PR 4256 to fix issue 4254 did not quite work as expected and mix delays stopped working.
Changes:
- Reworked the logic so delays work as they did prior to 4256.
- Renamed variables and structs for readability
- Disabled invalid test 'DelayOnSwitch2' (SWSRC_ON is not a valid switch value for a mix line).
Also tested that the issue raised in 4254 is still fixed.

fix(radio): Mix delay not working.

---

radio/src/targets/common/arm/stm32/bootloader/bin_files.cpp

Filter out any Unix or MacOS dotfiles in the bootloader firmware selection menu.

feat(bootloader): Don't show Unix/MacOS dotfiles in firmware list

---

radio/src/gui/128x64/menu_radio.cpp
radio/src/gui/212x64/menu_radio.cpp

In the radio Global Functions edit, the cursor cannot be scrolled across to the 'enable' checkbox.
Missed in the PR that added the enable checkbox to all SF/GF functions.

fix(bw): Cannot change the 'enabled' state for global functions

---

radio/src/gui/128x64/model_setup.cpp

Fixes #4444
Add some special case logic to handle when there is only one switch available to trigger a pre-start warning.

fix(MT12): Cannot properly edit pre-start check switch warning state on MT12.

---

radio/src/telemetry/telemetry_sensors.cpp
radio/src/telemetry/telemetry_sensors.h

fixes #4437
PR #4250 introduced a mechanism to allow a value widget to detect a change in GPS position. This was realized by storing a hash value in the `value `variable of class TelemetryItem. Unfortunately `value ` is defined in a union together with a placeholder for `distFromEarthAxis`.
```
class TelemetryItem
{
public:
union {
int32_t  value;           // value, stored as uint32_t but interpreted accordingly to type
uint32_t distFromEarthAxis;
};
...
```
By writing the hash for the changed lat/lon to `value` the calculated `distFromEarthAxis` is overwritten. In case a calculated telemetry sensor "distance" is defined this leads to a wrong calculation of the distance between craft and home point. 
Changes: 
- separated and moved storage of `distFromEarthAxis `to class …

fix(telemetry): Inconsistent/wrong GPS distance calculation

---

radio/src/targets/common/arm/stm32/sdcard_spi.cpp

Sometime, the fix looks trivial, yet the journey to get there hasn't been ....
This fixes #4439 
@raphaelcoeffic co-authored this change

fix: increase init repeat max time for slow(est) cards

---

radio/src/gui/common/stdlcd/view_text.cpp

using "=" as indicator for checkable entries on B&W radio to align the behavior with color LCD radios

fix(bw): Progressive checklist `=` behaviour was reversed

---

radio/src/targets/common/arm/stm32/usbd_conf.c

USB functionalities broken after PR #4207 for PL18 and PL18EV
This PR fixes the problem.

fix(PL18/PL18EV): Broken USB functionalities post #4207

---

radio/src/targets/common/arm/stm32/vs1053b.cpp

See section *9.3 EarSpeaker Spatial Processing* of the VS1053b datasheet.
Fixes #4325

fix(vs1053b): Remove EarSpeaker Spatial Processing

---

radio/src/opentx.cpp

Fixes #4463 
After the ADC refactor PR, instant trim only works in Mode 1. 
Other modes incorrectly map the axis channels when trying to process instant trim.

fix(radio): Instant trim only works correctly in mode 1

---

radio/src/tests/timers.cpp
radio/src/timers.cpp

Account for surface radio specific throttle.
This fixes #4499
This also fixes corresponding test scripts

fix: timers throttle condition on surface radio

---

radio/src/gui/128x64/view_channels.cpp
radio/src/gui/212x64/view_channels.cpp
radio/src/opentx.h
radio/src/tasks.cpp

Fixes #4467 
If the 'Channels Monitor' is the start view (or is selected after startup), the view opens on the 'Mixers Monitor' instead and the ENTER key cannot be used to change view. 
User must enter a setup menu and return to the main view for the channel monitor to work correctly.
On startup - the view is not initialised correctly.

fix(bw): Channel Monitor view not working correctly on startup

---

radio/util/hw_defs/pot_config.py

Fixes generation of hw defn json files for x9d+ and x9d+ 2019

fix(x9d+): Default pots and sliders config

---

radio/src/gui/colorlcd/model_mixes.cpp

Fixes #4462 
Restore code to handle empty mixer list (removed in PR #3999).

fix(color): Mixer list display incorrect after deleting all mixer lines.

---

radio/src/gui/colorlcd/view_statistics.cpp
radio/src/gui/colorlcd/widgets/radio_info.cpp
radio/src/gui/gui_common.cpp
radio/src/gui/gui_common.h
radio/src/lua/api_general.cpp
radio/src/serial.cpp
radio/src/serial.h

Fixes #4466
- added `serialGetBaudrate`, `serialSetBaudrate` and `serialGetModePort`,
- re-implement `luaSetSerialBaudrate`.

fix(lua): re-implement luaSetSerialBaudrate

---

radio/src/inactivity_timer.cpp

Fixes #4454 
Ignore pots/sliders that are not configured when checking for activity.

fix(firmware): False triggering of user activity.

---

radio/src/translations/en.h

Minor changes to better guide users during calib
Surface radio
'air' radio

chore: improve 128x64 calibration strings

---

radio/src/storage/yaml/yaml_datastructs_funcs.cpp

Fixes #4495
Fix for reading 2.9 model files in 2.10 - correctly handle 2.9 special/global function syntax.

fix(color): Special/Global functions from 2.9 not imported correctly in 2.10.

---

companion/src/firmwares/edgetx/yaml_modeldata.cpp
companion/src/helpers.h
companion/src/modeledit/flightmodes.cpp
companion/src/modelprinter.cpp
radio/src/gui/128x64/model_flightmodes.cpp
radio/src/gui/212x64/model_flightmodes.cpp
radio/src/gui/colorlcd/draw_functions.cpp
radio/src/gui/colorlcd/model_flightmodes.cpp
radio/src/gui/common/stdlcd/draw_functions.cpp
radio/src/mixer.cpp
radio/src/myeeprom.h
radio/src/opentx.cpp

Fixes #4453 
If trim is disabled in flight mode, treat it as a 3 position toggle switch in 'getValue' function.

feat: Use trim as a 3 pos toggle switch source

---

radio/src/gui/colorlcd/model_telemetry.cpp
radio/src/telemetry/telemetry_sensors.cpp

Fixes #4021
History:
During the transition from 2.8.5 to 2.9.0, there was several fixes to DSM sensor values.   The values itself are correct, but it exposes a poblem when using "ratio" to adjust the value of a sensor.
The "ECUR" (ESC Current) sensor change from been in "mAh" (prec=1) to "A" (prec=2).  The change of prec exposed the scaling problem with ratio, The value in 2.8.5 got 10x bigger in 2.9.0 when using ratio.
* Simply commenting out code that doing the x10 when prec==2.
* The other problem was when prec==0, it was converting it to prec=1, effectively doing a / 10.
How ratio works is that the value is multiplied by  ratio/255.   So using a ratio of 255 means no change.. value of less than 255 scale down the number, and values greater than 255 makes the value …

fix: Properly scale PREC2 sensor values using "ratio"

---

.github/workflows/win-cpn-32.yml

Was dropped in
https://github.com/msys2/MINGW-packages/commit/b379ec0637a836f3da5cd13a67788c4ddcbfdfad
Then the documentation for python-lz4 was listing an invalid install command, and even when the right command was used, it seems like MSYS2 has a patched version of `distutils` that wasn't been used 😖 What fun!
Fixes win32 companion build failure. If build is successful, will probably be needed in 2.9 branch also

chore(cpn): python-lz4 for win32 no longer in mingw repo

---

radio/src/telemetry/spektrum.cpp

With many getting the new SkyID device for FAA RemoteID,  someone reported that the Longitude was showing with only 2 Digits, when their location should be 3-digits.
After checking the code and documentation, the sensor data only send 2 Digits, BUT there is an extra bit flag to add +100 to it.
Fix: Added the code to take that flag into consideration.
Tested with "2.9" branch as well as "main"

Telemetry(DSM) Fix for Longitude greater than 99 deg

---

radio/src/opentx.cpp

Set internal default CRSF module to max working baudrate on specific hardware instead of current default of 400k

feat: set better internal crossfire module default baudrate

---

radio/src/opentx.cpp

Handle the case where a trim set as 3POS toggle is used as the source in the 'Adjust GVAR' special function.

fix(firmware): Behaviour of trim set to 3POS when used in SF Adjust GV function.

---

radio/src/storage/modelslist.cpp

If there are models without labels the 'Unlabeled' option should appear in the labels list of the Manage Models page.
This was broken in PR #4288.

fix(color): 'Unlabeled' option does not appear in labels list.

---

radio/src/datastructs_private.h
radio/src/model_init.cpp
radio/src/opentx.cpp
radio/src/storage/yaml/yaml_datastructs_128x64.cpp
radio/src/storage/yaml/yaml_datastructs_nv14.cpp
radio/src/storage/yaml/yaml_datastructs_pl18.cpp
radio/src/storage/yaml/yaml_datastructs_t20.cpp
radio/src/storage/yaml/yaml_datastructs_tpro.cpp
radio/src/storage/yaml/yaml_datastructs_x10.cpp
radio/src/storage/yaml/yaml_datastructs_x12s.cpp
radio/src/storage/yaml/yaml_datastructs_x9d.cpp
radio/src/storage/yaml/yaml_datastructs_x9e.cpp
radio/src/storage/yaml/yaml_datastructs_x9lite.cpp
radio/src/storage/yaml/yaml_datastructs_xlites.cpp

see discussion https://discord.com/channels/839849772864503828/839895574244229152/1194216145587286016
- yaml tag hatsMode only used for radios that have USE_HATS_AS_KEYS defined (currently NV14, EL18, PL18)

radio.yml / model.yml tag hatsMode for featured radios only

---

radio/src/targets/common/arm/stm32/usbd_storage_msd.cpp

Related to https://github.com/EdgeTX/edgetx/pull/4207
Forgot the hack, all radios appear as RM TX16S

fix: USB device name, remove the hack

---

radio/src/gui/128x64/lcd.cpp
radio/src/gui/128x64/lcd.h
radio/src/gui/common/stdlcd/model_curves.cpp

Improve LCD buffer protection by checking negative x/y values
This fixes #4544
NB: 
- this should be applied to 2.9.x too

fix: strengthen lcd buffer protection

---

radio/src/targets/horus/board.h

...an issue I nearly opened myself before opening the PR (but didn't!), and does not fix the open issues around backlights & X10 targets that I was able to find.
The diff truly does speak for itself in this case -- the brightness floor which was formerly 46 for X10 targets is now 1, hopefully w/ as few char changes as possible.
I was able to test on my own X10S Express. I do not have X10 hardware onto which I could load my build. There may be a "very good reason" the minimum of 46 had been set for X10 targets, but I see zero ill side-effects.
IMHO, bringing this into 2.9 _might_ be worth considering, but I may be the sole x10 owner whose retinas are made of delicate flower petals that were grown within earshot of sensitivity seminars in the bay area.
It feels good to no longer be backed …

allow X10(/S) Express radio displays to actually dim, not just get slightly less blinding

---

radio/src/targets/horus/board.h

If it looks familiar, it is! Same as #4539 but for the 2.9 branch.
Zero tears will be shed if this isn't something worth merging into the 2.9 branch.
I did build & flash this to my X10SE briefly, but decided running the actual 2.9.2 release w/ the same changes was a "safer" bet, so time spent was minimal, but so was the LCD backlight brightness, and zero flickers were observed. (I have a freakishly high flicker fusion threshold fwiw.)

Decrease backlight minimum for X10E on 2.9

---

radio/src/gui/colorlcd/model_select.cpp

Progress bar popup when deleting a label has 'Rename label' title string.

fix(color): Incorrect title for 'Delete label' progress bar popup.

---

radio/src/gui/common/stdlcd/radio_hardware.cpp

Fixes #4559
Code was setting 3 columns for all switches, instead of limiting this to flex switches only.

fix(b&w): Cursor vanishes in switch section of hardware setup page.

---

radio/src/gui/colorlcd/input_edit_adv.cpp

fix(color): Popup for setting Trim in Input edit does not show any values.

---

radio/src/gui/128x64/model_telemetry.cpp

A small quality of life improvement for BW128 users, that sometimes believe they  have lost their sensors when the list is simply not expanded. In such case, this will display the number of sensors to remind the user that there hidden things.

feat(bw128): Display sensor count when sensor list not expanded

---

.github/workflows/actions.yml
.github/workflows/linux_cpn.yml
.github/workflows/macosx_cpn.yml
.github/workflows/nightly.yml
.github/workflows/win_cpn-32.yml
.github/workflows/win_cpn-64.yml

- Bump checkout and upload-artifact to Node.js 20 based actions. While this was announced Sept last year, looks like Github only just flipped the notifications toggle in the last day or so for warnings in the actions logs. 
- upload-artifact@v4 does has some major breaking changes, ~~but it does not appear we use any of the changed functionality.~~ whereby artifacts are immutable, so we can't just keep uploading to the same artifact in each matrix run. 
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

chore(ci): Bump action versions due to Node.js 16 EoL

---

radio/src/storage/yaml/yaml_datastructs_funcs.cpp

Fixes #4575
Incorrect string length passed to function that converts source name to index.

fix(radio): Trainer SF properties not read correctly from YAML file.

---

companion/src/generaledit/generalsetup.ui
companion/src/translations/companion_cs.ts
companion/src/translations/companion_da.ts
companion/src/translations/companion_de.ts
companion/src/translations/companion_en.ts
companion/src/translations/companion_es.ts
companion/src/translations/companion_fi.ts
companion/src/translations/companion_fr.ts
companion/src/translations/companion_he.ts
companion/src/translations/companion_it.ts
companion/src/translations/companion_ja.ts
companion/src/translations/companion_nl.ts
companion/src/translations/companion_pl.ts
companion/src/translations/companion_pt.ts
companion/src/translations/companion_ru.ts
companion/src/translations/companion_sv.ts
companion/src/translations/companion_zh_CN.ts
companion/src/translations/companion_zh_TW.ts

Relates to #4571 - appears lupdate matches what it can for some text and higlights discrepancies in what looked like a bad translation  - the clue being the translation entry is left marked unfinished ;)

fix(cpn): QT lupdate gremlins in translations

---

radio/src/targets/common/arm/stm32/stm32_adc.cpp
radio/src/targets/pl18/hal.h

When trying to support PL18EV, in which it requires 17 ADC channels, in certain configuration, the EXT ADC may sometimes have output shifted by 1 channel and the EXT ADC channel mappings will goes all wrong.
I finally find a relevant case and got a solution and cannot see the problem anymore after this fix.
The related post can be found here:
http://forum.chibios.org/viewtopic.php?t=4608

fix: ADC EXT channel shifting on some ADC configuration

---

radio/src/targets/taranis/hal.h

This fixes MT12 trim name vs (nearly impossible to see on mine) printed label on radio

fix: MT12 T1/T2 reversed vs printout on radio

---

radio/src/telemetry/frsky_d.cpp

Fixes #4572
Tested on 2.9 branch (currently 2.9.3) as well as Main.
Make consistent the prec parameter with the Sensor definition below.
The code as it is, was creating a x10 after removing the code who was affecting other protocols when using "ratio" on PREC2 sensors (#4083).  Conversion from Prec0->Prec1 means 10x.
The sensor is really a Prec1 in the definition a few lines below (2nd screenshot)
FIX:

fix(telemetry): Correct A1..A2 voltage sensors value for Frsky_D/OMP

---

radio/src/gui/gui_common.cpp

Restore serial master trainer on bw radio that was likely removed by mistake.
successfully tested on mt12 (both the menu and the subs trainer itself)

fix: restore master serial option

---

companion/src/firmwares/customisation_data.cpp
companion/src/firmwares/customisation_data.h
companion/src/firmwares/opentx/opentxeeprom.cpp

Fixes #4528
- increase widget name length from 10 to 12 characters
- increase number of top bar zones from 4 to 6
- silence compiler warnings

fix(cpn): Custom screens yaml being truncated

---

radio/src/gui/212x64/model_special_functions.cpp
radio/src/gui/colorlcd/special_functions.cpp

PR #4621 fixed refresh of Lua scripts when a SF/GF is enabled/disabled on 128x64 B&W radios.
This PR extends that fix to 212x64 B&W and color radios.
For color radios it also fixes an issue where the radio.yml file would not get saved if a GF was pasted into the list.

fix(radio): Refresh Lua scripts if needed when SF/GF updated.

---

radio/src/thirdparty/libopenui/src/numberedit.h

For Color Radios,   small display inconsistency/bug.
Class EditNumber has the option to replace a zero value for any other text.   But was not working.
Looking at the code, there is no logic to handle the ZeroText.
**NOTE: this fix is only for the main (2.10) branch.
On branch 2.9, this code is in basenumberedit (BaseNumberEdit class).   Let me know if you want a PR specific for 2,9**
Example Screen: Telemetry Sensor Edit, the Ratio should show "-" when 0, and is not.  B&W radios works properly.
Example: Mixer Edit, Warning should show "Off" when zero.
Libopenui:   numberedit  (NumberEdit class):   Added code to show the zeroText string if the value is 0.
According to the the reference, is only used in 4 pages:

fix(color):  EditNumber class not implementing zeroText logic

---

radio/src/telemetry/spektrum.cpp

Fixes #4598
1. Hide "Flss" and "Hold" Sensors with populated with NO-DATA  (0x7FFF or 0xFFFF)
2. On PowerBox Telemetry (Voltage + Consumption), Only report data if the Sensor is connected (Volts > 0)
3. Handle Duplicate "Alt" sensor when RX reports separate messages for Altimeter (only)  and Vario  (Alt + VSpeed)
4. Handle Duplicate "RB1C" (Bat1 Consumption) if reported by Flight Pack Monitor Sensor and PowerBox in the same RX (Lemon)
5. Hide Bat2 data if Bat2 is not connected (PowerBox and FlightPack).  Most hardware only monitors 1 bat
**Note**:  On this scenario sometimes the duplicate sensors can show again:
1. Have Telemetry "Discover New" active, when we do "Reset Telemetry" on the main screen.
2. Have Telemetry "Discover New" active while binding. 
This is because we process the …

fix(telemetry): DSM/LemonRX sensor cleanup for Altimeter and Flight Pack Monitors

---

.github/workflows/win_cpn-32.yml

If this works... *famous last words* ... this will build libusb and dfu-util for the win32 companion package, as the i686/win32 versions were removed from the msys-mingw package repo four days ago via https://github.com/msys2/MINGW-packages/commit/db6517eb5ab862427c95f3a43fcee177dd6d324e

chore(cpn): use win32 dfu-util binary release 

---

radio/src/lua/api_general.cpp

Modified LUA crsfTelemetryPush() to support CRSF direct commands
Fixes #983 
Testing:
1. Legacy
Since this PR changes LUA function that is used in scripts to configure devices using CRSF protocol (ELRS)
- run ELRS LUA and check if everything works as intended
- run TBS Agent and check if everything works as intended
2. Direct commands
- Install TBS TX module (any) in radio - led on module button should light yellow
- Install enclosed LUA test script (move to /SCRIPTS/TOOLS/)
- Select "CRSF TX Module Start Bind" and press Enter - led on module button should blink green slowly
- Select "CRSF TX Module Stop Bind" and press Enter - led on module button should stop blinking and go back to solid yellow.
[CRSF_direct_cmd_test.lua.zip](https://github.com/EdgeTX/edgetx/files/142 …

feat(lua): add support for CRSF 'direct command' packets

---

radio/src/targets/common/arm/stm32/usbd_desc.c

stop gap change to fix #4580 by reverting the USB manufacturer string to the pre-2.9.0 state ("OpenTX" instead of "EdgeTX")

fix(radio): "DCL - The Game" not detecting USB joystick

---

radio/src/translations/ua.h

I suggest a correction in the Ukrainian localization.
I am a native speaker and found some mistakes.
I fixed errors of the following types:
- Incorrect order of letters in the word.
- Some words were in Russian - I replaced them with Ukrainian.
- Incorrect word meanings. I used the English localization as a basis and selected the best match in Ukrainian.
- The ending of the word. For example: TR_NO_PICTURE

fix: Fixed grammatical errors in the :ukraine: translation

---

radio/src/translations/da.h
radio/src/translations/fi.h
radio/src/translations/he.h
radio/src/translations/ru.h
radio/src/translations/se.h

Align all translations for TR_ENTER on the #if logic used by English and Chinese.

fix(translation): harmonise TR_ENTER for PCBPL18

---

radio/src/storage/modelslist.cpp

Fixes a memory leak in modelslist.cpp's ModelMap::renameLabel occuring only if labels are too long.

fix(radio): memory leak in ModelMap::renameLabel

---

radio/src/gui/gui_common.cpp
radio/src/hal/module_port.h
radio/src/trainer.cpp

... for radios supporting S.Port SBUS input
Fixes https://github.com/EdgeTX/edgetx/issues/3678
- adds Master/SBUS Module Trainer mode (true idle low SBUS required) for Tx16s and other radios on S.Port pin
- the few Taranis radios not being able to use the S.Port Pin will still work on the HB pin
- added some comments to radio/src/gui/gui_common.cpp
Tested on NV14 and TX16s

Trainer: allow Master/SBUS Module mode on S.Port pin

---

companion/src/firmwares/boardjson.cpp
companion/src/firmwares/boards.h
companion/src/firmwares/edgetx/yaml_switchconfig.cpp
companion/src/firmwares/generalsettings.cpp

Fixes #4640
- load switch default for new settings file and not max positions
- load defaults before reading yaml file to handle cases where yaml file does not include the switch settings

fix(cpn): switches default types

---

radio/src/gui/colorlcd/widget.cpp

When selecting a widget the popup list has the names sorted in case sensitive order.
This puts widgets whose name starts with a lower case letter (e.g. showall0.9) at the end.
This PR changes the sorting to case insensitive.

feat(color): Use case insensitive sorting for list of widget names.

---

radio/src/targets/taranis/board.cpp

Issue being resolved:
- as I've commented previously and was just reminded of in a review, T14 will power itself on if the USB is connected to charge, and re-power itself (in EM) if powered off with the USB connected. 
- this will catch power-on via USB for any radio with soft power button, and effectivel hang it until disconnected, and then power off
- while we're here doin' nothin', flash those leds as a crude "state of charge" indicator. I had initially gone for a simple "on/off" blink, but then though someone would thing the handset was just resetting itself, hence the more elaborate and more heartbeat-like timing. 
It's just a PoC, and I'm not particuarly attached to the blinky light code - and if it stays the voltage values probably need tweaking. 
@3djc What do you think? 
edit: …

fix: halt T14 power up when USB connected

---

radio/src/storage/yaml/yaml_datastructs_funcs.cpp

Fix a crash when wanting to select T7/T8 +- switches (in logical switch for example)
This was happening on T20 for example.

fix: T7/T8 yaml handling

---

radio/src/lua/api_general.cpp

Fixes #4605
- lua serialRead is not limited to CLI, so shouldn't be disabled when CLI not present (i.e. it is no different to serialWrite). 
It would be interesting to know the justification for this... perhaps it was some attempt at preventing CLI "noise" being read by `serialRead()` - maybe there was a shared buffer at that time?

fix(lua): serialRead is not limited to CLI

---

radio/src/gui/gui_common.cpp

Relates to #3691
- only offer CLI as a valid mode for USB VCP
Tested on T20, TX16S and Boxer

fix(radio): limit CLI to USB-VCP

---

companion/src/logsdialog.cpp

Fixes #4690
- fixed initialization of plots.min_x to no longer check against current time.

fix(cpn): initialisation of log viewer x-axis should use log time, not system time

---

radio/src/mixer.cpp

Fix potential crash if source is a 'SpaceMouse' input; but SPACEMOUSE is not defined in the build.
Reported on discord that this combination can crash the simulator in Companion.
Has the potential to cause issues on a radio as well as the code is accessing an invalid memory location.
It is not clear how the user ended up with a space mouse input source on their radio.
Also affects 2.9.x.

fix(radio): invalid memory access if SpaceMouse input present but not supported

---

radio/src/translations/ua.h

- some colorlcd translation strings were missing for UA

fix: add missing ua translation strings

---

radio/src/gui/128x64/model_special_functions.cpp

As reported on Discord.
Two different code blocks were trying to handle the long press Enter key. The resulting conflict made it very hard to figure out how to adjust the value.
This looks like it has been an issue for a long time.
If there is going to be a 2.9 update then it should be applied there as well as to 2.10 and 2.11.

fix(b&w): Long ENTER not working correctly when using ADJUST GV SF

---

radio/src/gui/colorlcd/model_outputs.cpp
radio/src/gui/colorlcd/page.cpp
radio/src/gui/colorlcd/page.h
radio/src/gui/colorlcd/radio_theme.cpp
radio/src/gui/colorlcd/tabsgroup.cpp
radio/src/gui/colorlcd/trainer_bluetooth.cpp
radio/src/gui/colorlcd/view_main.cpp
radio/src/gui/colorlcd/view_main.h
radio/src/gui/colorlcd/widgets/widgets_container_impl.h
radio/src/gui/colorlcd/widgets_container.h

Fixes #4279 
All setup pages inherit from the Page or TabsGroup (via PageTab) classes. These block the main view so no main view updates are processed while in the setup pages.
This PR adds a function to call just the 'background' function for all active widgets when using the setup pages. It does not call any of the UI objects 'checkEvents' functions so the only overhead is the processing time each widget 'background' call takes. So long as the widgets are well behaved, and there is not an excessive number of them it should not significantly affect performance.
However it needs extensive testing on a variety of radios especially with complex widget setups (which I don't use).

feat(color): Run widget 'background' function while in setup pages.

---

radio/src/targets/nv14/hal.h

The problem is due to the change in this PR:
https://github.com/EdgeTX/edgetx/pull/3779
when Raphael tested the firmware with his EL18, he found that the SWB and SWD is swapped, so he change the mapping in the above PR.
However, it is found that there are chances that the ext ADC will randomly shift channel when working out the PL18EV target, and this problem is due to improper handling of DMA, and is fixed in the following PR:
https://github.com/EdgeTX/edgetx/pull/4563
Now, I have received a few users reporting the same SWB/SWD swapped and after checking with Flysky.  they confirms the 2.10.0-RC1 has this problem.
This PR restores the correct mapping of SWB and SWD.

fix(el18): SWB and SWD swapped

---

radio/src/opentx.cpp

This revisit #4523 based on latest info from ELRS team.
This only affect radio that go through the process of radio.yaml recreation

chore: auto select radio fastest supported baudrate for elrs

---

radio/src/telemetry/spektrum.cpp

Fixes #4715
**Fix processing of message 0x3A:**
1. Create individual Cells Sensors (Cel1..Cel6)
2. Create Grouped "Cels" sensor who contains all the Cells.  This is compatible with FrSky, and can be used as the source to compute the Min/Max Cell.
**Fix Temperatures to have no decimals, otherwise they will not convert correctly between C/F.**

fix(telemetry): process DSM LIPO Cells Monitor sensor correctly

---

companion/src/simulation/simulatorwidget.cpp

When using the advanced USB joystick mode on a transmitter the pots, sliders and 6POS switch mappings do not work correctly in the simulator - moving the control on the transmitter does not move the corresponding control in the simulator.
Missed in PR #4406

fix(cpn): Joystick pots, sliders and 6POS switch not working in simulator.

---

radio/util/hw_defs/switch_config.py

- Default switch configuration is are swapped for TLite for SB and SC (1x 3POS and 1x 2POS on each side, not the 3POS switches on the left and 2POS on the right right)

fix(tlite): default switch configuration wrong

---

companion/src/simulation/simulateduiwidgetJumperT12.cpp
companion/src/simulation/simulateduiwidgetJumperTLITE.cpp
companion/src/simulation/simulateduiwidgetLR3PRO.cpp

Fixes #4737 
Fixes key mapping for NAVIGATION_TYPE 9X radios.

fix(cpn): Keys do not work in simulator for T-Lite, T12 and LR3PRO

---

radio/src/gui/128x64/view_main.cpp

Fixes #4742 
Fix key mapping on main view for NAVIGATION_TYPE 9X.

fix(b&w): ENTER key does not work on main view for T12, T-Lite and LR3PRO

---

radio/src/targets/simu/adc_driver.cpp

The battery level reported to the simulator is supposed to be halfway between battery min and max.
Fixes the initial value for the battery ADC channel in the simulator to match the code that converts this to a battery voltage.

fix(cpn): battery level incorrect in simulator for B&W radios

---

radio/src/gui/128x64/model_special_functions.cpp

Fixes #4750 
Adjust position of Play Value SF parameter to handle longer names.

fix(bw): SF Play Value parameter display clipped on 128x64 B&W

---

companion/src/simulation/simulatorwidget.cpp

Use T20 simulator UI for T20V2.

fix(cpn): T20V2 simulator uses the 9X UI in Companion.

---

radio/src/targets/taranis/hal.h

chore: redefinition warning for `INTMODULE_BOOTCMD_GPIO`

---

radio/src/gui/colorlcd/file_browser.cpp

When using the Radio SD Manager, after an image is selected, the displayed bitmap may not get cleared if the touch screen is used to change folder.

fix(color): displayed image not always cleared when changing folder in SD browser

---

radio/src/main.cpp

On B&W radios, when the USB mode is set to 'ask' and a USB cable is connected a popup menu is shown.
If the USB cable is disconnected before a choice is made, the popup menu does not close.
This PR closes the popup menu when the USB cable is disconnected.

fix(bw): USB popup menu may not close.

---

radio/src/targets/common/arm/stm32/bootloader/boot.cpp

Fixes the bootloader startup on the MT12 to be activated by pulling T1 and T2 towards each other.

fix(mt12): bootloader startup uses wrong trim switch direction.

---

radio/src/gui/128x64/view_main.cpp

On radios like the T20, where there are more than 3 dials/sliders, the bottom row of bars can overlap the top row.
When a bar on the bottom row is at maximum value it overlaps the top row by 1 pixel.
This PR adjust the position and size of the bars so there is always a 1 pixel gap between the two rows.
Before - note the uneven appearance of the bottom point for the top row of bars.
After - consistent display with 1 pixel gap.

fix(b&w): dial/slider bars can overlap on main view

---

radio/src/gui/128x64/view_main.cpp
radio/src/gui/212x64/view_main.cpp
radio/src/gui/colorlcd/layouts/trims.cpp

Do not draw the trim position indicator when trims are set to 3POS

chore: Do not display trims position when trim is set as 3POS

---

companion/src/firmwares/opentx/opentxeeprom.cpp

Fixes #4734
- The use of dynamic json hardware definitions breaks the binary import so regress to using pre-adc hardcoded values in the binary import.
- map binary sources to json sources fixing tx16s x12s x9e
- fix Error loading models and settings created by ETX v2.5.0 for Horis and tx16 families bump version when newer custom screens came into being ie 2.5 to 2.6 (Note: this is an issue for 2.9.4 too)
- debug messages added and commented out
- where getCapability replaced with pre 2.10 hard coding the call is commented out and left as a future reference
Tested:
- Companion radio profiles x9dp, x9e, x12s tx16s
- models and settings created by OpenTX 2.3.15 Companion binary data version 219
- models and settings created by EdgeTX 2.5 Companion binary data version 220 …

fix(cpn): application crash, binary load error and binary source value mapping inconsistencies

---

companion/src/updates/repo.cpp
companion/src/updates/repoassets.cpp
companion/src/updates/updatemultiprotocol.cpp
companion/src/updates/updatenetwork.cpp
companion/src/updates/updatenetwork.h

Fixes #4773
- increase the maximum results per page from 50 to 100 for multi protocol update
- use different gh media types for repo content and release asset json files (use case sd card fallback to content when no release asset found)

fix(cpn): multi protocol and sd card updates

---

radio/src/gui/128x64/radio_setup.cpp
radio/src/gui/common/stdlcd/features.h

Allow configuration of the Oled equivalent of LCD backlight control, where Oled will dim to the minimum where LCD equivalent backlight off.
Fixes #4789

feat: allow configuration of auto dimming for OLED screen

---

companion/src/firmwares/edgetx/yaml_modeldata.cpp
companion/src/firmwares/edgetx/yaml_rawsource.cpp
companion/src/firmwares/edgetx/yaml_rawswitch.cpp

Fixes #4759 and also display message for each model file where the version is ahead of Companion.

fixcpn): use model semver over radio semver for decoding model sources and switches

---

companion/src/firmwares/moduledata.cpp

fix(cpn): allow PPM and SBUS on external rf standard size module

---

radio/src/gui/colorlcd/model_gvars.cpp

feat(color): show FM name and number in GV edit page

---

radio/src/io/bootloader_flash.cpp
radio/src/targets/horus/bootloader/boot_menu.cpp
radio/src/targets/nv14/bootloader/boot_menu.cpp
radio/src/targets/pl18/bootloader/boot_menu.cpp
radio/src/targets/taranis/bootloader/boot_menu.cpp

Only allow to flash firmware when firmware target matches radio type
Tested on BW and TX16S
Should be ok but untested on NV14 and PL18

feat: only allow flash when target matches

---

radio/src/telemetry/frsky_sport.cpp

Fixes #4729
Bug report that Roll/Pitch should be from -180 to +180, so needs to be a signed 16 bits number.
**Change Angles to be processed as Signed int16**

fix(telemetry): frsky angles should be be signed (allow negative)

---

radio/src/storage/storage_common.cpp

While initial position was loaded on radio startup, "someone" forgot to load it on model changes too ...
Sorry

fix: custom switches startup position need to be loaded on model change

---

radio/src/gui/gui_common.cpp

The modelHasNotes() function allocates a string on the stack that is only long enough to handle the English version of STR_MODEL.
When using a non-English language build where the STR_MODEL string has unicode characters encoded with 2-byte or 3-byte character sequences, the modelHasNotes() function will cause a stack overflow.

fix: Stack overflow in some non-English language versions.

---

radio/src/cli.cpp
radio/src/targets/common/arm/stm32/usbd_cdc.cpp

Fixes #4731
Fixes #4740 
- removed wait for send state from `usbSerialPutc()`.
- use `usbPlugged()` instead of `cdcConnected` as the later is updated from the UI task which is blocked while in passthrough mode.

fix(usb): do not wait for send state

---

radio/src/gui/128x64/lcd.cpp
radio/src/gui/128x64/lcd.h
radio/src/gui/212x64/lcd.cpp
radio/src/gui/212x64/lcd.h
radio/src/gui/common/stdlcd/fonts.cpp
radio/src/gui/common/stdlcd/fonts.h
radio/src/gui/common/stdlcd/utf8.cpp

The fix in PR #4806 for handling language special characters in the B&W fonts did not work correctly for the 10x14 font.
This PR fixes that and cleans up the font handling to make the different font sizes more consistent.
It will now allow more than 64 special characters for language translation (if it is ever required).
It also fixes the STR_CHAR_UP and STR_CHAR_DOWN display on 128x64 size screens for the 4x6, 8x10 and 10x14 font sizes.

fix(bw): language special characters not working for 10x14 font size

---

radio/src/lua/interface.cpp
radio/src/main.cpp

Ignore unwanted key events when using Lua scripts:
- For B&W radios with a single PAGE key, kill the EVT_KEY_BREAK event after a long press of the PAGE key (duplicates #2668 functionality for B&W radios).
- For all radios, when a Lua standalone script exits, kill all pending events. Prevents the script from restarting if a long press of the ENTER key is used to exit the script.

fix(lua): ignore potential unwanted key events

---

radio/src/gui/128x64/model_telemetry_sensor.cpp
radio/src/gui/212x64/model_telemetry_sensor.cpp
radio/src/gui/colorlcd/model_telemetry.cpp
radio/src/telemetry/telemetry_sensors.cpp

Fixes #4723
1. Fixes converting from C to F (and vice versa) when the Temperature has decimal places.
2. Optimization: Remove loop to do 10^n, and use a table "Power10[n]" to change from one Prec to another.
3. Optimization: Only do the conversion if needed, i.e, Different UNIT or different Prec
4. Move the exception of not displaying "Precision" on 3 different GUIs when sensor is UNIT_FARENHEITH to a single share code by all GUIs.` TelemetrySensor::isPrecConfigurable()` is only used for this UI purpose, nowhere else.
Left the Precision not been configurable when sensor is UNIT_FARENHEITH, (same behavior as before).  I think this is because is already granular enough compared to UNIT_CELSIOUS.
Examples: Using LemonRX Gen2 who has a temperature sensor embeded.
NOTE: …

fix(telemetry): temperature UNIT conversion when temperature has decimals

---

radio/src/targets/common/arm/stm32/usbd_conf.h

Currently the longest string encoded by the USB interface is "Radiomaster Pocket Mass Storage".
The USB string descriptor for that is:
66 bytes = 1 (length) + 1 (type) + 32 * 2 (payload in UTF 16)
Reduce the buffer size from 512 to 98.
The longest supported string length thus changes from 255 chars to 48 chars.

chore(radio): reduce USB string buffer by 414 bytes

---

radio/src/gui/colorlcd/model_setup.cpp
radio/src/gui/colorlcd/preflight_checks.cpp
radio/src/translations/cn.h
radio/src/translations/cz.h
radio/src/translations/da.h
radio/src/translations/de.h
radio/src/translations/en.h
radio/src/translations/fr.h
radio/src/translations/he.h
radio/src/translations/it.h
radio/src/translations/pl.h
radio/src/translations/ru.h
radio/src/translations/se.h
radio/src/translations/tw.h

The 'Center Beep' setting does not really belong in Pre-start Checks.
This PR moves Center Beep and ADC filter into a new model setup page (to avoid cluttering the main setup page).

feat(color): move ADC Filter and Center Beep settings to 'Other' page

---

radio/src/gui/128x64/model_flightmodes.cpp

Fix missing GV9 in FM0 for radio that have more than 4 trims
Fixes #4848
@pfeerick  this is needed for 2.10 imho

fix: GV9 missing on FM0 when trims > 4

---

radio/src/gui/colorlcd/special_functions.cpp

Fixes #4860 
Fixes stack overflow when creating the function string for the SF list view.

fix(color): crash in SF list when using CN or TW translations.

---

radio/src/gps.cpp
radio/src/gps_ubx.cpp

Summary of changes: When NMEA messages are received (i.e. the baud rate is correct), the handset waits for up to 2 seconds to receive a valid UBX packet. When there are no UBX packets within a 2 second period, NMEA is selected.

feat(radio): prefer UBX over NMEA when both supported

---

radio/src/gui/colorlcd/startup_shutdown.cpp
radio/src/opentx.cpp
radio/src/tasks.cpp

Wait for splash screen to finish before showing throttle and switch alerts.
Use theme color for shutdown animation background.
Fixes #4855

fix(color): restore previous startup and shutdown functionality.

---

radio/src/translations/de.h

Fixes #3430
Some bootloader strings too long for 128x64 DE. Multi-line is not practical atm as `lcdDrawCentredLine` doesn't appear to like line breaks.

fix(de): bootloader translations too long

---

radio/src/audio.h
radio/src/bin_allocator.cpp
radio/src/bin_allocator.h
radio/src/cli.cpp
radio/src/gui/navigation/common.cpp
radio/src/hal/fatfs_diskio.cpp
radio/src/logs.cpp
radio/src/lua/interface.cpp
radio/src/opentx.h
radio/src/pulses/crossfire.cpp
radio/src/rtos.h
radio/src/sdcard.cpp
radio/src/targets/common/arm/stm32/audio_dac_driver.cpp
radio/src/targets/common/arm/stm32/bootloader/bin_files.cpp
radio/src/targets/common/arm/stm32/sdcard_spi.cpp
radio/src/targets/common/arm/stm32/stm32_exti_driver.cpp
radio/src/targets/common/arm/stm32/stm32_spi.cpp

clean up uncritical compiler warnings where `0`  was used instead of `nullptr` / `NULL`

chore(radio): cleanup -Wzero-as-null-pointer-constant warnings

---

radio/src/targets/taranis/CMakeLists.txt
radio/src/targets/taranis/hal.h

Removed as per Jumper request as it is not available on final hardware

chore(t14): remove unused ws2812

---

radio/src/gui/colorlcd/view_statistics.cpp

Show mixer period in statistic on colorlcd as it is done on BW radio

chore(color): display mixer period in statistic screen

---

radio/src/targets/taranis/board.cpp

Ensure radio stabilized before trying to measure vbat in charge mode
Fixes #4872
Confirmed ok by manufacturer.
@pfeerick : Please include in 2.10

fix(t14): charge led sometimes pink at USB connection

---

radio/src/targets/pl18/board.cpp
radio/src/targets/pl18/board.h

When work on some further development, discovered that the USB detection pin in PL18/PL18EV can be uninitialized in bootloader mode, this can cause potential problem.

fix(pl18): USB detect pin can be uninitialized in bootloader

---

radio/src/gui/128x64/model_flightmodes.cpp
radio/src/gui/128x64/model_select.cpp
radio/src/gui/common/stdlcd/menus.cpp
radio/src/gui/common/stdlcd/menus.h
radio/src/gui/navigation/navigation_9x.cpp
radio/src/keys.h
radio/src/main.cpp

From 2.10 the menu navigation on 9X style radios (T-Lite, T12 and LR3Pro) does not work correctly.
Issues:
- Horizontal navigation on the SF/GF list does not work. Cannot select all properties for each SF/GF type.
- The FM list view has too many lines. Scrolling up from the top shows two blank lines at the bottom.
- Returning from the FM edit page to the FM list view may show the list view with the wrong scroll position if the edit page was scrolled to the bottom before exiting. Also affects other B&W radios when using long press to exit FM edit page.
- The short press of the EXIT key following a long press to exit a subpage was not being killed resulting in spurious activation of the EXIT key. Also affects other B&W radios.
Fixing the above issues caused other issues requiring more fixes …

fix(bw): multiple issues with menu navigation for 9X type radios

---

radio/src/keys.h

Fixes regression introduced in #4884 whereby popup menu navigation is using L/R rather than Up/Down. Which may be trying to fix something in the navigation broken back in #3715 or earlier.

fix: menu up/down on 9x nav

---

radio/src/gui/colorlcd/model_templates.cpp

When creating a new model the pages that show the list of folders/templates do not have a scroll bar when the list is longer than the page size.

feat(color): missing scroll bar on model template select pages.

---

radio/src/translations/cn.h

For some reason, one item of the main menu in Chinese was using a '\n'
Currently
With this change
Reported by a partner (as you can guess, my Chinese knowledge is non existent)

chore: all Chinese main menu items on one line

---

radio/src/gui/colorlcd/model_select.cpp
radio/src/sdcard.h

Change personal template folder name to match SD card layout.
Fixes #4885

fix(color): personal templates saved to wrong folder

---

radio/src/storage/sdcard_common.cpp

Fixes an issue where, after creating a new model, two copies of the first model screen are added to the main view.
Can be reproduced by:
- select a model with all trims and sliders showing on main view
- create a new model using the 'Wing' wizard.
- note the duplicated trim/slider widgets on the main view.

fix(color): extra sliders and trims on main view after creating a new model.

---

companion/src/firmwares/edgetx/yaml_rawswitch.cpp

Fixes #4898
Note: I have not tested on hardware or simulator

fix(cpn): T-Pro function switches

---

radio/src/gui/screenshot.cpp

Inverts the black and white screen shot for OLED screen radios.

fix(bw): screen shots saved on radios with OLED screens inverted

---

radio/src/gui/colorlcd/file_preview.cpp
radio/src/thirdparty/libopenui/src/static.cpp
radio/src/thirdparty/libopenui/src/static.h

Images that are smaller than the preview window size are shown actual size (to match the 2.9 functionality).

fix(color): don't enlarge image in the file preview window.

---

radio/src/gui/128x64/radio_diaganas.cpp

Remove text overlap for line with longer names.
Before:
After:

fix(bw): analog debug page text overlap

---

radio/src/gui/common/stdlcd/model_usbjoystick.cpp

Fixes some potential crashes when editing the advanced USB settings on B&W radios.

fix(bw): potential crash when editing USB advanced setup

---

radio/src/gui/colorlcd/afhds2a_settings.cpp
radio/src/lua/interface.cpp

Looks like there was a missing `)` on some normally unused debug code, and a `}` in the wrong place for the NV14. 
The latter fix is probably needed in 2.10

fix: some cppcheck errors

---

radio/src/gui/colorlcd/view_text.cpp

Discovered by John on RC Video Reviews.

fix(color): last interactive checklist line not shown if EoF not newline

---

radio/src/gui/colorlcd/widgets/outputs.cpp

If the width is even then the bar does not extend fully to the left edge.

fix(color): ensure outputs widget channel width is odd for symmetrical display

---

radio/src/targets/common/arm/stm32/usbd_hid_joystick.c

USBD_HID_CONFIGURATION_FS_STRING and USBD_HID_INTERFACE_FS_STRING are defined but never used because the string IDs in the joystick descriptor are 0.
output from `lsusb -d 1209:4f54  -v` before:
> iConfiguration          0
> iInterface              0
output from `lsusb -d 1209:4f54  -v` after:
> iConfiguration          4 HID Config
> iInterface              5 HID Interface

chore(radio): actually use the defined USB joystick strings

---

radio/src/targets/common/arm/stm32/usbd_desc.c

Report the actual EdgeTX version in the USB device descriptor instead of a fixed "2.00"
Fixes #4903

fix(usb): report correct version number (#4903)

---

radio/src/gui/128x64/model_telemetry.cpp
radio/src/gui/212x64/model_telemetry.cpp
radio/src/gui/colorlcd/model_telemetry.cpp
radio/src/gui/gui_common.cpp
radio/src/gui/gui_common.h

Some people have a tendency to try to select Alt sensors as vario source, this change prevents it

feat: use only vario sensor for vario source

---

radio/src/targets/horus/board.cpp
radio/src/targets/nv14/board.cpp
radio/src/targets/nv14/board.h
radio/src/targets/pl18/board.cpp
radio/src/targets/pl18/board.h
radio/src/targets/taranis/board.cpp

Fixes #4958
**Summary of changes:**
#3814 implicitly exposed an assumption whereby AUX1 was being initialised for use for debugging when not available, and thus locking "Debug" out as an option for USB-VCP on radios with no available AUX1. Therefore, check if AUX_SERIAL is defined as well as DEBUG.

fix(debug): don't initalise SP_AUX1 if not exist

---

radio/src/telemetry/telemetry_sensors.cpp

Fixes #4874 
- struct TelemetrySensor holds the true unit after changing the unit manually
Background: All telemetry decoders communicate values and their units based on their intended and therefore constant data structs. At the time of discovery the data is stored to struct TelemetrySensor to be written (in parts) to modelxx.yml. A manual change of the unit will also be reflected in struct TelemetrySensor. At run-time the telemetry decoders call setTelemetryValue() but with the originally defined unit. Further down the call-tree setValue() accepts the value and unit of the telemetry sensor and scans if the unit is one of the "to be treated specially" units, like UNIT_CELLS,  UNIT_DATETIME_YEAR, etc but also UNIT_RPMS which requires a "special" and different scaling …

fix(telemetry): wrong scaling after changing unit to rpm

---

radio/src/gui/navigation/common.cpp
radio/src/keys.h

fix(bw): editing names on 9x/xlite nav radios & popup menu using wrong keys/events

---

companion/src/firmwares/sensordata.cpp

Spotted three missing unit strings when testing #4963. Reordered to match order in sensordata.h
No-one has complained, but 2.10 might as well have it also.

fix(cpn): missing telem unit strings

---

radio/src/gui/128x64/view_main.cpp

Fixes #4975 
- Adjust position of switch names to allow more room
- Center justify switch names so it looks more balanced.

fix(bw): adjust 128x64 layout to accommodate long switch names

---

radio/src/datastructs.h

- adds missing ModelData for RM Pocket
- also missing in 2.10, and struct is the same size

chore: missed check for Pocket ModelData size

---

radio/src/translations/he.h
radio/src/translations/jp.h
radio/src/translations/ru.h
radio/src/translations/ua.h

Modified translations had non-ASCII text for the bootloader, although the translations blocks specifically said ASCII only. 
Also, Hebrew translation had missing defines for the PL18

fix: replace non-compliant translations with EN ASCII

---

radio/src/gui/128x64/view_main.cpp

Fixes switch display on B&W radios with more than 6 switches.
Candidate for 2.10.1.

fix(bw): use small switch layout when more than 6 switches

---

radio/src/gui/colorlcd/model_select.cpp
radio/src/gui/colorlcd/model_select.h

In single select mode, adding new labels, deleting labels and moving labels does not update the selected label and model list correctly.
This is the fix for 2.10.

fix(color): selected label, model list not correctly updating in single select mode

---

companion/src/firmwares/opentx/opentxinterface.cpp

Fixes #5034
- force loading of board hardware definitions for each firmware checked
- skip otx firmwares where fourcc is not unique and not a match for the current radio profile board eg X9D, X9D+ and X9D+ 2019. Assume you have only one radio of the group and it is your current profile. Risk that data is interpreted incorrectly ie corrupted or worse app crash. Would mainly affect devs. This issue goes back to OTX days.

fix(cpn): ensure hardware definitions are loaded when reading binary files

---

radio/src/storage/storage_common.cpp

Stops forced  re-write of the selected model file on startup when firmware is built with PXX2=ON.

fix(pxx2): prevent unnecessary model yaml rewrite on load

---

companion/src/firmwares/edgetx/yaml_generalsettings.cpp
companion/src/firmwares/edgetx/yaml_switchconfig.cpp
companion/src/firmwares/generalsettings.cpp

Fixes #5018
- set all inputs and switches to None prior to parsing radio.yml
- remove loading default hardware definitions from within general settings init as not always wanted
- remove loading default hardware definitions before parsing switch settings as performed in general settings
- move needs conversion test to after final parse step (housekeeping)

fix(cpn): set input and switch types to none if not configured

---

tools/build-companion.sh

Although this is really to add hwdef for cpn
Tested linux build, just waiting for remaining tests before merge.

fix: add missing t20v2 simulator

---

.github/workflows/actions.yml
radio/src/targets/taranis/CMakeLists.txt

- typo in nightly action
- remove redundant CPU_TYPE

chore: fix ci typo, remove redundant CPU_TYPE

---

radio/src/gui/colorlcd/theme_manager.cpp

The load fails because the SD card is not started; but it should not even try.

fix(color): stop attempt to load themes when in emergency mode

---

radio/src/gui/colorlcd/listbox.cpp
radio/src/gui/colorlcd/listbox.h
radio/src/gui/colorlcd/model_select.cpp

Move the selected marker / text up and use a smaller font to avoid text overlap.
@pfeerick I don't this will cherry pick cleanly into 2.10. If you think this should go into 2.10.1 let me know and I can create a separate PR.
Fixes: #5071

fix(color): adjust layout of model labels list to reduce text overlap

---

companion/src/updates/updateinterface.cpp
companion/src/updates/updateinterface.h

fix(cpn): validate translated update component name when used for folder name

---

radio/src/gui/128x64/model_telemetry_sensor.cpp
radio/src/gui/212x64/model_telemetry_sensor.cpp
radio/src/gui/colorlcd/model_telemetry.cpp
radio/src/strhelpers.cpp
radio/src/strhelpers.h

Fixes #4648
**Works in main as well as 2.9 branch.**
Changes are isolated in the display portion of the UI
Change the Telemetry Sensor Edit to show the equivalent percentage.
Works on color and B&W radios.

feat(radio): modify Sensor Edit screens to show Ratio + Percentage

---

radio/src/targets/common/arm/stm32/usb_driver.cpp
radio/src/targets/common/arm/stm32/usbd_hid_joystick.c
radio/src/usb_joystick.cpp

Analog USB joystick axis are encoded as unsigned integers ranging [0 - 2047]. As a consequence input value 0 is reported as output 1024. This leads to asymmetric output: 1024 values smaller than 0 and 1023 values larger than 0.
mixer.cpp generates values [-1024 to +1024] (11 bit + 1) instead of [-1024 to +1023] (11 bit). Luckily the HID report descriptor  already reserves 16 bits so the shift from 11 bit to 12 bit output is easy.
Fix EdgeTX/edgetx#4881 by changing the joystick range from [0 - 2047] to [0 - 2048].

fix(radio): properly center analog USB joystick axis

---

radio/src/gui/common/stdlcd/model_usbjoystick.cpp

fix(bw): incorrect navigation in advanced USB setup on X9 radios

---

radio/src/gui/colorlcd/radio_diagcustswitches.cpp

Also removed unused code from radio_diagcustswitches.cpp.

fix: failing DEBUG simulator build for radios without customisable switches

---

radio/src/gui/colorlcd/radio_trainer.cpp
radio/src/translations/cn.h
radio/src/translations/da.h
radio/src/translations/en.h
radio/src/translations/he.h
radio/src/translations/jp.h
radio/src/translations/nl.h
radio/src/translations/pt.h
radio/src/translations/ru.h
radio/src/translations/ua.h

- on bw212, the "Slave" text was off-center due to double centering. had no effect on bw128
- on colorlcd, master trainer settings were still visible when in master mode, whereas hidden on B&W

fix(radio): correct different B&W and colorlcd trainer slave UI behaviour

---

radio/src/gui/colorlcd/layouts/layout_factory_impl.h
radio/src/gui/colorlcd/layouts/topbar_impl.cpp
radio/src/gui/colorlcd/layouts/topbar_impl.h
radio/src/gui/colorlcd/theme.cpp
radio/src/gui/colorlcd/theme.h
radio/src/gui/colorlcd/view_main.cpp
radio/src/gui/colorlcd/view_main.h
radio/src/gui/colorlcd/widget.cpp
radio/src/gui/colorlcd/widget.h
radio/src/gui/colorlcd/widgets_setup.cpp

Fixes #4371 & #2629 
Rework the way 'full screen' mode is selected for widgets.
> It uses the 'EdgeTX' button in the top left to differentiate mode - at the moment I need this to have a way to open the quick menu (tapping on the widget will not work).
>
> 'App mode' is enabled by creating a layout with 1 widget (the 'full screen' layout) and turning off the topbar, flight modes, sliders and trims.
>
> - The default 'app mode' view would be the selected widget (full screen); but also still showing the EdgeTX button in the top left corner (visual indicator of mode). Keys and touch events are not passed to the widget. Swiping can be used to change view and enter/touch brings up quick menu.
> - A long ENTER press or long touch on the screen hides the EdgeTX button and directs key and touch …

feat(color): widget app mode

---

radio/src/gui/colorlcd/model_mixer_scripts.cpp
radio/src/gui/colorlcd/model_setup.cpp
radio/src/gui/colorlcd/special_functions.cpp
radio/src/thirdparty/libopenui/src/choice.h
radio/src/thirdparty/libopenui/src/filechoice.cpp
radio/src/thirdparty/libopenui/src/filechoice.h
radio/src/thirdparty/libopenui/src/menutoolbar.cpp
radio/src/thirdparty/libopenui/src/menutoolbar.h

Change the file chooser popup to have filters like the switch and source popups.
Also adds the title to the file chooser.
Only shows filter buttons if there are actual files matching the filter.

feat(color): add filters to file chooser popup menu

---

radio/src/logs.cpp
radio/src/telemetry/telemetry.cpp

After loosing telemetry all sensor values will be frozen at the last valid value. This is nice feature that can be used to retrieve the last known GPS position of a crashed model by e.g. looking at the model settings/telemetry screen. However logging frozen values doesn't make much sense as they give the impression of live recorded data. 
This PR clears the sensor data written to the log file to their initial state in case telemetry is not streaming. That makes it easy to spot  "no live telemetry" phases in the log file or log charts.

Logs: reset telemetry sensor data to inital state if telemetry is not streaming

---

radio/src/gui/128x64/model_logical_switches.cpp

Fixes #5087
Side effect of ENTER key handling arising from changes in #4849

fix(bw): unresponsive rotary encoder after using popup menu on LS page

---

radio/util/hw_defs/switch_config.py

Fixes #5092
Move 2nd column of switches back to right side of the display.

fix(x9d): incorrect switch positions on main view

---

radio/src/targets/common/arm/stm32/stm32f2xx_hal_conf.h

Fixes the bootloader start speed and USB issues mentioned in https://github.com/EdgeTX/edgetx/pull/5023#issuecomment-2143165097.

fix(f2): system clock initialisation

---

radio/src/gui/128x64/model_outputs.cpp

- also allow for long press of ENT for popup menu on outputs page

fix(bw128): long press for outputs page popup menu

---

radio/src/gui/colorlcd/lcd.cpp
radio/src/targets/horus/lcd_driver.cpp
radio/src/targets/simu/simulcd.cpp
radio/src/thirdparty/libopenui/thirdparty/CMakeLists.txt

- initialise only the bare minimum of LVGL to use the `lv_draw_` routines.
- saves 24 KB in color LCD bootloader.

perf(color): reduce bootloader size

---

radio/src/gui/colorlcd/channel_bar.cpp
radio/src/gui/colorlcd/channel_bar.h
radio/src/gui/colorlcd/custom_failsafe.cpp
radio/src/gui/colorlcd/gvar_numberedit.cpp
radio/src/gui/colorlcd/gvar_numberedit.h
radio/src/gui/colorlcd/model_outputs.cpp
radio/src/gui/colorlcd/output_edit.cpp
radio/src/gui/colorlcd/radio_setup.cpp
radio/src/gui/colorlcd/widgets/outputs.cpp
radio/src/strhelpers.cpp
radio/src/strhelpers.h

Fixes #4977 and #3163
I've tried to match all the places that the PPM_US setting is used on B&W radios.
Channel monitor. Note if using PPM_US setting the value at the right above each channel changes to % instead of showing us value.
Custom failsafe settings:
Outputs list (min/max values):
Outputs widget:

feat(color): support PPM_US setting

---

radio/src/gui/128x64/lcd.cpp

Fixes #5106 
Don't display the telemetry symbol due to limited space available.

fix(bw128): telemetry source name overlaps V1 value on logical switch list view

---

radio/src/telemetry/mlink.cpp

... if all MLink addresses (telemetry items) are used to avoid telemetry lost/telemetry recovered mania 
tested with MPM/MLink and PPM/MLink
@pfeerick please consider cherry picking this into 2.10.x

fix(mlink): sometimes need > 1s timeout for MLink telem

---

radio/src/gui/128x64/model_logical_switches.cpp

Started with this
then noticed the final SWITCH col didn't take into account possible 4 characters
Then tweaked a little more and ended up with
Not entirely satisfied though as ends up cramped to allow for max possible lengths... but IMO better than overwriting values. 
Open to alternatives ;)

fix(bw128): column spacing for LS allowing for max values

---

radio/src/io/multi_firmware_update.cpp

Use proper timeout instead of MCU speed dependent loops
This fixes #5110
If confirmed solving the issue, needs to be cherry picked on main too

fix: timings for MPM update due to faster F4 MCUs

---

radio/src/gui/colorlcd/radio_version.cpp
radio/src/targets/horus/board.h
radio/src/targets/horus/hal.h
radio/src/targets/horus/lcd_st7796s_driver.cpp

Support for T15 version with IPS screen in 2.10 branch

feat: Jumper T15 IPS screen support

---

companion/src/firmwares/edgetx/yaml_generalsettings.cpp
companion/src/firmwares/generalsettings.h
companion/src/generaledit/generalsetup.cpp
companion/src/generaledit/generalsetup.h
companion/src/generaledit/generalsetup.ui
radio/src/datastructs_private.h
radio/src/gui/128x64/radio_setup.cpp
radio/src/gui/common/stdlcd/radio_hardware.cpp
radio/src/storage/sdcard_yaml.cpp
radio/src/storage/yaml/yaml_datastructs_128x64.cpp
radio/src/storage/yaml/yaml_datastructs_t20.cpp
radio/src/storage/yaml/yaml_datastructs_tpro.cpp
radio/src/storage/yaml/yaml_datastructs_xlites.cpp
radio/src/targets/simu/simpgmspace.cpp
radio/src/targets/taranis/board.h
radio/src/targets/taranis/lcd_driver_spi.cpp

Tested on OLED (T14 and T20v2) and LCD (X7, MT12 and TLite).
TODO:

feat(bw128): add option to invert LCD/OLED display

---

companion/src/firmwares/opentx/opentxinterface.cpp
radio/src/dataconstants.h
radio/src/datastructs.h
radio/src/datastructs_private.h
radio/src/gui/128x64/model_special_functions.cpp
radio/src/storage/yaml/yaml_datastructs_128x64.cpp
radio/src/storage/yaml/yaml_datastructs_nv14.cpp
radio/src/storage/yaml/yaml_datastructs_pl18.cpp
radio/src/storage/yaml/yaml_datastructs_t20.cpp
radio/src/storage/yaml/yaml_datastructs_tpro.cpp
radio/src/storage/yaml/yaml_datastructs_x10.cpp
radio/src/storage/yaml/yaml_datastructs_x12s.cpp
radio/src/storage/yaml/yaml_datastructs_xlites.cpp

Fixes #5044 
Wide screen B&W radios have a limit of 8 characters for the file name parameter (sound files and script files).
Color and 128x64 B&W radios limited this to 6 characters.
Color radios have plenty of memory so can easily handle an 8 character limit.
128x64 B&W radios allocated space for 8 characters even though only 6 where allowed - so increasing the limit does not use any more RAM.
A small tweak to the 128x64 UI allows the longest 8 character name to still fit on the SF/GF setup page.
Possible candidate for 2.10.1.

feat(radio): increase length of sound/script file name to 8 for SF/GF

---

companion/src/firmwares/boards.cpp
companion/src/firmwares/boards.h
companion/src/firmwares/generalsettings.cpp

The default battery range set up in Companion was missing entries (e.g. NV14, EL18, PL18).
If a blank document is created the battery range was set to 9V - 12V - resulting in continuous battery warnings in the simulator,
Moved the battery range settings to boards.cpp and aligned the values with what is currently set in the firmware.

fix(cpn): change the default battery range to match firmware

---

radio/src/gui/colorlcd/channel_bar.cpp
radio/src/gui/colorlcd/channel_bar.h

Small changes in channel value (e.g. noise in gimbals) would trigger an unnecessary refresh of the channel bar.

fix(color): remove unnecessary updates of channel bar

---

companion/src/datamodels/compounditemmodels.cpp
companion/src/firmwares/rawsource.cpp
radio/src/gui/colorlcd/sourcechoice.cpp

Fixes:
- Companion crashes when editing radio settings for radios without function switches.
- Add GRx sources to switch filter when selecting a source (color radios).

fix(cpn): crash when going into radio settings due to customisable switch groups source

---

companion/src/generaledit/generalsetup.cpp
companion/src/generaledit/generalsetup.h
companion/src/generaledit/generalsetup.ui
radio/src/gui/128x64/radio_setup.cpp
radio/src/gui/212x64/radio_setup.cpp
radio/src/gui/colorlcd/radio_setup.cpp
radio/src/gui/colorlcd/startup_shutdown.cpp
radio/src/opentx.cpp
radio/src/opentx.h
radio/src/translations/untranslated.h

Closes #5133
On color LCD also fixes:
- Shutdown animation did not show all four bars
- Highest power off delay option was shown as 4s; but the actual delay is only 3s (as per B&W radios).

feat: add 0.5 second option to power on/off delays

---

radio/src/opentx.cpp

Fixes issue where simulator is stuck on splash screen when started with the 'Simulate model' button.

fix(cpn): simulator may get stuck on splash screen.

---

radio/src/gui/gui_common.cpp
radio/src/trainer.cpp

Fixes #5139
- removed `#if defined(TRAINER_MODULE_SBUS_USART)` and just check presence of potential ports instead.

fix: check both SBUS trainer ports regardless of TRAINER_MODULE_SBUS_USART

---

radio/src/audio.cpp

Closes the file handle if a selected file on the SD card cannot be played for any reason.

fix(radio): close file handle if sound file cannot be played

---

companion/src/firmwares/generalsettings.cpp
companion/src/firmwares/moduledata.cpp
companion/src/firmwares/radiodataconversionstate.cpp
companion/src/firmwares/radiodataconversionstate.h
companion/src/firmwares/rawsource.cpp
companion/src/firmwares/rawswitch.cpp

Fixes #5137
- fix use profile default hardware switch type when file switch type not supported eg convert 3 Position to 2 Position
- fix hardware switch conversion to type (was reporting from)
- add 'unsupported' conversion type
- use 'unsupported' for hardware not existing in destination radio instead of 'invalid'
- when values 'invalid' also report conversion applied (future merge invalid and conversion rows - separate in this PR for expediency)

fix(cpn): profile conversion of models and settings

---

radio/src/thirdparty/libopenui/src/numberedit.cpp
radio/src/thirdparty/libopenui/src/textedit.cpp

After a number edit or text edit field is selected for editing, tapping on the same field will cause the background color to briefly flash. Long pressing on the field will change the background color to the non-edit color.
Cosmetic only - does not affect editing.

fix(color): cosmetic focus issue on text and number edit fields

---

radio/src/gui/colorlcd/function_switches.cpp

Remove top line "Startup" text now unused in customisable switches

chore(color): remove unused heading from UI

---

radio/src/gui/colorlcd/model_select.cpp
radio/src/thirdparty/libopenui/src/bitmapbuffer_fileio.cpp
radio/src/thirdparty/libopenui/src/static.cpp
radio/src/thirdparty/libopenui/src/static.h

Delay load the model images to improve responsiveness of the model select page.
The page loads quickly, instead of waiting for all the model images to be loaded from the SD card.
The model image will then populate after the page loads.

feat(color): delay image load on manage models page

---

companion/src/firmwares/generalsettings.cpp
companion/src/generaledit/hardware.cpp
companion/src/generaledit/hardware.h
radio/src/gui/colorlcd/hw_inputs.cpp
radio/src/gui/colorlcd/hw_inputs.h
radio/src/gui/common/stdlcd/radio_hardware.cpp

fix: hide 'invert' toggle for multipos switches

---

radio/src/model_init.cpp

When creating a new model for the T15 in the simulator the pre-flight checks state for the switches is incorrect.
SA is set to down instead of up.
Happens on MacOS, not tested on Linux or Windows.

fix(simulator): incorrect initialisation of preflight checks

---

radio/src/gui/colorlcd/function_switches.cpp
radio/src/gui/colorlcd/function_switches.h

Hide startup header when not in use

feat(color): hide customizable switch screen startup header when not used

---

radio/src/gui/colorlcd/CMakeLists.txt
radio/src/gui/colorlcd/layouts/layout_factory_impl.cpp
radio/src/gui/colorlcd/model_select.cpp
radio/src/gui/colorlcd/radio_sdmanager.cpp
radio/src/gui/colorlcd/radio_tools.cpp
radio/src/gui/colorlcd/standalone_lua.cpp
radio/src/gui/colorlcd/standalone_lua.h
radio/src/gui/colorlcd/view_main.h
radio/src/gui/colorlcd/widget.cpp
radio/src/gui/colorlcd/widget.h
radio/src/gui/colorlcd/widgets/timer.cpp
radio/src/lua/CMakeLists.txt
radio/src/lua/api_colorlcd.cpp
radio/src/lua/api_colorlcd.h
radio/src/lua/api_colorlcd_lvgl.cpp
radio/src/lua/api_general.cpp
radio/src/lua/interface.cpp
radio/src/lua/lua_api.h
radio/src/lua/lua_lvgl_widget.cpp
radio/src/lua/lua_lvgl_widget.h
radio/src/lua/lua_widget.cpp
radio/src/lua/lua_widget.h
radio/src/lua/lua_widget_factory.h
radio/src/lua/widgets.cpp
radio/src/lv_conf.h
radio/src/main.cpp
radio/src/thirdparty/Lua/src/linit.c
radio/src/thirdparty/libopenui/src/static.cpp
radio/src/thirdparty/libopenui/src/static.h
radio/src/thirdparty/libopenui/src/window.h

As discussed in #4627 
Sample scripts attached.
BattAnLvgl
- Rewrite of the BattAnalog script. This will work either with this PR or without. It demonstrates a simple pattern where the UI logic is split and the correct version is loaded when the script is run.
[BattAnLvgl.zip](https://github.com/EdgeTX/edgetx/files/14995388/BattAnLvgl.zip)
Lvgl
- Simple test widget demonstrating various features.
[Lvgl.zip](https://github.com/EdgeTX/edgetx/files/14995381/Lvgl.zip)
LvglMeter
- Test widget demonstrating the meter Lvgl object.
[LvglMeter.zip](https://github.com/EdgeTX/edgetx/files/14995377/LvglMeter.zip)
Lvgl Test Tool
- Test tool script demonstrating using the EdgeTX styled UI elements (buttons, toggle switch, edit box, etc).
Updated test tool zip file - see comment below - …

feat(lua): support for using LVGL objects on colorlcd

---

radio/src/targets/horus/hal.h

PCBREV now only uses PH8 on T15

fix: revise T15 PCBREV

---

radio/src/targets/nv14/bootloader/boot_menu.cpp
radio/src/translations/cn.h
radio/src/translations/cz.h
radio/src/translations/da.h
radio/src/translations/de.h
radio/src/translations/en.h
radio/src/translations/es.h
radio/src/translations/fi.h
radio/src/translations/fr.h
radio/src/translations/he.h
radio/src/translations/it.h
radio/src/translations/jp.h
radio/src/translations/nl.h
radio/src/translations/pl.h
radio/src/translations/pt.h
radio/src/translations/ru.h
radio/src/translations/se.h
radio/src/translations/tw.h
radio/src/translations/ua.h

Add bootloader specific strings for 'Enable' and 'Disable' used on NV14 and EL18.

fix(bootloader): use ASCII only strings for NV14/EL18

---

radio/src/serial.cpp
radio/src/targets/common/arm/stm32/pwr_driver.cpp

Fixes power been set when serial mode set to OFF and serial port power also set to OFF
Also fixes ON glitch at power on.
Fixes #5189

fix: serial power port handling

---

radio/src/switches.cpp

Properly show customisable switch name when one is defined
Fixes #5192
Another victim of ADC refactor 👯‍♂️

fix: customisable switch custom name not displayed

---

radio/src/opentx.h

Fixes an issue reported by Radiomaster in:
https://www.youtube.com/watch?v=18eATbYxygU&t=1s
Where you cannot select Axis as a source.
For 2.10.2 if possible as well please

fix: allow selection of axis as a source

---

radio/src/gui/colorlcd/standalone_lua.cpp

A stand alone script loads can load a second script by returning the script name from the run method.
When the second script exits, or is killed by long pressing the RTN key, the radio gets stuck in the first script instead of exiting back to the TOOLS menu.

fix(color): radio stuck when trying to close nested standalone script

---

radio/src/gui/colorlcd/widget_settings.cpp

Use fixed size for number edit field.

fix(color): incorrect size of number edit in widget settings for portrait layout.

---

radio/src/targets/common/arm/stm32/diskio_sdio.cpp
radio/src/thirdparty/FatFs/ffconf.h

This possibly fixes LUA sd corruption. This PR is raised to allow easier testing
While at it, use more sdio_check_card_state_with_timeout();
Finding by @philmoz 
This fixes #5077

fix: reduce file system corruption from standalone Lua scripts

---

radio/src/gui/colorlcd/color_editor.cpp
radio/src/gui/colorlcd/color_picker.cpp
radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
radio/src/gui/colorlcd/themes/etx_lv_theme.h

Fix padding for buttons on color editor dialog.
Fix color editor not working with rotary encoder.
Show border in EDIT color when changing color property with rotary encoder.
Focused:
Edited (with rotary encoder):

fix(color): issues with color picker dialog

---

radio/src/gui/colorlcd/LvglWrapper.cpp
radio/src/hal/rotary_encoder.h
radio/src/targets/common/arm/stm32/rotary_encoder_driver.cpp
radio/src/targets/horus/hal.h
radio/src/targets/simu/simpgmspace.cpp
radio/src/targets/taranis/hal.h

Re-write rotary encoder logic and update Lvgl driver to fix:
- detection of initial direction of encoder after startup
- change of direction issue on radios with incorrectly wired encoder
- handle all wiring variations (without needing special #defines)
May fix #3409 
Candidate for 2.10.2

fix(radio): various issues with rotary encoder.

---

radio/src/gui/colorlcd/widget.cpp

Fixes issue when long pressing on a widget, and then selecting 'Widget Settings', the first press on any button on the widget settings page may not work.

fix(color): first button press on widget settings page may not register

---

radio/src/gui/colorlcd/screen_setup.cpp
radio/src/gui/colorlcd/sourcechoice.cpp
radio/src/gui/colorlcd/switchchoice.cpp
radio/src/thirdparty/libopenui/src/filechoice.cpp
radio/src/thirdparty/libopenui/src/menu.cpp

Fix EM when shutting down if the layout select menu is open.
Fix double loading of menu content for file, source and switch menus.
Remove extra create/copy overhead on menu lines when building menu.

fix(color): issues with menus (possible EM, double loading of content)

---

radio/src/gui/colorlcd/LvglWrapper.cpp
radio/src/hal/rotary_encoder.h
radio/src/opentx.cpp
radio/src/opentx.h
radio/src/targets/common/arm/stm32/diskio_sdio.cpp
radio/src/targets/common/arm/stm32/rotary_encoder_driver.cpp
radio/src/targets/horus/hal.h
radio/src/targets/simu/simpgmspace.cpp
radio/src/targets/taranis/hal.h
radio/src/thirdparty/FatFs/ffconf.h

Fixes https://github.com/EdgeTX/edgetx/issues/5203
- the PR that keeps on giving - https://github.com/EdgeTX/edgetx/pull/3715 - changed the behaviour of reading the RTC battery, automatically disabling the vBatBridge after a run of adcRead(). Thus, it needs to be specifically enabled just before it is used, and technically doesn't need to be disabled, but that would mean more changes ;)
First two commits are unpushed cherry-picks - so ignore them for now.

fix: RTC boot check not working

---

radio/src/lua/interface.cpp

Fixes issues introduced with the Lvgl for Lua PR:
- standalone scripts without an 'init' function will not run
- syntax errors, or missing 'run' function may cause EM

fix(color): standalone Lua syntax errors or missing run() may cause EM

---

radio/src/gui/colorlcd/radio_hardware.cpp
radio/src/gui/colorlcd/radio_hardware.h
radio/src/opentx.cpp
radio/src/opentx.h

- As in #5207, enable the vBatBridge when needed on the startup run of `checkAll()` so that the RTC battery voltage is actually read. 
- Partially revert change in #5031 re: `enableVBatBridge()` as this needs to be called regularly so that the RTC voltage is actually read. The call to `disableVBatBridge()` while perhaps technically not needed since `adcRead()` will clear it itself once the voltage actually read certainly won't hurt.
- Changes to display of number on hardware page required as was occasionally flashing junk characters and number changing alignment.
Fixes #5203 for main
Tested on TX16S hardware by running separate PSU on RTC battery input to allow for voltage to be adjusted.

fix: RTC warning not being shown

---

radio/src/gui/colorlcd/view_text.cpp
radio/src/gui/colorlcd/view_text.h
radio/src/opentx.cpp

Prevents modules from being powered up until the checklist is closed.
Also sets the LED color to red while the checklist is open (to match B&W radios).
Note: this PR for 2.10, 2.11 is slightly different.

fix(color): block radio startup until checklist is closed.

---

.github/workflows/macosx_cpn.yml

The macOS 11 runner image will be removed on 28th of June 2024.
https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
This does unfortunately mean that while the prior minimum version of macOS for companion was anywhere between macOS 10.12 (Sierra, Sept 2016) and 10.15 (Catalina, Oct 2019), it is now either macOS 11 (Big Sur, Nov 2020)  or macOS 12 (Monteray, June 2021). There is no simple way around this, as we no longer have access to macOS runners for 11. Whether the minimum version is macOS 11 or macOS 12 I have no idea... QT6 says it uses weak links to allow for running on lower versions than you build on, but it will determine on runtime whether to spit the dummy or not, hence the uncertainly as to what the minimum versions is since I …

chore: bump macos runner version

---

radio/src/datastructs.h

Reduce redundant entries to make updates easier.
Warn on missing entries.

chore(build): simplify the CHKSIZE macros

---

radio/src/targets/taranis/CMakeLists.txt

Fixes #5234
Fixes #5153
pfeerick: I am going to tentatively say this resolves #1942 also as this gem has been present since 2.6, so could have been responsible since it was a 2.7 issue. 
- use `DEFAULT_INTERNAL_MODULE == ISRM_PXX2` as a better heuristic to determine the supported modules.
Note: it seems X9lite and X9liteS are impacted as well.

fix: supported internal module for monochrome radios w/ ISRM

---

radio/src/sdcard.cpp
radio/src/targets/common/arm/stm32/bootloader/boot.cpp
radio/src/targets/horus/CMakeLists.txt
radio/src/targets/horus/bootloader/boot_menu.cpp
radio/src/targets/horus/hal.h
radio/src/translations/cn.h
radio/src/translations/cz.h
radio/src/translations/da.h
radio/src/translations/de.h
radio/src/translations/en.h
radio/src/translations/es.h
radio/src/translations/fi.h
radio/src/translations/fr.h
radio/src/translations/he.h
radio/src/translations/it.h
radio/src/translations/jp.h
radio/src/translations/nl.h
radio/src/translations/pl.h
radio/src/translations/pt.h
radio/src/translations/ru.h
radio/src/translations/se.h
radio/src/translations/tw.h
radio/src/translations/ua.h

This PR add support to initialize SPI NOR flash in horus and nv14 targets:
1. Add storage initialization function in bootloader
2. Add placeholders for user to select the use of SPI NOR flash instead of SD card for storage

feat: bootloader support for SPI NOR flash storage

---

radio/src/gui/navigation/navigation.cpp
radio/src/opentx.h

Current main selects NAVIGATION_9X for X-Lite instead of NAVIGATION_XLITE.
Broken in PR #4893

fix(bw): incorrect X-Lite navigation selection

---

radio/src/gui/colorlcd/widget.h
radio/src/gui/colorlcd/widgets/widgets_container_impl.h

In current main, the built in widgets are not being updated when the view decorations (trim, sliders, etc) are turned on or off.

fix(color): built in widgets do not resize properly when view decorations turned on or off.

---

radio/src/opentx.cpp
radio/src/targets/taranis/board.h

Fixes #4798 since startup animation pwrOff() was responsible for shutting down radio
Fixes #4995 since screen was not being cleared on power up for radios with power switches

fix: Commando8 does not need the startup animation

---

radio/src/gui/colorlcd/layouts/layout1x1AppMode.cpp
radio/src/gui/colorlcd/layouts/layout_factory_impl.h
radio/src/gui/colorlcd/view_main.cpp
radio/src/storage/storage_common.cpp

Fixes #5246 
PR #4655 adds the requested 'App mode' functionality; but breaks existing 'Full screen' functionality for some widgets.
This PR restores the old functionality when the layout is set to 'Full screen'.
A new layout called 'App mode' implements the new app mode functionality.
The 'App mode' layout has a single widget and disables topbar, sliders, trims and flight modes.

fix(color): restore previous 'Fullscreen' functionality and add new 'App mode' layout

---

radio/src/dataconstants.h
radio/src/datastructs.h

Spotted while reviewing #5228 where someone
had done half of what I was thinking of doing a
few days ago :rofl: 
After this PR, there are no more of these 
`#if defined(PCBHORUS) || defined(PCBNV14) || defined(PCBPL18)` 
conditionals in the entire code base :relieved:

chore: remove PCB specific defines in preference to COLORLCD

---

radio/src/targets/common/arm/stm32/bootloader/bin_files.h

Fixes #5250
Also prevent future occurrences by checking size at compile time

fix: VersionTag.flavour[] too small for x10express

---

.github/workflows/actions.yml
.github/workflows/nightly.yml
companion/src/firmwares/opentx/opentxinterface.cpp
fw.json
tools/build-companion.sh
tools/build-gh.sh
tools/commit-tests.sh
tools/generate-hw-defs.sh
tools/generate-yaml.sh
tools/msys2_fetch_and_build_all.sh

Replace x10-access by x10express, which is flavor naming.
This also fixes commit-tests not run for x10 express because wrong PCBREV was used
This matches FrSky official naming
For the same reason x7-access is renamed to x7access (the later already used for FLAVOUR)

chore: remove discrepancy in x10/x7 naming

---

radio/src/gui/128x64/model_setup.cpp
radio/src/gui/212x64/model_setup.cpp

- Fix: when the ENTER key is pressed on the center beep warning list to enter edit mode, the first value is also toggled (128x64).
- Fix: 6POS switches are shown in center beep warning list (128x64).
- Fix: disabled pots/sliders are shown in the center beep warning list.
- Feat: hide the interactive checklist toggle if the checklist is disabled.
- Feat: hide the throttle custom position settings if the throttle warning is disabled.
- Feat: hide the throttle custom position value if the custom position check is disabled.
Potential candidate for 2.10.

fix(bw): fixes and improvements for model setup page

---

companion/src/firmwares/boards.cpp
radio/src/targets/nv14/CMakeLists.txt

The internal module of EL18 is capable to be flashed into ELRS, the change in this PR is to enable the choice of internal CRSF option in Radio Settings.
The ELRS part of the development will be followed here:
https://github.com/ExpressLRS/ExpressLRS/issues/2778

feat(el18): allow for for internal CRSF mods (ELRS/mLRS/etc)

---

radio/src/targets/horus/hal.h

fix(horus): pin naming for I2C_B2 pins

---

companion/src/simulation/simulateduiwidgetJumperT20.cpp

For us Mac users without scroll wheels 😄

feat(cpn): add keys to T20 simulator for rotary encoder movement

---

radio/src/targets/common/arm/CMakeLists.txt
radio/src/telemetry/telemetry.cpp

Targets which did not have support for CRSF or MULTI internal module (ex: X9D+ 2019, X7 ACCESS, NV14) would use a single telemetry buffer for internal and external module, thus causing clashes when 2 modules are used in parallel. This would for instance prevent using an external MPM as trainer module.
Please note that this will slightly increases memory usage for the targets mentioned above (up to 128 bytes).
- enable telemetry buffer for targets without CRSF or MULTI internal module support compiled into the firmware.

feat: telemetry buffer for all internal modules

---

radio/src/targets/common/arm/stm32/ads79xx.cpp
radio/src/targets/common/arm/stm32/sdcard_spi.cpp
radio/src/targets/common/arm/stm32/spi_flash.cpp
radio/src/targets/common/arm/stm32/stm32_spi.cpp
radio/src/targets/common/arm/stm32/stm32_spi.h
radio/src/targets/common/arm/stm32/vs1053b.cpp

According to the data sheets, SPI data width can only be set when the peripheral is not enabled (see RM0090; section 28.5.1):

fix: data width must be set before enabling SPI

---

radio/src/pulses/multi.cpp

Fixes #5285
Summary of changes: overrides auto detection with user choice for MPM telemetry disabling

fix: MPM disable telemetry user choice ignored

---

radio/src/lua/api_general.cpp

Fixes #5292
Corrected the source constant to use for min,
Now it returns properly min or max.

fix(lua): incorrect name for MIN source

---

radio/src/boards/generic_stm32/i2c_bus.cpp
radio/src/hal/i2c_driver.h
radio/src/targets/common/arm/stm32/stm32_i2c_driver.cpp

- fix I2C timing calculations for H7
- add `i2c_deinit`

fix: I2C support for H7

---

radio/src/gui/colorlcd/radio_diagkeys.cpp

The trims are not listed properly, the naming is wrong.
The code use different mapping interpretation as per v2.10
i.e. v2.10 do not have problem but 2.11 has problem

fix(pl18): key diagnostic screen display trims in wrong mapping

---

radio/src/io/bootloader_flash.cpp
radio/src/targets/common/arm/stm32/bootloader/CMakeLists.txt
radio/src/targets/common/arm/stm32/flash_driver.cpp

Fix issue introduced in #5232 and reported by @philmoz on Discord
https://discord.com/channels/839849772864503828/909552654328406056/1265246121484226661

fix: do not init the watchdog in flash driver

---

radio/src/gui/128x64/model_input_edit.cpp
radio/src/gui/128x64/model_mix_edit.cpp

On 128x64 B&W radios the long press of the enter key to open the curve edit page only works if the user is editing the custom curve value. 
On 212x64 radios the long press works whenever the custom curve value is selected.
Changes 128x64 B&W radio to match the 212x64 logic.

feat(bw128): allow long press to open curve edit without entering edit mode

---

radio/src/simu.cpp

- keyboard trims weren't working properly in simu - only half of the trims working, and wrong trims at that :zany_face: 
- cleanup comment that has not been correct for some time

fix(simu): keyboard trims not working properly

---

radio/src/gui/colorlcd/curveedit.cpp

Fix layout for T15.
Change point count value to a popup menu due to slow performance when rebuilding point list.
Fixes #5327

fix(color): curve edit lag when changing point count, t15 graph size

---

radio/src/gui/colorlcd/model_select.h

T15 does not use full height of LCD for model select.

fix(color): model select layout on T15 not full height

---

radio/src/gui/colorlcd/function_switches.cpp
radio/src/switches.cpp

Radios with customisable switches (i.e. T20V2, T15) can be set into an unexpected state when the switch type is set to Toggle.
To reproduce:
- Set switch type to 2POS, no group and startup to Last value.
- Press switch to turn it on.
- Change type to Toggle with switch turned on.
Toggle works backwards - with pressed state being switch UP and LED OFF.
Even on restart switch is backwards.
This PR ensures Toggle state is consistent when changed and on startup.

fix(radio): ensure customisable switch set as Toggle starts in the OFF state.

---

radio/src/gui/128x64/view_main.cpp
radio/src/gui/212x64/view_main.cpp
radio/src/rtc.cpp
radio/src/rtc.h

Inspired by discussion on RCG where users either have difficulties with RTC resets or simply don't care and do not put a battery.
In such case, time is not displayed anymore on main view

feat(bw): do not show time on main view when RTC not set

---

radio/src/hal/module_port.cpp
radio/src/hal/serial_driver.h
radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp

Fixes #5318
Implemented auto oversampling calculation.
Formula in STM document RM0090 (F429):
For 16 bit oversampling:
baud = pclk / 16 * USARTDIV
For 8 bit oversampling:
baud = pclk / 8 * USARTDIV
Minimum USARTDIV = 1, therefore when pclk / baud < 16, 8 bit oversampling should be used
@raphaelcoeffic ~~I think more cleanup is required, if oversampling is chosen automatically, then no need for code that choose to use 8-bit oversampling.~~  Already did the clean up

fix(el18): uart auto oversampling calculation

---

radio/src/MultiProtoDefs.h

Pascal called me because he could not select MouldKg protocol on his TX16S.
This fixes it

fix(mpm): some protocols excluded

---

radio/src/telemetry/spektrum.cpp

Fixes #5350
Tested with the 2.10 branch as well as main.
1. Looks like in the latest RX firmware, Spektrum changed the way the SkyID GPS data is sent on the telemetry. Originally, the SkyID GPS data was sent using the old/standard GPS Frames, but now is not doing it.  The GPS data now is embeded inside the RemoteID telemetry frames.. exact same format, so the existing parsing can be re-used.
3. A few people on Black&White radios has complained that the 40 telemetry sensors is not enough for for some of the Spektrum RX included in BNF setups (Usually FlightControl data, ESC data, Battery Data).   Removed the unnecessary debugging family of sensors 05xx, 26xx and 27xx  (about 5-6 each, so about 15 sensors saved)).
Probably I was the only one who used to use them on old …

feat(dsm): process new format for Spektrum Sky_ID GPS frames

---

radio/src/gui/128x64/model_logical_switches.cpp
radio/src/gui/212x64/model_logical_switches.cpp
radio/src/gui/colorlcd/model_logical_switches.cpp
radio/src/switches.cpp
radio/src/switches.h

Changes:
- Change color UI to show V1, V2 and AND switches in bold when they are on (to match B&W UI).
- Show 'Stcky' label for sticky switches in bold when the switch sticky state is ON.
Sticky LS with an AND switch can be off; yet still have the 'sticky' state set to on.
This can make setting up a LS somewhat confusing.
This change aims to show the 'sticky' state in addition to the LS switch state.

feat(radio): Logical Switch list display UI

---

companion/src/progresswidget.cpp
companion/src/progresswidget.h
companion/src/storage/minizinterface.cpp
companion/src/storage/minizinterface.h
companion/src/updates/repoassets.cpp
companion/src/updates/repoassets.h
companion/src/updates/updatecloudbuild.cpp
companion/src/updates/updatecloudbuild.h
companion/src/updates/updateinterface.cpp
companion/src/updates/updateinterface.h
companion/src/updates/updatenetwork.cpp
companion/src/updates/updatenetwork.h
companion/src/updates/updates.cpp

- fix multiple runs of updating sounds re-running previous selections
- add ability to interrupt miniz decompress
- add lots more check points for cancel button press test to stop processes earlier
- improve status refresh
- chores clean up network class and fix signal/slot disconnects

fix(cpn): sounds processing extra files and cancel update processes earlier

---

radio/src/bluetooth.cpp
radio/src/targets/common/arm/stm32/bluetooth_driver.cpp
radio/src/targets/horus/hal.h

fix(tx16s): turn on aux2 power when used for BT - 2.10

---

radio/src/gui/colorlcd/controls/source_numberedit.h
radio/src/gui/colorlcd/model/mixer_edit.cpp
radio/src/strhelpers.cpp

If the Weight value for an input or mix line is set to a GV, and the GV has a name, then just display the name instead of trying to show GVX:NAM in the list view (as it was pre PR 5220).
Fix layout for EL18 mix edit (remove horizontal scroll on Curve line).

fix(color): display only GV name in mix/input overview when used for weight

---

radio/src/gui/colorlcd/libui/tabsgroup.cpp

Check deleted state to prevent crash when shutting down.

fix(color): crash if radio shut down on some menu pages

---

radio/src/gui/colorlcd/model/special_functions.cpp

A special function that runs a Lua script may not work when:
- the SF is first created and the Enable toggle is set to on in the SF edit page
- the SF is disabled, then re-enabled in the SF edit page
Disabling then re-enabling on the SF list view page, or restarting, will activate the SF.

fix(color): ensure script loaded when Lua Script SF enabled

---

radio/src/gui/colorlcd/model/model_outputs.cpp
radio/src/gui/colorlcd/model/output_edit.cpp
radio/src/gui/colorlcd/model/output_edit.h

Fixes #1989 
Use code from output edit page to highlight min/max values on output list page.
Fixes issue when output is inverted.

fix(color): min/max highlight in output list swapped if inverted

---

radio/src/gui/colorlcd/mainview/widget.cpp
radio/src/gui/colorlcd/mainview/widget_settings.cpp
radio/src/gui/colorlcd/mainview/widgets_setup.cpp

Fixes #4183 
- Show widget name in popup menu title on long press
- Show widget name in widget settings dialog title
- When 'Select widget' option is chosen on an existing widget, set selected item in menu to the current widget name

feat(color): show widget name in settings popups

---

radio/src/gui/colorlcd/radio/radio_sdmanager.cpp

Changes in PR #5376 can cause crashes in the simulator.

fix(cpn): simulator crashes in SD browser

---

radio/src/gui/212x64/lcd.cpp
radio/src/gui/212x64/view_main.cpp

Fixes #5369
- T2 timer offscreen on telemetry screen
- The 'P' indicator for persistance was overlapping timer display on main view timer.
Both of these would have been fine pre https://github.com/EdgeTX/edgetx/pull/3871.

fix(bw212): timer display on telemetry screen, main view

---

radio/src/dataconstants.h
radio/src/gui/128x64/gui.h
radio/src/gui/128x64/model_input_edit.cpp
radio/src/gui/128x64/model_mix_edit.cpp
radio/src/gui/128x64/widgets.cpp
radio/src/gui/212x64/gui.h
radio/src/gui/212x64/model_input_edit.cpp
radio/src/gui/212x64/model_mix_edit.cpp
radio/src/gui/212x64/widgets.cpp
radio/src/gui/common/stdlcd/draw_functions.cpp
radio/src/gui/common/stdlcd/model_curves.cpp
radio/src/gui/common/stdlcd/model_inputs.cpp
radio/src/gui/common/stdlcd/model_mixes.cpp
radio/src/gui/navigation/navigation.cpp
radio/src/gui/navigation/navigation.h
radio/src/gui/navigation/navigation_9x.cpp
radio/src/gui/navigation/navigation_x7.cpp

Fixes for B&W radios from PR #5220:
- Fix source selection for weight/offset/curve to allow GV selection.
- Allow GV as source for mixer lines.
- Filter empty categories from source select popup.
Fixes https://github.com/EdgeTX/edgetx/issues/4007

fix(bw): unable to select GV as source for weight/offset/curve in input/mix

---

companion/src/shared/namevalidator.h
radio/src/gui/common/stdlcd/draw_functions.cpp

Fixes #1858 and fixes #4618 
Change the order of character selection to:
```C
" abcdefghijklmnopqrstuvwxyz0123456789-,."
```
Use long press to change case.

fix(bw): change char selection order when editing names

---

radio/src/gui/colorlcd/model/model_telemetry.cpp

Fixes #5400
Enable LVGL refresh after building sensor edit page.

fix(color): view refresh issues after opening telemetry sensor edit page

---

radio/src/lua/lua_widget.cpp
radio/src/lua/lua_widget.h

Fixes issues when using multiple main view screens:
- The background function for widgets on non-visible screens is not being called.
- For Lua widgets using Lvgl call the backgroundI() function when the widget is offscreen instead of the run() function.

fix(lua): widget background function not always run when offscreen

---

radio/src/gui/common/stdlcd/model_inputs.cpp
radio/src/gui/common/stdlcd/model_mixes.cpp

fix(bw): ignore short/long press of ENTER if cursor on menu line

---

radio/src/gui/colorlcd/mainview/view_main_menu.cpp

Steps to reproduce:
- load a model with failsafe not set
- before the 'Failsafe warning' dialog pops up, tap the screen to open the quick menu.
The failsafe warning page will show with the main view UI still visible underneath.

fix(color): fullscreen dialog may appear over the main view UI

---

radio/src/lua/interface.cpp

Kill short press event so page does not close.

fix(bw): LONG press RTN to exit Lua script closes tools menu

---

radio/src/gui/colorlcd/libui/tabsgroup.cpp

Scroll the menu bar in the Radio, Model and Screen setup pages to keep the selected tab icon visible.
Fixes issue on NV14/EL18, where selected tab icon goes off screen, when use hat trims as keys and paging left/right to select tabs.
Resolves #4133

feat(color): scroll menu bar so selected tab icon is always visible

---

radio/src/bluetooth.cpp
radio/src/targets/common/arm/stm32/bluetooth_driver.cpp
radio/src/targets/horus/hal.h

Enable/disable BT power on radio that remap AUX2 with power pin (introduced with stdperif removal)
Fixes #5352

fix(tx16s): turn on aux2 power when used for BT

---

companion/src/datamodels/compounditemmodels.cpp

Satisfies Companion side of #3591

refactor(cpn): sort custom functions list

---

radio/src/switches.cpp

Verified working on 2.9.4
Couldn't test on master because SD card isn't detected on my Boxer (probably related to #3957 ) 
Fixes #4663

fix: remove extra cycle in LS timer v2->v1 transition

---

radio/src/gui/128x64/widgets.cpp
radio/src/gui/212x64/widgets.cpp
radio/src/gui/navigation/navigation.h
radio/src/gui/navigation/navigation_9x.cpp
radio/src/gui/navigation/navigation_x7.cpp

Fixes #5419
Don't use 'isValueAvailable' function when editing a numeric value.

fix(bw): cannot select all numeric values for some fields.

---

radio/src/opentx.cpp
radio/src/targets/common/arm/stm32/timers_driver.cpp

This PR is necessary to be able to support polling I2C port expanders or similar slow things as part of the what is done in the 10ms timer. Mid-term, we'll need to split single items out and give them a dedicated soft-timer.
- execute the 10ms timer routine in a differed  way rather than inside ISR.

feat: async 10ms timer handler

---

companion/src/modeledit/expodialog.cpp
radio/src/gui/128x64/model_input_edit.cpp
radio/src/gui/212x64/model_input_edit.cpp
radio/src/gui/colorlcd/model/input_edit.cpp
radio/src/gui/colorlcd/model/mixer_edit.cpp

Extending the changes from PR #5220 this change allows the source for weight, offset and curve in an Input line to be another Input.
Reasoning behind this is I want to use a slider to fine tune the expo for a control.
I create an input for the slider and use weight and offset to control the range of values.
Currently to use this 'expo' input to control Expo on a stick input I need to add a mix line and then use the output channel - which over complicates things.
TODO:

feat: allow an 'input' as the source for weight, offset and curve in input line

---

radio/src/targets/common/arm/stm32/usb_driver.cpp
radio/src/targets/common/arm/stm32/usbd_cdc.cpp
radio/src/targets/common/arm/stm32/usbd_conf.c
radio/src/targets/common/arm/stm32/usbd_storage_msd.cpp
radio/src/targets/common/arm/stm32/usbd_storage_msd.h

At the moment, none of the supported targets have a USB HS PHY, however, some upcoming targets do (notably STM32H7RS). To add USB HS support on targets that have a USB HS PHY, `USE_USB_HS` must be defined. Additionally, support for open-drain VBUS sensing has been added (define `USB_GPIO_VBUS_OPEN_DRAIN` in `hal.h`).

feat: add support for USB HS

---

radio/src/targets/common/arm/stm32/usbd_conf.c
radio/src/thirdparty/STM32_USB_Device_Library/Class/CDC/Inc/usbd_cdc.h
radio/src/thirdparty/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c
radio/src/thirdparty/STM32_USB_Device_Library/Class/CustomHID/Src/usbd_customhid.c
radio/src/thirdparty/STM32_USB_Device_Library/Class/DFU/Inc/usbd_dfu.h
radio/src/thirdparty/STM32_USB_Device_Library/Class/DFU/Src/usbd_dfu.c
radio/src/thirdparty/STM32_USB_Device_Library/Core/Src/usbd_core.c
radio/src/thirdparty/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c

- the CDC changes, notably the removal of the SOF callback, have been removed compared to ST's version.
- DFU class support has been added.

chore: update ST USB middleware to v2.11.3

---

radio/src/targets/taranis/lcd_driver_aspi.cpp
radio/src/targets/taranis/lcd_driver_spi.cpp

The classical 10ms timer will be started later and should not be relied upon at this stage.
This fixes the issue introduced with #5424 (see https://github.com/EdgeTX/edgetx/pull/5424#issuecomment-2288548638).

fix: initial wait delay in SPI LCD.

---

radio/src/myeeprom.h

Fixes regression introduced in #5396 whereby running `generate-yaml` will fail due `#pragma once` line in `myeeprom.h`

fix: `generate-yaml` breaks on myeeprom pragma once

---

radio/src/targets/common/arm/stm32/stm32_softserial_driver.cpp

This was most visible when flashing an external MPM, which was broken.
This fixes #5348

fix: soft-serial polarity

---

radio/src/gui/colorlcd/libui/textedit.cpp
radio/src/gui/colorlcd/libui/textedit.h
radio/src/gui/colorlcd/model/input_edit.cpp
radio/src/gui/colorlcd/model/input_edit.h
radio/src/gui/colorlcd/model/model_setup.cpp

For Input edit:
- Fix preview not updating when a switch is assigned to the input.
- Fix name not updating in header when name changed.
- Show name in bold & ACTIVE color in header when input line is active.
Also fixes an issue where the model name was not being updated on the model select page list after editing the model name.

fix(color): refresh issues on Input edit page

---

radio/src/datastructs_private.h

Fixes #5444
For some reason the GCC version in MSYS does not compile correctly.

fix(simulator): SourceNumberEdit not working on Windows

---

radio/src/boards/generic_stm32/analog_inputs.cpp
radio/src/gui/128x64/radio_diaganas.cpp
radio/src/gui/212x64/radio_diaganas.cpp
radio/src/gui/colorlcd/radio/radio_diaganas.cpp
radio/src/hal/adc_driver.cpp
radio/src/hal/adc_driver.h
radio/src/targets/common/arm/stm32/flysky_gimbal_driver.cpp
radio/src/targets/common/arm/stm32/stm32_adc.cpp
radio/src/targets/common/arm/stm32/stm32_adc.h
radio/src/thirdparty/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_def.h

Allow users (or devs :D) to know if serial gimbal are been used on their radio.
When serial gimbal are use, a 'D' is displayed instead of leading 0
Despite being tiny, requires #5443 to fit on some targets
Some housekeeping while at it

feat: indicate in diag ana if serial gimbals are used

---

radio/src/lua/interface.cpp

Fixes #5456
Don't try and run script if SF disabled.

fix(lua): radio tries to run 'nil' script if SF disabled

---

radio/src/lua/api_general.cpp

Adds `screenshot()` function to Lua.
Here (positive) feedback about this PR being tested on EdgeTX Discord: https://discord.com/channels/839849772864503828/842693696629899274/1251223608173264979

feat(lua): add screenshot() function

---

radio/src/gui/colorlcd/libui/bitmapbuffer.h
radio/src/gui/colorlcd/libui/bitmapbuffer_draw_extra.cpp
radio/src/lua/api_colorlcd.cpp

adds text end coordinates to drawTextLines to enable stacking of draw textLines.
Fixes not knowing where prior multi-line drawTextLines calls have ended.
Adds new returns to lua.drawTextLines containing end bottom right corner of used text area.
I consider adding similar return to drawTimer, drawString, drawNumber

feat(lua): add end coordinates to lcd.drawTextLines

---

radio/src/targets/nv14/battery_driver.cpp
radio/src/targets/nv14/board.cpp
radio/src/targets/nv14/board.h
radio/src/targets/nv14/touch_driver.cpp
radio/src/targets/pl18/battery_driver.cpp
radio/src/targets/pl18/board.cpp
radio/src/targets/pl18/board.h
radio/src/targets/pl18/touch_driver.cpp

Battery charging animation problem due to PR#5424

fix(flysky): battery charging animation and other timing issues

---

companion/src/simulation/telemetrysimu.cpp
companion/src/simulation/telemetrysimu.h

The code to check for the old (pre-OpenTX 2.1.9, Sep 2016) format of GPS coordinates in log CSVs is no longer used since https://github.com/EdgeTX/edgetx/pull/5410 so remove it. Also, drive by spelling fix.
Prompted by https://github.com/EdgeTX/edgetx/issues/5473

chore(cpn): clean up now-unused code from telemetry log replayer

---

companion/src/modeledit/mixerdialog.cpp
companion/src/modeledit/mixerdialog.h
companion/src/modeledit/mixerdialog.ui
companion/src/modeledit/mixes.cpp
companion/src/modelprinter.cpp
radio/src/gui/128x64/model_mix_edit.cpp
radio/src/gui/212x64/model_mix_edit.cpp
radio/src/gui/colorlcd/model/mixer_edit_adv.cpp
radio/src/gui/common/stdlcd/model_mixes.cpp
radio/src/mixer.cpp

Fixes #47
For the first line in any mix:
- don't use the Multiplex setting in the mixer.
- don't display the Multiplex setting when editing the mix line (radio & Companion).
- remove 'MULT!' warning display (B&W radios and Companion).

fix(radio): multiplex setting is not valid for 1st line in a mix

---

radio/src/pulses/modules_helpers.h
radio/src/tests/module_ports.cpp

External module FrSky telem binding should only be disabled when internal module is already using sport.
This fixes #5466

fix: xjt lite telem binding

---

radio/src/gui/navigation/navigation_9x.cpp
radio/src/gui/navigation/navigation_x7.cpp

As discovered as part of #5485 investigation, autoswitch feature allow users to select unproper value.
This fixes it.
Likely needed in 2.10 too

fix(bw): prevent autodetection of unavailable sources

---

radio/src/gui/128x64/model_special_functions.cpp
radio/src/gui/212x64/model_special_functions.cpp
radio/src/gui/colorlcd/model/special_functions.cpp

Steps to reproduce:
- create a GF or SF which runs a Lua script (or RGB led script). Something that plays sound or flashes led is easiest to test.
- enable and test GF/SF.
- change GF/SF function to a non-script function and re-enable.
- trigger GF/SF - previous Lua script continues to run.

fix(radio): a Lua script GF/SF continues to run after function changed

---

radio/src/targets/taranis/lcd_driver_aspi.cpp
radio/src/targets/taranis/lcd_driver_spi.cpp

Fixes an issue spotted by @philmoz when in certain conditions (ie T12Max bootloader), lcd init might not be successful

fix(bw): wait time in lcd init

---

radio/src/gui/colorlcd/controls/channel_range.cpp
radio/src/gui/colorlcd/controls/channel_range.h
radio/src/gui/colorlcd/controls/gvar_numberedit.cpp
radio/src/gui/colorlcd/controls/input_source.cpp
radio/src/gui/colorlcd/controls/input_source.h
radio/src/gui/colorlcd/controls/source_numberedit.cpp
radio/src/gui/colorlcd/controls/source_numberedit.h
radio/src/gui/colorlcd/libui/choice.cpp
radio/src/gui/colorlcd/libui/choice.h
radio/src/gui/colorlcd/libui/slider.cpp
radio/src/gui/colorlcd/libui/slider.h
radio/src/gui/colorlcd/libui/toggleswitch.cpp
radio/src/gui/colorlcd/libui/toggleswitch.h
radio/src/gui/colorlcd/model/model_logical_switches.cpp
radio/src/gui/colorlcd/model/special_functions.cpp
radio/src/gui/colorlcd/module/afhds2a_settings.cpp
radio/src/gui/colorlcd/module/afhds2a_settings.h
radio/src/gui/colorlcd/module/afhds3_settings.cpp
radio/src/gui/colorlcd/module/module_setup.cpp
radio/src/gui/colorlcd/module/mpm_settings.cpp
radio/src/gui/colorlcd/radio/hw_inputs.cpp
radio/src/gui/colorlcd/radio/hw_inputs.h
radio/src/gui/gui_common.cpp
radio/src/pulses/flysky.cpp

- fix update of PPM frame when channel range changed (mode = PPM)
- fix display of switch type for flex switches (type not being shown)
- remove redundant event handling code
- fix layout of Axis, Pots and Switches setup dialogs (focus border clipped on bottom row)

fix(color): cleanup update/refresh/event handling

---

radio/src/gui/colorlcd/standalone_lua.cpp
radio/src/gui/colorlcd/standalone_lua.h

Fixes #5507 
Let LVGL manage display of script UI instead of DMA copying buffer directly to screen.

fix(color): use LVGL canvas for drawing standalone script UI

---

radio/src/pulses/crossfire.cpp

Problem:
ExpressLRS modules store the RF parameters in a model specific way using the modelID as index. EdgeTX sends the modelID once at first initialization of the module. If after that the module resets for any reason the module starts up and assumes modelID 0 for a lack of better information. This is not only annoying but also dangerous because a receiver will potentially not re-connect after the module comes back to live after the reset as the module is now using the RF parameters stored for the model with the modelID 0.
The effect is demonstrated in the attached video. The module is removed during normal operation with a receiver connected using a model with modelID 7 (100Hz in my case) to simulate a reset. After putting the module back in it starts up but uses modelID 0 RF …

fix(crsf): send modelID after module reset

---

radio/src/targets/common/arm/stm32/stm32_ws2812.cpp

DMA data length should be the same for both 16-bit and 32-bit timers.

fix(pl18): ws2812 not working properly after v16 support

---

radio/src/storage/yaml/yaml_datastructs_funcs.cpp

Fixes #5510 
Incorrect length passed when converting int value for CS position.
If additional character is a digit then bad index value is calculated.
Also needs to be applied to 2.10.5.

fix(radio): CS values may be read incorrectly from yaml

---

radio/src/gui/colorlcd/controls/curve_param.cpp
radio/src/gui/colorlcd/controls/curve_param.h

To reproduce:
- Assign a custom curve to an input or mix.
- Set focus to the curve button and long press the ENTER key to open the curve editor.
- Press RTN to exit the curve editor - the curve button remains in the pressed state.
Also removes some unused code.

fix(color): curve button remaining in pressed state when editing input or mix

---

radio/src/targets/taranis/hal.h

Fixes wrong defines (issues doesn't exist in main)
Fixes wrong external module behavior

fix: T-Pro S external module

---

radio/src/edgetx.h
radio/src/gui/colorlcd/controls/curve_param.cpp
radio/src/gui/colorlcd/controls/curve_param.h
radio/src/gui/colorlcd/model/curveedit.cpp
radio/src/gui/colorlcd/model/curveedit.h
radio/src/gui/colorlcd/model/input_edit.cpp
radio/src/gui/colorlcd/model/input_edit.h
radio/src/gui/colorlcd/model/mixer_edit.cpp
radio/src/gui/colorlcd/model/mixer_edit.h
radio/src/gui/colorlcd/model/model_curves.cpp
radio/src/gui/colorlcd/model/model_curves.h
radio/src/gui/colorlcd/model/output_edit.cpp
radio/src/gui/colorlcd/model/output_edit.h
radio/src/gui/navigation/navigation.cpp

As discussed in #4914 
- Use popup menu to select curve.
- Allow long press on curve button to jump to curve edit page.
Fixes #5520

feat(color): use curve select button on outputs edit page to match inputs and mixes

---

radio/src/gui/colorlcd/mainview/screen_setup.cpp

Fixes #2212 
Save and restore the screen options for topbar, flight modes, sliders, trims and mirrored when the layout is changed.
Note: does not apply if either the old or new layout is App Mode.

feat(color): keep screen options when changing layout.

---

radio/src/gui/colorlcd/mainview/zone.h
radio/src/lua/api_general.cpp
radio/src/lua/lua_api.h

Remove the SRCVAL and INTVAL entries added in #5518 as they are duplicates of existing SOURCE and VALUE entries.
Add some comments for future reference.

chore(lua): remove redundant entries added in 5518.

---

radio/src/gui/colorlcd/mainview/widget.h
radio/src/lua/api_colorlcd.cpp
radio/src/lua/lua_widget.cpp

Fixes #5540 
Should also be applied to 2.10.5

fix(color): full screen widget may not exit cleanly after calling lcd.exitFullScreen()

---

radio/src/gui/128x64/model_setup.cpp
radio/src/gui/128x64/radio_setup.cpp
radio/src/gui/212x64/model_setup.cpp
radio/src/gui/212x64/radio_setup.cpp

- Make Sound, Vario, Haptic, Alarms, Brightness, GPS and Enabled Features sections collapsable.
- Move Startup Sound checkbox to Sound section.

feat(bw): add collapsable sections to B&W radio setup tab

---

radio/src/gui/128x64/model_flightmodes.cpp

Fixes #5557
Also changes display to show up to 6 trims on the first line (if there are <= 6 in total) - this keeps all 5 trims on MT12 on a single line:

feat(bw): show trim name in top bar when editing FM trim value.

---

radio/src/gui/colorlcd/model/model_select.cpp

In some cases the model buttons may not be selected in order from top to bottom, left to right, when using the roller to change model.
To reproduce:
- Set labels select mode to single select
- Create a label that selects a subset of the available models (select from the middle of the model list)
- Enter the manage models page with the above label selected
- Uncheck the label to show all models
When using the roller to change model the selection order is not correct.

fix(color): wrong selection order of model buttons on manage models page

---

companion/src/modeledit/customfunctions.cpp

Fixes #5451 but not documentation!
- set minimum time to 0.1s
- set default time to 1.0s

fix(cpn): sf/gf sd logs minimum and default time

---

radio/src/gui/colorlcd/libui/modal_window.cpp

When setting the switch or source for an input, mix, etc, the automatic selection of any moved switch, axis or pot on the radio does not work.
Broken in #5558

fix(color): automatic switch and source selection in popup menus not working

---

radio/src/lua/widgets.cpp

The options array for a widget is allocated with new[]; but was being de-allocated with free() instead of delete[].
Potential crash if there are errors when loading the options for a widget.

fix(color): incorrect method called to free a widget options array

---

radio/src/gui/colorlcd/mainview/sliders.cpp
radio/src/gui/colorlcd/mainview/sliders.h
radio/src/gui/colorlcd/mainview/view_main_decoration.cpp

Clean up PL18 UI by having the three pots at the bottom and the two sliders on the sides.
Also repositions the 6POS display so that the selection box is aligned with the sliders.

fix(color): place UI for all three pots at bottom of main view for PL18/PL18EV

---

companion/src/firmwares/opentx/opentxeeprom.cpp

Fixes #5570
Note: this is for 2.10.5 ONLY as binary import dropped in 2.11

fix(cpn): set all sf/gf functions with repeat to enabled on otx import

---

radio/src/boards/generic_stm32/inputs.cpp
radio/src/keys.cpp
radio/src/targets/simu/simpgmspace.cpp

Fixes #5332 
Restore OpenTX functionality.
Note: not tested on actual radios, only in simulator.
Could be applied to 2.10.5.

fix(bw): unshifted trims on XLite radios should always adjust elevator and aileron

---

radio/src/gui/navigation/common.cpp
radio/src/gui/navigation/navigation.cpp
radio/src/gui/navigation/navigation_9x.cpp
radio/src/gui/navigation/navigation_x7.cpp
radio/src/mixer.cpp
radio/src/strhelpers.cpp

Fixes a number of issues from the changes that allow any source to be used for weight/offset/expo fields.
- Negative GV values are not calculated correctly (all radios).
- After changing field to a source value, the field reverts to a constant value (b&w only).
- Cannot change source value properly using roller, when an Input is selected for the field (b&w only).
- When selecting Inputs as the source type (using long press on the field), the second input is selected instead of the first (b&w only).

fix(radio): fix GV calculation and menu navigation in weight/offset/expo fields.

---

companion/src/firmwares/boardjson.cpp
companion/src/firmwares/customfunctiondata.cpp

fix(cpn): function switches induced crash

---

companion/src/firmwares/customisation_data.cpp
companion/src/firmwares/customisation_data.h
radio/src/datastructs.h
radio/src/gui/colorlcd/libui/filechoice.h
radio/src/gui/colorlcd/mainview/widget_settings.cpp
radio/src/gui/colorlcd/mainview/zone.h
radio/src/lua/api_general.cpp
radio/src/lua/lua_widget.cpp
radio/src/lua/lua_widget_factory.cpp
radio/src/lua/widgets.cpp
radio/src/storage/yaml/yaml_datastructs_f16.cpp
radio/src/storage/yaml/yaml_datastructs_nv14.cpp
radio/src/storage/yaml/yaml_datastructs_pl18.cpp
radio/src/storage/yaml/yaml_datastructs_t15.cpp
radio/src/storage/yaml/yaml_datastructs_x10.cpp

Resolves #5573 
Parameters:
- Option name
- FILE
- default value
- Folder to open to select file
Only the filename is returned for the option, excluding the path.
Filenames are limited to 12 characters maximum length.
> [!NOTE]
String widget option is increased from 8 characters to 12 characters
Example:
```C
{ "File", FILE, "testimg.png", "/IMAGES"},
```

feat(color): add FILE type for widget options

---

companion/src/translations/companion_cs.ts
companion/src/translations/companion_da.ts
companion/src/translations/companion_de.ts
companion/src/translations/companion_en.ts
companion/src/translations/companion_es.ts
companion/src/translations/companion_fi.ts
companion/src/translations/companion_fr.ts
companion/src/translations/companion_he.ts
companion/src/translations/companion_it.ts
companion/src/translations/companion_ja.ts
companion/src/translations/companion_nl.ts
companion/src/translations/companion_pl.ts
companion/src/translations/companion_pt.ts
companion/src/translations/companion_ru.ts
companion/src/translations/companion_sv.ts
companion/src/translations/companion_zh_CN.ts
companion/src/translations/companion_zh_TW.ts

- run `companion_translations` job to refresh companion translations files
- flag `en` translations as complete, as they are the source translations anyway

chore: run `companion_translations`

---

tools/msys2_fetch_and_build_all.sh

Move radio simulator library compilation step to before Companion and Simulator compilation steps
Note: Wiki page has been updated for performing steps manually

chore(tools): reorder msys2 compile steps

---

radio/src/hal/adc_driver.cpp
radio/src/targets/simu/adc_driver.cpp
radio/src/targets/taranis/board.h

Cleanup of VBAT measurement definition for Radiomaster and Jumper radio where we have exact drawings and resistors values. This will break existing calibration (likely not by a whole lot), but overall I think it is for the best. In most cases, default value should already be very accurate

chore: improve VBAT measurement

---

radio/src/gui/colorlcd/radio/radio_sdmanager.cpp

Preview remains visible after file deletion.

fix(color): preview not removed in SD manager after image file deleted

---

radio/src/lua/lua_lvgl_widget.cpp
radio/src/lua/lua_lvgl_widget.h

Add 'align' property for labels.
- use a seperate property to set text alignment (CENTER, RIGHT), instead of adding alignment to the 'font' property.
Add 'opacity' property for lines, rectangles, circles, arcs and triangles.
- Note: the opacity value range is 0 (transparent) to 255 (opaque).

feat(lua): add 'align' and 'opacity' properties for LVGL widget objects

---

radio/src/gui/colorlcd/radio/radio_trainer.cpp
radio/src/gui/common/stdlcd/radio_trainer.cpp

PPM multiplier is used only on trainer jack input (for history reason when PPM was hardly standardized), but is displayed in all mode. With this change, it is displayed only in master/jack mode
Fixes #5639

fix: only display PPM multiplier when PPM is used

---

radio/src/gui/colorlcd/libui/file_browser.cpp
radio/src/gui/colorlcd/libui/file_browser.h

Issues:
- Two taps may be required to close the popup menu for a file or folder.
- The popup menu for a file may open as soon as the file is selected using the touch screen. The popup menu should only open on long press or on the second tap on the file name.
The first issue (two taps to close the popup) happens when a long press of the ENTER key, or a long touch on the file name is used to open the popup.
The second issue happens when:
- Tap on a folder name.
- Tap on a file name; but do not open the popup menu.
- Tap on the '..' parent directory.
- Tap on the same folder name.
- Tap on the same file name. The popup opens immediately.

fix(color): touch events may not work correctly in the SD manager file browser.

---

companion/src/radiointerface.cpp
companion/src/radiointerface.h

Quick and nasty. Revisit in binary clean up.

fix(cpn): halt when multiple locations for read and write models and settings detected

---

radio/src/gui/colorlcd/model/special_functions.cpp

Show script name in list view.

fix(color): show script name for 'RGB led' function in SF/GF list view

---

radio/src/gui/colorlcd/mainview/screen_setup.cpp
radio/src/gui/colorlcd/mainview/topbar_impl.cpp
radio/src/gui/colorlcd/mainview/topbar_impl.h
radio/src/gui/colorlcd/mainview/view_main.cpp
radio/src/gui/colorlcd/mainview/view_main.h
radio/src/gui/colorlcd/mainview/widget.h
radio/src/gui/colorlcd/mainview/widgets_container_impl.h

Reported on discord.
Fixes a number of issues with the main view UI, introduced with the 'App Mode' layout changes.
1. EdgeTx button visibility not set correctly:
- Create a model with a single screen and top bar visible
- Add a second screen with top bar hidden
- Return to main view and scroll to second screen - EdgeTx button remains visible instead of being hidden
- Enter screen setup (TELE) while on second screen
- Return to main view, EdgeTX button is now hidden
- Scroll left to first screen - EdgeTx button remains hidden instead of being visible.
2. Trims, Sliders and Flight mode decorations may remain visible after being turned off:
- Enter screen setup and add a new screen
- Turn off topbar, trims, sliders and flight mode decorations
- Return to main view and scroll to newly added …

fix(color): issues with main view UI

---

companion/src/firmwares/boards.cpp
radio/src/gui/128x64/model_special_functions.cpp
radio/src/gui/212x64/model_special_functions.cpp
radio/src/gui/colorlcd/model/special_functions.cpp
radio/src/myeeprom.h
radio/src/storage/yaml/yaml_datastructs_funcs.cpp

Currently RGB Led Lua scripts are run continuously. 
PR adds the repeat option to match the 'Play Script' SF - allows simple Led scripts that just set the color to be run once only.
Existing models will default to 'On' (run continuously) for all 'RGB Led' SF entries.

feat(radio): add repeat option for 'RGB Led' SF

---

radio/src/lua/lua_lvgl_widget.cpp
radio/src/lua/lua_lvgl_widget.h

Closes #5680
Add 'dashGap' and 'dashWidth' properties to the 'hline' and 'vline' objects.

feat(Lua): add properties for dashed vertical and horizontal lines in Lvgl API.

---

radio/src/serial.cpp
radio/src/targets/horus/board.cpp
radio/src/targets/nv14/board.cpp
radio/src/targets/pl18/board.cpp
radio/src/targets/taranis/board.cpp

Remove "hack" allowing hardcoded early traces of ETX start on serial port 1, since it was done for us (me mostly) and we are now using JLink.
Output debug traces on any aux (including aux1) is still supported, just happens a bit later in the boot process

chore: remove hardcoded aux1 debug hack

---

radio/src/gui/colorlcd/controls/sourcechoice.cpp
radio/src/gui/colorlcd/controls/switchchoice.cpp
radio/src/gui/colorlcd/libui/file_browser.cpp
radio/src/gui/colorlcd/libui/file_browser.h
radio/src/gui/colorlcd/libui/listbox.cpp
radio/src/gui/colorlcd/libui/listbox.h
radio/src/gui/colorlcd/libui/menu.cpp
radio/src/gui/colorlcd/libui/menu.h
radio/src/gui/colorlcd/libui/table.cpp
radio/src/gui/colorlcd/libui/table.h
radio/src/gui/colorlcd/radio/radio_theme.cpp

Allow long press of ENTER to change 'Invert' state in switch and source popup menus when menu is open.
Fixes #5640

fix(color): cannot change 'Invert' state on radios with no touch screen

---

radio/src/lua/api_colorlcd.cpp

Make text drawing consistent between firmware, Lua 'lcd' drawing and Lua 'lvgl' drawing.
Fixes #5608 
Note: this may affect the visual display for some widgets.

chore!(color): remove font offsets for Lua 'lcd' text drawing

---

radio/src/mixer.cpp

Remove incorrect scaling of trim values.
Fixes #5656

fix(radio): trim values scaled incorrectly when displayed via Lua

---

.github/workflows/macosx_cpn.yml

GitHub is ending macos-12 support in December 2024, and is already throttling the build duration for this target as of July. 
> The macOS 12 runner image will be removed by December 3rd, 2024. To raise awareness of the upcoming removal, jobs using macOS 12 will temporarily fail during scheduled time periods defined below:
> 
> November 4, 9:00 AM - 7:00 PM EST
> November 11, 9:00 AM - 7:00 PM EST
> November 18, 9:00 AM - 7:00 PM EST
> November 25, 9:00 AM - 7:00 PM EST
> 
ref: https://github.com/actions/runner-images/issues/10721

chore: bump to macos-13

---

radio/src/targets/horus/board.cpp

- Six pos logic stuck at 6 when switched on because the adc did not start sampling yet.

fix(v16): 6pos logic stuck at 6 when switched on

---

radio/src/hal/adc_driver.cpp
radio/src/targets/horus/board.cpp

… adcValues to avoid random readings
Rework #5699
Properly init adcValues to avoid random readings before the mixer task starts, this should be better options for most cases.

fix(v16): Rework 6pos logic fix #5699 by proper init adcValues

---

radio/src/gui/colorlcd/libui/fullscreen_dialog.cpp

PR #5712 changed the fullscreen dialogs to have a solid background color.
This PR uses a less alarming color for non-alert fullscreen dialogs (e.g. flashing bootloader).

feat(color): only use red background for alert screens

---

companion/src/firmwares/generalsettings.cpp
companion/src/firmwares/generalsettings.h

- remove legacy binary GeneralSettings fields
- fix function GeneralSettings::fix6POSCalibration to point to current fields - this was missed when the new fields were added

chore(cpn): remove unused binary general settings fields

---

radio/src/gui/colorlcd/libui/table.cpp
radio/src/gui/colorlcd/libui/table.h

Fixes an issue introduced in PR #5663, where the rotary encoder may stop working on some setup screens.
To reproduce:
- Open the system menu Tools page, verify rotary encoder working
- Page to the SD Manager page, verify rotary encoder working
- Page to the Radio Setup page - rotary encoder stops working

fix(color): rotary encoder events not always working on some screens

---

radio/src/lua/api_model.cpp

Fixes #5666 
Add Lua API for getting details about Global Variables (not the value).
NOTE: I can and do code, but I _really_ don't know C++, however I have put significant effort into getting this right. Thanks.

feat(lua): add getter/setter for Global Variable details

---

radio/src/gui/128x64/model_setup.cpp
radio/src/targets/taranis/hal.h

Fixes:
- display issue in model setup screen
- sw6 was not working
- audio mute wasn't working (unless you pushed sw6, oh boy)

fix(bumblebee): customisable switches display issue, audio mute not working

---

radio/src/gui/colorlcd/libui/table.cpp

PR #5714 introduced a potential crash scenario when changing screen layouts.
Only seen in the simulator so far.

fix(color): potential crash when changing screen layout

---

radio/src/lua/api_colorlcd.cpp

Fix VCENTER offset for legacy Lua drawText function.
Missed in PR #5671 
Fixes #5729

fix(color): VCENTER does not work for Lua drawText function

---

radio/src/gui/128x64/model_setup.cpp

Fix menu line type so only one click of the roller is needed.
Only affects radios with customisable switches (e.g T20, GX12, etc).

fix(bw): roller needs two clicks to move past model setup 'Customisable Switches' line

---

radio/src/lua/interface.cpp

When generating the compiled .luac file for a script the file write may be done with a large number of very small writes to the SD card. For some reason this is failing on the GX12 with some scripts.
This PR buffers the data being written when a .luac file is generated and writes it in larger blocks to the SD card.
This is a workaround for the GX12 issue; but may also reduce the SD write overhead when creating .luac files.
**Note: the underlying issue with the GX12 SD writing should still be investigated and fixed.**
Resolves #5702 but does not fix underlying issue.

fix(radio): writing of .luac files can fail on some radios

---

radio/src/bin_allocator.cpp
radio/src/bin_allocator.h
radio/src/edgetx.cpp

B&W radios implement a custom memory allocator for Lua scripts (bin_allocator.cpp).
This PR makes more RAM available to B&W radios with CCM RAM (GX12, MT12, etc).
It works by moving the custom memory allocator memory area into CCM RAM and allocating more memory to it.
On the GX12 this increases available memory for Lua on startup by ~28K.

feat(bw): make more RAM available to Lua scripts on some radios

---

radio/src/edgetx.h
radio/src/gui/common/stdlcd/radio_tools.cpp

Current implementation of tools menu on BW hammers badly SDcard by continually read the directory and lua scripts.
With this change, all informations is stored in the reusable buffer (so NO extra ram is used at all), and SDcard is read once at load, and then once again when out of page scrolling does happen
For a typical access to the tools menu where you would spend 10sec and launch a script, that's around 100 times less sdcard access (hence the dramatically)

feat: dramatically reduce SDcard access while in Tools screen 

---

radio/src/lua/interface.cpp

Seems the last parameter to f_write is not optional (from PR #5716)

fix(radio): potential crash when writing .luac files

---

radio/src/CMakeLists.txt

- compiler version test that was included as part of #5263 was placed too high, and would false trigger when doing builds using the native compiler. This is now done later, when firmware target only configuration is done.

fix: move firmware compiler version check down 

---

radio/util/hw_defs/hal_adc.py

Comment out build diagnostic that outputs "['1', ' -1', ' 1', ' -1', ' 1', ' 1', ' 1']" string.

chore: remove ADC_DIRECTION diagnostic from build output

---

radio/src/translations/de.h

The term "armen" is a mixture of english and german. Because there is no good direct translation of the verb "to arm" I would suggest to leave the english term even in the german translation (as in other similar situations too). 
The german translation "scharf schalten" is too long.

chore(translation): change CRSF_ARMING_MODE German text

---

radio/src/targets/nv14/CMakeLists.txt

fix(nv14): AFHDS3 missing for FRM303 external module

---

radio/src/gui/128x64/model_setup.cpp
radio/src/hal/rgbleds.h
radio/src/targets/simu/led_driver.cpp
radio/src/targets/taranis/led_driver.cpp
radio/src/translations/cn.h
radio/src/translations/cz.h
radio/src/translations/da.h
radio/src/translations/de.h
radio/src/translations/en.h
radio/src/translations/es.h
radio/src/translations/fi.h
radio/src/translations/fr.h
radio/src/translations/he.h
radio/src/translations/it.h
radio/src/translations/jp.h
radio/src/translations/nl.h
radio/src/translations/pl.h
radio/src/translations/pt.h
radio/src/translations/ru.h
radio/src/translations/se.h
radio/src/translations/tw.h
radio/src/translations/ua.h

Fixes a number of issues with the way the colors are handled for the custom switches on the GX12:
- Default ON color is 'white'; but shows as 'blue' when viewed in model settings.
- If a custom value is set manually in the model file the color is shown as 'blue' instead of 'custom' in model settings.

fix(bw): customisable switch LED color text sometimes incorrect on GX12

---

companion/src/simulation/simulatorinterface.h
companion/src/simulation/simulatormainwindow.cpp
companion/src/simulation/simulatormainwindow.h
companion/src/simulation/simulatormainwindow.ui
companion/src/simulation/simulatorwidget.cpp
companion/src/simulation/simulatorwidget.h
radio/src/hal/adc_driver.cpp
radio/src/targets/simu/adc_driver.cpp
radio/src/targets/simu/opentxsimulator.cpp
radio/src/targets/simu/opentxsimulator.h

Fixes #5053
- add Battery Voltage option to Tools menu
Notes:
- the radio will not update to the new voltage instantly but over a number of adc read cycles as filtered adc averaging is used.
- there maybe instances of rounding variance as the radio uses integers
- the tx battery settings for min max and warn values are only read on sim load ie changes via radio ui will not be detected

feat(cpn): simulator allow manually setting transmitter battery voltage

---

radio/src/gui/colorlcd/model/preflight_checks.cpp

Fix position of custom throttle check value input.

fix(color): focus border clipped on custom throttle check input value

---

radio/src/CMakeLists.txt

- now that the version check is *not* breaking everything other firmware builds... the version check can be a fatal error unless `-DUSE_UNSUPPORTED_TOOLCHAIN=Y` is specified as a build option to force it to be skipped.

chore: make firmware check fatal error by default

---

companion/src/simulation/simulatorinterface.cpp
companion/src/simulation/simulatorinterface.h

With ~40 libsims currently available, the application load time and resource consumption is a worsening issue. The current loading method was developed when there were < 10 libsims.
- do not load, validate and unload all libsims during Companion start-up to reduce start-up time.
- load libsims on demand to reduce total memory reserved (varies per OS)
Note: based on a comment in Qt QLibrary documentation, MacOS does not unload shared resources until the application is terminated therefore the current unload is ineffective.

chore(cpn): delay loading libsims

---

radio/src/edgetx.cpp
radio/src/edgetx.h

The USB code uses `USBD_static_malloc`, which allocates a static buffer based on `sizeof(USBD_MSC_BOT_HandleTypeDef)`.

chore(usb): remove obsolete MSC_BOT_Data

---

radio/src/targets/horus/board.h

Using 400kB as baudrate for debugging via serial seems a bit strange because this is not a "standard baudrate" and some cheap USB/serial converter like the popular `CP210x` do not support these non-standard baudrates (at least with `picocom`).

Change the DEBUG_BAUDRATE to a standard baudrate (460800) for TX16S and F16

---

radio/src/gui/128x64/view_channels.cpp

feat(bw128): display PPM value in channel monitor

---

companion/src/firmwares/boards.cpp
companion/src/firmwares/boards.h
companion/src/firmwares/edgetx/yaml_modeldata.cpp
companion/src/firmwares/modeldata.h

Currently Companion will lose the function switch colors when loading model data from the radio.
Note: the colors cannot be edited or viewed in Companion yet. This just ensures they survive being loaded from the radio.

feat(cpn): add customisable switch colors to Companion YAML file handling

---

radio/src/edgetx.cpp

Fixes #5795 
Skip evalFunctionSwitches until fully initialised in simulator.

fix(sim): initial state for customisable switches not set correctly

---

radio/src/gui/128x64/radio_setup.cpp
radio/src/gui/common/stdlcd/radio_hardware.cpp

On color radios the battery range and calibration are together on the Hardware page, which makes sense to me.
On B&W the battery range is on Radio / Setup, and calibration is on Radio / Hardware.
This PR moves the battery range to be with calibration on the Hardware page.

feat(bw): move battery range settings to Radio / Hardware tab

---

radio/src/gui/128x64/model_setup.cpp
radio/src/hal/rgbleds.h
radio/src/targets/simu/led_driver.cpp
radio/src/targets/taranis/led_driver.cpp

Changes:
- Editing of custom function switches is on a new menu page so all the fields have labels to show what they are.
- On radios with RGB LEDs (GX12) the color RGB values can be edited to select any color.
- Removed the color editing from the main model setup menu page.
- All 24 color bits are sent to the LED strip instead of only 5 bits per color.

feat(bw128): add customisable switches edit page, allow editing custom colors

---

radio/src/CMakeLists.txt
radio/src/boards/generic_stm32/linker/stm32f40x/extra_sections.ld
radio/src/edgetx.cpp
radio/src/gui/colorlcd/standalone_lua.cpp
radio/src/lua/bin_allocator.cpp
radio/src/lua/ccm_allocator.cpp
radio/src/lua/custom_allocator.cpp
radio/src/lua/custom_allocator.h
radio/src/lua/interface.cpp
radio/src/lua/widgets.cpp

This PR replaces the current 'bin_allocator' with a new one that uses all free CCM RAM.
The CCM RAM free list is set up on startup instead of trying to do it at compile time. This removes the need to tweak the 'bin_allocator' settings as memory usage changes.
Applies to all B&W radios with CCM RAM.
B&W Radios without CCM RAM continue to use the old 'bin_allocator'.

feat(f4): more free memory on handsets with CCM RAM

---

radio/src/edgetx.h
radio/src/gui/common/stdlcd/radio_tools.cpp

Fixes buffer overflows in B&W Radio Tools page.
To reproduce copy a large set of .lua tool scripts to the SCRIPTS/TOOLS folder on a B&W radio.

fix(bw): radio tools list may display incorrect names

---

radio/src/lua/api_model.cpp

Model > Input -> Side is missing from the Lua API.
This PR puts it back in.
NOTE: I think this is correct, I've been able to compile firmware, but currently I am unable to get the simulator to compile on a Ubuntu22 VM. It dies with the following error and my C++ skills are not going to be sufficient to move forward.
```
In file included from /home/user/edgetx/edgetx_main/companion/src/firmwares/eeprominterface.h:27,
from /home/user/edgetx/edgetx_main/companion/src/storage/eepe.cpp:24:
/home/user/edgetx/edgetx_main/build-output/native/../../radio/src/definitions.h:28:10: fatal error: memory_sections.h: No such file or directory
28 | #include "memory_sections.h"
|          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

fix(lua): stick "side" missing from model.getInput

---

radio/src/lua/interface.cpp

Kill events when script closes itself to prevent the script running again.

fix(bw): prevent script from re-opening itself

---

radio/src/gui/colorlcd/module/mpm_settings.cpp

Display correct name for MPM RF Protocol.
Fixes #5812

fix(color): MPM - wrong display of used RF protocol

---

radio/src/targets/common/arm/stm32/bootloader/boot.cpp

This fixes an issue where since #5738, gx12 (and possibly others) would not enter BL on first cold try.
Also happened to help user [CarlosPC on Discord](https://discord.com/channels/839849772864503828/839895574244229152/1331620399154466846).
This only affect cold start, and not at all EM handling (that isn't coming from cold state, so doesn't need stabilisation time)

fix: gx12 not entering BL

---

radio/src/gui/colorlcd/widgets/value.cpp

Fixes the issue were the value widget wouldn't display units in any of the four row screen layouts.

fix(color): attempt to show units for value widget if height < 50  - 2.10

---

radio/src/gui/colorlcd/widgets/value.cpp

- don't drop value unit at all, just try to show it, even if it gets clipped
`main` version of #5811

fix(color): attempt to show units for value widget if height < 50

---

radio/src/lua/interface.cpp
radio/src/lua/lua_api.h

Prevent phantom 'Script error' message after trying to load a Lua 5.2 version file.
Radio shows a 'Script error' message after trying to run a tool where a Lua 5.2 version .luac file already exists.

fix(bw): prevent phantom 'Script error' message after trying to load a Lua 5.2 luac file

---

radio/src/gui/colorlcd/radio/hw_inputs.cpp
radio/src/gui/colorlcd/radio/hw_inputs.h

fix(color): setup dialog for pots on portrait LCD has overlapping text

---

radio/src/audio.cpp

The simulator f_readdir() function calls f_stat for each file in the directory.
This can be slow especially on network drives when the code is scanning the SYSTEM sounds folder, looking for the system sounds.
This PR changes the logic for the simulator to loop over the system sound files names, calling f_stat() for each one.
On my Mac this reduces the sound file scan time from 5.7s to 1.4s when reading from a NAS drive.

feat(sim): startup can be slow when scanning SYSTEM audio files

---

radio/src/thirdparty/Lua/src/liolib.c

Fixes #5832
Use parameter "n" instead of the fix LUAL_BUFFERSIZE

fix(lua): io.read always reading 256 bytes rather than specified value

---

radio/src/telemetry/spektrum.cpp

Fixes #5834 
1.  Replace calls for "sprintf" who internally use "malloc" for more basic formatting and concatenation functions.  Someone recommended this change since malloc could not be thread-safe for the telemetry thread.  
2. Remove unused (or always 0) Smart Battery sensors. Even after using a "smart" charger with "smart" batteries, seems that they are not populating the telemetry values properly.   
- Cycl: (Charger Cycles) comes as 0, 
- BUse (MAh used) comes as 0, 
- CLMa (Cell max v) comes as 0
This helps reduce the list of sensors, especially useful for B&W radios.

chore(dsm): remove always zero sensors, use thread safe functions

---

radio/src/boards/generic_stm32/linker/stm32h750_sdram/extra_sections.ld
radio/src/boards/generic_stm32/linker/stm32h7rs_sdram/extra_sections.ld

Yet another issue with H7 linker scripts.

fix(h750): missing .iram code

---

radio/src/edgetx.cpp
radio/src/targets/horus/hal.h
radio/src/targets/taranis/hal.h
radio/util/hw_defs/legacy_names.py
radio/util/hw_defs/pot_config.py

This precalibrate 6POS on TX16S radio, so that if 6POS is not manually calibrated by user, it operates with default values that should be ok unless radio has been somehow modded.
Note: this precalibration is loaded on radio default creation, so will only affect new/reformated radio. It will stay in place no matter how many times calibration is run as long as users doesn't initiate a 6POS calibration

feat(tx16s): default calibration for 6POS

---

companion/src/firmwares/boardjson.cpp
companion/src/firmwares/boards.h

- handle ADC switch type
- ADC switch TOGGLE set to non-toggle 3 position switch as toggle could be 2 or 3 positions
Note: hardware setup, assignable switches, simulator and yaml read/write will use 3 position non-toggle logic.
PL18 in main

fix(cpn): ADC switch type hardware definition

---

radio/src/gui/colorlcd/mainview/view_main.cpp

Restore 2.10 functionality.
Long press of ENTER enables widget selection mode, the popup menu should not open immediately so the user can select the widget to operate on with the rotary encoder.

fix(color): long ENTER on main view not allowing widget selection

---

companion/src/firmwares/boards.cpp
companion/src/firmwares/moduledata.cpp

Fixes #5839
- some handsets were missing sbus trainer capability
- bumblebee was missing default nano module state

fix(cpn): missing sbus trainer for some handsets

---

radio/src/targets/common/arm/stm32/vs1053b.cpp
radio/src/targets/common/arm/stm32/vs1053b.h
radio/src/targets/horus/board.cpp
radio/src/targets/nv14/board.cpp

- allows for boards to define custom callbacks for RST and MUTE pins, instead of assuming regular GPIOs.

feat(vs1053b): use callbacks for RST & MUTE pins

---

radio/src/edgetx.h
radio/src/strhelpers.cpp
radio/src/strhelpers.h
radio/src/targets/simu/opentxsimulator.cpp
radio/src/tests/gtests.cpp

If the flight mode has a non-empty name it is not being displayed correctly in the simulator window title.
Also cleans up some unused code and moves string related definitions to strhelpers.h.

fix(sim): flight mode name incorrect in the simulator window title bar

---

companion/src/companion.qrc
companion/src/firmwares/edgetx/yaml_modeldata.cpp
companion/src/firmwares/modeldata.cpp
companion/src/firmwares/modeldata.h
companion/src/firmwares/radiodata.cpp
companion/src/firmwares/radiodata.h
companion/src/images/originals/circle-green.svg
companion/src/images/originals/circle-orange.svg
companion/src/images/originals/circle-red.svg
companion/src/images/svg/circle-green.svg
companion/src/images/svg/circle-orange.svg
companion/src/images/svg/circle-red.svg
companion/src/mainwindow.cpp
companion/src/mdichild.cpp
companion/src/mdichild.h
companion/src/mdichild.ui
companion/src/modeledit/modeledit.cpp
companion/src/modeledit/modeledit.h
companion/src/modelslist.cpp

Fixes #5793
- check every model's inputs and mixes for source
- new traffic light status for each models and settings file, green if no errors
- if no source(s):
- only allow saving to etx format
- disable writing to radio or sd path as no source causes unexpected behaviours
- disable simulate model and radio for the same reasons
- new dialog to display errors
- change status to red and display the number of models with errors

fix(cpn): inputs and mixes must have source

---

radio/src/storage/storage_common.cpp

Fixes #5826
While this does fix the issue, I do wonder if it would be better to instead set this as part of the one-shot `generalDefault()` that is run if there is no settings present, and thus not also override the user setting if they *don't* want to build custom firmware.

fix(x12s): only preset AUX2 to GPS if enabled

---

radio/src/lua/api_model.cpp

Fixes #5873 
- add missing `speedPrec` to Lua getMix() and insertMix() functions
Tested on GX12 with two mixer lines on CH20, lua function script run via SF will create the third. It beeps when it runs ;)
```lua
local tab
local function init()
-- Called once when the script is loaded
end
local function run(event, touchState)
-- Called periodically while the Special Function switch is on
tab = model.getMix(19, 1) -- copy the first mixer line into the Table  "tab"
model.insertMix(19, 2, tab) -- Insert the mixer line ("tab") in the second line of the channel
playTone(2550, 160, 20, 3, -10)    -- play tone, use radio settings Beep volume
end
local function background()
-- Called periodically while the Special Function switch is off
end
return { run=run, …
```

fix(lua): missing speedPrec for getMix/insertMix

---

radio/src/lua/api_model.cpp

Mentioned in #5873, same test script as in #5874 can be used here. 
- add missing delayPrec to Lua getMix() and insertMix() functions
- related to #5314

fix(lua): missing delayPrec for getMix/insertMix

---

radio/src/targets/horus/board.cpp

Appears the (unintentional, as it is already done in board.cpp a few lines further down?) double init introduced in #5284 locks up T16 hard on boot if no TP present. Tested TX16S w/ TP, still working fine. 
Fixes #5328

fix: remove redundant touchPanelInit

---

radio/util/hw_defs/hal_json.py
radio/util/hw_defs/hal_keys.py

Fixes #5860 
- define override key labels per groups of radio targets to more closely match physical radios
- affects radio diagnostics and libsim buttons
TODO:
- add radio specific keys for all radios to lookup matrix

fix(chore): key labels match physical radios

---

companion/src/simulation/simulateduiwidget.cpp

For using the simulator on radios with a SHIFT button where the user keyboard does not have an 'Ins' key.

fix(sim): add 'Shift' key shortcut in the simulator

---

radio/src/edgetx.cpp
radio/src/gui/colorlcd/startup_shutdown.cpp

fix(color): unable to turn off radio if powered on with no SD card.

---

radio/src/targets/common/arm/stm32/rtc_driver.cpp

Fix RTC issue when RTC battery is removed.
I have a feeling it should fix 5782 too. If someone could test

fix: RTC issue causing time reset and lag on colorlcd 

---

radio/src/gui/colorlcd/mainview/layout.cpp
radio/src/gui/colorlcd/mainview/widgets_container_impl.h

Ensure all old top bar widgets are removed when changing models.
Can happen when switching from a model that has less top bar widget slots (using the size settings), to one with more slots.

fix(color): top bar widgets may not get removed when switching models.

---

radio/src/gui/gui_common.cpp

Fixes #5912 
Fix missing source option.

fix(radio): '---' option is missing when selecting some source values.

---

radio/src/gui/colorlcd/mainview/layout.cpp
radio/src/gui/colorlcd/mainview/layout.h
radio/src/gui/colorlcd/mainview/layout_factory_impl.cpp
radio/src/gui/colorlcd/mainview/layout_factory_impl.h
radio/src/gui/colorlcd/mainview/screen_setup.cpp
radio/src/gui/colorlcd/mainview/view_main.cpp
radio/src/gui/colorlcd/mainview/widgets_container.h
radio/src/gui/colorlcd/mainview/widgets_container_impl.h
radio/src/storage/sdcard_common.cpp
radio/src/storage/storage_common.cpp

Fixes #5909 
Ensure all view screens are correctly updated.
To reproduce, create a model with multiple view screens. Enter screen setup and change to a view other than the current visible one. Change settings (topbar, trims, sliders, etc). Exit screen setup and scroll to the changed screen.

fix(color): view screen layout may not update correctly after changing screen setup.

---

radio/src/gui/colorlcd/libui/list_line_button.cpp

Fixes #5884 
Reduce font size if mix source string is long.

fix(color): mix line source string may be truncated if it is too long.

---

radio/src/gui/128x64/model_setup.cpp
radio/src/gui/common/stdlcd/popups.cpp

Fixes #5895
- ensures `killAllEvents()` is only run on `POPUP_MENU_START()` starting a new menu

fix(bw): bluetooth discovery popup menu lockup

---

radio/src/targets/common/arm/stm32/rtc_driver.cpp

While looking into RTC issues, I stumbled into this piece of code that looked out of place according to STM docs

fix: enable/disable RTC_BACKUP write access

---

radio/src/CMakeLists.txt
radio/src/edgetx.h
radio/src/options.h
radio/src/targets/horus/board.cpp
radio/src/targets/pl18/board.cpp
radio/src/targets/taranis/board.cpp

Resolves #5010
- allows for user override of Power LED startup sequence from the mostly standardised RED (pre RTC init), BLUE (starting up), GREEN (ready to use) via compile time flag
- inverts the blue -> green sequence to be green -> blue, allowing for blue to be the "ready" color, and adds mention of this override to build opts listing. 
Tested on TX16S, Boxer and PL18EV

feat: allow for compile time user override of power LED color

---

radio/src/thirdparty/Lua/src/liolib.c

fix(lua): io.open(filename, “a”) overwriting instead of appending

---

companion/src/firmwares/edgetx/yaml_modeldata.cpp

- do not assume led on/off colour settings are present for every possible function switch

fix(cpn): don't assume all lcd customisable switches have colour settings

---

radio/src/targets/pl18/bootloader/boot_menu.cpp

Flash firmware screen has text overlapping (the green tick)

fix(color): bootloader text overlap on portrait layout

---

radio/src/edgetx.cpp
radio/src/targets/taranis/gx12/bsp_io.cpp
radio/src/telemetry/telemetry.cpp

First, I would like to thanks Radiomaster devs for their investigation and contribution to bring to surface this issue. Great work guys.
Bottom line is that we have an issue with async call handling based on xTimerPendFunctionCallFromISR(). We need some time to understand why we have that issue.
In the meantime, this workaround allows the switch to be read even if the call to xTimerPendFunctionCallFromISR() was not successful.
Another part of EdgeTX relying heavily on xTimerPendFunctionCallFromISR() is telemetry handling, but the protocol is handling it so this is not critical, so the workaround is not applied there.

refactor(radio): async call handling to prevent GX12 switch lockups

---

radio/src/gui/gui_common.cpp
radio/src/pulses/modules_helpers.h
radio/src/telemetry/crossfire.h

Fixes #5960
- If `-DCROSSFIRE=N` defined at compile time, calls to `CRSF_ELRS_MIN_VER()` are not valid, and response should simply be "no". `crossfireModuleStatus` does not exist, so should not be checked. 
- Also, use the helper function rather than reinvent the wheel

fix: don't check ELRS version if crossfire disabled

---

radio/src/functions.cpp

Fixes #5955, alternative to #5963
- change from uint16_t to int32_t data type, since we are getting a signed (negative) value also now
- preserve sign for source/value when needed, otherwise strip it to allow conditional processing to continue to work "normally"
Prior to this, it was going into the `if (idx >= MIXSRC_FIRST_TELEM)` branch for sources such as Inv Thr, since (using example of Inv Thr) idx was `65535`, not `-1`... :hand_over_mouth:

fix(radio): fix inverted source causing EM on PlayValue SF trigger

---

radio/src/CMakeLists.txt
radio/src/edgetx.h
radio/src/targets/taranis/board.cpp

- make power led sequence conditional on presence of LED_GREEN_GPIO or RGB capability rather than MFG defines
- sole exception is LR3PRO
Fixes standard power on sequence for Flysky radios, as they were omitting the startup green phase.

chore(radio): tweak POWER_LED_BLUE, fix Flysky startup sequence

---

companion/src/radiointerface.cpp

Due to multiple location detection (#5657) whoopsie. 
Fixes #5974
- store found sdcard path/file only if found rather than on each (and possibly invalid) check

fix(cpn): sometimes reads wrong SD card path

---

radio/src/boards/generic_stm32/rgb_leds.cpp
radio/src/boards/generic_stm32/rgb_leds.h
radio/src/targets/common/arm/stm32/stm32_ws2812.cpp
radio/src/targets/common/arm/stm32/stm32_ws2812.h
radio/src/targets/horus/board.cpp
radio/src/targets/pl18/board.cpp
radio/src/targets/taranis/board.cpp
radio/src/targets/taranis/hal.h

Get back around 120 bytes on GX12 and MT12
Remove some duplicates declarations between WS2812_MAX_LEDS  and LED_STRIP_LENGTH, and other cleanups and rationalisation (thx @raphaelcoeffic )

chore(radio): save some ram in radios with RGB LEDs

---

radio/src/gui/colorlcd/model/model_select.cpp

Reported on discord.
Set label background and transparency when model not selected.

fix(color): model name may be hard to read on model select page

---

radio/src/gui/colorlcd/model/model_curves.cpp
radio/src/gui/colorlcd/model/model_mixes.cpp

Fixes:
- mix line with a single mix has a 1 pixel vertical scroll
- curve type string is clipped along the bottom

fix(color): minor layout issues on mixes and curves screens

---

radio/src/lua/interface.cpp

i.e. for telemetry screens on bw, when you've deleted/moved the Lua, it will display "unknown error" when we can actually detect the file is missing. 
Resolves #5945

fix(lua): display "needs file" rather than "unknown error"

---

radio/src/gui/128x64/model_flightmodes.cpp

Resolves #5992
- flight/drive mode list should start at 0, not 1

fix(bw): FM/DM list starting at one, not zero

---

companion/src/firmwares/modeldata.cpp
companion/src/firmwares/modeldata.h
companion/src/modeledit/inputs.cpp
companion/src/modeledit/inputs.h

Fixes #5988
- new sort inputs function (based on sort mixes)
- replace complex shuffles with simple reference swap and sort (much lower risk)
- move down uses same method
- minor housekeeping

fix(cpn): moving input line up to an empty line resulted in input data loss

---

radio/src/edgetx.h
radio/src/gui/128x64/gui.h
radio/src/gui/128x64/model_curve_edit.cpp
radio/src/gui/128x64/model_input_edit.cpp
radio/src/gui/128x64/model_mix_edit.cpp
radio/src/gui/128x64/view_channels.cpp
radio/src/gui/128x64/view_main.cpp
radio/src/gui/212x64/gui.h
radio/src/gui/212x64/view_main.cpp
radio/src/gui/common/stdlcd/draw_functions.cpp
radio/src/gui/common/stdlcd/model_usbjoystick.cpp
radio/src/gui/common/stdlcd/radio_sdmanager.cpp
radio/src/gui/common/stdlcd/view_telemetry.cpp
radio/src/gui/gui_common.cpp
radio/src/gui/gui_common.h
radio/src/gui/navigation/navigation.h
radio/src/gui/navigation/navigation_x7.cpp
radio/src/keys.cpp
radio/src/keys.h

Move most of the configuration for the different B&W navigation types into the navigation code files.
This PR focuses on the KEY navigation variations, to hopefully make future changes easier to manage.
There are a few other places where NAVIGATION_X7 is being used to control how the UI is displayed.
These may be able to be cleaned up in future.
Not sure if this will be needed for 2.11 or can wait for 3.0.

chore(bw): cleanup and consolidate navigation code

---

radio/src/functions.cpp

Limit the backlight SF input value to admissible range
This fixes #6002

fix(radio): constrain Backlight SF input value to valid range

---

radio/src/gui/colorlcd/libui/list_line_button.cpp
radio/src/gui/colorlcd/mainview/layout.h
radio/src/gui/colorlcd/mainview/layout_factory_impl.h
radio/src/gui/colorlcd/mainview/screen_setup.cpp
radio/src/gui/colorlcd/mainview/widget.cpp
radio/src/gui/colorlcd/mainview/widget.h
radio/src/gui/colorlcd/mainview/widget_settings.cpp
radio/src/gui/colorlcd/mainview/widgets_container.h
radio/src/gui/colorlcd/mainview/widgets_setup.cpp
radio/src/gui/colorlcd/standalone_lua.cpp
radio/src/gui/colorlcd/standalone_lua.h
radio/src/lua/api_colorlcd.cpp
radio/src/lua/api_colorlcd_lvgl.cpp
radio/src/lua/api_general.cpp
radio/src/lua/lua_api.h
radio/src/lua/lua_lvgl_widget.cpp
radio/src/lua/lua_lvgl_widget.h
radio/src/lua/lua_widget.cpp
radio/src/lua/lua_widget.h
radio/src/lua/lua_widget_factory.cpp
radio/src/lua/lua_widget_factory.h
radio/src/lua/widgets.cpp
radio/src/strhelpers.cpp
radio/src/strhelpers.h
radio/src/telemetry/crossfire.cpp
radio/src/telemetry/frsky_sport.cpp
radio/src/telemetry/ghost.cpp
radio/src/telemetry/telemetry.cpp
radio/src/telemetry/telemetry.h
radio/src/tests/crossfire.cpp

Summary:
- Make current Lua script owner visible to API functions (for PR #5773).
- Add telemetry queue per widget (for PR #5773).
- Send path name of widget folder to script 'create()' function (requested by @offer-shmuely).
- Enhancements for widgets option default values, getSwitchIndex() and getSourceIndex() Lua function (for Issue #5917).
Details:
This PR allow the Lua API functions to access the widget or stand alone script that called the function. In addition this adds the telemetry queue per widget required for #5773.
The code now sends the path of the widget being loaded to the script 'create()' function (as the 3rd parameter).
The following changes have been made to the getSwitchIndex() and getSourceIndex() API functions:
- Both functions check the name value against the …

feat(color): telemetry queues for Lua, enhance default widget options

---

radio/src/gui/colorlcd/model/model_logical_switches.cpp

Don't try and process LS events if not initialised.

fix(color): logical switch list page crash

---

radio/src/lua/lua_lvgl_widget.cpp
radio/src/lua/lua_lvgl_widget.h

Fixes an issue when trying to clear part of a layout.
Using lvgl.clear() works and clears the entire layout.
Using lvgl.clear(child) does not clear the child part of the layout correctly.

fix(color): lvgl.clear() not working correctly for Lua child layouts

---

radio/src/gui/128x64/lcd.cpp
radio/src/gui/212x64/lcd.cpp

Fixes #6010 
Clip co-ordinates in line drawing functions.

fix(bw): drawing lines with out of bounds co-ordinates may crash

---

radio/src/telemetry/spektrum.cpp

Fixes #6013
A bit of History:
The Spektrum Documentation does not say what type of encoding to use.  So we and OpenXSensor assumed big-endian when we initially added support for this sensor.  #4715
1. Byte encoding was wrong for the Lipo 6s sensor. Should be little-endian.
2. The NO-DATA for Battery Temp is also an exception to the rule (0x7FFF instead of 0xFFFF for uint16). Added a check to avoid creating a sensor with the wrong value.
3. Added FrSky Style "Cells" (all Cells in a single censor) for Smart Batteries. This allows creation of calculated sensors for the lowest/highest/delta from the entire pack.  
TODO Discussion: Now that all batteries use the "Cels" group sensor. could be a good idea in the future to stop populating the individual cells.. There is a way …

fix(tele): DSM LIPO 6S sensor endian order

---

radio/src/edgetx.h
radio/src/gui/common/stdlcd/radio_tools.cpp

Fixes #6026
Increase the size of the buffer for the path string (changed in #5721).

fix(bw): tool scripts with long file names not working

---

radio/src/dataconstants.h

Fixes issue reported on Discord. 
https://discord.com/channels/839849772864503828/1353416655216312370/1353416655216312370
- change MIN_POINTS_PER_CURVE to 2 to match UI
Prior to this you could only create 3 point curves onwards via Lua. Tested on TX16S simulator using following mixer Lua. 
```
local curveIdx = 0
local function toint(f)
if f > 0 then
return math.floor(f)
else
return math.ceil(f)
end
end
local function updateCurve()
local value = getValue("s1")
print("value: " .. value)
value = value * (100.0 / 1024.0)
print("value-y: " .. value)
curve = {}
curve["x"] = {-100, 100}
curve["y"] = {-70, value}
curve["smooth"] = true
curve["type"] = 1
model.setGlobalVariable(8, 0, value * (100.0 / 1024.0) * 0.5 + 50)
val = model.setCurve(curveIdx, curve)
print("setCurve0: " …
```

fix(lua): setCurve min points should be 2

---

companion/src/datamodels/compounditemmodels.cpp

This is Companion part of #5488 to address #5485

fix(cpn): remove custom switches from global functions

---

radio/src/gui/colorlcd/model/model_templates.cpp

To reproduce, try and create a new model from the personal templates folder when there are no templates on the SD card.

fix(color): when the personal templates folder is empty the description section shows 'Text'

---

radio/src/gui/colorlcd/libui/page.cpp
radio/src/gui/colorlcd/libui/page.h
radio/src/gui/colorlcd/libui/tabsgroup.cpp
radio/src/gui/colorlcd/libui/tabsgroup.h
radio/src/gui/colorlcd/libui/window.cpp
radio/src/gui/colorlcd/libui/window.h
radio/src/gui/colorlcd/model/model_templates.cpp
radio/src/gui/colorlcd/model/model_templates.h
radio/src/gui/colorlcd/radio/radio_ghost_module_config.cpp
radio/src/gui/colorlcd/radio/radio_ghost_module_config.h

In 2.10 and earlier a long press of the RTN key would exit setup pages because the long press event was always followed by a short press event (unless cancelled).
This PR restores this functionality to 2.11.

fix(color): allow long press of RTN key to also exit setup pages

---

companion/src/helpers.cpp
companion/src/simulation/simulator.h
companion/src/simulator.cpp

Fixes #5919
Alternative solution to #5931
- Companion writes models and settings to a temporary directory and launches the standalone Simulator in a new process
- the Simulator startup dialog is bypassed unless something goes unexpectantly wrong
- Companion waits for the Simulator to finish before becoming responsive (like a modal dialog)
- new Simulator cli option flags to permit Companion to pass flags that it previously passed to its self contained simulator

fix(sim): libsims not unloading

---

radio/src/mixes.cpp

Fixes #6033 
Update the array used for slow up/down calculations when mix lines are inserted or deleted.

fix(radio): channel outputs may jump when mix lines are inserted or deleted

---

radio/src/gui/colorlcd/mainview/widget_settings.cpp

Reported on discord => https://discord.com/channels/839849772864503828/839856795781431317/1357351877175414824
The widget options default values are not being loaded on radio start.
When a widget is first added the default are parsed so the settings dialog shows the correct options.
After restart opening the widget settings dialog does not show the correct options.

fix(color): widget option default values are not loaded on radio restart

---

radio/src/targets/horus/hal.h
radio/src/targets/horus/led_driver.cpp

Fixes #6040
- LED_GREEN_GPIO should not be configured on X10/X10 Express as it is not MCU controlled

chore(x10): LED_GREEN_GPIO should not be configured

---

radio/src/gui/colorlcd/libui/etx_lv_theme.cpp
radio/src/gui/colorlcd/libui/etx_lv_theme.h
radio/src/gui/colorlcd/widgets/timer.cpp
radio/src/lua/lua_lvgl_widget.cpp
radio/src/lua/lua_lvgl_widget.h

Adds the following properties to the arc object:
- rounded
- bgColor
- bgOpacity
- bgStartAngle
- bgEndAngle
Example:
```Lua
lvgl.arc({radius=30, thickness=8, startAngle=155, endAngle=25,
bgStartAngle=120, bgEndAngle=60, bgColor=GREY, bgOpacity=255,
color=RED, rounded=true})
```

feat(lua): add additional properties to the Lua Lvgl arc object.

---

radio/src/gui/128x64/model_outputs.cpp
radio/src/gui/colorlcd/model/model_outputs.cpp
radio/src/gui/colorlcd/model/output_edit.cpp

Fixes #6058, fixes #6052
Changes (when PPM Unit = μs):
- B&W 128x64 - show subtrim edit value as μs
- Color - show subtrim edit value as μs
- Color - show subtrim value as μs on the list page
Wide screen B&W radios do not need any changes.

fix(radio): inconsistent display for sub trim in outputs, bold indicators for bw128

---

radio/src/translations/cn.h
radio/src/translations/cz.h
radio/src/translations/da.h
radio/src/translations/es.h
radio/src/translations/fi.h
radio/src/translations/fr.h
radio/src/translations/he.h
radio/src/translations/it.h
radio/src/translations/jp.h
radio/src/translations/nl.h
radio/src/translations/pl.h
radio/src/translations/pt.h
radio/src/translations/ru.h
radio/src/translations/se.h
radio/src/translations/tw.h
radio/src/translations/ua.h

Translation definition missing in other languages.  Changes in #5703 only updated en and de, with other languages missing.

fix(radio): missing translation strings

---

radio/src/gui/colorlcd/controls/color_editor.cpp
radio/src/gui/colorlcd/controls/color_picker.cpp

Currently when changing the values of the color bars in the color editor with the scroll wheel, moving the wheel left decreases the bar value and right increases the value.
Since most of the bars have 0 at the bottom, this means that scrolling left moves the indicator down and scrolling right moves the indicator up.
This is backwards compared to the rest of the UI, left moves up the screen and right moves down.
This PR makes the scroll wheel consistent on all the color bars - left moves the indicator up and right moves it down.

fix(color): scroll wheel direction is not intuitive when editing color bars

---

cmake/FetchMaxLibQt.cmake
cmake/FetchMiniz.cmake
cmake/FetchYamlCpp.cmake
cmake/GenericDefinitions.cmake
companion/src/CMakeLists.txt

- bumps commits for  EdgeTX/maxLibQt, miniz, yamp-cpp to latest commits, which are 4.0 compatible
- removes two no longer valid policies. CMP0023 appears to be a safe removal, CMP0026 *might* only be an issue for QT5 libraries (if at all - all three Companion builds were successful on my fork) (regex search `get_target_property\(.*LOCATION\)`)

chore: CMake 4.0 compatibility

---

radio/src/switches.cpp
radio/src/tests/mixer.cpp

Fixes #5975 
If a 2POS switch is wired to a 3POS connector, then treat the mid switch position as equivalent to the down position.

fix(radio): a 2POS switch connected to a 3POS socket may not behave as expected

---

radio/src/gui/colorlcd/libui/menu.cpp

fix(color): bluetooth setup menu crashes when discovering devices

---

radio/src/gui/128x64/view_main.cpp

Fixes #6073 
On radios with more than 6 switches the default is to use the small switch display layout.
If multiple switches are disabled the code tried to use the large switch display layout; but the switch position array values do not cater for this.
Changed to always use the small switch display if there are more than 6 physical switches.

fix(bw): switch display may overlap other elements if switches are disabled

---

companion/src/translations/companion_cs.ts
companion/src/translations/companion_da.ts
companion/src/translations/companion_de.ts
companion/src/translations/companion_en.ts
companion/src/translations/companion_es.ts
companion/src/translations/companion_fi.ts
companion/src/translations/companion_fr.ts
companion/src/translations/companion_he.ts
companion/src/translations/companion_it.ts
companion/src/translations/companion_ja.ts
companion/src/translations/companion_nl.ts
companion/src/translations/companion_pl.ts
companion/src/translations/companion_pt.ts
companion/src/translations/companion_ru.ts
companion/src/translations/companion_sv.ts
companion/src/translations/companion_zh_CN.ts
companion/src/translations/companion_zh_TW.ts
companion/src/wizarddata.cpp

Fixes #6003
- give context for Qt translation for some strings
- shorten length of some overly long mix names (> 6 chars)
- trim some `IS_SKY9X()` while there
- rerun `companion_transtions` task while here

fix(cpn): valid mix name lengths, wizard translation context

---

companion/src/storage/labeled.h
companion/src/storage/minizinterface.h

The miniz.h header now generates lots of 'unused function' warnings.

chore(cpn): disable all the warnings in the miniz header

---

radio/src/lua/lua_widget_factory.cpp

Clear list before reloading choice values.

fix(color): widget 'Choice' option popup may show duplicate entries

---

radio/src/cli.cpp
radio/src/targets/common/arm/stm32/flysky_gimbal_driver.cpp
radio/src/targets/common/arm/stm32/flysky_gimbal_driver.h

Currently, when enabling serialpassthrough gimbals, an automatic detection of gimbal is made like when radio starts. If for some reason, the gimbal doesn't behave like it uses to (like a failed update), the serial port will be disabled.
Will this change, calling serialpassthrough gimbals will bypass gimbal detection and assumes it is present.
This is needed in 2.11 too please

feat: force gimbal detection on serial passthrough init

---

radio/src/gui/colorlcd/libui/textedit.cpp

Ensure focus is cleared correctly.
Requires a T15 radio or simulator to reproduce (needs custom switches):
- Open 'Customisable Switches' in Model Setup
- Tap on a switch name to open the keyboard
- Tap on another switch name - edit shifts to the second name field; but both show the focus outline.

fix(color): customisable switch name focus outline not cleared when editing using touch

---

radio/src/gui/128x64/model_setup.cpp

On radios with custom function switches (GX12, T20V2, etc) the name set by the user may display incorrectly.
To reproduce:
- Set a custom name for both SW1 and SW2
- On the model setup page the name shown for SW1 will be incorrect.

fix(bw): name display for custom switches may be incorrect.

---

.github/workflows/macosx_cpn.yml
.github/workflows/win_cpn-64.yml
tools/aqt-settings.ini

- uses alternate action to allow for automatic caching to work again, as well as newer aqtinstall verison
- enable automatic caching for macOS builds
- macOS build needed python version bump (3.12, same as in use for win64) due to newer aqtinstall
- force use of backup mirrors for QT libraries via config file
Nothing needed for Linux build as QT libraries are included in the build environment.
QT server is still flutuating at the moment

chore(ci): force use of mirrors for Qt for now

---

radio/src/gui/colorlcd/startup_shutdown.cpp

removed an extra closing parenthesis in the TXT_Y macro definition introduced in #6012

fix(color): build-breaking typo in startup_shutdown.cpp

---

radio/src/targets/common/arm/stm32/flysky_gimbal_driver.cpp

Prevent EM when trying do deinit gimbal serial driver through serial passthrough (VCP) when boot gimbal detection did fail and already did deinit the serial port. 
This complement #6089, and has been tested by RM.
I know it's late in the process, by is needed in 2.11

fix: don't deinit non initialised Flysky gimbal interface

---

radio/src/lua/lua_lvgl_widget.cpp

Don't pass null to file picker for selected filename.

fix(color): LVGL file picker may crash if 'get' function is not set in Lua

---

radio/src/gui/128x64/model_setup.cpp
radio/src/gui/common/stdlcd/menus.cpp
radio/src/gui/common/stdlcd/radio_hardware.cpp

Issues:
- Editing model custom function switch settings did not set dirty flag for model
- Editing switch type did not set dirty flag for radio settings.
- Logic to determine whether model or radio settings page was loaded was wrong, so changing radio settings flags the model file as dirty instead.
Easiest to see in the simulator trace log.

fix(bw): changing some model and radio settings does not update corresponding yaml file.

---

radio/src/boards/generic_stm32/module_ports.cpp
radio/src/targets/common/arm/stm32/stm32_serial_driver.cpp
radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp

- force idle level via internal pull-up/down on H7.
- fix a race condition between DMA TC IRQ and actual UART TC.
- enable RX DMA on S.PORT where possible.
- improved DMA buffer detection in UART send.

fix(radio): half-duplex UART

---

tools/generate-yaml.sh

PL18 needs to be generated before NV14 - I assume this is a caching issue in CMake.

fix(build): PL18 yaml definition does not get updated by generate_yaml script.

---

companion/src/firmwares/customisation_data.h

Fixes #6128 
Increase the number of widget options to match firmware.
Missed in #5365

fix(cpn): widget options may not be saved when models loaded from radio

---

radio/src/translations/de.h

Also some minor file formatting. Fixes #6074
Is now deliberately shortened to `Reichw` for bw212, unchanged for bw128 and colorlcd.

fix(bw212): german text for "Range" too long

---

radio/src/simu.cpp
radio/src/targets/simu/led_driver.cpp
radio/src/targets/simu/switch_driver.cpp

with this PR function switches are displayed as buttons in the simu UI. Button colors are updated to reflect the model settings.
For radios without RGB-LEDs the buttons are either black or white

feat(simu): add support for (RGB!!) customisable  switches

---

radio/src/targets/simu/led_driver.cpp

- use same conditional `__weak` directives used elsewhere in code

fix(libsim): use different `__weak` syntax depending on target

---

radio/src/gui/colorlcd/controls/channel_bar.cpp
radio/src/gui/colorlcd/controls/channel_bar.h

Fix position of bars and inverted icon.

fix(color): channel monitor 'inverted' icon overlaps channel bars.

---

radio/util/find_clang.py

- Removes hard-coding of llvm paths, instead doing a search of any correctly prefixed folder with `lib` subdir). Then proceeds to add in the "known" list in reverse natural number sort order to ensure latest version first on the list if multiple versions present. 
Tested locally against current `main` build container - `/usr/lib/llvm-10/lib` was found when running `tools/generate-yaml.sh`

chore: more dynamic llvm path search on linux

---

radio/src/targets/taranis/board.h

This is a quick and dirty fix for TLite main voltage display. Unfortunately, the schematics we have do not allo proper encoding of the divider, so this is an empiric reverse engineering.
If/when we get proper schematics, will issue a follow up

fix: tlite vbat voltage

---

radio/src/boards/generic_stm32/CMakeLists.txt
radio/src/boards/generic_stm32/battery_voltage.cpp
radio/src/hal/adc_driver.cpp
radio/src/hal/adc_driver.h
radio/src/targets/common/arm/stm32/stm32_adc.cpp
radio/src/targets/horus/csd203_sensor.cpp
radio/src/targets/horus/hal.h
radio/src/targets/nv14/hal.h
radio/src/targets/pl18/hal.h
radio/src/targets/simu/adc_driver.cpp
radio/src/targets/simu/opentxsimulator.cpp
radio/src/targets/simu/opentxsimulator.h
radio/src/targets/taranis/board.h

- use the same voltage conversion formula for all targets
- fix RTC battery bridge on H7 targets

refactor(radio): unified battery and RTC voltage

---

.github/workflows/actions.yml
radio/util/build-firmware.py
radio/util/fwoptions.py
radio/util/hw_defs/switch_config.py

- add missed v12/v14 builds - missed in #5494
- fix v14 default switch options
- add v12/v14 to build_firmware python script

fix(ci): add missing fw build, correct v14 switch defs

---

radio/src/gui/colorlcd/controls/channel_bar.cpp
radio/src/gui/colorlcd/controls/channel_bar.h

Refresh channel bar when extended limits changes.

fix(color): channel bars on outputs list not correct size if extended limits setting changed

---

radio/src/targets/horus/board.cpp

Fixes # https://github.com/EdgeTX/edgetx/issues/4859
On Horus Radios with PWM_STICKS the optional support for the Flysky Hall gimbals is disfunctional since 2.10. The problem is that both use the same GPIOs. With sticksPwmDetect() the GPIOs get blocked thus flysky_gimbal_init() does not work any more. So I turned the order to first look for the Flysky Gimbals and go to PWM_Sticks if not found.

fix(horus): detection for Flysky Hall Gimbals not working

---

radio/src/gui/colorlcd/widgets/value.cpp

Also some minor re-order of field type tests  so they are in mixsrc order.
Prompted by a [question on Discord](https://discord.com/channels/839849772864503828/839849772864503832/1363421915632369664).

feat(color): value widget now shows voltage suffix for handset voltage

---

radio/src/gui/colorlcd/radio/radio_diagcustswitches.cpp
radio/src/hal/rgbleds.cpp
radio/src/hal/rgbleds.h
radio/src/switches.h
radio/src/targets/simu/led_driver.cpp
radio/src/targets/st16/led_driver.cpp
radio/src/targets/taranis/led_driver.cpp

Also fixes logic for checking switch color.

feat(color): show switch colors for customisable switches on diagnostic page

---

radio/src/boards/generic_stm32/battery_voltage.cpp

Fixed the conversion ratio for radios defining `BATT_SCALE` and `BATTERY_DIVIDER`. In my case it was the Commando8. The voltage displayed is now the same as before #6065.

fix(taranis): battery voltage computation

---

.github/workflows/nightly.yml

I hope this is the only place where it was missing. I could not find any other.

fix(actions): add UF2 to nightly releases

---

radio/src/targets/common/arm/stm32/CMakeLists.txt
radio/src/targets/common/arm/stm32/audio_dac_driver.cpp
radio/src/targets/common/arm/stm32/rotary_encoder_driver.cpp
radio/src/targets/common/arm/stm32/sdcard_spi.cpp
radio/src/targets/common/arm/stm32/stm32_hal_ll.h
radio/src/targets/common/arm/stm32/stm32_spi.cpp
radio/src/targets/common/arm/stm32/stm32_spi.h
radio/src/targets/common/arm/stm32/stm32_spi_h7.cpp

These drivers are now used by other targets, pulled out for other development branch to use.
Drivers included:
- Audio DAC driver
- SPI driver

fix(h7): common drivers for H7 support

---

radio/src/gui/colorlcd/model/mixer_edit_adv.cpp

- second header line not being generated/drawn properly
Before:
After:

fix(color): clipped second line for mixer adv edit header

---

radio/src/lua/api_colorlcd_lvgl.cpp
radio/src/lua/lua_lvgl_widget.cpp
radio/src/lua/lua_lvgl_widget.h

Allow Lua scripts to open a popup menu with multiple options for the user to select from.
Sample script:
```Lua
lvgl.button({text="Menu", x=10, y=10,
press=function() 
lvgl.menu({title="Menu",
values={"Option 1","Option 2","Option 3","Option 4","Option 5","Option 6","Option 7","Option 8","Option 9","Option 10",},
set=function(n)
-- 'Do something with the selected value'
end
})
end
})
```

feat(color): add 'menu' popup control to Lua API

---

radio/src/gui/common/stdlcd/radio_trainer.cpp

Fix a ghost line on BW trainer when Slave Jack trainer in not in use

fix(bw): hidden line (multiplier) on trainer screen

---

radio/src/gui/128x64/view_main.cpp

For example, a MT12 transmitter and S1 and S2 built-in, and if you get a external module for two additional inputs, S3 and S4 are available to be configured through the SYS->HARDWARE menu. It is possible for anybody to make custom external modules that had any combination of switches and potentiometer.
If you configure S3 as a slider and S4 as a switch, then three bars are drawn and everything is fine
If you configure S3 as a switch and S4 as a slider, which is my actual hardware configuration, then three bars are drawn, but when I adjust the slider, S1's bar is being moved. This is the bug I am trying to fix.
If you configure S3 as a slider and S4 as a slider, then four bars are drawn and everything is fine
Upon investigation, I found the bit of code `drawPotsBars()` to be the issue. …

fix(bw): drawPotsBars wrong draw pos if skipping entry

---

radio/src/boards/generic_stm32/module_ports.cpp
radio/src/pulses/pulses.h
radio/src/storage/storage.h
radio/src/targets/common/arm/stm32/usb_driver.cpp
radio/src/targets/horus/board.cpp
radio/src/targets/horus/board.h
radio/src/targets/taranis/board.cpp

- move "FrSky special" into board specific module port definition.
- init timers & delays first once and for all.

chore(radio): small board cleanup

---

radio/src/boards/generic_stm32/linker/stm32h750_sdram/extra_sections.ld
radio/src/boards/generic_stm32/linker/stm32h7rs_sdram/extra_sections.ld
radio/src/disk_cache.cpp
radio/src/disk_cache.h
radio/src/targets/common/arm/stm32/h7/memory_sections.h

- enable relocating the disk cache independently of the heap.
- STM32H750: relocate the cache to AXI SRAM.

feat(radio): static disk cache

---

radio/src/os/task_pthread.cpp
radio/src/os/timer_pthread.cpp
radio/src/os/timer_pthread.h
radio/src/os/timer_pthread_impl.h

As it seems, the `timer_queue` class wasn't made to allow for restart. This PR fixes it.
Fixes #6218

fix(simu): restarting timer_queue

---

radio/src/gui/colorlcd/module/module_setup.cpp

fix(color): selecting S.PORT as telemetry for SBUS

---

radio/src/gui/colorlcd/bitmaps.cpp
radio/src/gui/colorlcd/bitmaps.h
radio/src/targets/horus/bootloader/boot_menu.cpp
radio/src/targets/nv14/bootloader/boot_menu.cpp
radio/src/targets/pl18/bootloader/boot_menu.cpp
radio/src/targets/st16/bootloader/boot_menu.cpp

Prevents using `malloc()` before `main()`.
*Please note: this PR is necessary for #6172 to be applicable to F4 targets.*

fix(color): load bootloader bitmaps in bootloaderInitScreen()

---

companion/src/CMakeLists.txt
companion/src/translations.cpp
companion/src/translations/companion_cs.ts
companion/src/translations/companion_da.ts
companion/src/translations/companion_de.ts
companion/src/translations/companion_en.ts
companion/src/translations/companion_es.ts
companion/src/translations/companion_fi.ts
companion/src/translations/companion_fr.ts
companion/src/translations/companion_he.ts
companion/src/translations/companion_it.ts
companion/src/translations/companion_ja.ts
companion/src/translations/companion_ko.ts
companion/src/translations/companion_nl.ts
companion/src/translations/companion_pl.ts
companion/src/translations/companion_pt.ts
companion/src/translations/companion_ru.ts
companion/src/translations/companion_sv.ts
companion/src/translations/companion_zh_CN.ts
companion/src/translations/companion_zh_TW.ts

- `companion_ko.ts`: Full UI translation completed
- `translations.cpp`: Registered Korean language (`ko_KR`)
- `CMakeLists.txt`: Added Korean to the list of translation files
- Successfully built and tested in a local environment
- The translation is based on the latest `en.ts` file
- If there are any missing or improvable parts, your feedback would be greatly appreciated. 🙇‍♂️
Thank you!

feat(cpn): Korean (ko_KR) translation support

---

radio/src/gui/colorlcd/radio/radio_spectrum_analyser.cpp

Array too small for 320x240 LCD radios.

fix(color): incorrect array size calculation for grid lines in spectrum analyser.

---

radio/src/gui/colorlcd/mainview/layout_factory_impl.cpp
radio/src/gui/colorlcd/mainview/view_main_decoration.cpp

The initial zone size passed to a widgets 'create' function may be wrong on startup.

fix(color): widget zone size may be incorrect on startup.

---

radio/src/mixer.cpp

After the change to allow any source for weight/offset, the GV value calculation logic did not quite mimic the 2.10 behaviour.
Fixes: #6239

fix(radio): value calculation when GV used as source in weight/offset changed from 2.10

---

radio/src/targets/taranis/hal.h

T20v2 does have a 3,0V Ref, but was set at 3,3V. Because of that Vbat measurement where too high. With this fix, I'm at 0,03v difference between (uncalibrated) display and voltmeter.
This change will likely affect stick calibration, so I leave you to decide if it should be brought into 2.11 codeline or not.

fix(t20v2): incorrect default transmitter battery calibration

---

radio/src/targets/common/arm/stm32/stm32_spi.cpp

- DMA buffer detection: only reject buffers on the stack (CCM) and accept everything else.
- DMA transfers: in case the scratch buffer is used, split into smaller DMA transfer that fit into the scratch buffer.

fix(f4): SPI DMA transfers

---

radio/src/lua/lua_lvgl_widget.cpp

Reported by @offer-shmuely on Discord.
Sample test script:
```Lua
local function init()
lvgl.clear();
lvgl.line({
pts={{10,10},{320,240}},
color=RED,
thickness=5,
})
lvgl.line({
pts=function() return {{50,10},{320,240}} end,
color=BLUE,
thickness=5,
})
end
local function run(event, touchState)
return 0
end
return {init = init, run = run, useLvgl=true}
```

fix(color): Lua LVGL line color not set correctly when 'pts' property is a function

---

radio/src/gui/colorlcd/controls/channel_bar.cpp

Tapping in the area of the channel bar display may prevent the selected channel from getting focus, even though the menu pops up.
The channel bar is display only so make it non-clickable.

fix(color): output channel may not get focus when user taps on screen.

---

radio/src/gui/colorlcd/libui/list_line_button.cpp
radio/src/gui/colorlcd/model/model_mixes.cpp

To improve the load time for the mixes list on complex models, the PR creates the page initially with blank buttons for the mix lines and then populates them only when they are visible.
Dramatically reduces the page load time for very complex models (from 1.5s down to .6s).
It decreases the load time for simple models; but not as significantly.
The drawback is the page loads with blank button which then populate. This can take 100-300ms depending on the complexity of the mixes so it is noticeable.
The question is whether the load time improvement justifies the delay before the buttons populate.

feat(color): delay population of mix line button content so mixes tab loads faster

---

radio/src/gui/colorlcd/controls/channel_bar.cpp

fix(color): channel monitor bars are too wide and clip right edge.

---

radio/src/targets/horus/hal.h
radio/src/targets/taranis/hal.h

After another report of bat issue on RCG (this time on T14), I asked Jumper to provide a complete list of VREF per radio, which they kindly supplied.
If your Chinese is as non existent as mine, the strange thing means Bumblebee !
This is aligning our code to the list they supplied
Needed for 2.11 too

fix: review Jumper VREF values

---

radio/src/gui/colorlcd/libui/static.cpp
radio/src/gui/colorlcd/libui/static.h
radio/src/gui/colorlcd/mainview/topbar_impl.cpp
radio/src/gui/colorlcd/mainview/view_main.cpp
radio/src/gui/colorlcd/widgets/modelbmp.cpp

Use StaticBitmap instead of StaticImage for model info widget.
Does not look as nice (no anti aliasing); but is faster and does not slow down the left/right scrolling of the main view as much.

feat(color): reduce lag in scrolling main view when using model info widget

---

radio/src/gui/128x64/model_telemetry.cpp
radio/src/gui/212x64/model_telemetry.cpp
radio/src/gui/colorlcd/model/model_telemetry.cpp
radio/src/gui/colorlcd/model/model_telemetry.h
radio/src/telemetry/telemetry_sensors.cpp
radio/src/telemetry/telemetry_sensors.h

Radio does not stop trying to add new sensors and gets very confused.
Also changed the popup warnings for color radios to be consistent (changed full screen warning to message popup).
This fixes #6286

fix(radio): potential crash if too many telemetry sensors discovered

---

radio/src/FreeRTOSConfig.h
radio/src/boards/generic_stm32/CMakeLists.txt
radio/src/targets/common/arm/stm32/h7/CMakeLists.txt

When compiling with `DEBUG` set, the compilation was not propagated everywhere it was needed, thus causing issues with FreeRTOS structure sizes.
This is basically due to this:
```c
#if !defined(DEBUG)
#define configMAX_TASK_NAME_LEN         4
#define configUSE_TRACE_FACILITY        0
#define configCHECK_FOR_STACK_OVERFLOW  0
#else
#define configMAX_TASK_NAME_LEN         10
#define configUSE_TRACE_FACILITY        1
#define configCHECK_FOR_STACK_OVERFLOW  0
#endif
```
This would cause various FreeRTOS structures to have different sizes in different source code files, thus wrecking havoc in memory.

fix(radio): propagate DEBUG everywhere needed

---

radio/src/bootloader/boot_dfu.cpp

When applying  #6189 to 2.11 branch, the commit is mixed with the changes in #5840 which is not present in 2.11 branch.

fix(st16): incomplete #6189 merge

---

radio/src/gui/128x64/model_setup.cpp
radio/src/gui/212x64/model_setup.cpp
radio/src/gui/colorlcd/libui/button_matrix.cpp
radio/src/gui/colorlcd/model/preflight_checks.cpp
radio/src/switches.cpp
radio/src/switches.h

Add the same functionality that is available on B&W radios - a long press of the enter key when editing the pre-flight switch settings will use the current switch positions.
Marked for 3.0; but could be included in 2.11.2 if desired.
Fixes #6265 
Also improves the UI for the button matrix to differentiate the focus VS editing states.
This is most noticeable when using the rotary encoder rather than touch screen.
Not focused or edited (same as current UI):
Focussed but not editing:
Editing:

feat(color): handle long press enter for pre-flight switch checks

---

radio/src/gui/128x64/view_main.cpp

PR #6077 was not quite right and messed up the switch display on the X7S.
Hopefully this will be better.
Tested on X7S, GX12, TLite and T20V2. Also tested that #6073 is still fixed.

fix(bw): main view switch display may be incorrect

---

radio/src/gui/colorlcd/libui/choice.h

Ensure button updates when text handler set.
Fixes bug introduced in #6294 
Reported by gismo2004 [on discord](https://discord.com/channels/839849772864503828/839895574244229152/1377522492318679071).
To reproduce, open input editor, or mix editor. Source value may show a number instead of the source name.

fix(color): button text for some choice values may be incorrect

---

radio/src/targets/st16/hal.h

- Fix DMA conflict between `ADC1` and external module RX.

fix(st16): external module DMA conflict

---

radio/src/targets/common/arm/stm32/f2/memory_sections.h

fix(f2): DMA buffer alignment

---

radio/src/bootloader/boot_dfu.cpp
radio/src/bootloader/boot_menu.cpp
radio/src/bootloader/boot_uf2.cpp
radio/src/edgetx.cpp
radio/src/targets/common/arm/stm32/timers_driver.cpp
radio/src/tasks.cpp

This helps reducing the pressure on the timer queue.
2.11 version of #5966 which was merged into 3.0 as part of #5840

refactor(radio): move per10ms() to a software timer

---

radio/src/datastructs_private.h
radio/src/gui/common/stdlcd/model_curves.cpp
radio/src/lua/api_model.cpp

Incorrect data type for curve reference value.
Fixes #6356 
Fixes issue with the Lua API call (see issue 6356).
Also fixes an issue for a long press of the ENTER key on a custom curve name in inputs or mixes.
If the selected curve is negative (e..g -CV3), it will open the wrong curve on the radio and crash on the simulator.

fix(lua): curve value incorrect in model.getInput and model.insertInput API calls

---

radio/src/edgetx.cpp
radio/src/gui/colorlcd/standalone_lua.cpp
radio/src/lua/interface.cpp
radio/src/lua/lua_api.h
radio/src/lua/widgets.cpp
radio/src/mixer.cpp
radio/src/tests/lua.cpp
radio/src/thirdparty/Lua/src/lstate.c

Fixes #6336
Fix edge cases when shutting down Lua - order of closing Lua states seems to matter.

fix(color): fix EM crashes when shutting down Lua states

---

radio/src/targets/common/arm/stm32/diskio_sdio.cpp
radio/src/targets/st16/lcd_driver.cpp

This also fixes some issues seen when disabling `DMA2D` in LVGL.

fix(h7): improved data cache maintenance

---

radio/src/gui/colorlcd/widgets/outputs.cpp

Ensure value label is correctly updated when channel value changes.

fix(color): outputs widget channel value may not update if units is set to μs

---

radio/src/cli.cpp

- changes cli `repeat` function to takes ms instead of seconds (nb: this function is only available in debug builds)
- add a `testfatfs` cli command (only available in debug builds) that will perform read and write tests using fatFS calls (while existing `testsd` bypasses those)
It is essentially a tool for developers and manufacturers to have more option to test sd subsystem. if you want to run the test every 50ms, send in cli `repeat 50 testfatfs`

feat(debug): add a cli option for testing SD though fatFS

---

radio/src/targets/taranis/gx12/bsp_io.cpp

This resets the PCA95xx expanders if they are found non responding to I2C query,
Fixes #6159
For 2.11 also please.

fix(gx12): use PCA95xx reset pin in case of read issues

---

radio/src/gui/colorlcd/CMakeLists.txt
radio/src/gui/colorlcd/boot_lcd.cpp
radio/src/gui/colorlcd/lcd.cpp
radio/src/gui/colorlcd/libui/bitmapbuffer.h
radio/src/gui/colorlcd/lv_conf.h
radio/src/targets/common/arm/stm32/dma2d.cpp
radio/src/targets/common/arm/stm32/dma2d.h
radio/src/targets/horus/board.cpp
radio/src/targets/nv14/board.cpp
radio/src/targets/pl18/battery_driver.cpp
radio/src/targets/pl18/battery_driver.h
radio/src/targets/pl18/board.cpp
radio/src/targets/st16/battery_driver.cpp
radio/src/targets/st16/battery_driver.h
radio/src/targets/st16/board.cpp
radio/src/targets/stm32h7s78-dk/board.cpp

Fixes #6346
Changes:
- Disable LVGL DMA2D for all radios.
- Use partial screen refresh mode in LVGL for all radios.
- Remove direct drawing mode from battery charging display (ST16/EL18/PL18/NV14).
- Remove LVGL direct drawing code from the firmware (restricted to boot loader only).
- Create separate lcd handling code for the bootloader (boot_lcd.cpp) for readability.

fix(color): screen refresh may be slower on some radios after update to LVGL 8.4

---

radio/src/boards/generic_stm32/analog_inputs.cpp
radio/src/hal/adc_driver.cpp
radio/src/targets/common/arm/stm32/flysky_gimbal_driver.cpp
radio/src/targets/common/arm/stm32/flysky_gimbal_driver.h
radio/src/targets/horus/hal.h
radio/src/targets/st16/hal.h
radio/src/tasks/mixer_task.cpp

Flysky works out a new version of firmware that can support sync sampling:
1. Upon init the gimbal will operate in backward compatible mode (i.e. old EdgeTX will works after the gimbal firmware is upgraded)
2. New firmware will check the version of the firmware to see if sync mode is supported
3. New driver will send command to the gimbal for sync sampling
The gimbal driver changes:
1. It will automatic obtain the version of the gimbal to check if sync sampling is available
2. The default operation mode is backward compatible mode, will switch to sync modes only when new version of gimbal firmware is detected
3. Based on sampling frequency, the driver will automatically switch to sync sampling mode (<= 400Hz - switching threshold) or sync resampling mode (> 400Hz)
Testing:
1. Not breaking …

feat(flysky): Flysky Gimbal 2.0 Sync Sampling Support

---

radio/src/lua/interface.cpp

After exiting a stand alone script on B&W radios, Lua memory is not completely released.
Can also happen on all radios when switching models.
Bug in PR #6337.
Fixes #6370

fix(lua): memory leak when re-loading Lua scripts

---

companion/src/firmwares/customisation_data.h

Fixes #6328
Missed in #5605
- resync LEN_ZONE_OPTION_STRING value so widget option strings aren't truncated
- verified all other constants are in sync with firmware values

fix(cpn): length of widget option strings

---

radio/src/targets/simu/simpgmspace.cpp

Flex switches are not initialised in the simulator so they may show incorrectly in radio hardware settings.
To reproduce:
- create a blank document in companion for the TX16S
- run the simulator
- navigate to the Radio -> Hardware -> Switches view and scroll down to the flex switches.
- flex switches will all be set to S1

fix(sim): flex switches may be set incorrectly on startup

---

radio/src/gui/gui_common.cpp

Fixes #6387 
Fix switch offsets.

fix(color): switch picker for Lua scripts may show incorrect switch names

---

radio/src/lua/api_model.cpp

Fixes #6399 
Replace the code that calculate the number of points in the curve to work around what looks like a compiler optimisation bug.
In the previous code (below), the 'numPoints < MAX_POINTS_PER_CURVE' test gets optimised away so the loop falls off the end of the array and gets the number of points wrong.
```C
uint8_t numPoints=0;
do {
numPoints++;
} while (yPoints[numPoints]!=-127 && numPoints < MAX_POINTS_PER_CURVE);
```

fix(lua): model.setCurve function may fail when creating a curve with 17 points.

---

radio/src/fonts/lvgl/make_fonts.sh
radio/src/translations/pl.h
tools/cfn_sorter.sh
tools/check_translations.py
tools/update-companion-translations.sh

- Make following scripts less brittle / more robust by not having relative path dependencies:
- `make_fonts.sh`
- `cfn_sorter.sh` 
- add lazy helper script for companion tranlsation updates
- add translation checker `check_translations.py` which checks (validates?) translation strings are present for all languages - for individual headers and bootloader header
- add missing TR_GROUP translation for Polish (yay, the script works!)

chore: make helper tools more robust, translation helpers

---

radio/src/lua/interface.cpp

Prevent Lua script special functions from running when trigger is not set.

fix(radio): Lua script special functions running when no trigger set

---

companion/src/simulator.cpp

Fixes #6362
When starting the simulator use the radio profile sd path instead of the last run saved value.
Note: the profile sd path can be overridden via cli or startup ui.

fix(simulator): radio profile sd path

---

radio/src/translations/cn.h
radio/src/translations/cz.h
radio/src/translations/da.h
radio/src/translations/de.h
radio/src/translations/en.h
radio/src/translations/es.h
radio/src/translations/fi.h
radio/src/translations/fr.h
radio/src/translations/he.h
radio/src/translations/it.h
radio/src/translations/jp.h
radio/src/translations/ko.h
radio/src/translations/nl.h
radio/src/translations/pl.h
radio/src/translations/pt.h
radio/src/translations/tw.h
radio/src/translations/ua.h

Cleanup TR_ENTER translation so that radio that do not define PCBFRSKY are getting the right translation

chore: cleanup TR_ENTER translation

---

radio/src/gui/colorlcd/libui/textedit.cpp

Ensure display show '---' when text field value is erased.
To reproduce:
- edit text field (e.g. axis name), set a non-blank value, leave edit mode (close keyboard)
- edit field again, erase all characters - field shows as '---'
- leave edit mode - field shows as blank instead of '---'

fix(color): text input field may not display correctly when value is erased.

---

radio/src/telemetry/multi.cpp

Multiprotocol modules encapsulate protocol specific telemetry packets into their own framing per default since at least 2020 (feature appeared 2016). So let's remove support for the older buddy method without encapsulation since it seems to cause troubles.
Fixes #6400

chore(radio): obsolete raw telemetry packets from MPM

---

radio/src/gui/colorlcd/lv_conf.h

As there is plenty of RAM available on color radios, this PR increases the memory allocation to LVGL.
Mainly for Lua scripts that want to use images.

feat(color): increase RAM allocation to LVGL for Lua scripts with many images

---

cmake/NativeTargets.cmake
companion/src/CMakeLists.txt
companion/src/tests/CMakeLists.txt
radio/src/audio.cpp
radio/src/targets/simu/CMakeLists.txt
radio/src/targets/simu/audio_driver.cpp
radio/src/targets/simu/no_audio.cpp
radio/src/targets/simu/simpgmspace.cpp
radio/src/targets/simu/simpgmspace.h
radio/src/targets/simu/simuaudio.cpp
radio/src/tests/CMakeLists.txt
radio/src/tests/gtests.cpp
radio/src/tests/gtests.h
radio/src/tests/lcd.cpp
radio/src/tests/lcd_480x272.cpp
radio/src/tests/lua.cpp

- replaced Qt in unit test image comparison with `stb_image.h` 
- removed SDL2 dependency from radio unit tests

chore: remove Qt and SDL2 from radio unit tests

---

companion/src/firmwares/boards.cpp
companion/src/firmwares/boards.h
companion/src/firmwares/moduledata.cpp
companion/src/firmwares/opentx/opentxinterface.cpp
companion/src/modeledit/setup_module.cpp
companion/src/radiointerface.cpp
companion/src/storage/rlefile.cpp

- rip out 9XRPRO / SKY9X / AR9X remnants
- `FSIZE_` corrections (was in #6409, move here as not strictly necessary there)
WiP, some more optimisation / refactoring of some now otherwise redundant functions might still happen... ie. (IS_ARM() needs to go, `getReadFirmwareArgs()` / `getWriteFirmwareArgs()` can probably be flattened... etc. 
@elecpower Any reason not to rip these out now (as in for 3.0, not necessarily right this instant :hand_over_mouth:)?

chore(cpn): remove SKY9X/9XRPRO

---

radio/src/gui/colorlcd/libui/bitmapbuffer_fileio.cpp
radio/src/gui/colorlcd/libui/static.cpp

Change trace messages when loading images to error messages.

fix(color): debug messages when loading images in Lua script not shown as errors

---

companion/src/apppreferencesdialog.cpp

Workaround to stop cropping of checkboxes due to centre alignment

fix(cpn): update components checkbox spacing

---

radio/src/lua/api_general.cpp

While working on some stuff with an Etx partner, I did notice that lua did not have a way to query stick mode, so adding that

feat(lua): add getStickMode function

---

tools/msys2_fetch_and_build_all.sh
tools/setup_buildenv_ubuntu22.04.sh
tools/setup_buildenv_ubuntu24.04.sh

- update Qt version to 6.9.0
- use same method to install Qt
- formatting to make it easier to identify packages installed
Comment: 
- packages installed has not been cleaned up so scripts can be more easily regressed for 2.11. 
- Really need set for 2.11 and 3.0 and rationalise across build chains to reduce maintenance i.e. too many scripts to be updated for a single change e.g. add extra package.

fix(scripts): qt version and formatting

---

companion/src/simulation/simulateduiwidgetGeneric.cpp
companion/src/simulation/widgets/lcdwidget.h

Fix color for simulator on B&W radios. Broken in PR #6233.

fix(sim): wrong background color for B&W simulator

---

radio/src/lib_file.cpp
radio/src/targets/simu/simpgmspace.h
radio/src/targets/simu/simufatfs.cpp
radio/src/tests/gtests.cpp
radio/src/tests/lcd.cpp
radio/src/tests/lcd_480x272.cpp

- removed usage of POSIX headers in `simufatfs.cpp`
- use only plain C++17 to improve portability
This PR contains some of the changes already submitted in #6452 and will be rebased once that PR is merged.

refactor: convert simufatfs to C++17

---

radio/src/gui/colorlcd/radio/radio_hardware.cpp

Fix refresh of the value in the 'Battery calibration' field on Radio Hardware page.
The value would update if you tap on the field to edit it; but would not refresh if the hardware value changed.

fix(color): battery voltage value not updating on Radio Hardware page

---

radio/src/gui/128x64/model_special_functions.cpp

Fix value range check.
Fixes #6488

fix(bw): cannot select 'inc/dec' mode for Adjust SF on some radios

---

radio/src/targets/common/arm/stm32/usbd_desc.c

This allows for the WinUSB driver to be applicable to both ST's bootloader DFU device as well as our. It seems ST's driver doesn't care about this, as it seems to solely match on `VID:PID`.

fix(h7): device version in DFU mode

---

companion/src/simulation/simulatormainwindow.cpp

Qt 6.9 has changed ui colour inheritance

fix(cpn): simulator colours

---

.github/workflows/win_cpn-64.yml
cmake/NativeTargets.cmake
companion/src/burnconfigdialog.cpp

- follow-up TODO from #6476.
- fixes an issue with the path used for `dfu-util.exe` on Windows.

fix(cpn): add dfu-util and libusb to windows build

---

radio/src/CMakeLists.txt
radio/src/bootloader/CMakeLists.txt
radio/src/gui/colorlcd/CMakeListsLVGL.txt

The bootloader was failing to link when building Hebrew firmware due to undefined references to LVGL BIDI functions (lv_bidi_calculate_align, _lv_bidi_process_paragraph, _lv_bidi_get_logical_pos).
This occurred because:
- bootloader includes lv_draw_label.c which calls BIDI functions when TRANSLATION_IS_RTL set
- BIDI source (lv_bidi.c) not included in LVGL_SOURCES_MINIMAL
- TRANSLATION_IS_RTL conditional compilation worked for main firmware but not bootloader because it uses the larger LVGL_SOURCES list
FLAVOR=tx16s EXTRA_OPTIONS="-DTRANSLATIONS=HE" tools/build-gh.sh
```
[ 28%] Built target board_lib
lto-wrapper: warning: using serial compilation of 2 LTRANS jobs
lto-wrapper: note: see the '-flto' option documentation for more information …
```

fix(bootloader): resolve undefined BIDI references for Hebrew builds

---

radio/src/drivers/uf2_ghostfat.cpp

After flashing UF2 firmware, the bootloader would still use the old firmware size.
Beware that your OS might cache the FAT entry for `CURRENT.UF2`, so that you might have to unmount/mount if you want to see the new size. Hopefully it will however try to refresh the FAT entries after copying a file onto the UF2 drive.

fix: firmware size in UF2 bootloader after flashing

---

radio/src/targets/common/arm/stm32/h7/CMakeLists.txt
radio/src/targets/st16/CMakeLists.txt
radio/src/targets/stm32h7s78-dk/CMakeLists.txt
radio/src/targets/tx15/CMakeLists.txt

This interacts otherwise badly with `BOOTSTRAP`, such that some inline functions used inside `SystemClock_Config` are called with an address located in RAM (agressive LTO behaviour) instead of being inlined in place.
Fixes boot crash introduced in #6541.

fix(h7): no LTO for system_clock.c

---

radio/src/targets/common/arm/stm32/timers_driver.cpp

This prevents an old version of `_ms_ticks` being fetched while the free running part has already been reset.
See #6544 for more details.

fix(radio): microsecond timer

---

radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp

It seems that the boundaries chosen for PWM gimbal signal were a bit too tight for some radios. This should be better now.
**Please note:** this PR is based on upcoming v2.11.3 to allow users to test with a safe firmware.
Fixes #6404

fix(radio): wider PWM gimbal boundaries

---

tools/build-multilang.sh

Add a tool created after some prompting of Github Copilot/Claude AI that allows for easy building of various translation firmwares by simply specifing the variant(s). Automatically excludes languages that are not B&W compatiable, can be filtered to only do F2,F4,H7 MCUs, and will auto-detect new targets. Just adding this to the tools folder in case it is useful for anyone else. 
i.e. `tools/build-multi-lang.sh tx16s t15 st16 v14` would build all the language firmwares for those targets, and log any failures.

chore: add a helper tool for multi-lang building

---

companion/src/firmwares/boardjson.cpp
companion/src/firmwares/boardjson.h
companion/src/firmwares/boards.cpp
companion/src/firmwares/boards.h
companion/src/firmwares/customfunctiondata.cpp
companion/src/firmwares/edgetx/yaml_customfunctiondata.cpp
radio/src/gui/gui_common.cpp

PushCS cannot be available in global SF since we cannot know if target CS exists in the model.
@elecpower maybe it need a Companion mirror change too ?

fix: pushCS should not be a GF 

---

radio/src/boards/rm-h750/board.cpp

Fix bootloader been stuck (radio not responding to power on request) since last nighttly because delays where not started.
Also removed an unnecessary call to bsp_io_init() since it is already part of later called switchInit()
ps: this issue could not been seen when using Ozone :(

fix(tx15): unable to enter bootloader after #6585

---

radio/src/boards/generic_stm32/switches.cpp
radio/src/targets/simu/switch_driver.cpp

Radios with customisable switches (e.g. T15 and TX15), the source picker popup may show invalid switches.
To reproduce:
- create a blank model
- set all customisable switches to 2POS
- edit a mix line and open the Source picker
- the switch list may show invalid values after SW6

fix(color): source picker may show invalid switches

---

radio/src/model_init.cpp

As a side consequence of switch refactor, default for customizable switches default was changed from '6pos like' to individual non grouped custom switches. Drone pilot are therefore missing the 'GR1' channel to map their flight mode settings. 
This restores it to previous "well known" default settings (This applies only to future models created from defaults).

fix(firmware): default customizable switches to be like classic 6POS

---

radio/src/gui/colorlcd/module/module_setup.cpp

Fix potential crash when selecting external module type, if trainer mode is set to Master/SBUS.

fix(color): potential crash when configuring external module if trainer mode set to Master/SBUS

---

radio/src/gui/colorlcd/mainview/layout_factory_impl.cpp
radio/src/gui/colorlcd/mainview/layout_factory_impl.h

If a flight mode change alters which trims and/or sliders are visible, the widget zones changes may not get updated correctly.
Fixes #6630

fix(color): widgets may not update correctly when flight mode changes

---

radio/src/boards/jumper-h750/board.cpp
radio/src/boards/rm-h750/board.cpp
radio/src/targets/common/arm/stm32/f4/memory_sections.h
radio/src/targets/common/arm/stm32/h7/memory_sections.h
radio/src/targets/horus/board.cpp

Since #6541 `pwr_driver.cpp` is included in LTO (`board_bl`), which causes `_pwr_init_hook` to be evicted by the linker. This removed `pwrResetHandler` from the early init and thus broke EM fast reboot and power initialisation.
This PR marks all `__INIT_HOOK` symbols as **used**, which fixes the observed issues:
- `_pwr_init_hook` is present again in the bootloader's `__init_hook_array`
- should fix PL18 init as well (backlight hack; see `backlightLowInit`)

fix(radio): early init hooks

---

radio/src/model_init.cpp

Fix an issue introduced in #6604 where customizable switches are now defaulting like TX16S pos, but the switch check still wants SW1 UP on start (facepalm)

fix: configure default switch warning for customizable switches
