EdgeTX/edgetx

.github/workflows/actions.yml, radio/src/mixer_scheduler.cpp, radio/src/mixer_scheduler.h, radio/src/tasks.cpp, tools/build-gh.sh, tools/commit-tests.sh
introduced by opentx/opentx#8474
=> Fix mixer scheduler 33Hz only issue

.github/workflows/actions.yml, fw.json
This PR adds the metadata file and workflow mods for the Flasher Artifact downloader.
=> Add Flasher Metadata system

tools/setup_buildenv_ubuntu20.04.sh
If you deem this bash script worthy enough for main EdgeTX, feel free to merge - no point of it sitting on my fork only.
=> Build environment setup script for Ubuntu 20.04 LTS

radio/src/targets/horus/bootloader/boot_menu.cpp
=> Use the selection colour as the progress bar border

radio/src/gui/colorlcd/colors.h, radio/src/gui/colorlcd/select_fab_carousel.cpp
the title says it 
the issue in colors.h could in fact also considered a bug
=> Get rid of two warnings

radio/src/gui/colorlcd/radio_hardware.cpp
in the System->Hardware page, aligns the right hand fields throughout the page
it was probaby done on purpose that the alignment changes, but essentially ALL other pages have it aligned, and it IMHO also just looks so much better
=> System Hardware Menu, aligned it really looks much better

radio/src/gui/colorlcd/draw_functions.cpp, radio/src/main.cpp, radio/src/targets/horus/bootloader/boot_menu.cpp, radio/src/targets/horus/lcd_driver.cpp, radio/src/targets/simu/simpgmspace.cpp, radio/src/targets/simu/simulcd.cpp
This is done according to this article:
- http://www.lucadavidian.com/2017/10/02/stm32-using-the-ltdc-display-controller/
~~Potentially fixes #38 (to be tested)~~.
=> Switch the framebuffer address rather than using 2 LTDC layers

.github/workflows/nightly.yaml
first, a new release should be manually created and it's id retrieved. then, lines 3-4 of the yaml need to be changed accordingly.
=> add workflow to have a nightly release of the latest state

radio/src/main.cpp, radio/src/opentx.cpp, radio/src/telemetry/multi.cpp, radio/src/telemetry/multi.h
=> Moved MPM failsafe check to the UI task

radio/src/gui/colorlcd/radio_hardware.cpp, radio/src/gui/colorlcd/sourcechoice.cpp, radio/src/strhelpers.cpp
=> Fix source names

.github/workflows/actions.yml, .github/workflows/nightly.yml
also sync "actions.yml" with "nightly.yml" and some formatting
=> compose and use "dynamic" names for the assets to be released

radio/src/mixer_scheduler.h, radio/src/tasks.cpp
=> Raised maximum mixer scheduler period to 50ms (20Hz)

radio/src/lua/api_colorlcd.cpp
Uses EdgeTX/libopenui#2.
Simpler version of #131.
**New methods:**
- drawCircle
- drawFilledCircle
- drawTriangle
- drawFilledTriangle
- drawArc
- drawPie
- drawAnnulus
- drawLineWithClipping
- drawHudRectangle
=> Add some new LUA graphics plotting functions

radio/src/gui/colorlcd/model_mixes.cpp, radio/src/lua/api_general.cpp, radio/src/lua/api_model.cpp, radio/src/lua/lua_api.h, radio/src/telemetry/telemetry_sensors.cpp, radio/src/tests/conversions.cpp, radio/src/tests/lua.cpp
=> ZChar nightmare / take 2

radio/src/gui/colorlcd/screen_setup.cpp
=> SetupWidgetPage: fix forwarding touch events to children

radio/src/gui/colorlcd/widget.cpp, radio/src/gui/colorlcd/widget.h, radio/src/lua/lua_api.h, radio/src/lua/widgets.cpp, radio/src/opentx.cpp
=> Unregister LUA widgets when the factory is destroyed

README.md
Expand on once specifics are known.
This is here mostly as a reminder to add this if any icons of theirs are used. As of the 19th of May, 2021, they granted three months of access to their catalog, 100 assets per month, with free usage of any downloaded assets after that period has ended, in exchange for a link / attribution. 
> Every month you'll have access to 100 unique icons in all formats and sizes
> Yes, exactly: all assets that you download throughout this period of time you will be able to use as long as you need them, even after the expiry of your subscription
Was https://github.com/EdgeTX/edgetx/pull/49, but GitHub auto-stupidly closed the PR when I renamed the branch (so much for their claim of "Open pull requests and draft releases targeting the renamed branch will be …
=> Add mention of ICONS8

radio/src/opentx.cpp
=> B/W: make shutdown confirmation depending on the issue at hand

radio/src/gui/128x64/model_setup.cpp, radio/src/pulses/modules_helpers.h
=> Fixed MPM proto subtype reset on subtype change

radio/src/logs.cpp, radio/src/lua/api_general.cpp, radio/src/storage/eeprom_common.cpp, radio/src/strhelpers.cpp
=> Fixed more zchar / string copy errors

radio/src/gui/colorlcd/model_telemetry.cpp
=> [Color] make it a slow disco on telemetry screen

radio/src/datastructs.h
=> Restored proper data format for splashMode

radio/src/targets/horus/tp_gt911.cpp, radio/src/targets/horus/tp_gt911.h
=> Fix attempt for locked touch

radio/src/lua/widgets.cpp
=> Call LuaWidget background() if widget is not painted

radio/src/pulses/pulses.cpp, radio/src/pulses/pxx.h, radio/src/targets/common/arm/stm32/intmodule_serial_driver.cpp
=> Fix isrm pulses

radio/src/gui/colorlcd/model_select.cpp
=> avoid compile warning

radio/src/gui/colorlcd/model_telemetry.cpp
something should blink then it updates
=> telem item: let it blink

radio/src/functions.cpp, radio/src/gui/gui_common.h
=> [color] enable insta trim on all views

radio/src/gui/colorlcd/radio_hardware.cpp
=> isAux(2)ModeAvailable called incorrectly

radio/src/gui/colorlcd/model_select.cpp, radio/src/storage/modelslist.cpp, radio/src/storage/modelslist.h
=> [color] set focus on current model or close to the current operation

radio/src/gui/128x64/model_setup.cpp, radio/src/gui/212x64/model_setup.cpp
=> Fix timer countdown time setting

radio/src/dump.cpp, radio/src/dump.h
Improvements only for this extension
=> [radio/src/dump.cpp]Improvement

radio/src/gui/colorlcd/model_telemetry.cpp
Reported here: https://www.rc-network.de/threads/edgetx.11851434/post-12055992
=> [color] Fix vario settings range

radio/src/gui/colorlcd/CMakeLists.txt, radio/src/gui/colorlcd/getset_helpers.h, radio/src/gui/colorlcd/menu_model.cpp, radio/src/gui/colorlcd/model_mixer_scripts.cpp, radio/src/gui/colorlcd/model_mixer_scripts.h, radio/src/gui/colorlcd/model_setup.cpp
=> [color] mixer scripts screen

radio/src/gui/colorlcd/layouts/trims.cpp, radio/src/opentx.cpp
- "[...] trim reached" taking configured range into consideration (normal vs extended).
- color lcd: clip values displayed to stay within visual range.
=> Trim fixes

radio/src/gui/colorlcd/draw_functions.cpp, radio/src/gui/colorlcd/model_logical_switches.cpp
This fixies #445 and also corrects display for TIME source in edit logical switch window.
=> Fix timer edit and time display in logical switch edit

radio/src/gui/colorlcd/model_setup.cpp
Resolves #458 and possibly other related MPM issues.
=> [color] fixed MPM options (esp. DSM related)

radio/src/gui/colorlcd/model_setup.cpp
The SBUS out is battery voltage
=> Modify external RF SBUS voltage warning

radio/src/gui/colorlcd/widget.cpp, radio/src/gui/colorlcd/widget.h, radio/src/keys.h, radio/src/lua/api_general.cpp, radio/src/lua/widgets.cpp
Provides events from keys and the touch screen to Lua widgets when they are in full screen mode.
=> Lua widget events

radio/src/lua/api_colorlcd.cpp, radio/src/lua/api_general.cpp, radio/src/lua/widgets.cpp
=> Added VCENTER to lcd flags in Lua

radio/src/lua/widgets.cpp
Since Lua widgets only runs at 10 Hz, and the GUI runs at a higher frequency, events sometimes are skipped unless we store them in a buffer. This buffer is only two slots, but can be expanded by changing EVENT_BUFFER_SIZE.
=> Added event buffer to LuaWidget

radio/src/gui/colorlcd/timeedit.cpp, radio/src/gui/colorlcd/timeedit.h
This brings up virtual keyboard (NV14) for temer edit.
Also simplifies the code.
=> touch interface support for time_edit. Take2.

radio/src/gui/colorlcd/model_setup.cpp
=> [color] Set proper CRSF module state when model-ID has changed

tools/setup_buildenv_ubuntu20.04.sh
There are comments attached to each commit explaining the changes. 
But briefly, since the script does not do any error checking, I've turned on the 'halt on first error' flag. Added progress bar to the wget downloads. and removed a non-functional path import.
=> ubuntuBuildEnv

CMakeLists.txt
Change the project name ;)
Add summary and links to the documentation for the various policy settings.
=> Summarise the main project cmake policy settings

radio/src/storage/conversions/conversions_219_220.cpp, radio/src/tests/conversions.cpp
=> Fix timer data conversion

radio/src/gui/colorlcd/model_logical_switches.cpp
=> fix timer display for logical switches.

radio/src/telemetry/ghost.cpp
=> Ghost GPS: convert to signed before dividing

radio/src/gui/colorlcd/layouts/topbar_impl.cpp, radio/src/gui/colorlcd/themes/480_default.cpp
Resubmit in a more concise way.
Thanks to Peter Feerick for teaching me this method.
=> Optimize the date format of CN/TW

radio/src/targets/common/arm/stm32/bootloader/bin_files.h
Resolves #637
Since it has a much taller screen, lets make use of it! :)
=> Show more files on the NV14

radio/src/lua/widgets.cpp
Forgot that in PR #646
@pfeerick
=> Translate color option to create() function call

radio/src/gui/colorlcd/draw_functions.cpp, radio/src/gui/colorlcd/draw_functions.h, radio/src/lua/widgets.cpp
Also a new function drawTextLines(...) in draw_functions that splits a string over multiple lines
=> Show error message in Lua widgets instead of "disabled"

radio/src/gui/colorlcd/model_curves.cpp, radio/src/gui/colorlcd/model_flightmodes.cpp, radio/src/gui/colorlcd/model_gvars.cpp, radio/src/gui/colorlcd/model_heli.cpp, radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/model_inputs.h, radio/src/gui/colorlcd/model_logical_switches.cpp, radio/src/gui/colorlcd/model_mixer_scripts.cpp, radio/src/gui/colorlcd/model_mixes.cpp, radio/src/gui/colorlcd/model_outputs.cpp, radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/colorlcd/model_telemetry.cpp, radio/src/gui/colorlcd/radio_hardware.cpp, radio/src/gui/colorlcd/radio_setup.cpp, radio/src/gui/colorlcd/radio_tools.cpp, radio/src/gui/colorlcd/radio_trainer.cpp, radio/src/gui/colorlcd/radio_version.cpp, radio/src/gui/colorlcd/sourcechoice.cpp, radio/src/gui/colorlcd/sourcechoice.h, radio/src/gui/colorlcd/special_functions.cpp, radio/src/gui/colorlcd/themes/480_default.cpp, radio/src/gui/colorlcd/view_main_decoration.cpp, radio/src/lua/api_colorlcd.cpp
I have tracked down missing colors in the GUI and fixed them. I think that I got >90% of the cases, but please let me know if you find more.
@JimB40 @raphaelcoeffic
=> Fix missing colors

radio/src/CMakeLists.txt, radio/src/lua/api_colorlcd.cpp, radio/src/lua/api_filesystem.cpp, radio/src/lua/api_filesystem.h, radio/src/lua/api_general.cpp, radio/src/lua/interface.cpp, radio/src/lua/lua_api.h
Add 2 lua file system operations, inspired by PR #556.
There is currently 2 functions available: dir and fstat.
dir list all files in a directory and return their name, it is based on https://www.lua.org/pil/29.1.html.
Under the hood, It open a directory object which is then closed by the lua garbage collector.
The files are returned 1 by 1 until there is no one left, then the loop is closed.
There is currently no real debugging when the path is incorrect but it's open for suggestion.
```
for fname in dir(".") do
print(fname)
end
```
fstat return a lua table containing the information of a file. 
It is based on [fstat](http://elm-chan.org/fsw/ff/doc/stat.html) of FatFs and return [FILINFO](http://elm-chan.org/fsw/ff/doc/sfileinfo.html) fields.
If the path specified is incorrect, the lua …
=> Added LUA file system operations

radio/src/audio.cpp, radio/src/gui/colorlcd/view_text.cpp, radio/src/gui/gui_common.cpp, radio/src/opentx.h, radio/src/strhelpers.cpp
This fixies #641 and adds support for model notes file name as model#N.txt and modelName.txt
=> support both versions of model notes file name. Fix for #641

radio/src/gui/colorlcd/draw_functions.cpp, radio/src/gui/colorlcd/draw_functions.h, radio/src/lua/api_colorlcd.cpp
Drawing text across multiple lines inside bounding box
=> Add Lua function lcd.drawTextLines(...) 

radio/src/gui/colorlcd/draw_functions.cpp, radio/src/lua/api_colorlcd.cpp
Added newline with '\n', and automatic line break with '-', ':' and '/'. Implemented BLINK, INVERS and SHADOWED flags.
=> Improved Lua draw text lines

radio/src/targets/nv14/board.h
=> allow backlight change with special function on NV14 #527

radio/src/gui/colorlcd/widgets/outputs.cpp
Also allows text and bar colors to be customised!
Fixes #663
=> Set more sensible default colors for output widget

companion/src/modeledit/setup.cpp
=> Timer edit enable switch except when mode is off

radio/src/gui/colorlcd/widget.cpp, radio/src/lua/widgets.cpp, radio/src/targets/horus/tp_gt911.cpp, radio/src/touch.h
Added tapCount to touchState in the gt911 driver.
Modified widgets so fullscreen can be entered with double tap, and the menu pops up with a "slow tap".
Added tapCount to touchState in Lua widgets.
=> Double tap etc.

radio/src/gui/colorlcd/channel_bar.h, radio/src/gui/colorlcd/draw_functions.cpp, radio/src/gui/colorlcd/draw_functions.h, radio/src/gui/colorlcd/gvar_numberedit.h, radio/src/gui/colorlcd/model_outputs.cpp, radio/src/myeeprom.h
=> Model Outputs - GV for Subtrim, Min, Max values #683

radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/colorlcd/radio_hardware.cpp, radio/src/translations/en.h.txt
Added Bluetooth trainer options to models_setup.
Also requires a pull request on libopenui to get current selection from menu.
=> Bluetooth Trainer Options in model_setup

radio/src/gui/colorlcd/radio_diaganas.cpp, radio/src/targets/horus/flyskyHallStick_driver.cpp, radio/src/targets/horus/flyskyHallStick_driver.h
Show true raw input value on radio analogs diagnose screen for FlySky hall gimbals (signed short).
=> Show true raw info on radio analogs diagnose screen (FlySky hall gimbal only)

radio/src/lua/widgets.cpp, radio/src/targets/simu/opentxsimulator.cpp
=> Add tap count to simulator

radio/src/simu.cpp, radio/src/targets/simu/opentxsimulator.cpp
Teach the old dog new tricks... in this case how to tap dance... er... make that multi-tap counting.
=> Add tap count support to `simu`

radio/src/gui/128x64/model_outputs.cpp, radio/src/gui/212x64/model_outputs.cpp, radio/src/gui/colorlcd/channel_bar.h, radio/src/gui/colorlcd/draw_functions.cpp, radio/src/gui/colorlcd/draw_functions.h, radio/src/gui/colorlcd/gvar_numberedit.h, radio/src/gui/colorlcd/model_outputs.cpp, radio/src/myeeprom.h
=> Call GV_IS_GV_VALUE() without offset applied

radio/src/gui/colorlcd/radio_trainer.cpp
Solution for issue #662 
Will add another commit with auto-formatting.... once I figure out how it works right in VScode doesn't seem to want to use the clang file.. ;)
=> Trainer calibration button

radio/src/gui/colorlcd/model_setup.cpp, radio/src/pulses/modules_helpers.h, radio/src/pulses/pxx1.cpp
=> Fix max # channels and default channel range

companion/src/modeledit/expodialog.cpp, companion/src/modeledit/expodialog.ui, companion/src/modelprinter.cpp
Fix #753 
Add sensor unit to input dialog
Add non-zero scale to inputs list and model print/compare
=> Companion input scale fix and enhancements

companion/src/firmwares/input_data.cpp, companion/src/firmwares/input_data.h, companion/src/modeledit/expodialog.cpp, companion/src/modeledit/expodialog.h, companion/src/modeledit/expodialog.ui, companion/src/modelprinter.cpp
Fixes #769 
Scale fields cosmetics
=> Fix model input trims

companion/src/modeledit/expodialog.cpp
Duplicate of change made in OTX
=> Remove scale fields artefacts

radio/src/pulses/modules_helpers.h
This could be related to #802. If a protocol is chosen that is not in the internal static list, it would access a `NULL` pointer while checking for failsafe.
=> [MPM] Sanitized static protocol definition pointer checks

radio/src/gui/colorlcd/model_setup.cpp
Fix subType editing & set default channel start + range on change.
Resolves #567
=> [color] Fix D8/D16/LR12 selection on XJT modules

radio/src/targets/simu/simpgmspace.cpp
=> Simu: Adjust RTC according to local time on start

radio/src/lua/api_colorlcd.cpp
https://discord.com/channels/839849772864503828/842693696629899274/894878085210574889
=> Lua font alignment - per discussion on Discord

radio/src/gui/colorlcd/view_statistics.cpp, radio/src/gui/colorlcd/view_statistics.h
Basically none of the text on the statistics pages was using theme colours - except for some DebugInfoNumber headings.  
Also fixes the reset button not working whilst I'm here...
=> Statistics page theming

radio/src/gui/colorlcd/model_setup.cpp
Allows for selecting receiver channels (1-8 / 9-16) and telemetry usage (on/off).
Resolves #941
=> Add support for D16/R9 options

companion/src/firmwares/rawsource.cpp
Fixes #996 
Port of https://github.com/opentx/opentx/pull/8769
=> Handle model conversion with invalid sources

radio/src/translations/untranslated.h
=> MEGA BAUDS not milli

radio/src/gui/colorlcd/view_main.cpp
This PR implements #981.
Much simpler than the previous PR with the same name.
=> Split window touch toр carousel start #981

radio/src/lua/api_general.cpp
Added 16 shared memory variables which can be accessed both from Lua widgets and other Lua scripts.
=> Issue #132

radio/src/gui/128x64/popups.h, radio/src/gui/128x64/view_telemetry.cpp, radio/src/gui/212x64/popups.h, radio/src/gui/212x64/view_telemetry.cpp, radio/src/gui/colorlcd/draw_functions.cpp, radio/src/gui/colorlcd/radio_sdmanager.cpp, radio/src/gui/colorlcd/radio_tools.cpp, radio/src/gui/colorlcd/standalone_lua.cpp, radio/src/gui/colorlcd/standalone_lua.h, radio/src/gui/common/stdlcd/popups.cpp, radio/src/lua/interface.cpp, radio/src/lua/lua_api.h
Attempting to guess a fix for #773
=> Updates to Lua scripts

radio/src/targets/simu/simpgmspace.cpp
This PR fixes the unsteady/bumpy touch emulation after merging PR #1000
=> fix simu and simulator touch slide

radio/src/gui/colorlcd/listbox.cpp
fix listbox() compiler warning
=> fixed compiler warning as per Risto

radio/src/storage/conversions/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp
Fixes #1110 
Summary of changes: v3 for EDGE LS was not saved in the model.yml file.
=> Save third value for EDGE LS in YAML

radio/src/storage/conversions/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp
=> Fix length of Txx string

radio/src/storage/conversions/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp
=> Fix attribute comma separation in custom functions

radio/src/gui/colorlcd/model_setup.cpp, radio/src/storage/conversions/conversions.cpp, radio/src/storage/modelslist.cpp, radio/src/storage/sdcard_yaml.h, radio/src/storage/yaml/yaml_parser.cpp, radio/src/storage/yaml/yaml_parser.h
=> Save models list after changing a model name

radio/src/gui/colorlcd/standalone_lua.cpp, radio/src/gui/colorlcd/standalone_lua.h, radio/src/lua/interface.cpp, radio/src/lua/lua_api.h, radio/src/lua/widgets.cpp
As promised, here is an implementation of touch events to Standalone scripts, based on what I did for Lua widgets.
=> Touch events to Standalone Lua scripts

radio/src/storage/yaml/yaml_datastructs_funcs.cpp
Fixes #1136 
Summary of changes: eat coma
=> Read SF enable state from YAML #1136

radio/src/lua/widgets.cpp
Issue #916 
@JimB40 - please test and let us know if it works
=> Added zone.absx and zone.absy to give position of a Lua widget on the screen

radio/src/gui/colorlcd/channel_bar.h, radio/src/gui/colorlcd/menu_screen.cpp, radio/src/gui/colorlcd/model_mixes.cpp, radio/src/gui/colorlcd/screen_setup.cpp, radio/src/gui/colorlcd/special_functions.cpp
=> fix issues:

radio/src/storage/conversions/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_parser.cpp, radio/src/storage/yaml/yaml_parser.h
=> YaML: escape exclamation marks to avoid issues with compliant parsers

radio/src/CMakeLists.txt, radio/src/gui/128x64/model_setup.cpp, radio/src/gui/212x64/model_setup.cpp, radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/gui_common.cpp, radio/src/gui/gui_common.h, radio/src/options.h, radio/src/translations/untranslated.h
=> Remove FLEX options (and make it default)

radio/src/lua/api_general.cpp
I added 4 new Lua functions:
`getSwitchIndex(positionName)` gets the switch index from a name as shown on the radio menus
`getSwitchName(switchIndex)` opposite of the above
`getSwitchValue(switchIndex)` gets the true/false value of a switch
`getPhysicalSwitches()` gets a table with name and index of all physical switch positions
`SWITCH_COUNT` a constant for the highest switch index
=> Issue #978 - Get switch index, name, value and position in lua

radio/src/gui/colorlcd/special_functions.cpp
Issue raised on Discord by "mathieusan".
=> Reload Lua scripts when a new function script is selected on COLORLCD

radio/src/gui/colorlcd/menu_screen.cpp, radio/src/gui/colorlcd/model_select.cpp
=> Fix two minor compiler warnings

radio/src/storage/conversions/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp
=> Fixed "lua(...,...)" source

radio/src/gui/colorlcd/radio_sdmanager.cpp, radio/src/gui/common/stdlcd/radio_sdmanager.cpp, radio/src/sdcard.h
Implements #294 
Summary of changes: allow file paste into the same folder.
Prefix cp_ is added to the file name.
=> support file copy to the same folder #294

radio/src/gui/colorlcd/color_editor.cpp, radio/src/gui/colorlcd/file_carosell.cpp, radio/src/gui/colorlcd/file_carosell.h, radio/src/gui/colorlcd/fullscreen_dialog.cpp, radio/src/gui/colorlcd/fullscreen_dialog.h, radio/src/gui/colorlcd/listbox.cpp, radio/src/gui/colorlcd/preview_window.h, radio/src/gui/colorlcd/radio_theme.cpp, radio/src/gui/colorlcd/radio_theme.h
1. fix issue with confirmationDialog not processing mouse down.
2. lots of layout tweaks on both horus and NV14 radios
3. theme preview bitmaps do not load when theme browser is not on the top of the stack.  better performance
4. more preview controls to see additional colors.
=> Fix theme defects

radio/src/gui/colorlcd/radio_tools.cpp, radio/src/gui/colorlcd/radio_tools.h
=> sort lua scripts before building ui in radio tools

companion/src/firmwares/generalsettings.cpp
Fixes #1216
Align Companion radio settings defaults to firmware
=> Align Companion radio default settings

radio/src/gui/colorlcd/menu_model.cpp, radio/src/gui/colorlcd/model_outputs.cpp
PR in response to https://www.rcgroups.com/forums/showthread.php?3916381-Official-EdgeTX-Discussion-Thread/page101#post48295353
This PR needs testing.
=> Fix building with -DGVARS=NO

radio/src/gui/colorlcd/model_mixes.cpp
make channel monitor in model_mixes size correctly on nv14
=> fix mix channel monitor size on nv14

radio/src/lua/interface.cpp
=> Truncate Mixer Lua script input and output names to 6 chars

radio/src/lua/widgets.cpp
String options were not working for Lua widgets.
=> Fixed string option for Lua widgets

radio/src/gui/colorlcd/radio_tools.cpp
=> fixed 376 by making each line 10 pixels higher.

radio/src/targets/horus/CMakeLists.txt, radio/src/targets/nv14/CMakeLists.txt, radio/util/generate_datacopy.py
Allows for building on ARM64 hosts (tested on AWS `t4g.micro`).
=> ARM64 fixes

radio/src/gui/colorlcd/radio_version.cpp, radio/src/targets/nv14/lcd_driver.cpp
show LCD controller type on NV14 radio version screen
fix ST7796S LCD controller detection
fix ST7796S driven displays to show correct colors
fix NV14 lcd_driver.cpp compiler warning
=> repair support for ST7796S driven displays

radio/src/gui/colorlcd/radio_diaganas.cpp, radio/src/targets/horus/tp_gt911.cpp, radio/src/targets/horus/tp_gt911.h, radio/src/targets/nv14/board.h, radio/src/targets/nv14/touch_driver.cpp, radio/src/targets/simu/simpgmspace.cpp
fixes the touch screen test in the analog input test screen by using the correct data.
thx @pfeerick
=> fix touch screen test in analog input test screen

radio/src/lua/interface.cpp
Fixed a dumb bug where I used the wrong index
=> Fix Lua Mixer index issue

radio/src/targets/common/arm/stm32/rotary_encoder_driver.cpp
... and match TX16S roller navigation style, making it easier for users to switch and migrate between these radios.
=> Make Zorro roller direction more natural

.gitmodules, radio/src/gui/colorlcd/CMakeLists.txt, radio/src/targets/simu/simulcd.cpp
lvgl has an error when copying a buffer to a canvas. I created a fork of LVGL and fixed the problem.
with this PR my fork is used, until the problem is fixed in LVGL.
Also TX16S simu drawing problems fixed
libopenui was not pulled with the correct commit, which is also fixed now
=> Lvgl switch to fork + fixing drawing problems

radio/src/curves.cpp, radio/src/curves.h, radio/src/gui/128x64/model_curve_edit.cpp, radio/src/gui/212x64/model_curve_edit.cpp, radio/src/gui/colorlcd/model_curves.cpp
Resolves #1295
- "Clear curve" now correctly handles shifts in global point array.
- Change applied to B&W targets as well.
=> Fixed clearing curves

tools/setup_buildenv_ubuntu20.04.sh
=> fix Ubuntu 20.04 prepare script, libclang-11-dev was missing

companion/src/firmwares/edgetx/yaml_logicalswitchdata.cpp
=> Fix EDGE logical switch (de-)serialization

companion/src/firmwares/edgetx/yaml_rawsource.cpp
=> Fix switch indexes

companion/src/mdichild.cpp, companion/src/modelslist.cpp, companion/src/modelslist.h
Fixes #1375
Remove heading and redundant code
=> Companion remove size column heading from model list

companion/src/firmwares/edgetx/yaml_modeldata.cpp, radio/src/gui/colorlcd/model_setup.cpp
Resolve #1393
- (de-)serialize failsafe settings properly
- fixed radio failsafe display (use proper scale instead of raw value)
=> Fix failsafe settings

companion/src/firmwares/opentx/opentxeeprom.cpp
Accounts now for EX3 & EX4
Resolves #1398
=> Fix throttle trace source conversion error

radio/src/lua/api_general.cpp
OK, I think that issue #1346 has been fixed now, but the iNav people have to confirm that.
=> Issue 1346

radio/src/lua/lua_api.h
=> Increased Lua buffer size for standalone and telemetry scripts

radio/src/translations/translation.py
- Fixes issues with translation.py script by forcing it to open files using utf-8 encoding.
=> Fix translation.py script encoding

companion/src/firmwares/edgetx/yaml_customfunctiondata.cpp, companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/edgetx/yaml_modeldata.cpp, companion/src/firmwares/edgetx/yaml_rawsource.cpp, companion/src/firmwares/edgetx/yaml_rawswitch.cpp
- Fix (de-)serializing enable param for backlight custom function
- Fix OFF backlight
- Fix power ON/OFF delay
- Fix flight mode trim disabled
- Fix trim switch index
- Fix deserializing SLIDER[1,2]
- Fix shift for logical switches in raw sources
=> Various Companion fixes

radio/src/telemetry/frsky.h, radio/src/telemetry/frsky_sport.cpp, radio/src/telemetry/multi.cpp, radio/src/tests/frsky.cpp
=> multi: move the TQly & TRSS hack where it belongs

companion/src/firmwares/modeldata.cpp, companion/src/firmwares/opentx/opentxeeprom.cpp, companion/src/modeledit/setup.cpp, companion/src/modeledit/setup.h, companion/src/modeledit/setup_function_switches.ui, radio/src/gui/128x64/model_setup.cpp, radio/src/myeeprom.h, radio/src/switches.cpp
Import:
- fix for T-Pro function switch Toggle behaivour
- add always on group behaviour
- update Companion to suit
- fixes setting a function switch to none disabling unrelated switches
=> TPro - fix function switch behaviour

companion/src/firmwares/edgetx/yaml_modeldata.cpp
Fixes #1518
Add field ignoreSensorIds to yaml read/write
=> Companion include telemetry setting ignore instances in yaml

radio/src/lua/api_colorlcd.cpp
The background box was misaligned.
=> Fixed a bug with drawing INVERS + CENTER

radio/src/storage/conversions/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp
Works on my TX16S. @raphaelcoeffic should verify that it does not break something in Companion!
=> Fixed issue #1500

radio/src/lua/widgets.cpp
Replaces #1496. This one is based on `main`.
=> Increased resources for Lua widgets 2

companion/src/firmwares/edgetx/yaml_modeldata.cpp
=> Companion fix trainer data yaml read and write

radio/src/gui/colorlcd/special_functions.cpp
This is a simplified code version for the PR #1561
Fixes #1539
Summary of changes: remove unnecessary code.
=> fix SF repeat field problem (#1539). Simplified version

companion/src/firmwares/edgetx/yaml_modeldata.cpp
Fixes #1557
Add union struct on read and write.
Alternative array iterations method on write.
=> Companion fix b&w custom telemetry screens yaml

companion/src/firmwares/edgetx/yaml_generalsettings.cpp
Fixes #1541 and mentioned in part in 1413
Improve messages and remove reference to conversion as there is no indication of how successful the conversion was giving the user the impression all is ok when it may not.
OTX file format conversion is very detailed.
=> Companion improve read radio settings messages

companion/src/firmwares/edgetx/yaml_customfunctiondata.cpp
Fixes #1564
Add specific read and write rules for haptic function
=> Companion fix special function haptic

tools/setup_buildenv_ubuntu20.04.sh
Tested by me and @3djc and deemed to work with current Ubuntu 20.04 LTS.
=> Fix Ubuntu build script - match GH clang v6.0

radio/src/translations/cz.h
Added Czech translation as requested on Discord. I have tried to align it with `fr.h` as much as possible.
Unfortunately I haven't tested it yet.
=> Czech translation

radio/util/crossfire-parse.py
* Additional data input formats
* Support for more CRSF message types
* Support for chunked messages
=> Updates to CRSF parsing script

companion/src/translations/companion_sv.ts
Summary of changes: Swedish translations for Companion revised and updated.
=> Updated Swedish translations

radio/src/targets/taranis/board.cpp
(https://github.com/opentx/opentx/pull/8871)
Fixes #
=> Port of OpenTX Tpro charge led indicator

radio/src/gui/colorlcd/model_select.cpp
I added a callback function to update the model image after the template has been read.
=> Update model image after reading template

radio/src/datastructs.h, radio/src/datastructs_private.h, radio/src/opentx.cpp, radio/src/storage/conversions/conversions.cpp, radio/src/storage/conversions/conversions.h, radio/src/storage/eeprom_rlc.cpp, radio/src/storage/sdcard_yaml.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_datastructs_nv14.cpp, radio/src/storage/yaml/yaml_datastructs_t12.cpp, radio/src/storage/yaml/yaml_datastructs_t8.cpp, radio/src/storage/yaml/yaml_datastructs_tlite.cpp, radio/src/storage/yaml/yaml_datastructs_tpro.cpp, radio/src/storage/yaml/yaml_datastructs_tx12.cpp, radio/src/storage/yaml/yaml_datastructs_x10.cpp, radio/src/storage/yaml/yaml_datastructs_x12s.cpp, radio/src/storage/yaml/yaml_datastructs_x7.cpp, radio/src/storage/yaml/yaml_datastructs_x9d.cpp, radio/src/storage/yaml/yaml_datastructs_x9e.cpp, radio/src/storage/yaml/yaml_datastructs_x9lite.cpp, radio/src/storage/yaml/yaml_datastructs_x9lites.cpp, radio/src/storage/yaml/yaml_datastructs_xlite.cpp, radio/src/storage/yaml/yaml_datastructs_xlites.cpp, radio/src/storage/yaml/yaml_datastructs_zorro.cpp, radio/src/tests/conversions.cpp
And remove `version`/`variant`.
=> Write 'semver' tag with the current firmware version

companion/src/firmwares/edgetx/yaml_rawswitch.cpp
=> Companion fix reading of Act and Telemetry switches

radio/src/cli.cpp
implement canonial terminal back delete
=> implement canonial terminal back delete

.github/workflows/actions.yml, fw.json, tools/build-frsky.py, tools/build-gh.sh
added X9E target to github actions and a `x9e-hall` target with `STICKS=HORUS` option set.
some discussion about this on discord
https://discord.com/channels/839849772864503828/839856795781431317/955528981812215868
=> added X9E target

radio/src/gui/colorlcd/model_mixer_scripts.cpp, radio/src/lua/interface.cpp, radio/src/strhelpers.cpp, radio/src/strhelpers.h
fixes the non-terminated fixed-string problem in lua-mixer-script
added some useful info to the script-line
make the popup menu to delete a script
=> Try to fix use of unterminated strings in mixer setup (#1317)

radio/src/pulses/multi.cpp, radio/src/pulses/pulses.cpp, radio/src/pulses/pulses.h, radio/src/telemetry/multi.cpp, radio/src/telemetry/multi.h, radio/src/telemetry/telemetry.h
=> Let's do some dirty hack with MPM RX

radio/src/pulses/ppm.cpp, radio/src/pulses/pulses.h
- fix last period depending on the PPM driver used.
- apply frame length setting properly
=> Fix trainer signal period

companion/src/firmwares/edgetx/yaml_moduledata.cpp
=> Fix Lemon-rx dsmp type yaml

companion/src/modeledit/colorcustomscreens.cpp
Fixes #1762
- Test for null values in theme.yml
- improve handling of missing files and folders likely caused by out of sync sd card
=> Companion improve themes exceptions handling

radio/src/storage/conversions/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp
=> YAML: Quote stick names

companion/src/modeledit/curves.cpp
Fixes #1800
- add context menu to curve image
- add note to advise how the add a new curve
=> Companion enhancements to curves tab

radio/src/gui/colorlcd/model_select.cpp
#1809 wizard now worky again me thinks
=> Fix for issue #1809

companion/src/modeledit/setup.cpp
=> Companion remove multi protocol Config from list

radio/src/strhelpers.cpp
=> Remove offset when copying timer name

companion/src/modeledit/setup.cpp
=> Companion antenna mode dropdown not displaying for new models with antenna support

companion/src/apppreferencesdialog.cpp
=> Fix companion radio profile default module resetting to board default

companion/src/translations/companion_sv.ts
Summary of changes: A few corrections and minor changes to the Swedish language translations for Companion.
=> Companion se translations

tools/setup_buildenv_msys2_py_requirements.txt, tools/setup_buildenv_msys2_stage2.sh
Fix Python bcj-cffi and pyppmd package installation under MSYS2 and match better the GitHub MSYS2 environment setup.
=> MSYS2 dev. env. setup script update/fix

radio/src/gui/colorlcd/radio_hardware.cpp, radio/src/targets/horus/telemetry_driver.cpp
Tested successfully by Discord user Ian_Gage on X10S: https://discord.com/channels/839849772864503828/867878348037947402/979133214520119326
=> Added OneBit option also to color radios

companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/edgetx/yaml_modeldata.cpp, companion/src/firmwares/generalsettings.h, companion/src/firmwares/modeldata.h
=> Companion read/write semver in model and radio yml files

radio/src/gui/128x64/model_special_functions.cpp, radio/src/gui/212x64/model_special_functions.cpp
=> Fix B&W compile with DANGEROUS_MODULE_FUNCTIONS enabled

radio/src/gui/colorlcd/confirm_dialog.cpp, radio/src/gui/colorlcd/confirm_dialog.h, radio/src/gui/colorlcd/draw_functions.cpp, radio/src/gui/colorlcd/lcd.cpp, radio/src/gui/colorlcd/model_select.cpp, radio/src/main.cpp, radio/src/opentx.cpp, radio/src/targets/common/arm/stm32/bootloader/boot.cpp, radio/src/targets/horus/board.cpp, radio/src/targets/horus/bootloader/boot_menu.cpp, radio/src/targets/horus/lcd_driver.cpp, radio/src/targets/nv14/battery_driver.cpp, radio/src/targets/nv14/board.cpp, radio/src/targets/nv14/bootloader/boot_menu.cpp, radio/src/targets/simu/backlight_driver.cpp, radio/src/targets/taranis/bootloader/boot_menu.cpp
- USB screen now displayed properly.
- Bootloader start without visual artefacts
- Firmware start without visual artefacts
- Fixed all other "fatal screens" ("No SD card" / "Wrong PCB rev", etc)
=> fix(colorlcd): multiple display issues

radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
=> fix table behavor on touch release (Highlight)

radio/src/targets/common/arm/stm32/stm32_i2c_driver.cpp, radio/src/targets/common/arm/stm32/stm32_i2c_driver.h, radio/src/targets/nv14/touch_driver.cpp, radio/src/targets/nv14/touch_driver.h
support for a new NV14 touch controller
=> support new NV14 touch controller

radio/src/translations/cz.h
Fixes #
Update Czech translations
=> Update Czech translation

companion/src/translations/companion_da.ts, radio/src/translations/da.h
After merge with main base, some missing translations where discovered. Now fixed.
=> Update minor changes to danish translations

radio/src/targets/horus/lcd_driver.cpp
=> TX16S LCD max clock 12 MHz

companion/src/firmwares/edgetx/yaml_moduledata.cpp
=> Companion fix yaml handling of ACCESS receiver names

radio/src/storage/yaml/yaml_datastructs_nv14.cpp, radio/src/storage/yaml/yaml_datastructs_t12.cpp, radio/src/storage/yaml/yaml_datastructs_t8.cpp, radio/src/storage/yaml/yaml_datastructs_tlite.cpp, radio/src/storage/yaml/yaml_datastructs_tpro.cpp, radio/src/storage/yaml/yaml_datastructs_tx12.cpp, radio/src/storage/yaml/yaml_datastructs_x10.cpp, radio/src/storage/yaml/yaml_datastructs_x12s.cpp, radio/src/storage/yaml/yaml_datastructs_x7.cpp, radio/src/storage/yaml/yaml_datastructs_x9d.cpp, radio/src/storage/yaml/yaml_datastructs_x9e.cpp, radio/src/storage/yaml/yaml_datastructs_x9lite.cpp, radio/src/storage/yaml/yaml_datastructs_x9lites.cpp, radio/src/storage/yaml/yaml_datastructs_xlite.cpp, radio/src/storage/yaml/yaml_datastructs_xlites.cpp, radio/src/storage/yaml/yaml_datastructs_zorro.cpp
- regenerates yaml files as they were not re-generated after https://github.com/EdgeTX/edgetx/pull/2064/commits/0207b049731bce6630ebde10d780f9dbc05147d6
=> chore(yaml): PR#2064 didn't regenerate files

radio/src/translations/da.h, radio/src/translations/tts_da.cpp
Danish changes as PR 2109 and 1891
=> Changes as to PR 2109

radio/src/switches.cpp, radio/src/targets/taranis/hal.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/untranslated.h
Fixes that were lost when TX12MK2 PR was raised.
Will be merged after compile checks as were already tested locally and in private testing.
=> Misc fixes

radio/src/translations/jp.h
I modified jp.h while watching the display. Replaced it with the latest en.h. Also fixed around IMU.
=> Japanese modifications were made to the display.

radio/src/gui/colorlcd/custom_failsafe.cpp
=> fix: type cast for failsafe channel update

companion/src/modeledit/setup.cpp
Fixes #2177
- Change switch filter
=> Companion fix timer switch list

radio/src/gui/colorlcd/access_settings.cpp, radio/src/gui/colorlcd/access_settings.h, radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/colorlcd/module_setup.cpp, radio/src/gui/colorlcd/textedits.h, radio/src/pulses/pulses.cpp, radio/src/pulses/pxx2.cpp, radio/src/pulses/pxx2.h
Currently based on #2100 and shall be rebased once that PR is merged.
Needs https://github.com/EdgeTX/libopenui/pull/58
=> fix(access): ported pop-up dialogs to flex layout

radio/src/targets/common/arm/stm32/sdio_sd.c
Some background here : https://forum.sparkfun.com/viewtopic.php?t=31759
Succesfully tested by Radiomaster
=> Prevent TF lock

companion/src/translations/companion_da.ts, radio/src/translations/da.h
Changes to companion and radio
=> More translated to Danish

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
Summary of changes: major review and addition of several missing translation contexts in Companion, plus a few changes for radio firmware.
=> Swedish translations - major update

companion/src/translations/companion_da.ts, radio/src/translations/da.h
More translation inspired by ulfhedlund
Changed ChannelsPanel to Channels (seems more need to do that)
=> Companion translate da

radio/src/gui/colorlcd/curveedit.cpp
=> fix: custom curves corruption

companion/src/translations/companion_da.ts, radio/src/translations/da.h
Summary of changes: minor changes of danish translation
=> More Danish translations

companion/src/firmwares/boards.h, companion/src/firmwares/eeprominterface.h, companion/src/firmwares/generalsettings.cpp, companion/src/firmwares/modeldata.cpp, companion/src/firmwares/opentx/opentxinterface.cpp
Fixes #2237
- validate radio settings internal module matches radio profile default module, if not set to OFF
- new firmware capabilities
=> Companion improve module and protocol conversion

radio/src/translations/de.h
=> hotfix for german translation

companion/src/mdichild.cpp
Fixes #2280
Thanks to @dlktdr for identifying root cause
=> Companion simulator will not start after adding new model

radio/src/gui/colorlcd/LvglWrapper.cpp
- re-implemented rotary encoder velocity in LVGL rotary encoder driver
=> feat(color): re-add support for rotary encoder velocity increase

radio/src/gui/colorlcd/widget.cpp, radio/src/gui/colorlcd/widget.h
=> fix(color): disallow fullscreen mode for topbar widgets

radio/src/translations/it.h
Fixes #
Summary of changes: minor fix
=> fix(color): Fix appearance of Italian shutdown warning messages 🇮🇹

radio/src/gui/colorlcd/radio_version.cpp
Fixes #2320
changed the popup to two columns and two separate lines for type and status, for pictures see issue #2320
=> fix(color): Improve layout of Module / RX version pop up

radio/src/translations/cz.h
@daleckystepan prosím o review
Czech translation
Fixes #
=> fix: Updates to Czech translations 🇨🇿

radio/src/lua/lua_widget.cpp
=> fix(lua): handle ENTER_LONG properly

radio/src/gui/colorlcd/view_main_decoration.cpp
=> fix(color): Remove Main View - Main Zone left side offset

radio/src/gui/colorlcd/LvglWrapper.cpp, radio/src/gui/colorlcd/color_editor.cpp
=> Better encoder accel

radio/src/lua/api_colorlcd.cpp
=> fix(lua): lcd.drawGauge wide gauge error

radio/src/gui/colorlcd/model_flightmodes.cpp, radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/preview_window.h, radio/src/gui/colorlcd/radio_theme.cpp, radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
Fixes #2304
Requires EdgeTX/libopenui#67
=> fix(color): Unify button colors

radio/src/lua/api_colorlcd.cpp, radio/src/lua/api_colorlcd.h
=> fix(gui): fixes #2370 wrong Lua font aligntment

radio/src/tasks.cpp
Fixes fixes https://github.com/EdgeTX/edgetx/issues/2364
=> fix(cpn): Calculated telemetery sensors in simulator not updating

companion/src/updates/updatecompanion.cpp
Fixes #2365
Tested selfbuild and simulated release by setting environment variable EDGETX_VERSION_TAG
=> fix(cpn): Start up interface error 301

radio/src/gui/colorlcd/screen_setup.cpp
Fixes the focus order changing the layout of a screen.
=> fix(color): focus order after layout choice

radio/src/model_init.cpp
=> fix: default input names on model creation

radio/src/gui/colorlcd/themes/480_default.cpp, radio/src/gui/colorlcd/themes/flysky.cpp
Summary of changes: see title ;)
=> fix(gui): vertical tab title alignment on color lcd radios fixed

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
- added translations for recently changed items in Companion, mainly related to update
- some minor changes to firmware translations, for added consistency
=> New Swedish translations

radio/src/translations/de.h
I've made a few more german translations and fix one too long translation for QX7
=> feat: Few more German translations 🇩🇪

companion/src/modelprinter.cpp
=> Model print pot warnings

companion/src/multimodelprinter.cpp
=> Model print remove B&W eeprom size

companion/src/translations/companion_da.ts, radio/src/translations/da.h
=> Danish translations

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
- New radio translation for #2397 and a few tweaks for other stuff
- A few Companion translations also tweaked
=> More Se translations

radio/src/translations/tw.h
=> Fixed TW translation missing line, issue #2485.

radio/src/gui/colorlcd/widget_settings.cpp
Fixes #2465
Summary of changes: added dirty storage flag to new source value assignment
=> fix(color): dirty storage flag to new source value assignment

radio/src/translations.h, radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h
and streamline translation definitions.
Fixes #
=> chore: remove useless BREAKSPACE

radio/src/gui/128x64/model_setup.cpp, radio/src/gui/212x64/model_setup.cpp, radio/src/gui/colorlcd/module_setup.cpp
=> fix(multi): set bind status explicitly when aborted manually

radio/src/gui/colorlcd/preflight_checks.cpp
Fixes #2477 
Summary of changes: add appropriate offset to the inex
=> fix sliders and potentiometers warning (#2477)

radio/src/gui/colorlcd/custom_failsafe.cpp
=> feat(color): add copy button to failsafe channel

radio/src/gui/colorlcd/fullscreen_dialog.cpp, radio/src/gui/colorlcd/fullscreen_dialog.h
=> FullscreenDialog: add support for long pressed ENTER

radio/src/translations/cz.h
=> CZ translations

radio/src/targets/nv14/lcd_driver.cpp
According to the information given by Flysky.
Fixes #2524
=> fix(NV14/EL18): Reduce LCD pixel clock to 1000000

radio/src/gui/colorlcd/model_select.cpp
=> fix(X10): simulated page up in menu toolbar

radio/src/gui/colorlcd/module_setup.cpp
=> fix(color): RF power drop-down

radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/model_mixes.cpp
=> fix(color): copy/paste inputs/mixers

radio/src/gui/colorlcd/radio_spectrum_analyser.cpp
=> fix: clear spectrum analyser data buffer on init

radio/src/mixer.cpp
=> fix(global functions): reset global function context if disabled

radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/model_select.h
Fixes #2627 
Summary of changes: Add menu item "Save as template" to the model selection.
=> fix(color): Re-add "save as template" to model select

radio/src/gui/colorlcd/module_setup.cpp
=> fix(isrm): add module options to ISRM/D16

companion/src/translations/companion_da.ts, radio/src/translations/da.h
Changed translations to Champanion after correction in #2602
Changed translations to Radio, including PR #2655 (including latest changes)
=> More translations to DK

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
Minor updates for Swedish translations for both firmware and Companion.
=> More se updates

radio/src/gui/colorlcd/model_outputs.cpp
Fixes #2660, since `invalidate` is not updating all the line elements, but I'm not convinced it's the right way to fix it.
=> fix(color): Outputs lines not updating after reset

radio/src/targets/nv14/board.h
=> chore(el18): Change default switch configuration to match production

companion/src/translations/companion_da.ts
Changes to 2 panels in Companion
=> chore(cpn): More Danish translations (customfunctiondata)

radio/src/gui/colorlcd/layouts/sliders.cpp, radio/src/gui/colorlcd/layouts/sliders.h
Fixes #2679 
Summary of changes: add checkEvents() to the MainView6POS.
This fixies display issue, but it looks like 6POS calibration is broken.
=> fix(color): 6POS display on the main and calib. screens (#2679)

radio/src/gui/colorlcd/flysky_settings.cpp
=> Fixed phy mode naming of AFHDS3.

radio/src/audio.cpp, radio/src/targets/nv14/audio_spi_driver.cpp
=> Streamlined the SPI audio init of EL18.

radio/src/targets/nv14/board.cpp
=> NV14/EL18 Added reboot when detect USB is plugged.

companion/src/modeledit/setup.cpp, companion/src/modeledit/setup.h, companion/src/modeledit/setup_module.ui
=> cpn(fix): Multi module DSM protocol options

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
Just some corrected to misspellings.
=> Se translation corrections

companion/src/firmwares/edgetx/yaml_sensordata.cpp
Fixes #2753 though applies to all sensors
=> cpn(fix): yaml encode/decode telemetry sensor subId

radio/src/gui/colorlcd/topbar.cpp, radio/src/gui/colorlcd/topbar.h
=> fix(ui): fixed a memory leak and warning in topbar.cpp

radio/src/lua/lua_widget.cpp
=> fix(lua): do not push long enter key press on long touch

companion/src/firmwares/edgetx/yaml_rawsource.cpp, companion/src/firmwares/radiodata.cpp, companion/src/mdichild.cpp
=> chore(cpn): remove some compiler warnings

radio/src/gui/colorlcd/special_functions.cpp
the special function edit screen now has the new look and feel
=> chore(ui): update special function edit screen to LVGL

radio/src/targets/taranis/board.cpp
Removed obsolete audio mute related functions from B/W code.
=> Audio mute: remove obsolete functions

companion/src/firmwares/generalsettings.cpp
=> cpn(fix): Set default voice language to en

radio/src/translations/jp.h
We have identified several areas where the translation differs, which have been corrected.
=> Updates to Japanese translations 🇯🇵

companion/src/shared/curvedialog.cpp, companion/src/simulation/simulateduiwidgetX9D2019.cpp, companion/src/simulation/simulateduiwidgetX9LITE.cpp, companion/src/storage/yaml.h, radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/theme_manager.cpp, radio/src/storage/modelslist.h, radio/src/strhelpers.cpp, radio/src/telemetry/frsky_pxx2.cpp, radio/src/telemetry/multi.cpp
Fixes #
A small number of cosmetic changes to remove compiler warnings while building companion and libsimulator.
=> Minor changes to remove compiler warnings when building companion and libsimulator.

companion/src/translations/companion_da.ts, radio/src/translations/da.h
=> More translated

radio/src/gui/colorlcd/LvglWrapper.cpp, radio/src/gui/colorlcd/LvglWrapper.h, radio/src/gui/colorlcd/fm_matrix.cpp, radio/src/gui/colorlcd/fm_matrix.h, radio/src/gui/colorlcd/gvar_numberedit.cpp, radio/src/gui/colorlcd/gvar_numberedit.h, radio/src/gui/colorlcd/preflight_checks.cpp
Make ButtonMatrix button text color behave like TextButton for flight modes and pre-flight checks.
Show 'GV' button as checked if corresponding input value is a global var.
=> fix(ui) - Make button colors consistent

radio/src/gui/colorlcd/model_select.cpp
- adds confirmation prompt before saving a model as a template, or duplicating it
=> feat(color): Confirm before duplicate or saving model as template

radio/src/translations/tw.h
Add the translations to tw.h that I missed previously.
=> fix(color) - Add missing translations for earlier PR's.

radio/src/gui/colorlcd/model_setup.cpp
=> fix(ui) - Adjust model setup layout to better fit on portrait LCD screen.

radio/src/translations/jp.h
Fixed overlapping of strings due to line breaks in Japanese display.
=> Fixed overlapping strings due to line breaks

companion/src/translations/companion_da.ts, radio/src/translations/da.h
Small bad chosen names changed
=> Danish translation - minor changes

radio/src/gui/colorlcd/curve.cpp, radio/src/gui/colorlcd/curve.h, radio/src/gui/colorlcd/curveedit.cpp, radio/src/gui/colorlcd/model_curves.cpp, radio/src/gui/colorlcd/model_curves.h
Implementation of design from issue #2970
=> feat(ui) - New model curves page layout.

radio/src/gui/colorlcd/input_edit.cpp
Fixes #3098
Fix size for curve preview in model input edit view.
=> fix(ui) - Inputs - curve line is offset

radio/src/gui/colorlcd/model_curves.cpp, radio/src/gui/colorlcd/model_curves.h
Show popup of available curves to allow user to select which curve to add or set preset on.
=> fix(color) - Make new curve handling work like special functions.

radio/src/gui/colorlcd/model_templates.cpp, radio/src/gui/colorlcd/model_templates.h
=> fix(ui) - LVGL flex conversion for model template selection pages.

radio/src/gui/colorlcd/radio_spectrum_analyser.cpp
There are no significant changes to the look or functionality - just converted the footer section.
=> fix(ui) - LVGL flex conversion for spectrum analyser footer.

radio/src/gui/colorlcd/model_gvars.cpp, radio/src/gui/colorlcd/model_gvars.h, radio/src/strhelpers.cpp, radio/src/strhelpers.h
Update the colors and style to better match inputs, mixes, special functions etc.
Changed the 'FMx' header string to smaller font so the values stand out more.
Center the GV name vertically.
=> feat(color) - Change global variables layout to better match other pages.

radio/src/pulses/afhds3.cpp, radio/src/pulses/afhds3_transport.cpp, radio/src/pulses/afhds3_transport.h
=> FRM303 support for EL18, branch 2.8, enhancement 2863

radio/src/gui/colorlcd/view_logical_switches.cpp
Fixes #3136
Fix column position for duration and delay parameters.
=> fix(color) - Fix footer layout in logical switch monitor page.

radio/src/translations/cn.h, radio/src/translations/tw.h
=> fix(color) - Update translations for theme save and delete strings.

companion/src/translations/companion_da.ts, radio/src/translations/da.h
New strings in companion and aligment with radio
=> Companion and radio: Qt changes and aligment in da.h

radio/src/gui/colorlcd/view_statistics.cpp, radio/src/gui/colorlcd/view_statistics.h
=> fix(ui) - LVGL flex conversion for statistics and debug pages.

companion/src/modeledit/customfunctions.cpp
=> fix(cpn): Save set main view screen number for special/global function

radio/src/targets/taranis/stm32f2_flash.ld, radio/src/targets/taranis/stm32f4_flash.ld
=> chore: move __global_locale to FLASH

radio/src/translations/tw.h
=> Fixed build error in TW language, fixes #3184

radio/src/translations/cz.h, radio/src/translations/de.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/it.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h
=> fix(b&w): missing timer labels

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
Added missing strings for Save and delete theme plus some minor corrections
=> Se translation updates

companion/src/firmwares/edgetx/yaml_modeldata.cpp, companion/src/firmwares/modeldata.h, radio/src/storage/storage_common.cpp
Fixes #2806
~~Totally untested so far :-D~~ seems to work for me 👻
Btw. I know the worst case is $O(n^2)$, but it should not ever happen. The goal of this is to avoid spending too much FLASH on something hopefully useless.
=> fix: sort mixer lines after loading model

tools/msys2_fetch_and_build_all_tx16s.sh
- stop on error
- support different branch's (not only main)
- add all the radio option on top of the script
- support re-run of the build (handle existing dir & git pull)
- add logs to follow the progress steps (especially in case of failure)
Fixes #
=> feat: MSYS2 build script enhancements

radio/src/logs.cpp, radio/src/spacemouse.cpp
fixes https://github.com/EdgeTX/edgetx/issues/3207
- removed obsolete check for mixer task running
=> fix: logs not written to SD card and SpaceMouse not working

radio/src/gui/colorlcd/curveedit.cpp, radio/src/gui/colorlcd/model_gvars.cpp, radio/src/gui/colorlcd/model_logical_switches.cpp, radio/src/gui/colorlcd/model_mixer_scripts.cpp, radio/src/gui/colorlcd/model_telemetry.cpp, radio/src/gui/colorlcd/page.cpp, radio/src/gui/colorlcd/page.h, radio/src/gui/colorlcd/radio_calibration.cpp, radio/src/gui/colorlcd/radio_diagkeys.cpp, radio/src/gui/colorlcd/radio_ghost_module_config.cpp, radio/src/gui/colorlcd/radio_sdmanager.cpp, radio/src/gui/colorlcd/radio_setup.cpp, radio/src/gui/colorlcd/radio_theme.cpp, radio/src/gui/colorlcd/special_functions.cpp, radio/src/gui/colorlcd/throttle_params.cpp, radio/src/gui/colorlcd/trims_setup.cpp
Many pages have a 2nd line of text in the header.
This change moves management of this to the 'Page' class to clean up the code a bit.
=> chore(color) - Add 'title2' to Page class to manage 2nd header title line.

companion/src/firmwares/customfunctiondata.cpp, companion/src/firmwares/customfunctiondata.h, companion/src/modelprinter.cpp, companion/src/modelprinter.h, companion/src/multimodelprinter.cpp
Fixes #3074
- fix generate set timer parameter value
- do not generate parameter when function does not support
- do not generate repeat when function does not support
- convert to table format with per column compare highlighting
- minor housekeeping
Before
After
=> fix(cpn): Model print global and special functions

radio/src/gui/colorlcd/radio_diaganas.cpp, radio/src/gui/colorlcd/radio_diaganas.h
Replace 'paint' function with LVGL objects.
=> chore(color) - Convert analog debug pages to lvgl.

radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h
Fixes #3304 
Change units to SI
=> Fixes #3304 - Wrong case used for units of time

companion/src/translations/companion_da.ts
=> Update danish translation in Companion

radio/src/gui/128x64/lcd.cpp, radio/src/gui/128x64/view_main.cpp
Fixes #3303 
See the above issue for discussion and screen shots.
=> feat(b&w) - Show time on the main screen and telemetry screen.

radio/src/targets/nv14/board.cpp
=> Fix the BUG that unplugs the USB and automatically power on

radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/model_inputs.h
Show list of available inputs when the '+' button is tapped on the inputs page.
Fixes #3313
=> feat(color) - Make Inputs page '+' button work like other pages.

radio/src/opentx.cpp
Bypass MCU check if running simulator.
=> fix(simulator) - Fix simulator crash introduced in PR #3272

radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/model_templates.cpp, radio/src/gui/colorlcd/model_templates.h
Cancelling from the template select page will return to the model select page, and no longer create a blank model.
Fixes: #3312
=> fix(color) - Only create a new model if the user actually selects a template.

radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h
=> Fix trainer mode translations for BW screens

companion/src/datamodels/compounditemmodels.cpp, companion/src/modeledit/expodialog.cpp
Fixes Companion part of #3086
- inclusion of gvars to input sources
- move gvars before telemetry as radio
=> fix(cpn): Add gvars to input sources

radio/src/gui/colorlcd/menu_screen.cpp, radio/src/gui/colorlcd/screen_setup.cpp, radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h
Fixes the issue reported in: https://github.com/EdgeTX/edgetx/pull/3073#issuecomment-1471827610 that was introduced by PR #3073 
Results:
=> fix(ui): Main view numbering #3073

radio/src/gui/colorlcd/model_logical_switches.cpp, radio/src/gui/colorlcd/view_logical_switches.cpp
Tweak the column sizes in the list view and the channel monitor footer to fit largest V2 value for 'Edge' function.
=> fix(color) - Adjust the column sizes for the logical switches

radio/src/lua/api_general.cpp
* Adds two new functions to LUA API: serialGetPower() and serialSetPower() to read and control serial port power pins from LUA on radios that support this functionality.
Widget demonstrating functionality here: https://github.com/EdgeTX/edgetx-sdcard/pull/101
=> feat(lua): added serial[Get|Set]Power() to LUA API.

radio/src/gui/colorlcd/model_telemetry.cpp, radio/src/gui/colorlcd/model_telemetry.h
Also refresh view when 'Ignore instances' changes.
=> fix(color) - Fix telemetry ID display when 'Ignore instances' is set.

radio/src/targets/common/arm/stm32/stm32_softserial_driver.cpp
=> fix(pxx1): pulse length should be 8us

companion/src/modeledit/logicalswitches.cpp, companion/src/modeledit/logicalswitches.h
- Fix maximum allowed value for V3
- Update V3 displayed value when V2 changes.
=> fix(cpn) - Fix handling of logical switch 'Edge' parameters in Companion.

radio/src/gui/colorlcd/radio_setup.cpp
Add missing SET_DIRTY() call to the affected radio settings.
=> fix(color) - Some radio settings not triggering an update to the radio.yml file.

radio/util/generate_yaml.py, tools/generate-yaml.sh
I've extracted this fix by @raphaelcoeffic from from PR #2631 in the hope it can get merged in the near future so I don't have to keep manually applying it in order to regenerate the radio yaml definition files.
=> fix(build) - Fix for yaml generator on MacOS

radio/src/targets/common/arm/stm32/bluetooth_driver.cpp
Fixes https://github.com/EdgeTX/edgetx/issues/3376
- fixed logic error where txCompleted was reported as UART is still transmitting
=> fix: BT not working

companion/src/storage/labeled.cpp
=> fix(cpn) - load models into slot based on filename for B&W radios

radio/src/gui/colorlcd/view_statistics.cpp
=> fix(color) - Adjust portrait layout for debug view.

radio/util/generate_datacopy.py
Modified for clang 16, spelling attribute is no longer empty for anonymous structures but contains a descriptive string in brackets. Resolves the build error "Cannot handle non anonymous unions" from this script.
Fixes #
=> Win64 Companion build, fix for "Cannot handle non anonymous unions" exception

radio/src/pulses/afhds3.cpp
=> Fixed EL18 failsafe only have 4 channels functioning

radio/src/telemetry/spektrum.cpp
Fixes #3470 
Incorporate 2 fixes from main to use them for 2.8.3
Summary of changes:  
Spektrum GPS Fixes (#3290)
TextGen support (#3125)
=> (v2.8.3 Telemetry fix) Bring Spektrum Telemetry Changes from main to 2.8 branch (GPS+TextGen)

radio/src/targets/common/arm/stm32/rotary_encoder_driver.cpp
Fixes #3409 
Delay initial direction detection until the 2nd input from the rotary encoder.
Tested on QX7S and TX16 Mk2.
=> fix(radio) - Fix direction detection for rotary encoder on startup.

radio/src/pulses/afhds3.cpp, radio/src/telemetry/flysky_ibus.cpp, radio/src/telemetry/flysky_nv14.cpp
=> (v2.8) Fix the bug that some sensor values are displayed incorrectly

radio/src/translations/tts_cn.cpp, radio/src/translations/tts_cz.cpp, radio/src/translations/tts_da.cpp, radio/src/translations/tts_de.cpp, radio/src/translations/tts_en.cpp, radio/src/translations/tts_es.cpp, radio/src/translations/tts_fr.cpp, radio/src/translations/tts_hu.cpp, radio/src/translations/tts_it.cpp, radio/src/translations/tts_nl.cpp, radio/src/translations/tts_pl.cpp, radio/src/translations/tts_pt.cpp, radio/src/translations/tts_ru.cpp, radio/src/translations/tts_se.cpp, radio/src/translations/tts_sk.cpp
=> fix(radio) - Announce timer value as hours and minutes when played from special function.

radio/src/gui/colorlcd/module_setup.cpp
Suggested UI to refresh module window.
=> Refresh module UI if module data was updated.

radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp
=> fix(usart): possible endless loop in case some error flag is set but RXNE is not

radio/src/gui/common/stdlcd/radio_sdmanager.cpp, radio/src/sdcard.cpp, radio/src/sdcard.h, radio/src/translations.cpp, radio/src/translations.h, radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h
Reduce risk AND reduce flash size by 1928 bytes
=> [2.8] Formating the sd card is a bad idea with EdgeTX

radio/src/gui/colorlcd/model_gvars.cpp
=> fix(color) - Update GV value in header when precision changes.

radio/src/gui/colorlcd/model_gvars.cpp
Update title if unit is changed.
Update FM values if outside min/max range for GV.
Fixes #3561
=> fix(color) Fixes for GVAR edit page.

radio/src/gui/colorlcd/model_logical_switches.cpp, radio/src/gui/colorlcd/model_usbjoystick.cpp, radio/src/gui/colorlcd/preflight_checks.cpp, radio/src/gui/colorlcd/preview_window.h, radio/src/gui/colorlcd/radio_hardware.cpp, radio/src/gui/colorlcd/radio_theme.cpp
EdgeTX/libopenui#89 makes the number edit and text edit box height consistent with other UI elements.
This introduces some minor layout issues that are fixed in this PR.
This should be merged in conjunction with PR 89 from libopenui.
=> chore(color) - Fix minor layout issues arising from libopenui PR 89.

radio/src/translations/fr.h
continuation of the translation...
It's not over yet!
Fixes #
=> chore: Update French translations

companion/src/generaledit/generalsetup.cpp
=> feat(cpn): Add Hebrew voice to radio settings

companion/src/apppreferencesdialog.ui, companion/src/firmwares/opentx/opentxinterface.h
- add Finnish
- add Japanese
- add Taiwanese
- remove Russian
=> feat(cpn): update supported radio ui languages

companion/src/storage/yaml.cpp
=> fix(cpn): simulate from model only yml file

companion/src/storage/firmwareinterface.cpp, companion/src/storage/rlefile.cpp, companion/src/storage/rlefile.h, companion/src/updates/repodatamodels.cpp, companion/src/updates/repodatamodels.h, companion/src/updates/repometadata.cpp, companion/src/updates/reporeleases.h, companion/src/updates/updateinterface.cpp, companion/src/updates/updatenetwork.cpp
Cleaning up some compiler warnings for Companion.
=> chore(cpn) - Fix compiler warnings when building Companion.

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
Swedish translation catchup (PR #3619), both for Companion and radio
=>  Translation catchup #3619 (Swedish)

radio/src/audio.cpp, radio/src/targets/nv14/audio_spi_driver.cpp, radio/src/targets/nv14/board.cpp, radio/src/targets/nv14/hal.h
=> fix(el18): Audio output should be OFF if no audio playing

radio/src/gui/colorlcd/fullscreen_dialog.cpp, radio/src/gui/colorlcd/fullscreen_dialog.h
=> fix: flash progress text stuck at device reset

companion/src/firmwares/edgetx/yaml_expodata.cpp
=> fix(cpn) - Fix input offset value saved to YAML file by companion.

radio/src/targets/simu/opentxsimulator.cpp
Quickfix to match ADC refactor and companion widgets scaling
=> Fix libsimu analog inputs

radio/src/storage/yaml/yaml_datastructs_funcs.cpp
Fixes issue from switch-refactor PR where old style trim names are not loaded from model files.
=> fix(radio) - Fixes for radio and model YAML files.

radio/src/gui/212x64/model_setup.cpp, radio/util/hw_defs/legacy_names.py
Fix bug reported by @elecpower
Fix X9E pot/slider default
The fix for 128 is included in T20 PR
=> Fix centerbeep on 212 display

radio/src/thirdparty/Lua/src/linit.c
Fixes missing 'package' and 'string' libraries as reported on Discord.
=> fix(Lua): Enable 'package' Lua library.

radio/src/opentx.cpp
Handles the two MCU versions found in TLite
=> fix: TLite V2 is using another MCU

radio/src/targets/common/arm/stm32/stm32_exti_driver.cpp, radio/src/targets/horus/hal.h, radio/src/targets/horus/tp_gt911.cpp
Credits should go to @raphaelcoeffic  :)
=> chore: Move gt911 touch to generic EXTI driver

radio/src/gui/colorlcd/mpm_settings.cpp, radio/src/gui/colorlcd/mpm_settings.h
=> fix(color): Fix crash in MPM settings from PR #3637

radio/src/translations/jp.h
changes:
- update JP language
@pfeerick this is for #3802 and if possible to add in 2.9 too
=> JP language update for SD card full

companion/src/firmwares/boards.cpp, companion/src/firmwares/boards.h, companion/src/firmwares/moduledata.cpp, companion/src/firmwares/opentx/opentxinterface.cpp, companion/src/modelprinter.cpp, companion/src/simulation/CMakeLists.txt, companion/src/simulation/simulateduiwidget.h, companion/src/simulation/simulateduiwidgetEL18.cpp, companion/src/simulation/simulateduiwidgetEL18.ui, companion/src/simulation/simulatorwidget.cpp
Fixes #3247
- based on #3783 (so this PR will need to be rebased as necessary)
=> Companion and simulator support for Flysky EL18

radio/src/gui/colorlcd/CMakeLists.txt, radio/src/gui/colorlcd/afhds2a_settings.cpp, radio/src/gui/colorlcd/afhds2a_settings.h, radio/src/gui/colorlcd/afhds3_settings.cpp, radio/src/gui/colorlcd/afhds3_settings.h, radio/src/gui/colorlcd/module_setup.cpp, radio/src/pulses/modules_helpers.h
As requested I've split the flysky_settings files into separate AFHDS2 and AFHDS3 files.
=> Separate AFHDS2A and AFHDS3 UI settings.

radio/src/gui/colorlcd/channel_range.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp
And fix 'Channel Range' layout on portrait LCD.
=> Fix AFHDS3 conversion from old subtype value.

radio/src/mixer.cpp, radio/src/tests/mixer.cpp
=> fix: throttle invert and gimbal dead zone

radio/src/translations/fr.h
=> fix: translation for timer mode

radio/src/gui/colorlcd/model_gvars.cpp, radio/src/gui/colorlcd/special_functions.cpp, radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
=> fix(color): Use ACTIVE theme color for inputs, mixes, LS, GV and SF.

radio/src/keys.cpp
=> fix: only SHIFT should not trigger repeated events

radio/src/thirdparty/libopenui/src/menu.cpp, radio/src/thirdparty/libopenui/src/menutoolbar.cpp
Replace KEYS_GPIO_REG_PGUP with KEYS_GPIO_REG_PAGEUP.
=> fix(radio): Fix 'PAGE <' key in menu toolbar.

radio/src/gui/colorlcd/layouts/topbar_impl.cpp, radio/src/gui/colorlcd/widgets/widgets_container_impl.h, radio/src/storage/storage_common.cpp
In case widget name is 12 chars long.
=> chore(color): Use strAppend and strncmp on widgetName to avoid termination issues.

radio/src/logs.cpp
=> fix: logs not matching user stick mode

radio/src/pulses/afhds3.cpp, radio/src/pulses/afhds3_config.h
=> fix: AFHDS3 V0 receivers problem when switching between ibus-in/ibus-out/sbus output

companion/src/labels.cpp, companion/src/labels.h, companion/src/mdichild.cpp, companion/src/mdichild.h, companion/src/modelslist.cpp, companion/src/modelslist.h
Fixes #3960
- labels use sorted models list
- fix typo
- cosmetics
=> fix(cpn): model and labels lists sync

companion/src/translations/companion_de.ts, companion/src/translations/companion_pl.ts
=> fix(cpn): de translation

radio/src/gui/colorlcd/themes/etx_lv_theme.cpp, radio/src/thirdparty/libopenui/src/slider.cpp
=> fix(color): Fix for slider control blocking RTN key.

radio/src/gui/colorlcd/model_setup.cpp
Update model setup page to show if timers are active.
=> feat(color): Show active timers on model setup page.

radio/src/gui/128x64/model_special_functions.cpp, radio/src/gui/212x64/lcd.cpp, radio/src/gui/212x64/model_special_functions.cpp, radio/src/gui/colorlcd/special_functions.cpp, radio/src/gui/gui_common.cpp, radio/src/gui/gui_common.h, radio/src/storage/yaml/yaml_datastructs_funcs.cpp, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/he.h, radio/src/translations/it.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h
Fix timer not been saved a mixer source in YAML since adc refactor mega PR
Also fixes UI inconsistencies (see below)
This fixes #3946
MERGE NOTE: partner for https://github.com/EdgeTX/edgetx/pull/3956
=> fix: YAML timer handling

companion/src/firmwares/modeldata.h, companion/src/mdichild.cpp, companion/src/mdichild.h, companion/src/modelslist.cpp
=> feat(cpn): Identify new and changed models by italicising row

companion/src/firmwares/edgetx/yaml_customfunctiondata.cpp
=> fix(cpn): custom function filename length

companion/src/translations/companion_da.ts, radio/src/translations/da.h
Get danish translation up to date.
=> Translate for danish

radio/src/opentx.cpp, radio/src/tasks.cpp
Fixes #3882 
The startup code needs some attention and cleanup; but this should work for now.
Tested on TX16S and X7S.
=> feat(radio): Delay warnings until after splash screen finished

radio/src/gui/colorlcd/model_telemetry.cpp, radio/src/gui/colorlcd/radio_diagkeys.cpp, radio/src/gui/colorlcd/radio_sdmanager.cpp, radio/src/gui/colorlcd/view_text.cpp, radio/src/gui/common/stdlcd/radio_sdmanager.cpp, radio/src/lua/interface.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp, radio/src/targets/common/arm/stm32/f4/system_stm32f4xx.c, radio/src/telemetry/multi.cpp
Fixes some warnings generated by GCC 12.2 on MacOS.
=> chore(radio): Fix some compiler warnings when building firmware

radio/src/io/frsky_firmware_update.cpp
- Clear RX buffer before waiting for signature
=> fix: iXJT firmware update

radio/src/pulses/afhds3.cpp, radio/src/pulses/afhds3_transport.cpp
Reduce console noise when running simulator.
=> chore(radio): Cleanup TRACE output for AFHDS3 module.

radio/src/gui/colorlcd/screen_user_interface.cpp, radio/src/gui/colorlcd/screen_user_interface.h
Fixes issue where background color does not update on the Screen Settings -> User Interface page when the theme is changed.
=> fix(color): Update background color on user interface page when theme is changed.

radio/src/gui/colorlcd/screen_user_interface.cpp
Fix broken theme change from PR #4078
=> fix(color): Ensure all items are updated on theme change in user interface settings.

radio/src/targets/common/arm/stm32/vs1053b.cpp
Fixes issue introduced in #3957.
=> fix: VS1053b initialisation on NV14/EL18

radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
Fixes #4109 
Change background color, knob color and knob size.
=> fix(color): Make toggle switch UI consistent with other UI elements

radio/src/gui/colorlcd/radio_trainer.cpp
=> fix(color): Remove unnecessary scrolling on trainer setup page.

companion/src/translations/companion_da.ts, radio/src/translations/da.h
=> Update Danish translation

radio/util/hw_defs/switch_config.py
=> fix(b&w): Fix radio UI display for switches on X9D, X9D+ and X9D+2019.

radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/he.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h
Remove unused entries and add missing entries to various translation files.
=> chore(radio): Cleanup translation files.

companion/src/translations/companion_ru.ts
Fixes # translation
Summary of changes: Added Russian lines
=> chore(translation): Russian translation updates for Companion

radio/src/translations/it.h
Summary of changes: fix missing terminating " character.
=> fix(translation): Missing " for IT translation

radio/src/lua/interface.cpp, radio/src/mixer.cpp
Also fixes an issue where a GF that runs a Lua script would still run even when the GF feature was turned off.
=> feat(radio): Disable Special Functions when feature turned off

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
Updates and clean up of Swedish translations for firmware and Companion
=> chore(translation): Updated SE translations

radio/src/gui/colorlcd/special_functions.cpp, radio/src/targets/nv14/bootloader/boot_menu.cpp, radio/src/translations.cpp, radio/src/translations.h, radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/he.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h
Enable or disable SF/GF without having to enter the edit page.
=> feat(color): Add Enable/Disable option to SF/GF popup menu

radio/src/cli.cpp, radio/src/targets/common/arm/stm32/diskio_sdio.cpp
=> fix: Allow compile with DEBUG=Y

radio/src/targets/nv14/CMakeLists.txt, radio/src/targets/nv14/hal.h, radio/src/targets/nv14/touch_driver.cpp
I tested in my EL18 and works fine.
=> chore: Update NV14/EL18 touch driver to generic EXTI driver

radio/src/drivers/frftl.cpp, radio/src/drivers/frftl.h, radio/src/hal/fatfs_diskio.cpp, radio/src/hal/storage.cpp, radio/src/hal/storage.h, radio/src/targets/common/arm/stm32/bootloader/CMakeLists.txt, radio/src/targets/common/arm/stm32/bootloader/bin_files.cpp, radio/src/targets/common/arm/stm32/bootloader/boot.cpp, radio/src/targets/common/arm/stm32/diskio_spi_flash.cpp, radio/src/targets/common/arm/stm32/diskio_spi_flash.h, radio/src/targets/common/arm/stm32/spi_flash.cpp, radio/src/targets/common/arm/stm32/spi_flash.h, radio/src/targets/horus/CMakeLists.txt, radio/src/targets/horus/hal.h, radio/src/targets/nv14/CMakeLists.txt, radio/src/targets/nv14/hal.h
- New wear levelling driver
- New SPI flash driver
On behalf of @richardclli 😋
=> feat: SPI flash driver

radio/src/gui/colorlcd/themes/etx_lv_theme.cpp, radio/src/thirdparty/libopenui/src/slider.cpp, radio/src/thirdparty/libopenui/src/slider.h
=> feat(color): Slider styling and tick marks.

radio/src/thirdparty/libopenui/src/button_matrix.cpp
=> fix(color): Keep last selected button focused within Button Matrix

radio/src/dataconstants.h, radio/src/datastructs_private.h, radio/src/storage/yaml/CMakeLists.txt, radio/src/storage/yaml/yaml_datastructs_t12.cpp, radio/src/storage/yaml/yaml_datastructs_x12s.cpp, radio/src/storage/yaml/yaml_datastructs_x7.cpp, radio/src/storage/yaml/yaml_datastructs_x9d.cpp, radio/src/storage/yaml/yaml_datastructs_x9e.cpp, radio/src/storage/yaml/yaml_datastructs_x9lite.cpp, radio/src/storage/yaml/yaml_datastructs_x9lites.cpp, radio/src/storage/yaml/yaml_datastructs_xlite.cpp, radio/src/storage/yaml/yaml_datastructs_xlites.cpp
Fixes https://github.com/EdgeTX/edgetx/issues/4059#issuecomment-1741103229
- storage config is invalid for iFlight Commando8 on 2.9
=> fix: Add missing yaml storage config for iFlight Commando8

companion/src/modeledit/setup.cpp
=> fix(cpn): Add back failsafe settings for protocols that support

radio/src/gui/128x64/lcd.cpp, radio/src/gui/212x64/lcd.cpp
Use correct offset for DBLSIZE language font characters.
Fixes #4193
=> fix(bw): Use correct offset for DBLSIZE language font

companion/src/translations/companion_ru.ts
=> chore(translation): Add Russian Companion translations 🇷🇺

companion/src/translations/companion_da.ts, radio/src/translations/da.h
Update Danish translations for radio and companion
=> Update danish translations radio/companion

.gitmodules, cmake/FetchYamlCpp.cmake, companion/src/CMakeLists.txt, companion/src/firmwares/CMakeLists.txt
=> chore(cpn): bump yaml-cpp to version 0.8.0

radio/src/gui/colorlcd/menu_model.cpp, radio/src/gui/colorlcd/menu_model.h, radio/src/gui/colorlcd/menu_radio.cpp, radio/src/gui/colorlcd/menu_radio.h, radio/src/gui/colorlcd/menu_screen.cpp, radio/src/gui/colorlcd/menu_screen.h, radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/model_select.h, radio/src/gui/colorlcd/page.cpp, radio/src/gui/colorlcd/page.h, radio/src/gui/colorlcd/tabsgroup.cpp, radio/src/gui/colorlcd/tabsgroup.h, radio/src/gui/colorlcd/view_channels.cpp, radio/src/gui/colorlcd/view_channels.h, radio/src/gui/colorlcd/view_main.cpp, radio/src/gui/colorlcd/view_main.h, radio/src/thirdparty/libopenui/src/window.cpp, radio/src/thirdparty/libopenui/src/window.h
Fixes #169 
As suggested in #4111, this PR extends the key navigation changes.
- Add TELE long press (open Channel Monitor)
- SYS, MDL and TELE keys can navigate freely between Main View, Radio Setup, Model Setup, Channel Monitor, Manage Models and Screen Setup pages.
=> feat(color): Improved hardware key navigation.

radio/src/gui/212x64/model_setup.cpp, radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/colorlcd/radio_sdmanager.cpp, radio/src/gui/colorlcd/widgets/modelbmp.cpp, radio/src/gui/common/stdlcd/radio_sdmanager.cpp, radio/src/lua/api_model.cpp, radio/src/storage/modelslist.cpp
Fixes #4201
Fix truncation of model bitmap name on color radios.
Cleanup code.
=> fix(color): Bitmap name truncation if exactly 14 characters long

radio/src/translations/ru.h
=> chore: Updates to Russian translations 🇷🇺

radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
Another change from the LVGL 8.3 PR that was not quite right.
=> fix(color): Theme change not updating all colors

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
Summary of changes: new and revised SE translations for firmware and Companion
=> chore: SE firmware and companion translation updates

companion/src/simulation/simulatorwidget.cpp
Extra trims set to T7/T8 on TX16S after PR #4227
Fixes: #4300
=> fix(cpn): Incorrect T5/T6 trims on TX16S

radio/src/mixer.cpp, radio/src/storage/storage_common.cpp
=> fix(color): Improvements to NV14/EL18 dead zone logic.

radio/src/targets/nv14/hal.h
Added potentiometer gimbal support to NV14/EL18
=> fest(nv14/el18): Add potentiometer gimbal support

radio/src/gui/colorlcd/draw_functions.cpp, radio/src/lua/api_colorlcd.cpp, radio/src/strhelpers.cpp, radio/src/strhelpers.h, radio/src/thirdparty/libopenui/src/bitmapbuffer.cpp, radio/src/thirdparty/libopenui/src/bitmapbuffer.h
Remove unused code.
Move 'formatNumberAsString' function to strhelpers.
=> chore(color): Cleanup bitmap code.

radio/src/gui/colorlcd/radio_spectrum_analyser.cpp
Fixes layout issue where the frequency selection button gets sized too tall.
=> fix(color): Spectrum analyser layout is incorrect.

radio/src/audio.h
Fixes #4397 
Fix issue introduced in PR #3784
=> fix(radio): BG Music special function does not work.

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
Summary of changes: updated SE translations for Companion and firmware
=> chore: Updated SE translations

tools/setup_buildenv_ubuntu20.04.sh, tools/setup_buildenv_ubuntu22.04.sh
Requires  #4409
Tested building firmware, simu and companion
Will add to wiki once merged
This closes #3154
=> feat: add Ubuntu 22.04 support script

radio/src/targets/pl18/lcd_driver.cpp, radio/src/targets/pl18/lcd_driver.h
The LCD detection not working properly after DMA2D changes and fixed in this PR
=> fix(pl18): Fixed LCD detection code

radio/src/translations/cz.h
I got an email from Petr Faltus asking for this change. Which seems to be reasonable. He tested the change on TX16S.
=> chore(translation): CZ "Manage Models"

companion/src/simulation/simulateduiwidgetBoxer.cpp, radio/src/gui/common/stdlcd/popups.cpp, radio/src/targets/simu/opentxsimulator.cpp, radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/he.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/ru.h, radio/src/translations/se.h, radio/src/translations/tw.h
Fixes
- Swapped PAGE >, PAGE < on Boxer
- Simu rotary encoder inversion not matching radios
- Scrolling in popup menus not going in same direction as vertical navigation
=> fix(b&w): Various rotenc. inversion bugs on radio and simu

radio/src/thirdparty/libopenui/src/filechoice.cpp
Unix and MacOS dot files are filtered out from the SD card browser; but not from the file chooser popup menu,
=> fix(color): Filter Unix/MacOS dot files from file chooser popup menu.

radio/src/targets/common/arm/stm32/stm32_pulse_driver.cpp
=> fix(soft-serial): timer toggle mode would skip first period

companion/src/translations/companion_cs.ts, companion/src/translations/companion_da.ts, companion/src/translations/companion_de.ts, companion/src/translations/companion_en.ts, companion/src/translations/companion_es.ts, companion/src/translations/companion_fi.ts, companion/src/translations/companion_fr.ts, companion/src/translations/companion_he.ts, companion/src/translations/companion_it.ts, companion/src/translations/companion_ja.ts, companion/src/translations/companion_nl.ts, companion/src/translations/companion_pl.ts, companion/src/translations/companion_pt.ts, companion/src/translations/companion_ru.ts, companion/src/translations/companion_sv.ts, companion/src/translations/companion_zh_CN.ts, companion/src/translations/companion_zh_TW.ts
Revises line numbers for code and adds any missing "unfinished" translation strings
=> chore(cpn): QtLinguist translation files refresh

companion/src/translations/companion_ru.ts
Fix 6p.
Fixes https://github.com/EdgeTX/edgetx/issues/4421
=> fix(cpn): 6-position translation for RU

radio/src/storage/modelslist.cpp
Suggested by @ulfhedlund in #4122
=> feat(color): Make model sorting case insensitive

radio/src/audio.h
PL18 has intermittent audio playback, just try to fine tune to see if anything helps
=> fix(pl18): Audio playback hiccup problem when SPI flash is writing

radio/src/targets/common/arm/stm32/diskio_sdio.cpp
=> fix(sdio): Check card state after each block written

radio/src/targets/taranis/hal.h
Approved by Radiomaster
Fixes #4460
=> fix: Invert MT12 T5 direction

radio/src/targets/pl18/battery_driver.cpp, radio/src/targets/pl18/board.cpp
Added charging LED animation for PL18 and PL18EV.
LCD display will draw a lot of power and make charging slow.  Making display off during charging cannot observe charging status easily.  LED is a better choice with much power requirement and nice charging status animation.
=> feat(pl18): Charging LED animation

companion/src/translations/companion_da.ts
=> chore(translation): Correct notice of Simulator import settings for DA

radio/src/targets/horus/usb_descriptor.h, radio/src/targets/taranis/usb_descriptor.h
=> chore: usb names

radio/src/gui/colorlcd/model_select.cpp
Delay load model image & text to improve performance of Manage Models page.
=> fix(color): Slow performance of Manage Models page.

radio/src/gui/colorlcd/model_gvars.cpp, radio/src/gui/colorlcd/popups.cpp, radio/src/gui/colorlcd/popups.h, radio/src/gvars.cpp, radio/src/gvars.h, radio/src/main.cpp, radio/src/opentx.cpp
Match existing B&W functionality.
Fixes #4511
=> feat(color): Add 'popup' option to GVARs for color LCD radios.

companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/generalsettings.h, companion/src/generaledit/generalsetup.cpp, companion/src/generaledit/generalsetup.h, companion/src/generaledit/generalsetup.ui
Update Companion to support new settings added in PR's #4524 and #4532
=> feat(cpn): add support for new 'Manage Models' settings

radio/src/translations/jp.h
Since a display bug was confirmed in jp.h of v2.9.3, we have reviewed it again based on en.h.
=> Japanese: Correction of display defects identified in v2.9.3

radio/src/gui/128x64/model_special_functions.cpp
Fixes #4616
Reloads lua scripts on change
=> fix: load LUA SF after selection

radio/src/gui/128x64/model_flightmodes.cpp
Fixes #4615
Now automatically adapt to trim number
=> fix: MT12 ghost trim entries

radio/src/translations/jp.h
There was an omission in the translation, so we are updating it.
=> Update Japanese translations

radio/src/switches.cpp
Fixes #4587 
Add delay on state change of delta LS functions to ensure activation is captured.
=> fix(radio): Delta Logical Switch functions may not work consistently for all sources.

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
Summary of changes: SE translation updates for firmware and Companion
=> chore: updates to SE translations

radio/src/thirdparty/libopenui/src/menutoolbar.cpp
For example, open the Model Setup --> Throttle page and tap the Source button.
The Source select popup shows an entry for the group 'Other' that contains no options.
=> fix(color): Switch and source select popup may show buttons for empty groups.

companion/src/translations/companion_ja.ts
Based on the latest English translation file "companion_en.ts", the Japanese has been modified.
We apologize that we have not been able to support this project for quite a while.
=> Update Japanese translation (Companion maintenance)

companion/src/firmwares/boards.cpp, companion/src/firmwares/boards.h, companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/ersky9x/ersky9xeeprom.cpp, companion/src/firmwares/ersky9x/ersky9xeeprom.h, companion/src/firmwares/generalsettings.h, companion/src/firmwares/opentx/opentxeeprom.cpp, companion/src/generaledit/generalsetup.cpp
=> chore(cpn): Align general settings naming to radio

radio/src/lua/api_model.cpp
=> fix(lua): add 'repetition' property to getCustomFunction and setCustomFunction tables

radio/src/gui/common/stdlcd/model_mixes.cpp
Fixes #4739
Summary of changes: fix an issue introduced in #3999
=> fix: issue in copy in BW mixer screen

companion/src/translations/companion_da.ts
=> fix(cpn): DK wrong translation

radio/src/translations/pt.h
Surface radio stick name on air, plus some tweaks on telemetry and USB joystick.
=> chore: translation updates for PT

companion/src/firmwares/edgetx/yaml_modeldata.cpp
Fixes #4768 part 2 adding model name to version check message
=> fix(cpn): model semver check inc model name in warning msg

radio/src/gui/128x64/view_telemetry.cpp, radio/src/gui/212x64/view_telemetry.cpp
=> fix(bw): display GVar name if exist in telemetry screen

companion/src/constants.h, companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/edgetx/yaml_modeldata.cpp
=> chore(cpn): add Accept and Decline buttons to yaml decode unsupported versions dialogs

radio/src/gui/colorlcd/layouts/trims.cpp, radio/src/gui/colorlcd/layouts/trims.h, radio/src/gui/colorlcd/view_main_decoration.cpp, radio/src/gui/colorlcd/view_main_decoration.h
Fixes #4808
Looks like my quick fix for #4777 was not quite right - sorry about that.
=> fix(color): trims are still displayed even when turned off in view settings.

radio/src/translations/pt.h
Many revisions and added special characters
Needs #4806 merged
=> chore:  PT translation update with special characters

radio/src/translations/pt.h
Quick menu label was broken because long strings.
Plus some minor tweaks
=> fix(pt): broken quick menu, minor tweaks

radio/src/CMakeLists.txt, radio/src/targets/common/arm/CMakeLists.txt, radio/src/targets/common/arm/stm32/CMakeLists.txt, radio/src/targets/common/arm/stm32/bootloader/CMakeLists.txt, radio/src/targets/common/arm/stm32/sdcard_spi.cpp
Please somebody comes with a better fix :)
Fixes #4707
=> fix: allow compilation of BW radio when DEBUG=Y

radio/src/targets/common/arm/stm32/usbd_desc.c, radio/src/targets/common/arm/stm32/usbd_desc.h
remove unused USBD_StringSerial from usbd_desc.c
=> chore: remove unused USBD_StringSerial

radio/util/hw_defs/lua_keys.jinja
=> fix(lua): add missing EVT_PAGEDN_xxx events for Lua

radio/src/targets/common/arm/stm32/usbd_hid_joystick.c
general code review of radio/src/targets/common/arm/stm32/usbd_hid_joystick.c
Fixes #4724
Fixes #4725
- code de-duplication
- LOBYTE / HIBYTE coding ensuring that more complex joysticks can implemented -not yet critical for main branch but already encounted in other branches
=> fix(radio): usb joystick descriptor, unusable joystick axis 

radio/src/gui/colorlcd/layouts/topbar_impl.cpp, radio/src/gui/colorlcd/topbar.h, radio/src/gui/colorlcd/widgets/radio_info.cpp
Adjust topbar widget spacing so all widgets are equal size on portrait layouts.
Make rightmost widget slightly wider on portrait layouts.
=> feat(color): adjust top bar widget sizes.

radio/src/gui/colorlcd/layouts/sliders.cpp
Fix the Github build error in the Mac version of Companion.
=> fix(cpn): Mac Companion build error on Github.

radio/src/gui/colorlcd/radio_diagkeys.cpp
Use theme color on Hardware Keys test page.
Fixes #4868
=> fix(color): keys test page does not use theme color.

radio/src/pulses/pxx2.cpp, radio/src/pulses/pxx2.h, radio/src/telemetry/frsky_pxx2.cpp
As recommended by @bsongis on discord
=> fix: pxx2 can transport 24 chans

radio/src/gui/colorlcd/list_line_button.h, radio/src/gui/colorlcd/model_mixes.cpp
=> fix(color): mixes list view not resizing when mixer monitors enabled

radio/src/lua/api_filesystem.cpp, radio/src/lua/api_general.cpp, radio/src/targets/simu/simufatfs.cpp
Resolves #4847
Also fixes bug introduced in https://github.com/EdgeTX/edgetx/pull/4288
=> feat(lua): add 'mkdir'  and 'rename' functions

radio/src/gui/128x64/radio_setup.cpp, radio/src/gui/common/stdlcd/features.h, radio/src/opentx.cpp, radio/src/translations.cpp, radio/src/translations.h
=> chore: remove unused PWM_BACKLIGHT define

radio/src/thirdparty/libopenui/src/bitmapbuffer_draw_extra.cpp
Fix crash in lcd.drawFilledCircle Lua function.
=> fix(crash): crash in LibGUI widget in fullscreen mode.

companion/src/datamodels/compounditemmodels.cpp, companion/src/firmwares/sensordata.cpp, companion/src/firmwares/sensordata.h, companion/src/modeledit/telemetry.cpp
=> feat(cpn): only use vario sensors for vario source

radio/src/translations/ru.h
Add RU translation for PR #4845
=> chore(color): RU translation for Radio Info widget.

radio/src/translations/ua.h
- catchup UA translations for #4697 and #4845 
Second commit is for 2.10 also
=> chore: updates for UA

radio/src/CMakeLists.txt, radio/src/opentx.cpp
Allow Frankenbuild.
Result of a discusion with Gregor on Discord
=> feat: compile option to disable MCU check

radio/src/gui/212x64/lcd.cpp
Issue in #5000 lacks details, but I was able to find an issue in the area described
This fixes : #5000
For 2.10.1 too please :)
=> fix(bw212): wrong source string display

companion/src/firmwares/generalsettings.cpp, companion/src/firmwares/opentx/opentxeeprom.cpp, radio/util/hw_defs/legacy_names.py, radio/util/hw_defs/pot_config.py
Match declaration with OTX initial source
Fixes #5006
=> fix(x9e): missing F3/F4 pots, slider hwdef changes

radio/src/targets/common/arm/stm32/usbd_hid_joystick.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/CompositeBuilder/Inc/usbd_composite_builder.h, radio/src/thirdparty/STM32_USB_Device_Library/Class/CompositeBuilder/Src/usbd_composite_builder.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/CustomHID/Inc/usbd_customhid.h, radio/src/thirdparty/STM32_USB_Device_Library/Class/CustomHID/Src/usbd_customhid.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/CustomHID/Src/usbd_customhid_if_template.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/HID/Inc/usbd_hid.h, radio/src/thirdparty/STM32_USB_Device_Library/Class/HID/Src/usbd_hid.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc_data.h, radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc_scsi.h, radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c, radio/src/thirdparty/STM32_USB_Device_Library/Core/Inc/usbd_core.h, radio/src/thirdparty/STM32_USB_Device_Library/Core/Inc/usbd_def.h, radio/src/thirdparty/STM32_USB_Device_Library/Core/Src/usbd_core.c, radio/src/thirdparty/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
update STM32_USB_Device_Library to the current STMicroelectronics/stm32_mw_usb_device@7b5e6886d2f11ad15d2b46364e8a96984358f639
=> chore(radio): stm32_mw_usb_device v2.11.2 catchup

radio/util/hw_defs/switch_config.py
Fix issue reported on Discord
@pfeerick also for 2.10.1 please
=> fix: Jumper T12 switches

radio/src/targets/common/arm/stm32/diskio_sdio.cpp
=> feat: add debug for SDIO switch from 1bit to 4bits

radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/model_select.h
2.11 version of #5048 plus fix for RTN key not working when creating a new label.
=> fix(color): selected label, model list not correctly updating in single select mode

fw.json
=> chore: add missing t15

companion/src/firmwares/edgetx/yaml_generalsettings.cpp
=> fix(cpn): global functions yaml decode

radio/src/gui/colorlcd/listbox.cpp, radio/src/gui/colorlcd/listbox.h, radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
=> fix(color): adjust layout of model labels list to reduce text overlap

radio/src/targets/taranis/hal.h
=> chore: allow X7 hardware debugging

radio/src/gui/128x64/model_logical_switches.cpp
Fixes issue when editing a LS and changing the function, the V1 and V2 values may briefly display the wrong value.
Add long press of ENTER key to allow opening the LS popup menu in the list view (for consistency with other pages).
=> fix(bw128): improve logical switch navigation & editing

radio/src/gui/colorlcd/mixer_edit_adv.cpp
=> fix(color): slow prec not updating fields when changing precision

companion/src/simulation/simulatorwidget.cpp
Handle index shift introduced by #4722
=> fix(simulator): mapping of labels to controls

companion/src/multimodelprinter.cpp
- offset index + 1
- housekeeping
=> fix(cpn): model print flight mode trim labels

radio/src/lua/api_general.cpp, radio/util/hw_defs/lua_inputs.jinja
Fixes #5100 
Another victim of the ADC refactor PR.
=> fix(lua): getFieldInfo() not returning switch info

radio/src/lv_conf.h
=> fix(cpn): windows build failing because sbrk does not exist on mingw

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
Various SE translations updates and fixes for firmware and Companion
=> chore(translation): update SE for firmware and companion

companion/src/generaledit/calibration.cpp, companion/src/mdichild.cpp, companion/src/updates/repobuild.h, companion/src/updates/repogithub.h, companion/src/updates/updatecloudbuild.cpp
Warnings generated when building on MacOS.
=> chore(cpn): cleanup build warnings

companion/src/modeledit/setup.cpp, companion/src/modelprinter.cpp, companion/src/simulation/joystickdialog.cpp
Arising from index shift in #4722:
- model printer
- throttle trim source
- joystick configuration
=> fix(cpn): more fixes to RawSource calls

radio/src/gui/128x64/model_custom_scripts.cpp, radio/src/gui/128x64/model_display.cpp, radio/src/gui/128x64/model_failsafe.cpp, radio/src/gui/128x64/model_outputs.cpp, radio/src/gui/128x64/model_select.cpp, radio/src/gui/128x64/model_setup.cpp, radio/src/gui/128x64/model_special_functions.cpp, radio/src/gui/128x64/radio_calibration.cpp, radio/src/gui/212x64/model_custom_scripts.cpp, radio/src/gui/212x64/model_display.cpp, radio/src/gui/212x64/model_logical_switches.cpp, radio/src/gui/212x64/model_outputs.cpp, radio/src/gui/212x64/model_select.cpp, radio/src/gui/212x64/model_setup.cpp, radio/src/gui/212x64/model_special_functions.cpp, radio/src/gui/212x64/radio_calibration.cpp, radio/src/gui/colorlcd/radio_sdmanager.cpp, radio/src/gui/common/stdlcd/calibration.cpp, radio/src/gui/common/stdlcd/model_curves.cpp, radio/src/gui/common/stdlcd/model_inputs.cpp, radio/src/gui/common/stdlcd/model_mixes.cpp, radio/src/gui/common/stdlcd/radio_sdmanager.cpp, radio/src/gui/navigation/navigation_9x.cpp, radio/src/gui/navigation/navigation_x7.cpp, radio/src/gui/navigation/navigation_x9d.cpp, radio/src/gui/navigation/navigation_xlite.cpp, radio/src/opentx.h
=> chore(bw): remove unused READ_ONLY and READ_ONLY_UNLOCKED macros

radio/src/gui/212x64/model_telemetry.cpp, radio/src/gui/212x64/view_main.cpp
Fixes https://github.com/EdgeTX/edgetx/issues/4797
- fix for x9e/x9dp main view whereby sliders not being drawn (another ADC refactor victim)
- add https://github.com/EdgeTX/edgetx/pull/4565 for bw212
=> fix(bw212): main view sliders, omitted sensor count display

companion/src/firmwares/opentx/opentxeeprom.cpp
=> fix(cpn): binary import of multi position switches

radio/src/gui/colorlcd/file_preview.cpp, radio/src/gui/colorlcd/model_select.cpp, radio/src/thirdparty/libopenui/src/bitmapbuffer.cpp, radio/src/thirdparty/libopenui/src/bitmapbuffer.h, radio/src/thirdparty/libopenui/src/bitmapbuffer_fileio.cpp, radio/src/thirdparty/libopenui/src/static.cpp, radio/src/thirdparty/libopenui/src/static.h
The model select page can be slow to scroll when there are a lot of models / images.
=> fix(color): slow scrolling on model select page

radio/src/gui/colorlcd/tabsgroup.cpp, radio/src/gui/colorlcd/tabsgroup.h, radio/src/thirdparty/libopenui/src/static.cpp
Delete page tab objects when exiting setup pages.
=> fix(color): memory leak in setup pages

companion/src/modeledit/logicalswitches.cpp
=> fix(cpn): logical switch move units refresh

companion/src/comparedialog.cpp, companion/src/comparedialog.h, companion/src/mdichild.cpp, companion/src/modelslist.cpp, companion/src/modelslist.h
=> feat(cpn): add filenames to model compare

radio/src/targets/common/arm/stm32/pwr_driver.cpp
- 2.10 version of #5190 GPIO code
=> chore: 2.10 version of #5190 GPIO code

radio/src/gui/colorlcd/model_setup.cpp, radio/src/thirdparty/libopenui/src/choice.cpp, radio/src/thirdparty/libopenui/src/choice.h, radio/src/thirdparty/libopenui/src/filechoice.cpp, radio/src/thirdparty/libopenui/src/menutoolbar.cpp
Fixes a few issues with the file chooser from recent PR's:
- wrong icon on the file chooser button
- fix portrait layout dialog width
- fix file filter not checking all possible values
=> fix(color): issues with file chooser

radio/src/thirdparty/libopenui/src/choice.cpp
=> fix(color): choice button being skipped when using rotary encoder

radio/src/gui/colorlcd/special_functions.cpp, radio/src/thirdparty/libopenui/src/choice.cpp
Side effect of changes in PR #5201
=> fix(color): crash when changing 'Mode' for 'Adjust' SF

radio/src/gui/128x64/widgets.cpp
=> chore: remove useless editGVarFieldValue

radio/src/lua/api_general.cpp
=> Save telemetry sensor generated by LUA setTelemetryValue()

radio/src/gui/colorlcd/view_text.cpp, radio/src/gui/colorlcd/view_text.h, radio/src/opentx.cpp
=> fix(color): block radio startup until checklist is closed.

radio/src/gui/colorlcd/lcd.cpp
Fixes EL18/NV14 battery charging display.
=> fix(el18): restore direct drawing capability for battery charging display

radio/src/targets/nv14/hal.h
Fixes issue introduced in #5023.
=> fix: NV14/EL18 S.PORT TX DMA handler

radio/src/boards/generic_stm32/CMakeLists.txt, radio/src/boards/generic_stm32/i2c_bus.cpp, radio/src/drivers/pca95xx.cpp, radio/src/drivers/pca95xx.h, radio/src/hal/i2c_driver.h, radio/src/targets/common/arm/stm32/lsm6ds_driver.cpp, radio/src/targets/common/arm/stm32/stm32_i2c_driver.cpp, radio/src/targets/common/arm/stm32/stm32_i2c_driver.h, radio/src/targets/horus/cst8xx_driver.cpp, radio/src/targets/horus/hal.h, radio/src/targets/horus/tp_gt911.cpp, radio/src/targets/nv14/hal.h, radio/src/targets/nv14/touch_driver.cpp, radio/src/targets/pl18/hal.h, radio/src/targets/pl18/touch_driver.cpp, radio/src/targets/taranis/eeprom_driver.cpp, radio/src/targets/taranis/hal.h, radio/src/targets/taranis/volume_i2c.cpp
Based on #5228, so merge after that.
=> feat: generic I2C and PCA95xx driver

radio/src/targets/taranis/CMakeLists.txt
Fixes #5261
Just double checking INTERNAL_MODULE_SERIAL _is_ correct here?
=> fix: configure default internal module for XJT_PXX1

radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/colorlcd/radio_setup.cpp
Fix colorlcd compilation when HELI is disabled
=> fix: colorlcd compilation with DHELI=NO

radio/src/hal/gpio.h, radio/src/targets/common/arm/stm32/diskio_sdio.cpp, radio/src/targets/common/arm/stm32/stm32_gpio.cpp
Fixes #5259
- reinstate GPIO init as they were before (pull-ups, speed very high)
- better DMA buffer check
=> fix: SDIO issues after H7 support

radio/src/boards/generic_stm32/CMakeLists.txt, radio/src/targets/horus/CMakeLists.txt, radio/src/targets/nv14/CMakeLists.txt, radio/src/targets/pl18/CMakeLists.txt, radio/src/targets/taranis/CMakeLists.txt
No user changes, based on @raphaelcoeffic comments in #5272
=> chore: ws2812 support to comply with #5232 style

radio/util/hw_defs/legacy_names.py
Fixes #5330
Summary of changes: add missing lua names for axis
=> fix: lua axis name for T15, T14, T12Max

radio/src/gui/colorlcd/curveedit.cpp, radio/src/gui/colorlcd/curveedit.h
On the T15 the curve preview width is too big causing layout issues when editing curves.
=> fix(color): T15 curve preview, cleanup curve edit layout

radio/src/tests/lua.cpp
Simple test to ensure legacy_names.py includes some needed information
=> chore: add legacy_names to gtest

radio/src/thirdparty/libopenui/src/choice.cpp, radio/src/thirdparty/libopenui/src/choice.h
=> fix(color): restore CHANGED event handler for Choice class

radio/src/hal/module_port.cpp, radio/src/hal/serial_driver.h, radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp
=> fix(el18): uart auto oversampling calculation (v2.10)

radio/src/gui/colorlcd/controls/fm_matrix.cpp
=> chore(color): use padding values for flight mode button matrix layout

radio/src/gui/colorlcd/libui/bitmapbuffer.cpp, radio/src/gui/colorlcd/libui/bitmapbuffer.h, radio/src/gui/colorlcd/libui/bitmapbuffer_draw_extra.cpp, radio/src/lua/lua_widget.cpp
Last round of cleanup was a bit too aggressive 😄
=> fix(color): flickering Lua widgets when full screen is refreshed

radio/src/gui/colorlcd/model/model_outputs.cpp
=> feat(color): add confirmation to 'Add all Trims to subtrims' button

radio/src/gui/colorlcd/libui/bitmapbuffer_fileio.cpp, radio/src/gui/colorlcd/radio/radio_sdmanager.cpp, radio/src/gui/colorlcd/radio/radio_sdmanager.h
Fixes #4166 
Make UI more responsive when scrolling through file list.
=> feat(color): delay load images in SD browser,  show 'Loading...' msg

radio/src/datastructs.h, radio/src/gui/colorlcd/mainview/widgets_container.h, radio/src/storage/yaml/yaml_datastructs_nv14.cpp, radio/src/storage/yaml/yaml_datastructs_pl18.cpp, radio/src/storage/yaml/yaml_datastructs_t15.cpp, radio/src/storage/yaml/yaml_datastructs_x10.cpp, radio/src/storage/yaml/yaml_datastructs_x12s.cpp
Fixes #1840 
Prerequisite for #1095
=> feat(color): allow up to 10 widget options.

radio/src/gui/colorlcd/mainview/view_statistics.cpp
=> fix(color): use TIMERS value instead of assuming always 3

radio/src/gui/common/stdlcd/radio_trainer.cpp
Adjust page layout for < 4 sticks.
=> fix(bw): two blank lines where cursor disappears on MT12 trainer page

radio/src/gui/colorlcd/CMakeListsLVGL.txt, radio/src/gui/colorlcd/lv_conf.h, radio/src/lua/api_colorlcd_lvgl.cpp, radio/src/lua/lua_lvgl_widget.cpp, radio/src/lua/lua_lvgl_widget.h
Before I start seriously trying to document the API.
=> feat(lua): add lvgl.page(), add optional parent property to lvgl.build()

radio/src/boards/generic_stm32/rgb_leds.h, radio/src/targets/common/arm/stm32/stm32_pulse_driver.cpp, radio/src/targets/common/arm/stm32/stm32_ws2812.cpp, radio/src/targets/common/arm/stm32/stm32_ws2812.h, radio/src/targets/pl18/board.cpp, radio/src/targets/taranis/board.cpp
... and fix pulse driver to support H7.
=> feat: add color formats to WS2812 driver

radio/src/targets/common/arm/stm32/stm32_spi.cpp
The issue was introduced in #5425.
Fixes #5432
=> fix: SPI word transfer

radio/src/gui/navigation/navigation_x7.cpp, radio/src/gui/navigation/navigation_x9d.cpp, radio/src/gui/navigation/navigation_xlite.cpp
Fixes #5434 
Move check for changed value to after popup menu is processed.
=> fix(bw): switch & source changes may not be saved to the SD card.

radio/src/gui/colorlcd/model/input_edit.cpp, radio/src/gui/colorlcd/model/input_edit.h, radio/src/gui/colorlcd/model/model_inputs.cpp
- Fix input edit preview refresh when active line changes.
- Fix missing switch display on input list.
=> fix(color):  input edit preview refresh, missing switch display

radio/src/dataconstants.h, radio/src/gui/gui_common.cpp, radio/src/gui/gui_common.h
Refactor the code for the various isSourceAvailable functions to remove code duplication and (hopefully) make it easier to understand. Also saves a few bytes of FLASH.
=> chore(radio): cleanup code for isSourceAvailable functions

radio/src/targets/taranis/hal.h
Cleanup some of my mess, apologies.
=> chore: de-duplication of TPROS defines

radio/src/lib_file.cpp, radio/src/logs.cpp, radio/src/storage/modelslist.cpp, radio/src/thirdparty/FatFs/ffconf.h
=> chore: replace f_puts and f_printf functions from FatFS to save FLASH space.

radio/src/gui/colorlcd/libui/choice.cpp, radio/src/gui/colorlcd/libui/choice.h
Changes:
- adjust padding on Choice button to fit more text
- where Choice button is fixed width, use smaller font if text does not fit.
=> feat(color): adjust font size of text in Choice box to fit

companion/src/simulation/telemetryproviderfrsky.cpp, companion/src/simulation/telemetryproviderfrsky.h
Update TelemetryProviderFrSky to use SimulatedGPS so we only have the one implementation.
Fixes https://github.com/EdgeTX/edgetx/issues/5473
=> chore(cpn): finish SimulatedGPS refactor, fix GPS lat/long not working

radio/src/gui/colorlcd/module/afhds3_options.cpp, radio/src/gui/colorlcd/module/afhds3_options.h, radio/src/gui/colorlcd/module/afhds3_settings.cpp, radio/src/gui/colorlcd/module/custom_failsafe.cpp, radio/src/gui/colorlcd/module/custom_failsafe.h, radio/src/gui/colorlcd/module/module_setup.cpp
=> fix(color): portrait layout issues

radio/src/switches.cpp
=> fix: register activity on CS changes

radio/src/gui/colorlcd/widgets/value.cpp
=> fix(color): Value widget not showing date or GPS telemetry sensors

radio/src/gui/navigation/navigation_9x.cpp, radio/src/gui/navigation/navigation_x7.cpp
=> fix(bw): enabling/disabling of GF/SF causing EM

companion/src/simulation/simulateduiwidgetJumperT12max.cpp, companion/src/simulation/simulateduiwidgetJumperTPROS.cpp
- fix PAGEDN key / button acting as PAGEUP
- use KEY macros instead of magic numbers
=> fix(simu): incorrect key mappings for T12MAX, TPROS

radio/src/gui/colorlcd/module/module_setup.cpp
=> chore(color): remove unused code

radio/src/gui/colorlcd/model/model_gvars.cpp, radio/src/gui/colorlcd/model/special_functions.cpp
Fixes #3623 
SF/GF edit:
SF list:
GV edit (title bar):
Source select (already in 2.11):
=> feat(color): show global variable names in UI

radio/src/gui/128x64/model_flightmodes.cpp
=> fix(bw): adjust 128x64 B&W FlightModes tab layout to better fit values.

radio/src/storage/yaml/yaml_datastructs_128x64.cpp, radio/src/storage/yaml/yaml_datastructs_f16.cpp, radio/src/storage/yaml/yaml_datastructs_nv14.cpp, radio/src/storage/yaml/yaml_datastructs_pl18.cpp, radio/src/storage/yaml/yaml_datastructs_t15.cpp, radio/src/storage/yaml/yaml_datastructs_t20.cpp, radio/src/storage/yaml/yaml_datastructs_tpro.cpp, radio/src/storage/yaml/yaml_datastructs_x10.cpp, radio/src/storage/yaml/yaml_datastructs_x9d.cpp, radio/src/storage/yaml/yaml_datastructs_x9dp2019.cpp, radio/src/storage/yaml/yaml_datastructs_x9e.cpp, radio/src/storage/yaml/yaml_datastructs_xlite.cpp, radio/src/storage/yaml/yaml_datastructs_xlites.cpp
=> chore: update yaml_datastructs files.

radio/src/cfn_sort.cpp
=> chore: update sf/gf sort order from recent changes

radio/src/storage/yaml/yaml_datastructs_funcs.cpp
=> fix(color): special function 'Set Main Screen' settings not written to YAML file correctly

radio/src/translations/ua.h
- fix build with UA translation (not found symbol TR_PWR_AUTO_OFF)
- fix overflows on BW radios (Radiomaster)
=> fix overflows on BW radios in UA translation

companion/src/modeledit/customfunctions.cpp
=> fix(cpn): moving lua script functions

radio/src/cfn_sort.cpp, radio/src/translations/es.h
=> chore: update ES for #5589

companion/src/mainwindow.cpp, companion/src/mainwindow.h, companion/src/mdichild.cpp
This is an alternative to #5161
=> fix(cpn): update last used directory on save

companion/src/firmwares/generalsettings.cpp
=> fix(cpn): active file radio profile conversion

radio/src/gui/colorlcd/model/model_outputs.cpp
=> feat(color): add option for 'Copy min/max/center to all outputs'

radio/src/sbus.cpp, radio/src/sbus.h, radio/src/serial.cpp, radio/src/tasks/mixer_task.cpp, radio/src/trainer.cpp
Fixes #5646
Read SBUS serial on aux idle irq (so as soon as pulse as finished) instead of periodic 5ms . Only complete checked frames will update trainer data.
Also completes a TODO ! Code by Raph and Malte
=> feat: trainer SBUS processing in IDLE IRQ

companion/src/firmwares/edgetx/yaml_moduledata.cpp, companion/src/firmwares/moduledata.cpp, companion/src/firmwares/moduledata.h, companion/src/modeledit/setup_module.cpp, companion/src/modelprinter.cpp
adds CPN support for EdgeTX PR #5689
=> add CPN support

radio/src/gui/colorlcd/mainview/view_logical_switches.cpp
=> fix(color): channel monitor crash when changing from logical switch view

cmake/toolchain/native.cmake, radio/src/CMakeLists.txt, radio/src/edgetx_helpers.h, radio/src/functions.cpp, radio/src/gui/colorlcd/model/special_functions.cpp, radio/src/gui/common/stdlcd/radio_tools.cpp, radio/src/gui/common/stdlcd/view_telemetry.cpp, radio/src/lua/lua_widget.cpp, radio/src/strhelpers.cpp, radio/src/targets/simu/module_drivers.cpp, radio/src/targets/simu/simpgmspace.cpp, radio/src/thirdparty/Lua/src/liolib.c, radio/src/trainer.cpp
Fix warnings when building firmware and simulator.
=> chore: cleanup compiler warnings, disable "unaligned pointer value" warning

radio/src/gui/common/stdlcd/radio_tools.cpp
=> fix(bw): simulator may crash on Linux when SYS key pressed

radio/src/targets/taranis/hal.h
Fixes #5783
- this partially reverses #5703
@3djc you may need to add some new defines to cover what you intended and potentially change the title of this PR
=> fix(bw): remove default SYS key

radio/src/CMakeLists.txt
=> chore: quieten CMake unused variable warning

radio/src/drivers/uf2_ghostfat.cpp, radio/src/drivers/uf2_ghostfat.h, radio/src/hal/abnormal_reboot.h, radio/src/hal/flash_driver.cpp, radio/src/hal/flash_driver.h, radio/src/targets/common/arm/stm32/abnormal_reboot.cpp, radio/src/targets/common/arm/stm32/bootloader/CMakeLists.txt, radio/src/targets/common/arm/stm32/bootloader/boot.cpp, radio/src/targets/common/arm/stm32/bootloader/boot.h, radio/src/targets/common/arm/stm32/bootloader/boot_dfu.cpp, radio/src/targets/common/arm/stm32/bootloader/boot_uf2.cpp, radio/src/targets/common/arm/stm32/h7/system_stm32h7xx.c, radio/src/targets/common/arm/stm32/stm32_qspi.cpp, radio/src/targets/common/arm/stm32/stm32_qspi.h, radio/src/targets/common/arm/stm32/usbd_storage_msd.cpp, radio/src/targets/stm32h7s78-dk/bootloader/boot_menu.cpp, radio/util/elf2uf2.py
- streamlined QSPI driver
- improved UF2 & DFU bootloader
=> feat: Improved H7 bootloader

radio/src/trainer.cpp
=> fix(sim): crash if trainer mode is set to Master/SBUS

radio/src/fonts/lvgl/lz4_font.cpp, radio/src/gui/colorlcd/lv_conf.h
Fix font generation after H7 changes.
=> fix(color): LVGL font generation not working

radio/src/gui/colorlcd/model/model_select.cpp, radio/src/gui/colorlcd/radio/radio_sdmanager.cpp
Fix for wizard scripts not running. 
Also fixes running scripts from SD manager.
=> fix(color): wizard Lua scripts are not run

radio/src/targets/common/arm/stm32/sdcard_spi.cpp, radio/src/targets/taranis/hal.h
This is a possibly temporary fix for #5841 and other GX12 related issues. We need to talk to RM to get to the bottom of this, but in the meantime, this fix found by Hawku seem to allow the radio to work.
Please do not close the issues until we know for sure this is the right fix
=> fix: gx12 SD write issue (possibly temporary fix)

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
New and revised SE translations for firmware and Companion
=> chore: swedish translation updates

radio/src/cli.cpp
=> chore: removed undefined command "volume" from cli

companion/src/mainwindow.cpp
=> fix(cpn): startup crash when "prompt for radio profile" enabled

companion/src/translations/companion_da.ts, radio/src/translations/da.h
too bad, 3 days late for 2.10.6
=> chore: update Danish companion and radio translations

companion/src/translations/companion_sv.ts
Add Companion translation string for Flight/Drive modes tab title (issue #5633)
=> chore(cpn): 🇸🇪 translation for Flight/Drive modes tab title

radio/src/gui/128x64/lcd.cpp, radio/src/gui/128x64/lcd.h, radio/src/gui/212x64/lcd.cpp, radio/src/gui/212x64/lcd.h
=> fix(bw): putsChn() should return always channel number

companion/src/storage/labeled.cpp
=> fix(cpn): read and delete model file names case insensitive

radio/src/audio.h, radio/src/targets/common/arm/stm32/vs1053b.cpp
=> fix(audio): clipped SPI audio on nv14/el18/x12s

radio/src/FreeRTOSConfig.h, radio/src/storage/sdcard_common.cpp
RM has conducted extensive testing with SDcard and found that those fix might help some of the issue identified
=> fix: only clear storageDirtyMsk bits when no errors, extend RTOS queues

radio/src/storage/sdcard_common.cpp
Prevent infinite loop retrying SD card writes if a fatal error has occurred.
=> fix(radio): limit the number of consecutive retries when writing SD card data.

radio/src/gui/colorlcd/widgets/timer.cpp
=> fix(color): timer widget displays wrong UI for count up timers.

companion/src/modeledit/expodialog.cpp
Fixes #5946
Another as a consequence from post inverted sources PR
=> fix(cpn): input edit window title

radio/src/translations/se.h
Some minor updates for a few words too long to fit B/W small screens
=> Swedish translation fixes

companion/src/modeledit/mixerdialog.cpp
=> fix(cpn): include global variables in mixes source list

radio/src/translations/ua.h
- fix some overflows
- correction of some terms to Ukrainian translation of the EdgeTX User Manual
=> chore(radio): update Ukrainian 🇺🇦 translations

radio/src/gui/colorlcd/model/model_telemetry.cpp
=> fix(color): missing telemetry ID instance input field

radio/src/targets/common/arm/stm32/rtc_driver.cpp
Improve rtcInit(()
Possible fix for #5782
=> fix(radio): improve initialisation of RTC

radio/src/lua/lua_widget.cpp
=> fix(color): touch release event is incorrectly sent to Lua scripts after key presses.

radio/src/lua/api_colorlcd.cpp
Addresses the issue discussed in: https://discord.com/channels/839849772864503828/839849772864503832/1358196802813300767
=> fix(doc): describe more clearly availability of colorlcd Lua API functions

radio/src/gui/common/stdlcd/view_telemetry.cpp, radio/src/gui/navigation/navigation.h
=> fix(bw): PAGE key events not passed to Lua telemetry scripts

companion/src/translations/companion_sv.ts, radio/src/translations/se.h
A few new SE translations for firmware and Companion
=> chore: SE translation updates

radio/src/lua/lua_lvgl_widget.cpp, radio/src/lua/lua_lvgl_widget.h
Requested by @offer-shmuely to allow dynamic image changing.
=> feat(lua): allow the filename for an image object to be set via a function.

radio/src/lua/api_colorlcd_lvgl.cpp, radio/src/lua/lua_lvgl_widget.cpp, radio/src/lua/lua_lvgl_widget.h
=> feat(color): add file picker button to Lvgl Lua API

companion/src/firmwares/customisation_data.h, companion/src/modeledit/colorcustomscreens.cpp, radio/src/datastructs.h, radio/src/gui/colorlcd/mainview/widgets_container.h, radio/src/storage/yaml/yaml_datastructs_f16.cpp, radio/src/storage/yaml/yaml_datastructs_nb4p.cpp, radio/src/storage/yaml/yaml_datastructs_nv14_family.cpp, radio/src/storage/yaml/yaml_datastructs_st16.cpp, radio/src/storage/yaml/yaml_datastructs_t15.cpp, radio/src/storage/yaml/yaml_datastructs_x10.cpp
=> feat(color): increase max length for widget name

radio/src/storage/yaml/yaml_datastructs_pl18.cpp
The PL18 yaml datastruct is not updated properly. This fixes the main branch problem.
Main is different because of https://github.com/EdgeTX/edgetx/pull/6119
=> fix(pl18): YAML datastructs not updated properly

radio/util/find_clang.py
=> chore: allow for more libclang versions

radio/src/targets/simu/led_driver.cpp, radio/src/targets/simu/opentxsimulator.cpp
Address conflicting changes from #6129 & #6132
=> chore(simulator): fix build of simulator libraries

radio/src/targets/simu/led_driver.cpp, radio/src/targets/simu/opentxsimulator.cpp
This reverts commit 26eee4aa3edeb6bbbbbf0e234019538303906048.
Fixes #
=> revert: "chore(simulator): fix build of simulator libraries (#6138)"

.devcontainer/devcontainer.json
- devcontainer syntax has changed
- `simu` on Linux needs extra docker flag, has not apparent effect on Windows/WSLg
=> chore(devcontainer): new devcontainer schema, graphics perms on linux

radio/src/targets/taranis/hal.h
=> fix(x7access): internal module power

radio/src/targets/st16/CMakeLists.txt, radio/src/targets/st16/battery_driver.cpp, radio/src/targets/st16/battery_driver.h, radio/src/targets/st16/board.cpp, radio/src/targets/st16/board.h, radio/src/targets/st16/bsp_io.cpp, radio/src/targets/st16/hal.h
Align charging control with other Flysky radios with charge end detection.  Old implementation did not have charge end detection.
=> fix(st16): port Flysky specific charging driver

radio/src/gui/colorlcd/libui/tabsgroup.cpp, radio/src/gui/colorlcd/libui/tabsgroup.h, radio/src/gui/colorlcd/libui/window.cpp
For color radios with both PAGE UP and PAGE DN keys.
=> feat(color): allow long press of PAGE keys to navigate menus.

radio/src/gui/colorlcd/model/model_flightmodes.cpp, radio/src/gui/colorlcd/model/model_logical_switches.cpp, radio/src/gui/colorlcd/model/model_mixer_scripts.cpp, radio/src/gui/colorlcd/model/model_outputs.cpp, radio/src/gui/colorlcd/model/model_usbjoystick.cpp, radio/src/gui/colorlcd/model/special_functions.cpp, radio/src/gui/colorlcd/model/special_functions.h, radio/src/gui/colorlcd/widgets/outputs.cpp
Fix high CPU usage on outputs page.
=> fix(color): slow update of channel bars on outputs page.

radio/src/thirdparty/STM32_USB_Device_Library/Class/CDC/Inc/usbd_cdc.h, radio/src/thirdparty/STM32_USB_Device_Library/Class/CompositeBuilder/Src/usbd_composite_builder.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/CustomHID/Inc/usbd_customhid.h, radio/src/thirdparty/STM32_USB_Device_Library/Class/CustomHID/Src/usbd_customhid.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/CustomHID/Src/usbd_customhid_if_template.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc.h, radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc_data.h, radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc_scsi.h, radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.c, radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c, radio/src/thirdparty/STM32_USB_Device_Library/Core/Inc/usbd_def.h, radio/src/thirdparty/STM32_USB_Device_Library/Core/Src/usbd_core.c, radio/src/thirdparty/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
This fixes USB Mass storage Issues with H7 based radios
=> chore: update ST USB middleware to 2.11.4

radio/src/boards/generic_stm32/analog_inputs.cpp, radio/src/boards/generic_stm32/analog_inputs.h, radio/src/cli.cpp, radio/src/targets/common/arm/stm32/flysky_gimbal_driver.cpp, radio/src/targets/common/arm/stm32/flysky_gimbal_driver.h, radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp, radio/src/targets/common/arm/stm32/sticks_pwm_driver.h, radio/src/targets/horus/board.cpp, radio/src/targets/horus/hal.h, radio/src/targets/pl18/board.cpp, radio/src/targets/taranis/board.cpp, radio/src/targets/taranis/hal.h
This is a follow up on #6158 to cleanup the `#if defined(...)` jungle.
=> feat(radio): improve gimbal detection

radio/src/targets/common/arm/stm32/h7/system_stm32h7xx.c, radio/src/targets/st16/hal.h
=> fix(st16): PPM timer

radio/src/lua/lua_lvgl_widget.cpp, radio/src/lua/lua_lvgl_widget.h
Line works with a fixed point array; but does not draw properly if points are set by a function.
=> fix(color): Lua LVGL object does not draw correctly when using a function

radio/src/targets/common/arm/stm32/audio_dac_driver.cpp, radio/src/targets/horus/hal.h, radio/src/targets/pl18/hal.h, radio/src/targets/stm32h7s78-dk/hal.h, radio/src/targets/taranis/board.cpp, radio/src/targets/taranis/board.h, radio/src/targets/taranis/hal.h
- improve code reuse and splitting into functions.
This probably needs to be revisited once #6149 has been merged. This means that #6149 should be merged first.
=> chore(radio): DAC driver cleanup

companion/src/firmwares/edgetx/yaml_modeldata.cpp, radio/src/gui/colorlcd/lv_conf.h
Removes the variable length array.
=> fix(cpn): 'variable length array' warning

radio/src/edgetx.cpp, radio/src/storage/sdcard_yaml.cpp
No functional change, just a (possibly) more logical function placement
=> chore(bw): place screen inversion in a more logical place

radio/src/lua/lua_lvgl_widget.cpp
Fix side effect of changes in PR #6193.
=> fix(color): Lvgl 'line' object in Lua script may crash

radio/src/lua/api_colorlcd_lvgl.cpp, radio/src/lua/lua_lvgl_widget.cpp, radio/src/lua/lua_lvgl_widget.h, radio/src/lua/lua_widget.cpp, radio/src/lua/lua_widget.h
=> fix(color): prevent crash, show error if Lua script uses a deleted LVGL object

radio/src/storage/sdcard_yaml.cpp
Fixed an issue with SD card file naming when creating or backing up a model.
=> 120 Slots - Fixed an issue with SD card file naming

radio/src/lua/lua_lvgl_widget.cpp, radio/src/lua/lua_lvgl_widget.h
Allows a script to filter which options are displayed when the user opens the popup menu.
=> feat(color): add a filter function to the Lua choice popup

radio/src/targets/common/arm/stm32/pwr_driver.cpp
=> fix(t18): normal switch off with one button

radio/src/lua/lua_widget.cpp
Fix thx to Mickey via ExpressLRS Discord.
=> fix(lua): memory leak

radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp
=> fix(radio): verify PWM gimbal pulse length

radio/src/gui/colorlcd/libui/choice.cpp, radio/src/gui/colorlcd/libui/choice.h, radio/src/gui/colorlcd/libui/filechoice.cpp, radio/src/gui/colorlcd/libui/filechoice.h, radio/src/lua/api_colorlcd_lvgl.cpp, radio/src/lua/lua_lvgl_widget.cpp, radio/src/lua/lua_lvgl_widget.h
Changes:
- Fix the 'Choice' control so it will update the button content if the value returned by 'get' function changes.
- Add an option to limit scroll directions for containers (box, rectangle, page).
- Add a function to return current scroll position of a container object.
Sample script for scroll control:
```Lua
local b4;
local function init()
lvgl.clear();
local lyt = {
{type="rectangle", x=10, y=10, w=(LCD_W-40)/2, h=100, scrollDir=lvgl.SCROLL_OFF, name="b1",
children={
{type="label", x=2, y=2, color=BLACK, text="No scroll"},
{type="label", x=10, y=150, color=BLACK, text="Scroll test"},
{type="label", x=500, y=10, color=BLACK, text="Scroll test"},
}
},
{type="rectangle", x=LCD_W/2+10, y=10, w=(LCD_W-40)/2, h=100, scrollDir=lvgl.SCROLL_VER, name="b2",
children={
{type="label", x=2, …
```
=> feat(color): additions/fixes for Lua LVGL API

radio/src/lua/api_model.cpp
Add 'state' and 'persistent' properties to getLogicalSwitch and setLogicalSwitch functions.
=> feat(lua): add state & persistent properties to the logical switch API

radio/src/targets/taranis/gx12/bsp_io.cpp
Remove double timer init noticed by @philmoz in #6325
=> chore(gx12): clean double timer init

radio/src/gui/colorlcd/libui/choice.cpp
=> fix(color): choice button display not updating if values list changed

radio/src/gui/colorlcd/radio/radio_hardware.cpp
=> fix(color): incorrect portrait layout for radio hardware page

radio/src/gui/128x64/model_special_functions.cpp, radio/src/gui/212x64/model_special_functions.cpp, radio/src/gui/colorlcd/model/special_functions.cpp, radio/src/gui/gui_common.cpp, radio/src/gui/gui_common.h, radio/src/translations.cpp, radio/src/translations.h, radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/he.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/ko.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/ru.h, radio/src/translations/se.h, radio/src/translations/tw.h, radio/src/translations/ua.h
Fixes #6306 
Show 'No timers' message if no timers configured.
Fixes color crash and updated B&W to match UI.
=> fix(color): UI freeze when setting up 'Set' special function with no timers configured

companion/src/firmwares/rawsource.cpp
=> fix(cpn): units for special telemetry (Batt, Time, GPS)

radio/src/storage/yaml/yaml_datastructs_128x64.cpp, radio/src/storage/yaml/yaml_datastructs_f16.cpp, radio/src/storage/yaml/yaml_datastructs_gx12.cpp, radio/src/storage/yaml/yaml_datastructs_nb4p.cpp, radio/src/storage/yaml/yaml_datastructs_nv14_family.cpp, radio/src/storage/yaml/yaml_datastructs_pl18.cpp, radio/src/storage/yaml/yaml_datastructs_pl18u.cpp, radio/src/storage/yaml/yaml_datastructs_st16.cpp, radio/src/storage/yaml/yaml_datastructs_t15.cpp, radio/src/storage/yaml/yaml_datastructs_t20.cpp, radio/src/storage/yaml/yaml_datastructs_tpro.cpp, radio/src/storage/yaml/yaml_datastructs_x10.cpp, radio/src/storage/yaml/yaml_datastructs_x9d.cpp, radio/src/storage/yaml/yaml_datastructs_x9dp2019.cpp, radio/src/storage/yaml/yaml_datastructs_x9e.cpp, radio/src/storage/yaml/yaml_datastructs_xlite.cpp, radio/src/storage/yaml/yaml_datastructs_xlites.cpp
=> chore: update YAML files.

radio/src/telemetry/crossfire.cpp
Add support for TBS ALT + VARIO packet frame ([0x09 Barometric Altitude & Vertical Speed](https://github.com/tbs-fpv/tbs-crsf-spec/blob/main/crsf.md#0x09-barometric-altitude--vertical-speed))
This resolves #6401
=> feat(telem): add support for CRSF 0x09 packed vertical speed

radio/src/gui/colorlcd/model/model_mixer_scripts.cpp, radio/src/lua/interface.cpp
Fix buffer overflow.
Reported on Discord.
=> fix(color): radio may crash if custom mixer Lua script output name is 6 chars long.

radio/src/drivers/frftl.cpp
Fixes #6426
- fix(frftl): array out of bounds issue
=> fix(frftl): array out of bounds issue

companion/src/CMakeLists.txt, radio/src/audio.cpp, radio/src/targets/simu/CMakeLists.txt, radio/src/targets/simu/simuaudio.h
Also fix compiling without SDL2, that is, without sound support.
=> fix(simu): SDL sound init in libsimulator

radio/src/lua/lua_lvgl_widget.cpp, radio/src/lua/lua_lvgl_widget.h
=> fix(color): momentaryButton in Lua script crashes radio

companion/src/CMakeLists.txt
- add compiler dlls to installer
=> fix(cpn): windows installer

radio/src/edgetx.h, radio/src/gui/colorlcd/libui/etx_lv_theme.cpp, radio/src/gui/colorlcd/libui/etx_lv_theme.h, radio/src/gui/colorlcd/radio/radio_spectrum_analyser.cpp, radio/src/telemetry/frsky_pxx2.cpp, radio/src/telemetry/multi.cpp
Fixes https://github.com/EdgeTX/edgetx/issues/1827
Tested with simulator and FrSky X10S Express. Only colorlcd at the moment.
=> feat(color): spectrum analyzer peak hold

cmake/FetchMaxLibQt.cmake
[Qt 6.9.0 PR 6 merged into EdgeTX/maxLibQt ](https://github.com/EdgeTX/maxLibQt/pull/6)
=> fix(cpn): update maxlibqt commit reference

radio/src/targets/simu/CMakeLists.txt, radio/src/targets/simu/arg_parser.cpp, radio/src/targets/simu/arg_parser.h, radio/src/targets/simu/bt_driver.cpp, radio/src/targets/simu/sdl_simu.cpp, radio/src/targets/simu/simpgmspace.cpp, radio/src/targets/simu/simpgmspace.h
This removes yet another POSIX dependency. Replaced with standard C++.
=> chore(simu): remove dependency to `getopt()`

radio/src/gui/colorlcd/libui/file_carosell.h
=> chore: fix MacOS Companion build on GH.

radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp
=> fix(radio): wider PWM gimbal boundaries

companion/src/flash/flashfirmwaredialog.cpp, companion/src/flash/process_sync.h, companion/src/flash/radiointerface.cpp, companion/src/flash/radiointerface.h, companion/src/mainwindow.cpp, companion/src/progress/progresswidget.cpp, companion/src/progress/progresswidget.h, companion/src/storage/firmwareinterface.cpp
- only update status on step change
- less verbose status messages
- compress long running task multi progress messages into a single updating message
=> feat(cpn): improve flashing messages

radio/src/lua/api_general.cpp
=> fix(doc): indicate setCFSLedColor() introduction date

companion/src/firmwares/modeldata.cpp
Companion changes to match #6604.
=> chore(cpn): set default for CFS to mimic 6POS.

radio/src/gui/colorlcd/radio/radio_ghost_module_config.cpp
=> fix(color): navigation for Ghost module config tool

companion/src/firmwares/modeldata.cpp, companion/src/firmwares/modeldata.h, companion/src/helpers.cpp, companion/src/helpers.h, companion/src/modeledit/checklistdialog.cpp, companion/src/modeledit/checklistdialog.h, companion/src/modeledit/checklistdialog.ui, companion/src/modeledit/setup.cpp, companion/src/modeledit/setup.h, companion/src/modeledit/setup.ui, companion/src/print/modelprinter.cpp, companion/src/storage/etx.cpp, companion/src/storage/etx.h, companion/src/storage/labeled.cpp, companion/src/storage/labeled.h, companion/src/storage/sdcard.cpp, companion/src/storage/sdcard.h
Model notes and checklist files read from and written to:
- etx files
- radio sd card
- profile sd path
- simulator temporary models and settings sd path (written only same as models and settings)
Checklist filename based on model name so renaming the model does not break the association.
Note: if the model is renamed, the old checklist file is not removed from SD card structure.
=> feat(cpn): model notes and checklist files packaged with model files

companion/src/firmwares/boardjson.cpp, companion/src/firmwares/boards.cpp
This adds support for IMU in TX15 to Companion
=> fix(cpn): support IMU for TX15

radio/src/gui/colorlcd/mainview/layout_factory_impl.cpp, radio/src/gui/colorlcd/mainview/layout_factory_impl.h
PR #6631 did not quite fix the issue.
Fixes #6630
=> fix(color): widgets may not update correctly when flight mode changes (v2)
