radio/src/gui/colorlcd/model_telemetry.cpp
the alignment of the fields in the model telemetry page is terrible, this PR corrects this following the general design layout
there is also an issue with the discovery button, in that if it is pressed the first time it does not show stop discovery. The change made in this PR appears to correct that. I specifically write "appears to correct" it, since it's not clear how that thing in the handler is supposed to work, and the coloring might not be as intended either, and so on ... all I can say that from a usage point of view it behaves more like it should
risto and me are seeing that then telemetry is streamed on can't switch off anymore. This is not addressed here, it is just UI.
before:
after:
=> Model Telemetry page: terrible alignment and issue with discovery button

radio/src/gui/colorlcd/radio_setup.cpp
two issues with the Gps entrie sin the System -> Radio Setup Menu: 
* it is shown even if there is no GPS
* ALL fields on this page have half page width, only the Time zone field is quarter width
this PR corrects both
=> System Radio Setup Menu: Gps has two issues

radio/src/gui/colorlcd/layouts/sliders.cpp, radio/src/gui/colorlcd/view_main_decoration.cpp
the view main decoration has three issues:
* the ticks for the left and right sliders LS, RS are too short
* the displaying of T2, T3 is swapped
* the displaying of potis S1, S2 is reverted
for correcting the last point there had been just also a pr by pfeerick,  https://github.com/EdgeTX/edgetx/pull/43. You may want me to remove that change here and rather use his pr, which only would be fair.
observed and tested on T16
:)
=> View Main Decoration, three issues

radio/src/gui/colorlcd/layouts/sliders.cpp
PR https://github.com/EdgeTX/edgetx/pull/45 corrected the ticks for sliders if only RS,LS were visible, but made it wrong for then also Ext1,Etx2 are visible. 
Thx to @rotorman for reporting.
This works now for both situations.
Tested on a T16.
=> Ticks for the left and right sliders II

radio/src/gui/colorlcd/select_fab_carousel.cpp, radio/src/gui/colorlcd/tabsgroup.cpp, radio/src/gui/colorlcd/view_main.cpp
This is the continuation of #58. It adds a small fix in libopenui to allow the main menu to work properly. However, I believe that it also changes the default behavior for **all** buttons from **key-release-detection** to **key-press-detection**. I could probably make it less invasive, but this seems to be a necessary change if we want to be consistent (reactive behaviour vs. waiting for key release). Touch behaviour does not change here and works as before.
=> Owpr keylong

radio/src/bluetooth.cpp, radio/src/gui/common/stdlcd/radio_sdmanager.cpp, radio/src/io/bootloader_flash.cpp, radio/src/io/frsky_firmware_update.cpp, radio/src/io/multi_firmware_update.cpp, radio/src/sdcard.cpp
Fixes compile errors for T12, X7 and X9D+ with GNU Arm Toolchain v10 2020-q4.
=> stdio.h missing in 6 files

radio/src/targets/horus/board.cpp
Fixes power-off HardFault during hw-debugging at the end of boardOff(), when power supply to MCU is forced (developer boards, w/o cutting power with pwrOff() ).
=> Fixes HardFault on boardOff() with forced power supply

radio/src/lua/interface.cpp
the title says it, avoids this
=> Avoid a compiler warning

radio/src/lua/api_colorlcd.cpp
this fixes color handling for lcd.clear() and lcd.drawGauge()
=> colorlcd: fixes for lcd.clear() and lcd.drawGauge()

radio/src/targets/simu/CMakeLists.txt
Removed AddressSanitizer for Simu to get rid of ASan error on Simu start. Tested with Ubuntu 20.04 and RM TX16S fw simu lib.
=> Removed AddressSanitizer for radio simulator library

radio/src/gui/colorlcd/view_main_menu.cpp
This PR
* changes the order of the buttons in the main menu so that "Select Model" and "Channel Monitor" come first. IMHO that's much more user friendly, since the both the "Model Settings" and "Radio Settings" options are also and quicker available through "SYS" and "MDL" keys, while the "Select Model" and "Channel Monitor" are not, so that the user might want to get them first in the main menu.
* renames the button "Screens Setup" to "Screens Settings". This so to make the naming more systematic. "Setup" is used in the other menus for sub categories while "Settings" is used for the option name.
Before:
After:
=> Main Menu: Change order of buttons for easier access

radio/src/timers.cpp
At the moment, the timer configuration has an additional switch that can be set, but is used only if the timer mode is set to `Start`. This PR make timer modes (except `OFF`) conditional on the switch set.
This allows for the following:
- `ON`: runs if switch is activated.
- `Start`: starts the timer if the switch is activated. Once started, the switch is not used any more.
- `THs`: count only if throttle is not `-100%` and switch is activated.
- `TH%`: count proportionally to the throttle, if switch is activated.
- `THt`: start timer once throttle has passed threshold and switch is activated. Once the timer has started, it stays conditional on the switch. 
Comments / test reports welcome :-)
=> Make timers conditional on switch (if set)

radio/src/gui/colorlcd/sourcechoice.cpp, radio/src/gui/colorlcd/switchchoice.cpp
=> Select the first element by default, even if hardware touch is supported

radio/src/lua/api_colorlcd.cpp, radio/src/lua/api_colorlcd.h
requires https://github.com/EdgeTX/libopenui/pull/4
probably the vertical offset is needed in other lua draw* methods as well, needs checking
=> colorlcd: fix for drawNumber INVERS and text per font size h/v offsets

radio/src/simu.cpp
At least with Jumper T16 and RM TX16S. the RGB565 connection scheme is not just cutting/zeroing the 3 lowest bits of red and blue and 2 lowest bits of green, but is actually using a copy of the highest bits for the "missing" bits instead.
Example: let red be (in binary, MSB first) b'abcdefgh', green b'ijklmnop' and blue b'qrstuvwx' then the resulting RGB value used by the the LCD is NOT:
red b'abcde**000**', green b'ijklmn**00**', blue b'qrstu**000**', but instead
red b'abcde**abc**', green b'ijklmn**ij**', blue b'qrstu**qrs**'.
Here the schematic snippet of RM TX16S LCD hookup showing this (see Jumper T16 schem [here](https://github.com/opentx/opentx/files/5035629/T16.Schematic.pdf) for similar hookup):
This PR matches the usage of lower 3 bits of red and blue and lower 2 bits of green …
=> Better match simulator colors to color radio display

radio/src/lua/api_colorlcd.cpp, radio/src/lua/api_colorlcd.h
this should fix the BOLD font offsets and hopefully the lcd.clear() issue reported by @JimB40
=> colorlcd: fix for BOLD font h/v offsets, fix for lcd.clear()

radio/src/gui/colorlcd/special_functions.cpp
To be more uniform with other elements, such as curves and global variables that start from 1.
=> Show special functions from 1 to 64, instead of 0 to 63

radio/src/translations/cn.h.txt, radio/src/translations/cz.h.txt, radio/src/translations/de.h.txt, radio/src/translations/en.h.txt, radio/src/translations/es.h.txt, radio/src/translations/fi.h.txt, radio/src/translations/fr.h.txt, radio/src/translations/it.h.txt, radio/src/translations/nl.h.txt, radio/src/translations/pl.h.txt, radio/src/translations/pt.h.txt, radio/src/translations/se.h.txt, radio/src/translations/tw.h.txt
Adjusts the warning message accordingly (simplified/traditional Chinese is using the same hieroglyphs for this phrase).
=> The UARTs of radios are using 3.3V logic level, not TTL / 5V.

radio/src/gui/colorlcd/special_functions.cpp
Inactive state was being set to menu background colour...
=> Fix colour of inactive SF/GF state in header

radio/src/lua/api_general.cpp
Resolves #319 
Extends lua getVersion() so that it returns a sixth parameter, the OS name, allowing scripts to identify if running on OTX or ETX. 
Didn't see a readily usable pre-existing define that had `EdgeTX` in it so added `VERSION_OSNAME`
=> Extend lua getVersion()

radio/src/targets/horus/tp_gt911.cpp, radio/src/targets/horus/tp_gt911.h
This fix contains 2 modifications:
- poll GT911_READ_XY_REG for 20ms in case not yet ready
- write 0 to GT911_READ_XY_REG in all cases
These fixes are largely inspired from the Linux GT9xx driver (see https://gitlab.com/AdyaAdya/goodix-touchscreen-linux-driver/-/blob/master/goodix.c)
=> [color] fix attempt for GT911 touch sensor driver

radio/src/gui/colorlcd/model_setup.cpp
Currently missing, and was present on OTX. Without it, fine tuning is impractical to do at best. 
If it can be right aligned, even better, but it appears to be functional on TX16S - the RSSI value updates continuously, and more importantly, while the fine tune value is being changed. 
I started with just copying the format from OTX as is... 
... and currently have this:
Interestingly, the latter implementation doesn't show up on `simu`. 
This is probably a squash merge candidate ;)
=> Show RSSI if RF Freq Fine tuning supported

radio/src/gui/colorlcd/model_logical_switches.cpp
Resolves #375 
Use the v1 handler to update v2 range if the v2 source box has already
been created, so that the min/max values are correctly updated from v1.
Read it and weep over my atrocious code. :-P
As always, open to suggestions and being told there's a better way to do it. TX16S hasn't crashed yet :-P
=> Reset logical switch v2 range if v1 changes

radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/model_mixes.cpp
Resolves #387 
For some reason, the input page appeared to work, but was mixing uint8_t and uint32_t data types... so I've updated both to align with the underlying uint32_t used by the actual data structures. 
Need to test this further on the TX as only simu tested to verify that the button actually toggled now - I haven't verified the flight mode is behaving correctly yet.
=> Use uint32_t values consistent with underlying data structures

radio/src/gui/colorlcd/model_setup.cpp
Resolves #410 by ensuring an out of range sub-protocol is not set
when the protocol is changed. Stops the module from complaining
about an invalid protocol, as well as stops simu from crashing.
Tested on TX16S and simu. 
The bug being fixed is easily reproduced in a nightly by:
1. Picking the top entry (FlySky) and then CX20 as the sub-protocol (i.e. fifth sub-protocol).
2. Picking V2x2 (which only has three sub-protocols) , and you'll see the sub-protocol choice is blank, and the module status is "Protocol invalid" instead of showing the version and channel order.
If you do the same steps in `simu`, it will segfault.
=> Reset MultiProtocol subType reset to zero on protocol change

radio/src/pulses/pulses.cpp, radio/src/pulses/pxx.h, radio/src/targets/common/arm/stm32/heartbeat_driver.cpp
- Use longer period for PXX2 modules triggered by heartbeat signal and reset timer early:
- This allows to cope for the different frame rates used by ACCESS and ACCST modes.
- see opentx/opentx#8601 for details.
- Simplify pulses code with respect to period settings with PXX1 and PXX2 (incl. a bit of cleanup).
=> Fix isrm ixjt pulses issues

radio/src/gui/colorlcd/radio_diaganas.cpp, radio/src/targets/horus/hal.h, radio/src/targets/horus/tp_gt911.cpp, radio/src/targets/horus/tp_gt911.h, radio/src/targets/nv14/touch_driver.cpp
Based on PR #408 ff34616 that according to @rcvideoreviews on Discord works.
Added:
* @olliw42 PR #415 STOP condition fix.
* @raphaelcoeffic EXTI_Trigger_Rising from PR #413 
* fixed some uint8_t / bool confusions
* added volatile keyword to touchEventOccured that is set from ISR and accessed from main code
* changed to upload GT911 config also if config version is the same
=> Touch Lockup Recovery

radio/src/gui/colorlcd/model_select.cpp
Saves the current category so that it is also re-opened when re-visiting the model selection page.
Completes #345, as I would expect both the last model and last category to be visible, if it is not in the first category ;)
Also clears the following compiler warning since I was in the vicinity ;)
Tested with `simu` and TX16S. It's nice to have the category the model belongs to re-opened now! 😃 
```
/src/radio/src/gui/colorlcd/model_select.cpp:275:34: warning: comparison of integer expressions of different signedness: 'const int' and 'std::__cxx11::list<ModelCell*>::size_type' {aka 'unsigned int'} [-Wsign-compare]
275 |                     update(index < category->size() - 1 ? index : index - 1);
|                            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~
```
=> Re-open selected model category

radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/colorlcd/textedits.h
PR complementing issue https://github.com/EdgeTX/edgetx/issues/431
adds more extra chars to the text edit field for model name.
it does so only for model name. If it should happen that similar extension should be desired elsewhere, it would be easy to add, and maybe the extra char string defined more globally, but all this and such should be part of a separate PR, IMHO.
tested on tx16s
=> Model Setup, Model Name: Add extra chars

radio/src/gui/colorlcd/widgets/outputs.cpp
Resolves #430.
Basically, current behaviour would incorrectly use the names of INPUTS if a OUTPUT was not named. 
i.e. Given that the first and fourth outputs have been named (CH1 = "O T", CH4 = "O R"), you can see that two and three are using the input name (I2 = "I A", I3 = "I E"). 
This is ok, except for those times when your inputs don't match the order of your mixes, and hence output names or numbers. 
This makes it so they instead fall back to showing the channel number, consistent with the 'unnamed' form of outputs.
Thus also consistent with OTX behavior (for now) ;)
=> Make outputs widget use outputs names

radio/src/gui/colorlcd/model_mixes.cpp, radio/src/gui/colorlcd/model_outputs.cpp
Fixes #460, whereby editing the name of a mix or output would result it it not being save to storage, and being lost as soon as you changed models or powered of the radio. It looks like a when the value was changed, it triggered radio settings to be saved, not model settings, which is why changing another value at the same time worked, as that did trigger model settings to be saved.
Has been tested on `simu`, not hardware yet as off to bed. However, simu is now acting as expected, and saying the right thing... i.e. 
```
13.16 eeprom write model
```
instead of 
```
11.18 eeprom write general
```
like it was doing before...
=> TextEdit should trigger Model save, not Radio save

radio/src/targets/horus/CMakeLists.txt, radio/src/targets/horus/hal.h, radio/src/targets/horus/i2c_driver.cpp, radio/src/targets/horus/i2c_driver.h, radio/src/targets/horus/tp_gt911.cpp, radio/src/targets/horus/tp_gt911.h, radio/src/targets/taranis/hal.h, radio/src/targets/taranis/i2c_driver.cpp
This is a Frankenmod PR, where I took the I2C code incl. it's state machine from STM32F4 HAL and reworked it to fit and work with remaining EdgeTX running StdPeriph Lib.
Tested on RM TX16S.
=> Fully rewrote I2C based on STM32F4 HAL

radio/src/gui/colorlcd/model_select.cpp, radio/src/pulses/pulses.cpp
Thanks to @eshifri for the hint on exiting the menu.
Triggers the standard safety checks that are would run on startup, so appears to behave exactly the same as how OpenTX did. 
e.g. Throttle warning, switch warning, low rf power, no failsafe set, pre-flight checklist shown if configured (when functional), stuck key warning (when functional). 
Tested on simu and TX16S
Resolves #348
=> Run safety checks on model select and exit menu

radio/src/lua/widgets.cpp
Apparently, onTouchSlide gets called more frequently than Lua widgets, and hence we miss some of the sliding if we do not accumulate between calls to Lua.
=> Accumulate (slideX, slideY) with touch slide events to Lua

.devcontainer/devcontainer.json
Add VSCode Docker [Development Container](https://aka.ms/vscode-remote/containers/getting-started) support, and possibly also [GitHub Codespaces](https://github.com/features/codespaces) when it becomes generally available. 
I would like independent verification that this is functional before it merges, as I already have an environment setup, so it could be 'just working' for me because it already does. I should be able to test this in a day or two on a clean laptop with Linux and Windows 10 on it. 
Ideally, one should only have to install the pre-requisites detailed in the link above, and it should prompt to open the repo inside a "remote/development container" and auto download and spin up the docker image, launching a terminal into the container ready for use.
=> Add VSCode Development Containers support

radio/src/lua/api_colorlcd.cpp
Gets the width and height (incl. vertical offset) of text on the LCD with flags applied.
=> Added a lua function lcd.sizeText(text[, flags])

radio/src/gui/colorlcd/special_functions.cpp
Resolves #531 by adding missing the text for the 'Adjust' Special Function 'source' (input field above the enable checkbox). 
I was going to simply use 'STR_VALUE' for all of them, then thought it would be nicer if the label synced with the drop_down that changes the input the label is for.
=> Add missing SF "Adjust" label, dependent on source

radio/src/gui/colorlcd/screen_setup.cpp
Fix for #529 Allows to exit widget setup screen using touch interface
=> Fix for #529 Allows to exit widget setup screen using touch interface. Take 2

radio/src/targets/nv14/board.cpp
Fix for #515
Looks like this fixies the rtcInit() and also does not go into endless EMERGENCY MODE  after crashes.
=> rtcInit() to NV14

radio/src/gui/colorlcd/model_logical_switches.cpp
Similar to #325, colour was wrong with logical switch was inactive, but worse, the display was never updated when the state changed! 😆
=> Refresh display when logical switch state changes

radio/src/lua/interface.cpp
The function luaResume(...) assumed that it was called alternatingly in the background and the foreground.
But on color LCD radios it is only called in the foreground by standalone and tools script, and otherwise only in the background by mixer and function scripts. So it got stuck waiting for a foreground call.
=> Fix for issue #537

radio/src/gui/colorlcd/topbar.cpp, radio/src/gui/colorlcd/widgets_container.h, radio/src/hal/adc_driver.cpp
This is the fix for #579 and #581.
Added exit button to the topbar widgets setup screen.
Split the maximum number of topbar widgets for horizontal and vertical screens.
Fixed the swap of SWG and SWH switches.
=> Fix 579 581

radio/src/targets/nv14/telemetry_driver.cpp
This is the fix for #590, however, I discovered that NV14 supports both INV and NOINV telemetry.  And this mechanism is missing in the current code base.  Please help to review and see how to make this right.
The Open-Flysky code base has this in the telemetry driver:
void telemetryPortInit(uint32_t baudrate, uint8_t mode)
{
.....
if(mode & TELEMETRY_SERIAL_NOT_INVERTED) {
TELEMETRY_TX_POL_NORM();
TELEMETRY_RX_POL_NORM();
}
else {
TELEMETRY_TX_POL_INV();
TELEMETRY_RX_POL_INV();
}
}
And seems the mode parameter can be used to select whether INV is used or not.
Any ideas?
=> Fix 590 - telemetry for NV14 external module.

radio/src/gui/colorlcd/model_setup.cpp, radio/src/pulses/modules_helpers.h
Partially resolves https://github.com/EdgeTX/edgetx/issues/521 by setting DSM2 and MPM DSM2 max channel values, and treating rest of MPM as 16 channels max for now. Only tested in `simu` at present, just offering this up whilst I get around to trying it out on hardware in the next day or so. 
Also kicks the max channel value if you change the protocol and the value is now out of range (i.e. switching from XJT (16 CH) to DSM2 (7/8 CH) would leave it at 16 before). 
Either way, maxModuleChannels_M8 seems to be the culprit.
=> Tweak Max channels

radio/src/gui/colorlcd/layouts/topbar_impl.cpp, radio/src/targets/horus/libopenui_config.h, radio/src/targets/nv14/libopenui_config.h
A few more tweaks to the top bar icons
* moved USB and SD logging icons for NV14
* moved GPS and EXT_ANT icons for NV14 just because
* made remaining icon positions controllable by target
Will merge if checks complete.
=> NV14 topbar icon tweaks

radio/src/targets/horus/CMakeLists.txt
Tested on RM TX16S, AUX1/USART3 and FlySky Hall Sticks on UART4, both now work simultaneously.
=> Enables AUX1 again when FlySky Hall sticks are used

radio/src/CMakeLists.txt, radio/src/gui/colorlcd/radio_diaganas.cpp, radio/src/options.h, radio/src/targets/common/arm/stm32/bootloader/boot.cpp, radio/src/targets/common/arm/stm32/lsm6ds_driver.cpp, radio/src/targets/horus/CMakeLists.txt, radio/src/targets/horus/board.cpp, radio/src/targets/horus/board.h, radio/src/targets/horus/hal.h, radio/src/targets/horus/i2c_driver.cpp, radio/src/targets/horus/imu_lsm6ds33.cpp, radio/src/targets/horus/imu_lsm6ds33.h, radio/src/targets/horus/tp_gt911.cpp, radio/src/targets/nv14/hal.h, radio/src/targets/taranis/board.cpp, radio/src/targets/taranis/hal.h, radio/src/targets/taranis/i2c_driver.cpp
This PR adds support of [LSM6DS33 IMU](https://www.st.com/en/mems-and-sensors/lsm6ds33.html) to RadioMaster/Eachine TX16S via AUX1 port.
With new CMake key **IMU_LSM6DS33**, std. serial USART3/AUX1 will be converted to second I2C bus (first internal I2C bus is for touchscreen on TX16S).
The temperature, gyro and linear acceleration values of LSM6DS33 are sampled and displayed at radio analogs dialog screen in SI-units.
Here [Adafruit LSM6DS33 breakout](https://www.adafruit.com/product/4480) during simultaneous testing with [FlySky Paladin EV digital gimbals](https://www.flysky-cn.com/paladin-evdescription) on RM TX16S:
Presently, no further action is done using the IMU data, which is sampled/gathered at 10 Hz and saved in SI units into internal variable `IMUoutput` of following structure …
=> Adds support of LSM6DS33 IMU to TX16S via AUX1 port

radio/src/lua/api_colorlcd.cpp, radio/src/lua/api_colorlcd.h, radio/src/lua/widgets.cpp
To support new color encoding in Lua widgets.
@pfeerick please check if this solved the color option problem for Lua widgets!
=> Color options for Lua widget get translated to Lua color flags

radio/src/gui/gui_common.cpp
Resolves #178 by removing the blocking of negative states for 2POS switches. Only `simu` tested at present.
Also prevent 'unused variable' compiler warning that results from change. 
Remo
=> Don't remove 2POS from avail switches for invert

radio/src/logs.cpp
This changes the log file name format from `modelnamexxxxxx_YYYY-MM-DD.log` to `modelnamexxxxxx_YYYY-MM-DD-HHMMSS.log`. This effects that basically every new flight will create a new log file (with its own header, etc...).
Resolves #548
=> Use the current time to generate the log filename

radio/src/telemetry/crossfire.cpp
This PR adds the 50 mW TX power level to the CRSF protocol. TBS is adding this power level in a future firmware version and they already added support for it in OpenTX. ExpressLRS uses 50 mW but cannot include it in the link statistics until the various projects that use CRSF support it, hence this PR.
=> Add 50 mW TX power level to CRSF protocol 

radio/src/gui/colorlcd/theme.h, radio/src/gui/colorlcd/themes/480_default.cpp, radio/src/gui/colorlcd/themes/flysky.cpp, radio/src/lua/api_colorlcd.cpp
Trying to optimize speed for theme color changes. FlySky is not optimized yet.
=> Do not reload bitmps during theme update, unless reload argument is true

radio/src/gui/colorlcd/model_mixes.cpp, radio/src/mixer.cpp
This resolves #658 allowing mix with "--" source in the middle of the mixes list.
The b/w version is not affected. :-)
=> allow mixes without source

radio/src/gui/colorlcd/model_setup.cpp
Add empty string to the bottom of the model_setup screen (trainer setup) to simplify access
=> Add line to the bottom of the model_setup screen for NV!4

radio/src/gui/colorlcd/CMakeLists.txt, radio/src/gui/colorlcd/choiceex.cpp, radio/src/gui/colorlcd/choiceex.h, radio/src/gui/colorlcd/menu_model.h, radio/src/gui/colorlcd/model_curves.cpp, radio/src/gui/colorlcd/model_curves.h, radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/model_mixes.cpp
This PR implements a jump to curve edit screen from long-press of curve Choice() on the input screen and mixer screen.  I implemented a ChoiceEx which handles long-press and passes it back to the creator to take action.  This ideally should be in libopenui
=> Implement Jump to Curve Edit from input and mixer screens

radio/src/targets/horus/CMakeLists.txt
As TX16S and T18 are only Horus targets with hardware touch as standard
Also only enable SOFTWARE_KEYBOARD with HARDWARE_TOUCH
- Jumper T16 builds work again with this change
- RM TX16S touch / software keyboard is still functional
Also, a check of my understanding... I beleive CMake only cares about booleans - so does this mean duplicate declarations like 
```
set(HARDWARE_TOUCH YES)
set(HARDWARE_TOUCH ON)
```
could be cleaned up?
=> Only enable HARDWARE_TOUCH for TX16 & T18 (Horus targets) by default

radio/src/lua/api_colorlcd.cpp
Now it can take *either* (r, g, b) as before *or* one single argument between 0 and 0xFFFFFF.
=> Modify Lua function lcd.RGB(...)

radio/src/gui/colorlcd/widget.cpp, radio/src/gui/colorlcd/widget.h, radio/src/lua/api_colorlcd.cpp, radio/src/lua/api_colorlcd.h, radio/src/lua/widgets.cpp
Added Lua function lcd.exitFullScreen().
Removed full screen message "Press [RTN] long to exit".
Removed unused function exec().
Set error message when script fails in create().
=> Lua widgets

radio/src/targets/nv14/touch_driver.cpp
Building on Jespers excellent tap count for the TX16S/T18 targets, this is for the NV14 (_without_ re-writing the handler part of the driver...). 
Double tap is working, ~~but I've just realised the press and hold for menu isn't working~~ press and hold is now working. I haven't verified how the GT911 driver functions, but I gather it only fires the down event once, whereas the ft6x06 on the NV14 continuously fires while pressed, so needed a little more hand-holding.
=> Implement tap count for NV14 TP also

radio/src/targets/nv14/hal.h
Fixies #699 - blue tooth can be compiled for NV14 now.
Code ported from https://github.com/open-flysky/Flysky-OpenTX-Test-Branch/tree/nv14_bluetooth
written by @qba667 
Changes to CMakeLists.txt for NV14 target are not included into this PR.
=> fix BT build on NV14

radio/src/targets/horus/telemetry_driver.cpp, radio/src/targets/taranis/telemetry_driver.cpp
This fixes #711 as verified by the user that raised the issue. Also continues to work on ELRS, on all baud rates.
=> Enable medium GPIO speed and 8bit sampling on high baud rates only

radio/src/gui/colorlcd/CMakeLists.txt, radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/colorlcd/multi_rfprotos.cpp, radio/src/gui/colorlcd/multi_rfprotos.h, radio/src/gui/gui_common.cpp, radio/src/gui/gui_common.h, radio/src/io/multi_firmware_update.cpp, radio/src/io/multi_protolist.cpp, radio/src/io/multi_protolist.h, radio/src/pulses/multi.cpp, radio/src/pulses/pulses.cpp, radio/src/storage/storage_common.cpp, radio/src/targets/horus/CMakeLists.txt, radio/src/targets/nv14/CMakeLists.txt, radio/src/telemetry/multi.cpp, radio/src/telemetry/multi.h, radio/src/telemetry/telemetry.cpp
This is implementing a new and better method as in #682.
Previously, the dynamic proto list used was based on the status packet returned by the MPM after switching to a protocol. It would return basically the previous/next protocol number, and a couple of attributes. However, when populating the protocol drop-down on ETX, this would have required to switch to each and every protocol to know those valid and the order. Due to the fact that the MPM would physically enable this protocol first (thus reseting all the radio chips, etc), it was very slow.
The new protocol implemented by Pascal to fetch the list is much faster. It is uses the proto number `0` and returns upon request a full description of the protocol queried:
```
MPM telemetry packet format type = MultiProtoDef (0x11)
data[0] …
```
=> [color] Dynamic MPM proto list

companion/src/firmwares/eepromimportexport.h, companion/src/firmwares/opentx/opentxeeprom.cpp, companion/src/simulation/CMakeLists.txt, companion/src/simulation/simulateduiwidget.cpp, companion/src/simulation/simulatorinterface.h, companion/src/simulation/widgets/lcdwidget.cpp, companion/src/simulation/widgets/lcdwidget.h, radio/src/targets/simu/opentxsimulator.cpp, radio/src/targets/simu/opentxsimulator.h, tools/build-companion-nightly.sh
Based on #561, this PR adds touch support to the radio simulator. Mouse events are translated into touch events for the radio.
=> Add touch support to simulation

radio/src/targets/common/arm/stm32/bootloader/boot.cpp
Don't allow switching to USB mode whilst firmware is being flashed!
Only tested once on TX16S - allowed firmware to finish flashing and then jumped to USB mode on completion. 
Perhaps also on `ST_FLASH_DONE` so that the completion screen is shown?
=> Prevent USB activation while flashing firmware

radio/src/bluetooth.cpp, radio/src/bluetooth.h, radio/src/dataconstants.h, radio/src/gui/colorlcd/model_setup.cpp, radio/src/translations/untranslated.h
I have modified the GUI so that you can select between 4-16 channels of PPM output channels with values adjustable in dataconstants.h, on color LCD.. B/W still uses fixed values.
Also found a bug in Bluetooth/Slave where if you choose a starting channel slave/jack other than 1 then switch to slave/bluetooth the data isn't sent **properly** anymore. Also a bug of mine where you could set the start channel on BT higher MAX_OUTPUT_CHANNELS should have gone ;)
I did notice that the PPM polarity is backwards (EdgeTX Tx16s) & (OpenTX/Taranis) (Should it be flipped?)
On EdgeTX (**ColorLCD**), With + polarity you get,
On OpenTx with + polarity you get,
=> Slave/Jack - more channels, Bluetooth/Slave bug fix

radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/sourcechoice.cpp
=> [color] properly filter sources in drop-downs

radio/src/dataconstants.h
Resolves #736 when FlySky hall sticks are built into firmware.
Before this bugfix:
After this bugfix:
=> Fixes EX3 and EX4 bug caused by myself

radio/src/gui/colorlcd/radio_spectrum_analyser.cpp, radio/src/gui/colorlcd/radio_spectrum_analyser.h, radio/src/io/multi_protolist.cpp
Resolves #465 
Adds a `closeHandler` to _actually_ run the spectrum analyser stop code, as well as remove now non-functional "stopping" dialog message. 
Additionally, always remember the MPM on or off state, not just the on state, so that it is correctly handed on stop. 
And finally, always return module back to normal state - otherwise if you had the MPM off, use the spectrum analyser, and then turn it on, it will be stuck in analyser mode. :-O
Have had TX16S going in and out of analyser using touch and keys, MPM on and off, and has been working perfectl, so just needs sanity checking and some more testing please!
=> Correctly turn off or restore MPM to normal after running spectrum analyser

radio/src/io/multi_protolist.cpp, radio/src/io/multi_protolist.h, radio/src/pulses/multi.cpp, radio/src/pulses/pulses.cpp
Overloading the frame counter causes aa race condition with the UI thread (see SEND_FAILSAFE_1S()).
=> [color] use own protocol counter for MPM proto list

radio/src/translations.h
Strings defined for "x" (shortest) are mostly defined if "LCD_W < 212", which is not the case for the NV14, thus leading to faulty static strings (see TR_VFSWRESET in en.h.txt translation for example).
Resolves #756
=> [nv14] Fix translation strings used

radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/sourcechoice.cpp, radio/src/gui/colorlcd/sourcechoice.h, radio/src/gui/colorlcd/switchchoice.cpp, radio/src/gui/colorlcd/switchchoice.h
This potentially deletes the source/switch choice, which then triggers a "use-after-free".
Resolves #759
=> [color] do not use setValue() in SourceChoice / SwitchChoice

radio/src/gui/colorlcd/radio_diaganas.cpp, radio/src/opentx.cpp, radio/src/opentx.h, radio/src/targets/horus/flyskyHallStick_driver.cpp, radio/src/targets/horus/flyskyHallStick_driver.h
Removes FlySky digital hall gimbal double value conversion. The existing code was first using the FlySky factory calibration values min,mid and max to convert the gimbal +/- ca. 2500 input signal to 0 to 4095. Second, this value was converted again into EdgeTX internal 11-bit range 0 to 2047.
The removal of such double conversion has the added benefit of precision increase and also avoiding unnecessary computation. The code also does not need to read out the FlySky factory calibration values at all anymore - these are close, but not perfectly matching the real min, mid, max values, as I tested.
I needed to change internally some variables from uint16_t to uint32_t, as the jitter removal computation would otherwise go over the 16-bit range due to the resolution increase of the FlySky …
=> Removes FlySky digital hall gimbal double value conversion

radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/radio_version.cpp
Fixes version string on SYS menu having been deliberately (but unnecessarily) indented on NV14.
Also fix only one column of models being shown on NV14 model select screen when there was room for two ;) Resolves #636
=> Nv14-screen-width-fixes

radio/src/targets/horus/telemetry_driver.cpp, radio/src/targets/nv14/telemetry_driver.cpp, radio/src/targets/taranis/telemetry_driver.cpp
This prevents the USART TC IRQ handler to trigger right after the DMA request has completed, and thus turning the output OFF before the last byte has been transmitted.
Resolves #801
Tests:
=> telemetry driver: clear TC flag before re-enabling TC interrupt

radio/src/gui/128x64/model_setup.cpp
Fixes #656
Looks to be a copy and paste error from the 212x64 radios
=> Use correct index on 128 B&W radios for MPM status

radio/src/gui/128x64/model_setup.cpp, radio/src/gui/212x64/model_setup.cpp
This should fix the annoying sound continuing after binding has been completed on D8 / D16 internal XJT (and maybe others).
=> [bw] set multi binding mode only if multimodule

radio/src/gui/colorlcd/page.cpp, radio/src/gui/colorlcd/tabsgroup.cpp, radio/src/targets/horus/libopenui_config.h, radio/src/targets/nv14/libopenui_config.h
Make it so the invisible 'back' hitbox is bigger, and not linked to header icon size since it's a different sized icon. 
Has been bugging me since #609 ;)
=> Make 'back' hitbox bigger for touch

companion/src/firmwares/boards.cpp, companion/src/firmwares/opentx/opentxeeprom.cpp
Fixes #814
Cause NV14 has no multi position pots
Companion and Simulator testing:
- no shifts for new models created using TS16S, X9D+ and NV14 profiles
- using NV14 profile importing and converting TS16S models and settings
- using X9D+ profile importing and converting NV14 models and settings
=> Fix shift in NV14 switches during Companion import and export

companion/src/radiointerface.cpp
Tested under Ubuntu 20.04.1 with dfu-util v0.11
=> Fixes DFU-Util "Unexpected argument" error

radio/src/gui/colorlcd/screen_setup.cpp
Increase the size of the virtual RTN button on the widgets setup page. 
Especially important for NV14.
=> Increase exit button on the widgets setup page

radio/src/gui/colorlcd/screen_setup.cpp
Currently when user selects a (new) widget the SW returns to the main widget setup screen.
This may be confusing.
This PR after widget selection takes user directly to the widget setup menu.
=> When changing widget go directly to widget settings

radio/src/pulses/pulses.cpp, radio/src/syscalls.c, radio/src/targets/horus/CMakeLists.txt, radio/src/targets/nv14/CMakeLists.txt, radio/src/telemetry/telemetry.cpp
This has been discovered while debugging with the TX18S, hunting #802. It is however not related.
This PR does 2 things:
- make `malloc()` thread-safe in the FreeRTOS context by suspending the scheduler between `__malloc_lock` and `__malloc_unlock`. This assumes that `malloc()` is never used from an ISR, which is our case.
- makes sure that the MPM is started from the UI thread on boot to solves a potential conflict while allocating the protolist singleton related to the module started. Otherwise, the polling loop for telemetry could potentially interfere while the module is not yet fully enabled.
=> Concurrency fixes related to MPM protolist

companion/src/printdialog.cpp
Fixes #854
Fixes in the sense it removes a file format that does not convert the html document generated by the print function with any degree of accuracy
=> Remove odt file format option from print model

companion/src/firmwares/eeprominterface.h, companion/src/firmwares/er9x/er9xinterface.cpp, companion/src/firmwares/er9x/er9xinterface.h, companion/src/firmwares/ersky9x/ersky9xinterface.cpp, companion/src/firmwares/ersky9x/ersky9xinterface.h, companion/src/firmwares/modeldata.cpp, companion/src/firmwares/modeldata.h, companion/src/firmwares/opentx/opentxinterface.cpp, companion/src/firmwares/opentx/opentxinterface.h, companion/src/modeledit/setup.cpp, companion/src/multimodelprinter.cpp
Fixes #843
Edited models in Companion and Simulator checking file names up to 10 chars excl .bmp extn for eeprom and 14 chars inc extn for sd card radios. Tested:
- TX16S
- X9D+
Image list sorted case insensitive to match radio.
Use firmware capabilities rather than specifying boards.
=> Fix companion model edit image names

radio/src/targets/common/arm/stm32/timers_driver.cpp, radio/src/targets/nv14/board.h, radio/src/targets/nv14/lcd_driver.cpp
Fixed:
- delay shortened.
- adjusted priority of IRQs used before FreeRTOS is started.
Resolves #863
=> [nv14] Boot issue fixes

radio/src/gui/colorlcd/draw_functions.cpp
@JimB40 Are `COLOR_THEME_SECONDARY1` for the background color, and `COLOR_THEME_PRIMARY1`  for the animation the right ones to use here? 
One point to consider is that for the default theme, this makes the animation black.
=> Use theme color for poweroff

radio/src/gui/128x64/model_setup.cpp, radio/src/gui/212x64/model_setup.cpp, radio/src/gui/colorlcd/model_setup.cpp, radio/src/pulses/pulses.h
Decided to try to squash an easy bug #733. turns out it was a little more involved. The SBUS refresh rate wasn't adjusting at all, color and B/W. It was incorrectly setting the ppm.framelength value in the GUI instead of sbus.refreshrate
Also removed some numbers to make it (hopefully..) easier to read. Removed a few but now all from PPM too.
I have tested this on my TX16S on the scope. Also found that the maximum default value of 40.0ms period won't work because it overflows the unsigned 16bit when the value is larger than 32.5ms. So I set the maximum to this. I don't think too many people want an SBUS rate that low anyway :)
I have not tested the changes to the B/W models and hopefully someone can confirm if they work :)
=> External RF SBUS refresh rate not functional

radio/src/gui/colorlcd/screen_setup.cpp, radio/src/gui/colorlcd/widget.h, radio/src/gui/colorlcd/widgets/modelbmp.cpp, radio/src/gui/colorlcd/widgets/widgets_container_impl.h, radio/src/translations.cpp, radio/src/translations.h, radio/src/translations/untranslated.h
Add options for text colour, size, fill enable and colour
I've mostly tried this on `simu`,  but also on the TX16S. 
There are a couple of things I would like help with / feedback on:
=> modelBmp options and tweaks

radio/src/gui/colorlcd/model_curves.cpp, radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/page.h, radio/src/gui/colorlcd/view_about.cpp
Fixes #963
Also some screen cosmetic changes
Although it is not strictly necessary to resolve the issue, I would also like to make it so `CurveDataEdit` will touch scroll, as without that the NV14 will not be able to edit more than 5 points on radio. The TX16S has the same issue, but is able to get around that due to hardware keys which will make it scroll.
=> [nv14] Add crash causing missing curveDataEdit

companion/src/generaledit/generalsetup.cpp, radio/src/gui/colorlcd/radio_setup.cpp, radio/src/gui/colorlcd/radio_setup.h, radio/src/opentx.cpp
no more backlight off for color lcd radios
disable backlight input controls in radio setup screen, when they are not used by the selected backlight mode -> needs PR ~~https://github.com/EdgeTX/libopenui/pull/34~~ to work
https://github.com/EdgeTX/libopenui/pull/33
force backlight on to be at least the brightness of backlight off
=> improve backlight handling on color lcd radios

radio/src/main.cpp, radio/src/opentx.cpp, radio/src/targets/horus/board.cpp, radio/src/targets/horus/board.h, radio/src/targets/horus/tp_gt911.cpp, radio/src/targets/horus/tp_gt911.h, radio/src/targets/nv14/board.h, radio/src/targets/nv14/touch_driver.cpp, radio/src/targets/simu/opentxsimulator.cpp, radio/src/targets/simu/simpgmspace.cpp, radio/src/targets/simu/simpgmspace.h, radio/src/touch.h
this PR needs https://github.com/EdgeTX/libopenui/pull/34 to compile and work correctly.
With this PR touch handling is modified to prevent touch events from happening, if the backlight is off.
For this to work, touch drivers now need to return the TouchEvent structure instead of writing into a libopenui global variable.
The interface between touch driver and backlight control now hast to go through libopenui, to be able to filter touch event there, without activating the backlight before libopenui can handle the event.
The touch driver for NV14 got the necessary modifications and compiles, but is untested.
This should close #420
=> Touch backlight handling

radio/src/targets/taranis/bootloader/boot_menu.cpp
Taranis bootloader: menu should not contain 'Restore EEPROM' if EEPROM is not used
=> Taranis Bootloader: Menu fix

radio/src/gui/colorlcd/model_telemetry.cpp
Was trying to calibrate the remote battery voltage today and it was a little more difficult than it should have been without live feedback. 
This pull request adds a <s>footer bar at the bottom</s> header on the telemetry edit screen showing the live value. Font goes red on stale data.
Let me know if this is an okay place for it. Only issue I see is if you use the OSK it hides the footer.
Tested on TX16S.
=> Add live data to Telemetry Edit Screen

companion/src/firmwares/curvedata.cpp
Fixes #1067 (on Companion side)
Assigning the proposed default to an input, mix or output has no effect on the target value and thus is safer especially if applied to a throttle.
Some housekeeping.
=> Companion set new curves (-100,-100) to (100,100)

radio/src/gui/colorlcd/radio_sdmanager.cpp
Fixes #1027 
- use `.c_str()` instead of `.data()` when a 0-terminated string is used.
=> std::string::data() gives no guaranty on 0-termination

radio/src/gui/colorlcd/view_main.cpp
Fixes #1088 
take into account that for multiple main screens the x coordinate may be bigger than the screen width.
=> fix split touch window for carousel #1088

radio/src/gui/colorlcd/listbox.cpp, radio/src/gui/colorlcd/preview_window.h, radio/src/gui/colorlcd/radio_theme.cpp, radio/src/gui/colorlcd/screen_setup.cpp, radio/src/gui/colorlcd/theme.h, radio/src/gui/colorlcd/theme_manager.cpp, radio/src/gui/colorlcd/theme_manager.h, radio/src/gui/colorlcd/themes/480_default.cpp
Please note that pull requests are NOT an appropriate way to ask questions or support.
Fixes #1064 
1. Fix KEY_EXIT processing when theme changed
2. Also fixes some color issues on ListBox()
3. Fixes various issues with PreviewWindow()
4. theme file structure implementation to match #897 
5. Sort theme names
6. changed touch handling on Theme List.  You now need to long-press to bring up the menu.
7. Added more controls to PreviewWindow()
=> Fix theme editor

radio/src/targets/common/arm/stm32/stm32_hal_adc.cpp
Forgot to handle X9E in my FlySky gimbal auto-detection. According to feedback from Discord, this PR fixes it for X9E: https://discord.com/channels/839849772864503828/839856795781431317/911686864237396029
=> Fix building for X9E

radio/src/targets/common/arm/stm32/mixer_scheduler_driver.cpp
The max period is now 50ms, so that it overflows the 16bit timer when set to the max period.
Many thanks to @marianomd for finding the issue and the proposed fix!
=> Fixed mixer scheduler timer overflow

radio/src/gui/128x64/lcd.cpp, radio/src/gui/212x64/lcd.cpp, radio/src/targets/taranis/board.cpp, radio/src/targets/taranis/board.h, radio/src/targets/taranis/bootloader/boot_menu.cpp
Fixes #1031 
Taranis based radios with B/W screens now have LCD_CONTRAST_DEFAULT initialization in bootloader and normal startup.
This prevents 'unreadable (too low or too high contrast' screen in bootloader and 'blink' after 'dots' on Jumper T-Lite and other similar radios.
=> Taranis-based B/W: Initial Contrast fix

radio/src/targets/horus/tp_gt911.cpp, radio/src/targets/nv14/touch_driver.cpp
fixes deltaX and deltaY values in touch events not being resetet
=> fix touch slide deltaX/deltaY not resetting

tools/build-font-bitmap.py
So timers etc. do not jump back and forth. Assumes that 4 is the widest digit.
=> Monospaced font for digits

radio/src/gui/colorlcd/radio_sdmanager.cpp, radio/src/gui/colorlcd/radio_sdmanager.h, radio/src/io/multi_firmware_update.h
Completely stab in the dark implementation based on OTX code and no hardware to test. `simu` seems to identify a frsk file as the correct update type. 
More work is needed to integrate/test the remaining menu items
May just be a matter of correct parameters for deviceFirmwareUpdate
=> Hacky port of FRSKY_FIRMWARE_EXT update menu

radio/src/lua/api_model.cpp, radio/src/storage/conversions/conversions_220_221.cpp, radio/src/storage/sdcard_yaml.cpp, radio/src/storage/sdcard_yaml.h
Proposal to add a `filename` table element to model.getInfo, so that the yaml filename can be used in a lua script.
Resolves #1065 
Tested as functional on TX16S (colourlcd) and TX12 (B&W).
@raphaelcoeffic I'm not particularly happy just copying and pasting the `getModelNumberStr` function in... is there a better way to do this?
Test script:
```lua
local w, h
local function run(event)
lcd.clear()
local info = model.getInfo()
if LCD_H > 64
w, h = lcd.sizeText("Model Info")
else
h = 8
end
lcd.drawText(1, 0, "Model Info")
if info['name'] then
lcd.drawText(1, h*2, "Name: "..info['name'])
else
lcd.drawText(1, h*2, "Name: none")
end
if info['bitmap'] then
lcd.drawText(1, h*3, "Bitmap: "..info['bitmap'])
else
lcd.drawText(1, h*3, "Bitmap: none")
end
if info['filename'] then
lcd.drawText(1, h*4, …
```
=> Add filename to lua `model.getInfo()`

radio/src/thirdparty/Lua/src/linit.c
Resolves #1141 
- Enable lua table library for all colorlcd targets, not just Horus-style targets
- Firmware size change: 1397888 => 1402632
Tested with following on both TX16S and NV14 hardware. 
```lua
local toolName = "TNS|Table Sort Test|TNE"
local function run(event)
local t = {5,4,3,2,1}
local w, h = 0, 0
local x, y = 0, 0
-- Lazy B&W test
if LCD_H > 64 then
w, h = lcd.sizeText("M")
else
w, h = 8, 8
end
lcd.clear()
x = 5
lcd.drawText(x, h*1, "Unsorted table")
for k in pairs(t) do
x = w*k + 5
lcd.drawText(x, h*2, t[k])
end
table.sort(t)
x = 5
lcd.drawText(x, h*4, "Sorted table")
for k in pairs(t) do
x = w*k + 5
lcd.drawText(x, h*5, t[k])
end
return 0
end
return {run=run}
```
Thanks to @JimB40 for the initial skeleton ;)
=> Enable lua `table`  for colorlcd, not just horus style targets

radio/src/gui/colorlcd/special_functions.cpp
Fixes #1145
Summary of changes: SF overrides limits made dependent  on the model extended limits.
=> fix SF override limts #1145

radio/src/audio.cpp, radio/src/opentx.cpp
This will resolve the recent comments about audio being played out of sequence. 
Whilst Lua still manages to play before the welcome, this is also a OTX behaviour, and I suspect could be because Lua scripts and widgets start before the audio queue.
=> Play "Welcome to..." before switch checks, SF

radio/src/storage/yaml/yaml_datastructs_funcs.cpp
This should fix an issue which effected that a delay on an "Edge" logical switch would not be read properly if less than 1 second, which correspond to a 1 digit delay (tenth of seconds).
=> Fix reading second delay for single digit (< 1s)

radio/src/gui/colorlcd/colors.h, radio/src/lua/api_colorlcd.cpp
Fixes #1134 at least partially
Summary of changes: if lua script uses colorFlag==0 use PRIMARY1 color instead of default color.
The change effects lua scripts only.
=> Use COLOR_THEME_PRIMARY1 as a default lua script color

radio/src/bluetooth.cpp
In XOR state only 0x7E ^ 0x20 = 0x5E or 0x7D ^ 0x20 = 0x5D are expected.
Copy of my https://github.com/opentx/opentx/pull/8427
=> Bluetooth trainer byte parsing: catch XOR state errors

radio/src/gui/colorlcd/widget.cpp
As discussed on Discord with @pfeerick  and @lshems
=> Removed the call to update() when widget leaves fullscreen mode

radio/src/gui/colorlcd/fullscreen_dialog.cpp, radio/src/opentx.cpp, radio/src/opentx.h
Fixes #206 
also adds a close condition callback to the confirmation dialog
=> fix auto power off on cleared warning trigger

radio/src/targets/common/arm/CMakeLists.txt, radio/src/targets/horus/CMakeLists.txt, radio/src/targets/nv14/CMakeLists.txt, radio/src/targets/taranis/CMakeLists.txt
Resolves #1159
This allows for configuring the available internal modules via cmake as follows:
```
cmake -DPCB=X7 -DPCBREV=T12 -DINTERNAL_MODULES="PXX1;PXX2" -DGHOST=OFF -DAFHDS3=OFF -DCROSSFIRE=OFF ...
```
Please note that `-DCROSSFIRE` will disable the CRSF on the external module interface. Without removing CRSF from the internal modules, it would automatically activate support for CRSF, and thus override `-DCROSSFIRE`.
=> Make list of supported internal module configurable per cmake option

radio/src/gui/colorlcd/tabsgroup.cpp, radio/src/gui/colorlcd/tabsgroup.h
Fixes #298 
handle slide events on the tab bar and ignore touch end event with old coordinates when touch ends.
Please check on NV14
=> 298 keys stuck

radio/src/lua/api_general.cpp, radio/src/opentx.h, radio/src/opentx_helpers.h, radio/src/switches.cpp
Here is another go at adding a Lua function to set the value sticky logical switches (Issue #817). It uses a circular buffer to send data from Lua to `logicalSwitchesTimerTick()`.
@raphaelcoeffic @rotorman please review!
=> Take 2 on Issue817

radio/src/gui/colorlcd/draw_functions.cpp, radio/src/gui/colorlcd/theme_manager.h
Resolves #874
- add `isDefaultTheme()` bool to ThemePersistance()
- Use COLOR_THEME_SECONDARY1 as background, COLOR_THEME_PRIMARY2 as foreground colours for shutdown screen (i.e. the same as the top bar background colour and top bar icon colour) unless using default theme. In that case, it uses a black background, and white foreground. 
Based on the results of the poll on Discord, of the ~35 respondents, 31 were in favour, and none not in favour of the shutdown screen being themed. I believe the remain four were basically wondering why I even asked... if not, be warned, I know you you are! 😆 
https://discord.com/channels/839849772864503828/839849772864503832/910109100115902514
=> Use theme colours for shutdown animation/screen

radio/src/gui/common/stdlcd/radio_hardware.cpp
Remove blanks lines for BACKUP_EEPROM & FACTORY_RESET, which are later disabled. 
Used to be this pre-yaml:
which became this:
and will now be:
=> [B&W] Don't add entries for non-existant rows

fw.json
Added trailing - on access radio versions to fix the naming on saved files.
x7-edgetx-v2.5.0 would stay
x7-accessedgetx-v2.5.0 would change to x7-access-edgetx-v2.5.0
Fixes EdgeTX/flasher#36
=> Fix filename when saved manually via flasher.

radio/src/gui/colorlcd/tabsgroup.cpp
Fixes crash on tab group sub page access/exit and not working access to top bar elements that are on top of tab bar tab icons
Fixes #1203
=> fix crash on tab group sub page access/exit

radio/src/opentx.cpp
e.g. where before a complete wipe or unsupported upgrade path failure
failed to enable NV14 internal module by default.
This was tested by attempting to upgrade the NV14 from OpenFlysky OTX 2.1 and also by simply deleting all the yaml configuration files. Prior to this PR, it would result in internalModule being off, now it correctly sets it to Flysky.
=> Ensure stock internal module is used as default if defined

radio/src/datastructs.h, radio/src/datastructs_private.h, radio/src/gui/colorlcd/model_setup.cpp, radio/src/opentx.h, radio/src/storage/yaml/yaml_datastructs_nv14.cpp, radio/src/storage/yaml/yaml_datastructs_t12.cpp, radio/src/storage/yaml/yaml_datastructs_t8.cpp, radio/src/storage/yaml/yaml_datastructs_tlite.cpp, radio/src/storage/yaml/yaml_datastructs_tx12.cpp, radio/src/storage/yaml/yaml_datastructs_x10.cpp, radio/src/storage/yaml/yaml_datastructs_x12s.cpp, radio/src/storage/yaml/yaml_datastructs_x7.cpp, radio/src/storage/yaml/yaml_datastructs_x9d.cpp, radio/src/storage/yaml/yaml_datastructs_x9e.cpp, radio/src/storage/yaml/yaml_datastructs_x9lite.cpp, radio/src/storage/yaml/yaml_datastructs_x9lites.cpp, radio/src/storage/yaml/yaml_datastructs_xlite.cpp, radio/src/storage/yaml/yaml_datastructs_xlites.cpp
Fixes #1124 
1. Do not display non-existent potentiometers in the warnings group.
2. Increase the size of the potsWarnEnabled field in the ModelData to 16 bits in order to save all possible potentiometers and sliders.
=> pots warning enabled fix

radio/src/gui/colorlcd/radio_tools.cpp, radio/src/targets/nv14/CMakeLists.txt
- enable GHOST on NV14 so is the same as horus colorlcd targets
- re-enabled GHOST tools config entry, for further testing, until Lua alternative available (#577)
=> NV14 Ghost and Tools config entry

radio/src/opentx_types.h
Fixes #806 
Summary of changes: change data type of source_t from uint8_t to uint16_t. 
One byte is not sufficient any more for all sensor sources.
I do not understand why it works for other targets, but apparently it does.
Most likely, almost everything is considered to be PCBFRSKY. :-)
=> change source_t from uint8_t to uint16_t for NV14. #806

radio/src/gui/colorlcd/menu_model.cpp, radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/model_mixes.cpp
Fixes where  `FLIGHT_MODES=N` leaves UI elements visible
- model setup tab
- model mixes flight mode controls
- model inputs flight mode controls
=> Fix UI elements left visible when `FLIGHT_MODES=N`

radio/src/bluetooth.cpp, radio/src/bluetooth.h, radio/src/targets/common/arm/CMakeLists.txt, radio/src/targets/common/arm/stm32/bluetooth_driver.cpp
Bluetooth prints a ridiculous amount of data with or without debug turned on. It's currently writing every byte received. Fills the console so quick you can't see anything else happening.
This pull request only prints that data if specifically requested via a cmake option.
Printing of every byte is completely removed.
=> Add a DEBUG_BLUETOOTH option to clean up console

radio/src/targets/nv14/touch_driver.cpp
TE_UP needs to be reset to TE_NONE after touch read from MainWindow. If this is not done, the TE_UP event is handled multiple times
This fixes the NV14 touch sensitivity problem.
fixes #1245
=> Fix NV14 touch behavior.

companion/src/mainwindow.cpp, companion/src/process_sync.h
Fixes #1072
Summary:
On change of profile :
- default local folder to current profile
- force re-probe for an attached radio
=> Reset sdcard sync local folder and radio on change of profile

radio/src/gui/colorlcd/radio_ghost_module_config.cpp, radio/src/gui/colorlcd/radio_ghost_module_config.h
A temporary fix while the Ghost menus are ported to their Lua form, this restores the EdgeTx Ghost Menus to a functioning state. 
Add code to catch the GHST_MENU_STATUS_CLOSING message sent from the Ghost module when the EdgeTx Ghost menu can be close (backing out of the root menu).
=> Fix Return behavior on Ghost Menus

radio/src/gui/colorlcd/gvar_numberedit.h, radio/src/gui/colorlcd/model_outputs.cpp
Fixes #1254
Summary of changes: second variant of the fix. Alternative to PR 1255. Please select. :-)
Get rid of the typedef in gvars_numberedit.h.
=> Fix outputs  max/min without GVARS ver.2 #1254

radio/src/targets/horus/board.h
Fixes #1239
Apply same power delay for T16 as TX18S, as it seems at least some (perhaps the early version?) of the T16 suffers from the same power supply instability.
=> Add power delay for when turning on MPM for T16

radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/colorlcd/switch_warn_dialog.cpp, radio/src/gui/colorlcd/switch_warn_dialog.h, radio/src/switches.cpp, radio/src/switches.h
Fixes #1277 
Summary of changes: it was rather messy. :-)
=> Fix pots and sliders warning #1277

radio/src/switches.cpp
Fixes #1301 
Summary of changes: add definitions for NV14 switches for CF support
=> Add switches definitions for NV14 #1301

radio/src/gui/128x64/radio_diagkeys.cpp, radio/src/gui/common/stdlcd/radio_hardware.cpp, radio/src/strhelpers.cpp, radio/src/targets/taranis/keys_driver.cpp
Two connectors are present on TX12 main board (near top of internal TX module) and are mapped as SI (2) and SJ (1), but were not read out by the firmware.
With this update they might be used for some further hacking of the radio (ex. adding additional 2-pos switches, adding detector of external module insertion etc.).
Resubmitted PR #1302 
- Add readout of SI and SJ switches in switchState
=> Fixed support for Radiomaster TX12 additional switches (SI and SJ)

companion/src/apppreferencesdialog.cpp, companion/src/apppreferencesdialog.ui, companion/src/firmwares/boards.cpp, companion/src/firmwares/boards.h, companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/generalsettings.cpp, companion/src/firmwares/generalsettings.h, companion/src/firmwares/moduledata.cpp, companion/src/firmwares/moduledata.h, companion/src/generaledit/hardware.cpp, companion/src/mainwindow.cpp, companion/src/modeledit/setup.cpp, companion/src/modeledit/setup_module.ui, companion/src/storage/appdata.h
Based on ~~main~~ Companion YAML branch ~~as not sure where yaml would be at and it compiles~~.
Things to do:
=> Add support for internal module to Companion

radio/src/gui/colorlcd/radio_version.cpp, radio/src/opentx.h, radio/src/stamp.cpp
Resolves #1081
- EEPR => CFGV
- eeprom_stamp => cfgv_stamp
- updated strings correspondingly
- some auto formatting
=> Remove reference to EEPROM / EEPR in radio version screen

radio/src/gui/colorlcd/radio_hardware.cpp, radio/src/gui/common/stdlcd/radio_hardware.cpp, radio/src/opentx.h
Resolves #1299 
Ensures if you change the internal module at the radio level, that the currently active model internal rf settings are cleared, thus inhibited. This is not needed on model load, as there is a model load check which inhibits the dissimilar settings being made active. 
- On colorlcd, if you chose an option for the internal protocol other than the current one, the active model level setting is cleared  - so you can view the list and abort or re-select the current internal module without loosing any settings.
- On B&W, as soon as you scroll to see any other internal protocol other than the currently selected one, the active model level setting is cleared. Due to how the menu is displayed, you can't view the list without the setting being cleared. 
Tested on …
=> Clear internal RF module settings if radio level setting changed

radio/src/lua/api_general.cpp, radio/src/lua/lua_api.h
- `getfieldInfo` can now also take a source index as argument. Plus it was modified to also handle "telem1+" etc.
- New functions `getSourceIndex(sourceName)` and `getSourceName(sourceIndex)` were added, which use the names shown on the screen instead of the special names table used by `getFieldInfo` and `getValue`.
- Indices are the same for all of the functions, so `getValue(sourceIndex)` also works with indices from `getSourceIndex`.
- New iterator functions `sources([first[, last]])` and `switches([first[, last]])` for getting ranges of sources and switches with a `for` loop.
- `getPhysicalSwitches` was removed, as I consider the iterator function to be a better solution.
=> Issue #1285

radio/src/storage/yaml/yaml_bits.cpp
Avoids overflowing when the bit mask should be 32bits long.
Resolves #1351
=> Fix bit mask generation

companion/src/firmwares/edgetx/yaml_trainerdata.cpp
Resolves #1349
Fixes reading this:
```yaml
trainer: 
calib: 
2:
val: -512
3:
val: -3
mix: 
0:
srcChn: 3
mode: ADD
studWeight: 100
1:
srcChn: 1
mode: ADD
studWeight: 100
2:
srcChn: 2
mode: ADD
studWeight: 100
3:
srcChn: 0
mode: ADD
studWeight: 100
```
=> YAML Trainer data: iterate through nodes rather than assuming their presence

radio/src/telemetry/flysky_nv14.cpp
Fixes #1097 
Summary of changes: if the RM FW version is old and the Sgnl value is low [0, 10] use scaled RSSI (OTX formula) for alarm.
=> Improve support for old NV14 Radio Module FW

radio/src/gui/colorlcd/fullscreen_dialog.cpp, radio/src/opentx.cpp, radio/src/switches.cpp
Resolves #470 
Show warning led color (i.e. red) with throttle warning, switch warnings, and alerts generally, e.g. 
- Failsafe not set
- MULTI Low power warning
- RTC low battery warning
- storage conversion warning
=> Show warning LED with switch and throttle alerts

radio/src/targets/common/arm/stm32/stm32_hal_adc.cpp
Checked with in-circuit-debugger on physical RM TX16S, only after this fix, _isVBatBridgeEnabled()_ returns false, otherwise VBat bridge remained active.
=> Disable RTC VBat bridge after first run

radio/src/opentx.cpp
Fixes #1271 
Summary of changes: During the boot check for stuck key and display FullScreenDialog with the warning and the name of the key that causes the problem.
The message is displayed for ~5 seconds and goes away (as for b/w TX) or can be cleared by RTN or ENTER (or touch).
=> Stuck key test for COLORLCD #1271

companion/src/firmwares/edgetx/edgetxinterface.cpp, companion/src/modelslist.cpp, companion/src/radiointerface.cpp, companion/src/storage/categorized.cpp
Changes:
- properly catch YAML load exception
- fall back to scanning the `/MODELS` directory in case `models.yml` cannot be loaded.
=> Fallback to model file scanning if models.yml cannot be read

radio/src/gui/colorlcd/view_main_decoration.cpp, radio/src/strhelpers.h
Temporary reversion of EdgeTX/edgetx#1337 as it causes Mac Companion builds to fail when building `libsimulator`
https://github.com/EdgeTX/edgetx/runs/4755792840
=> Revert "Potential out of bounds access of flightmode name on main screen (#1333)"

radio/src/opentx.cpp, radio/src/storage/sdcard_common.h, radio/src/storage/sdcard_yaml.cpp
This PR reads the radio settings early enough so that the power on delay can be properly evaluated. However, this introduces an additional delay (mount SD card + read settings) which is quite noticeable.
A better implementation should use settings in EEPROM / FLASH to get rid of this delay. Similar techniques could be used for some settings which are needed early on color radios.
Resolves #1366
=> Load radio settings before power on delay is evaluated

companion/src/modeledit/colorcustomscreens.cpp, companion/src/modeledit/modeledit.cpp
- re-enable custom screens disabled in yaml PR
- change themes to use sd card
Note: if the profile sd card is not a copy of the radio sd card then Companion has the potential to display the incorrect theme.
Future enhancement is for read models and settings from radio to also copy the /THEMES/selectedtheme.txt file to the etx file.
=> Companion re-enable custom screens with sd card themes

companion/src/firmwares/boards.cpp, companion/src/firmwares/boards.h, companion/src/firmwares/moduledata.cpp, companion/src/generaledit/generaledit.cpp, companion/src/generaledit/generaledit.h, companion/src/generaledit/hardware.cpp, companion/src/generaledit/hardware.h, companion/src/mainwindow.h, companion/src/mdichild.cpp, companion/src/mdichild.h, companion/src/modeledit/modeledit.cpp, companion/src/modeledit/modeledit.h, companion/src/modeledit/setup.cpp
- allow user the opportunity cancel hardware internal module update
- after hardware change, check and update all models internal module protocol to OFF if incompatible
- on model edit load, check and update model internal module protocol to OFF if incompatible
- fixed: do not allow radio settings to be edited whilst any models are in edit mode ~~(requires internationalization testing)~~
- fixed: prevent multiple edit instances of same model ~~(requires internationalization testing)~~
- fixed: destroy model edit dialog on close and reduce memory bloat
- fixed: change Edit Radio Settings to modal dialog
=> Companion hardware internal module continued

companion/src/storage/categorized.cpp
Fixes #1384
- Fixes issue whereby Companion was writing bin files with yml extension
=> [companion] fix: only write yaml to radio, not bin

radio/src/opentx.cpp
Fixes #1407
Checking only key presses for closing throttle warning instead of any event.
This replicates the behavior for switch warning.
=> Rotary encoder movement not to close throttle warning

radio/src/gui/colorlcd/radio_setup.cpp, radio/src/opentx.cpp
When configuration is broken it can happen, that on Color LCD radios the backlight is set to off and/or the brightness is set to off and/or the backlight timer is set to 0.
All of those conditions render the radios unusable.
These changes enforce usable backlight settings, even when they are overwritten by functions or lua scripts.
=> force a valid backlight on setting on color lcd radios

radio/src/lua/widgets.cpp
Fix wrong x-coordinate for Lua touchState during sliding on mainviews other than the first screen
Fix for issue #1348 as discussed on https://github.com/EdgeTX/libopenui/pull/49
=> Fix wrong x-coordinate for Lua touchState during sliding

radio/src/gui/gui_common.cpp
Currently, if your 6POS is not calibrated correctly, you cannot select anything but the first position in switch select drop-downs, because `isSwitchAvailable()` verifies that the 6POS has the number of calibrated positions before letting you choose these positions, which is an issue in simulation, as you cannot really calibrate the 6POS properly.
Further, I think it might be confusing to not be able to select a switch position just because the calibration is off.
This PR removes the check for calibrated positions.
=> Remove calibration check when asserting availability of 6-pos switch positions

radio/src/gui/colorlcd/widgets/outputs.cpp
This fixes the initally reported problem in issue #1103.
Changed code to allow one column display of outputs already with a width of 100. 
Reason: On the Nirvana the screen width is 320 pixels. Thus the widget width is less than 150 pixels, if you select a two column out layout.
The rendering of the outputs looks good with a width of 100px, so there is no need for the "150" - we can start displaying from 100. Should make no difference to the radios with width 480px.
=> Make Outputs work with NV14 & two rows

radio/src/targets/taranis/board.cpp
New Zorro revision uses internally 3.3V VREF and requires this change to properly sense the battery voltage. Tested on latest revision of physical Zorro. (Do note that with this fix, the battery values output on earlier prototype versions will require explicit manual offset calibration.)
=> Fixed Zorro battery voltage sensing

.github/workflows/win-cpn-32.yml, .github/workflows/win_cpn.yml
- enable caching for QT install for Windows actions, which should mitigate the download failures causing the actions to fail periodically
You can see the results here 
- [initial run which needs to complete successfully in order for the cache to be preserved](https://github.com/pfeerick/edgetx/runs/4812194015?check_suite_focus=true) 
- [subsequent run which uses the cache instead of re-downloading](https://github.com/pfeerick/edgetx/runs/4814176473?check_suite_focus=true)
Also, this PR itself, if it is lucky enough to build successfully, should create the initial cache.
=> Github Actions for Windows Companion - Qt cache

radio/src/gui/colorlcd/radio_ghost_module_config.cpp, radio/src/targets/nv14/board.h, radio/src/targets/nv14/keys_driver.cpp, radio/src/targets/simu/simpgmspace.cpp
Enabled the ghost menu to work with the NV14 joystick trims like in lua (for non-touch luas). 
Changed layout to work with NV14.
Cleaned the code tn the NV14 key_driver.cpp
=> Make Ghost menu work with NV14 joystick trims

radio/src/gui/colorlcd/fullscreen_dialog.cpp, radio/src/gui/colorlcd/radio_setup.cpp
Fixes #1428
when displaying a full screen dialog on color lcd radios, the backlight is forced on and therefore the touch screen is enbaled, if the radio has one.
=> force backlight on when displaying full screen dialogs

CMakeLists.txt, radio/src/storage/yaml/CMakeLists.txt
Makes EdgeTx (firmware, companion, simulator) build on M1 macs.
In addition to the dependencies described on the Wiki page, a build on a M1 based Mac requires the following to set the CMake environment variable:
export CMAKE_APPLE_SILICON_PROCESSOR=arm
=> Make compilation on M1 Macs work

radio/src/gui/colorlcd/model_setup.cpp
Summary of changes: for NV14 RANGE dynamic dialog actually shows Sgnl rather  than RSSI and it is better (for NV14), since Sgnl is linear rather than logarithmic and thus more sensitive.
This PR changes the name of the telemetry value displayed and removes DB units for NV14.
Other targets are not affected.
=> Change range units label for NV14

radio/src/gui/common/stdlcd/draw_functions.cpp, radio/src/gui/common/stdlcd/draw_functions.h, radio/src/opentx.cpp
- when a B&W radio is started without a mountable SD card, the following screen is displayed:
=> Add a "No SD card" screen on boot

radio/src/targets/horus/tp_gt911.cpp, radio/src/targets/nv14/touch_driver.cpp
No more continuing TE_SLIDE_END events after sliding with inertia
reset tapCount in NV14 touch driver for TE_SLIE_END events, as this is incompatible with full screen lua events
Needs PR [libopenui#50](https://github.com/EdgeTX/libopenui/pull/50)
=> fix TE_SLIDE_END repetition issue, reset tapCount on NV14

radio/src/gui/colorlcd/model_select.cpp, radio/src/opentx.cpp, radio/src/opentx.h
Fixes #1466 
This PR adds a warning "Model is still connected" when user attempts to select a new model (on color LCD TXs).
Summary of changes: audio message and confirmation dialog are added.
=> Warn on connected model (#1466)

.github/workflows/linux_cpn.yml, .github/workflows/macosx_cpn.yml, .github/workflows/win-cpn-32.yml, .github/workflows/win_cpn.yml, tools/build-gh.sh, tools/commit-tests.sh, tools/generate-yaml.sh
I wanted to contribute to edgetx somehow and was going over the bash and python files when I spotted a small bash issue which could cause a little bit of trouble in the future, that is if anybody tries to run those from a folder that contains whitespaces.
I'm not familiar enough of edgetx yet to know how likely that is to happen, the github workflows are probably safe but the ones under tools/ seems to be more exposed, in anycase the fix is straightforward and there's no downsides to it.
Please also let me know if you would be interested in PRs porting the python2 scripts to python3, pep8 fixes and fixes to other shellcheck findings. I could contribute more to these areas.
Commit message below:
These invocations will all cause bugs when pwd returns something that
can be interpreted by …
=> Fix bash's word-splitting bugs when parsing the result of pwd command

radio/src/datastructs_private.h, radio/src/gui/128x64/model_setup.cpp, radio/src/gui/212x64/model_setup.cpp, radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/gui_common.h, radio/src/pulses/ghost.cpp, radio/src/storage/conversions/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_datastructs_nv14.cpp, radio/src/storage/yaml/yaml_datastructs_t12.cpp, radio/src/storage/yaml/yaml_datastructs_t8.cpp, radio/src/storage/yaml/yaml_datastructs_tlite.cpp, radio/src/storage/yaml/yaml_datastructs_tpro.cpp, radio/src/storage/yaml/yaml_datastructs_tx12.cpp, radio/src/storage/yaml/yaml_datastructs_x10.cpp, radio/src/storage/yaml/yaml_datastructs_x12s.cpp, radio/src/storage/yaml/yaml_datastructs_x7.cpp, radio/src/storage/yaml/yaml_datastructs_x9d.cpp, radio/src/storage/yaml/yaml_datastructs_x9e.cpp, radio/src/storage/yaml/yaml_datastructs_x9lite.cpp, radio/src/storage/yaml/yaml_datastructs_x9lites.cpp, radio/src/storage/yaml/yaml_datastructs_xlite.cpp, radio/src/storage/yaml/yaml_datastructs_xlites.cpp, radio/src/storage/yaml/yaml_datastructs_zorro.cpp, radio/src/telemetry/ghost.cpp, radio/src/telemetry/ghost.h
* Add 4 new frames with scaling that supports up to 12bit resolution (currently it transfers 11bit -1024:1024 as EdgeTx provides)
* Add checkbox in model setup menu to enable/disable new 12 bit mode.
* BF 4.3 and Ghost FW V1.0.5.2+ is needed.
Benefits:
* smoother feedforward
* smoother flight
Fixes:
* truncation errors with old scaling
Betaflight PR
https://github.com/betaflight/betaflight/pull/10801
OpenTx commit about this
https://github.com/opentx/opentx/commit/0b699e6f614f788f3e5134a8e69dfad550770e2e
Thanks @tonycake for support and help. @3djc for OpenTx implementation.
=> IRC Ghost 12 bit support

radio/src/datastructs_private.h, radio/src/gui/128x64/model_setup.cpp, radio/src/gui/212x64/model_setup.cpp, radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/gui_common.h, radio/src/lua/api_general.cpp, radio/src/pulses/ghost.cpp, radio/src/storage/conversions/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_datastructs_nv14.cpp, radio/src/storage/yaml/yaml_datastructs_t12.cpp, radio/src/storage/yaml/yaml_datastructs_t8.cpp, radio/src/storage/yaml/yaml_datastructs_tlite.cpp, radio/src/storage/yaml/yaml_datastructs_tpro.cpp, radio/src/storage/yaml/yaml_datastructs_tx12.cpp, radio/src/storage/yaml/yaml_datastructs_x10.cpp, radio/src/storage/yaml/yaml_datastructs_x12s.cpp, radio/src/storage/yaml/yaml_datastructs_x7.cpp, radio/src/storage/yaml/yaml_datastructs_x9d.cpp, radio/src/storage/yaml/yaml_datastructs_x9e.cpp, radio/src/storage/yaml/yaml_datastructs_x9lite.cpp, radio/src/storage/yaml/yaml_datastructs_x9lites.cpp, radio/src/storage/yaml/yaml_datastructs_xlite.cpp, radio/src/storage/yaml/yaml_datastructs_xlites.cpp, radio/src/storage/yaml/yaml_datastructs_zorro.cpp, radio/src/telemetry/ghost.cpp, radio/src/telemetry/ghost.h
Add support for MSP with Ghost protocol.
`luaGhostTelemetryPush` and `luaGhostTelemetryPop` similar to CRSF version.
Need new Ghost FW v1.0.6.0+
New features:
- Betaflight LUA Scripts will work https://github.com/betaflight/betaflight-tx-lua-scripts/pull/419
- We can create LUA script for Ghost setup later
BF: https://github.com/betaflight/betaflight/pull/11242
Agreed with @raphaelcoeffic to put it to ETX 2.7.
Merge after https://github.com/EdgeTX/edgetx/pull/1233
FYI: @tonycake @TheIsotopes
=> Ghost MSP support

companion/src/firmwares/rawsource.cpp, companion/src/firmwares/rawswitch.cpp
=> Companion use default hardware name when name only spaces

radio/src/gui/128x64/model_setup.cpp, radio/src/gui/212x64/model_setup.cpp, radio/src/pulses/crossfire.cpp, radio/src/telemetry/telemetry.cpp
For internal CRSF modules, the modelid ("Receiver") set in the Model Setup was not properly being sent to the internal module. It always stays modelid 0. 
* The colorlcd variant had the proper code to trigger the send, but the B&W screens would always trigger a send for the EXTERNAL module, which would never fire. This updates the trigger to apply to the correct module. (`model_setup.cpp`)
* The actual send code would always use the EXTERNAL module's `modelId` when generating the CRSF packet. Updated to use the correct module's modelId. (`crossfire.cpp`)
* When there's a telemetry KO -> OK transition, the code would trigger sending the modelId to the EXTERNAL module always. I've changed it to trigger it on either or both modules, whichever are CRSF-type, I'm not 100% sure on this change …
=> Send correct internal CRSF modelid on change for B&W screens

radio/src/gui/colorlcd/listbox.cpp, radio/src/gui/colorlcd/listbox.h
This pull request allows the listbox to be a multi select widget. For use in model labels. Separated for use in LVGL modifications at @kevinkoenig request.
Sets Mutliselect mode with setSelectionMode(LISTBOX_MULTI_SELECT);
Allows a callback function setMultiSelectHandler() which passes list of selected indexes on change.
When in multiselect mode a dashed outline will show the focus line. Also as indicator when listbox has focus.
=> Listbox multiline selectable

companion/src/storage/appdata.cpp
When companion cannot find app settings matching its version it goes looking for older settings to import and if necessary upgrade. This generally occurs when companion first installed or a version upgrade occurs.
The search method relies upon a fixed list of previous versions however due to the rapid pace of ETX development this created a need to continually maintain the versions list.
This PR replaces the hardcoded version list with an iterative decrementing search starting with its version minus one and looking as far back as the first version of EdgeTX i.e. 2.4
=> Improve searching for previous versions of companion app settings

radio/src/targets/nv14/keys_driver.cpp
Fixes NV14 bootloader navigation no longer working
- #1416 broke bootloader navigation - and for some reason setting the default value for `getTrimsAsButtons()`, subsituting the function or setting or `trimsAsButtons` when in BOOT is not working with the bootloader.
=> fix: NV14 bootloader navigation not working

radio/src/gui/colorlcd/model_mixer_scripts.cpp, radio/src/lua/interface.cpp, radio/src/switches.cpp
The default values of VALUE inputs in the input table of a mixer script were used as a offset, not as a default value.
=> Fix handling default values of VALUE inputs of mixer scripts

radio/src/gui/colorlcd/special_functions.cpp
This PR fixies a jump from !1x to 60s when editing the "repeat" field for SF setup
Fixes #1539 
Summary of changes: convert uint8_t field in the cfn structure to int8_t when providing value to NumberEdit(), since the valid range is [-1, 60].
=> fix SF repeat field problem (#1539)

radio/src/gui/common/stdlcd/radio_hardware.cpp, radio/src/targets/taranis/board.h
Fixes some TX12 specific issues observed near the end of or post 2.6.0
- fixes inabliity to set SE or SF as 3POS as reported in discord by SS64
- fixes default contrast (used in bootloader, and during boot) being way too high/dark since #1099
=> Tx12-fixes

radio/src/gui/colorlcd/model_setup.cpp
Behaviour with this PR (example with SIYI HM30 that transmits via S.PORT in the protocolName field "HM30\0\0\0"):
Old behaviour without this PR:
For comparison OpenTX 2.3.14:
Following function call was missing in EdgeTX:
https://github.com/opentx/opentx/blob/801b28958045d683b8c8058db5c167ae0c39da65/radio/src/gui/480x272/model_setup.cpp#L1080
String extraction:
https://github.com/opentx/opentx/blob/801b28958045d683b8c8058db5c167ae0c39da65/radio/src/gui/480x272/lcd.cpp#L455-L458
=> List ProtocolName next to Mode: MULTI

radio/src/lua/api_model.cpp
When GV was set to e.g. `FM0` , `setGlobalVariable` would change it to own value. Now it will keep using FMx and adjust it accordingly
=> Fixed bug in Lua get/setGlobalVariable

radio/src/targets/taranis/CMakeLists.txt, radio/src/targets/taranis/board.cpp
Fixed ZORRO's date and time reset issue https://github.com/EdgeTX/edgetx/issues/1588
Added judgment on BOR LEVEL to fix the date and time reset issue in a simple way, for Zorro already owned by the user, updating the firmware is the most convenient way.
I have used various destructive tests, none of which will cause the date and time to reset.
So I think, TX16S and other radios, sometimes directly unplugging the battery or some unconventional operations, will cause the firmware to be damaged and unable to boot, which is also related to this BOR LEVEL.
=> Fixed ZORRO's date and time reset issue #1588

radio/src/lua/api_model.cpp
Compile option breakage from #1602
Fixes #1644
- Removes LUA `getGlobalVariable` and `setGlobalVariable` functions if running a `GVARS=NO` firmware build
=> fix: Disable LUA GV funcs if `GVARS=NO` build

radio/src/gui/128x64/model_flightmodes.cpp
look at the bottom line from flight modes. found this on rm zorro
before:
after:
=> fixed cosmetic in flight modes

radio/src/gui/colorlcd/model_outputs.cpp
Fixes #1652 
Summary of changes: move call to Windows::checkEvents() to after update() call.
This fixies erratic behavior of the rotary selector on the outputs screen.
Maybe fixies  #1639 as well, but I was never able to reproduce this one.
=> handle events on the outputs screen (#1652)

radio/src/gui/colorlcd/radio_tools.cpp, radio/src/gui/common/stdlcd/radio_tools.cpp
Fixes #1647
Showing of the "(int) Spectrum Analyser" was determined at build time,
dependent on the default internal module, which is wrong post #1117
This now makes it so it is dependent on current internal module setting (if the radio has an internal module) for both colorlcd and B&W radios.
Tested on TX16 and Zorro (ELRS). Tool entry added with MULTI, not added with CRSF.
=> fix: Make decision to show int MPM spectrum analyser entry settings dependent

radio/src/telemetry/crossfire.cpp
When the CRSF telemetry parser gets a CRC error, I've found that the only case that causes these is missing bytes in the CRSF telemetry stream. This leads to not only the bad packet being dropped, but also the following packet will be dropped as well, because some of that packet's bytes were used to fill the previous packet's LEN.  A single lost byte causes **at least** two lost packets every time. There can be more lost due to the parser trying to pick up mid-packet and misinterpreting a payload byte as a packet start.
Here's the issue in action, where I've added some extra debug logging. The `*` asterisk indicates a CRSF packet passing CRC, and the `^` is a UART error (green underline). The lines starting with the little `ox` are me printing the bytes that are "out of band" following an …
=> On CRSF CRC error, search for second packet embedded in the failed one

radio/src/telemetry/flysky_nv14.cpp
This PR implements vertical speed sensor for NV14.
FS CAT-01 sensor reports air pressure and temperature - no altitude and vertical speed reporting.
NV14 code calculates altitude, but there is no vertical speed sensor that is needed for variometer.
This PR adds Vspd sensor defined as altitude derivative.
Fixies #1477
Summary of changes: compute altitude change between two measurements and accumulate changes for averaging is telemetry calls frequency is high enough. 
Compute vertical speed as altitude change divided by time.
Many thanks to @Ktr128 for testing!
=> Vertical speed sensor for NV14

radio/src/gui/colorlcd/radio_sdmanager.cpp
Fixes #1668 
Add menu line "Assign Bitmap" to SD manager file menu when image file is selected.
If applied the selected image will be used for current model.
=> add  "Assign bitmap" to image file menu (#1668)

companion/src/firmwares/boards.cpp, companion/src/firmwares/boards.h, companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/generalsettings.cpp, companion/src/firmwares/generalsettings.h, companion/src/firmwares/opentx/opentxeeprom.cpp
Fixes #1566
Radio specific mapping of radio field enum to display value.
New board capability SportMaxBaudRate which influences the mapping between companion and radios. (Please double check this list! It is based on radio target hals and CMakelists.txt)
Changes required to yaml read/write and otx eeprom import/export (pre-yaml issue).
Tested a number of radio simulators. However there are a lot of radios.
This is another one of those legacy fields with twister logic that keeps coming back to haunt us Boooooo
=> Companion fix otx and etx read and write for max telemetry baudrate

companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/generalsettings.cpp, companion/src/firmwares/generalsettings.h
Addresses part of the issues raised in #1413 and in other discussions.
When reading radio yaml settings for a board which does not match the current radio profile board do not import potentially incompatible values. Use current profile radio defaults.
Note: this only addresses yaml settings.
A further enhancement could be to display the Radio Settings dialog to give the user the opportunity to adjust the settings prior to importing the models. This will require refactoring the reading process to permit passing flags back the calling processes rather than the success/fail bool return, similar to bin processing.
=> Companion set critical radio general settings to profile defaults if mismatched boards

radio/src/targets/horus/flyskyHallStick_driver.cpp
As there was no Interrupt-Service-Routine defined for FlySky Hall RX DMA (DMA1_Stream2_IRQHandler, IRQ no 13), should not enable the interrupt.
Tested on RM TX16S with FlySky digital hall sticks.
=> Do not enable DMA1_Stream2 IRQ for FlySky Hall Sticks

radio/src/gui/colorlcd/model_outputs.cpp
Resolves #1385
Summary
This can wait until 2.8 along with adding the footer statusbar for mixes and outputs page. 
TX16S:
NV14:
=> Add channel bar to Output Edit Screen

radio/src/opentx.cpp
This PR simply resets the backlight timeout on colorlcd radios whenever the power button is pressed. 
Thus instead of the shutdown animation flashing up and the screen turning off immediately if you release the button (if the backlight was in auto off mode), it now stays on for the timeout interval.
=> proposal: Pressing power button should reset backlight timeout

radio/src/gui/colorlcd/theme_manager.cpp
Fixes #1680
- Ensures global background image is used if a theme does not provide it's own when a theme is loaded. Thus consistent with power-on behaviour.
=> fix: colorlcd "Global" bg image not being loaded at theme change

radio/src/gui/128x64/model_setup.cpp
Fixes issues where the wrong moduleData index is being written to when editing XJT module settings on 128x64 radios.
=> fix: Ext mod XJT opts on 128x64 B&W altering int mod settings

radio/src/opentx.cpp
The CPU_UID data stored from address 0x1FFF7A10 + 4 is on my radio
0x1FFF7A10+4 : 0x06, 0x51, 0x38, 0x31, 0x33, 0x37, 0x30, 0x33
Since the control character 0x06 (ACK) was mixed, I changed it to another character.
Looking at RM0090 39.1, it seems that the characters are stored from the lower byte of the UID, so the character storage order is set so that the upper byte comes first.
=> read CPU_UID

radio/src/targets/taranis/board.h, radio/src/targets/taranis/hal.h
Fixes #1587
Where Trainer Slave not recognized in Master due to trainer detect pin being inverted on ACCESS radios. 
Import of:
- https://github.com/opentx/opentx/pull/8811
- https://github.com/opentx/opentx/commit/2241c3f4ce3b0c6cd3fd41a45770c09ce3e75a7e
Currently untested. Needs testing on:
=> fix: Trainer Slave not recognized in Master for ACCESS radios

radio/src/targets/nv14/lcd_driver.cpp
Fixes #1531
Summary of changes: assume ST7796S display controller on NV14, when no other is detected
=> fix #1531, not wokring screen on NV14 with ST7796S display controller

companion/src/firmwares/multiprotocols.cpp
Fixes #1717
- Update protocol to string list to match protocol defs
- Fixed typo in MT99 sub-types
=> Companion update MPM list and MT99 sub-types

radio/src/lua/api_general.cpp
Using `ModelCustomFunctionsContext` instead of `LogicalSwitchesContext` to get "One" and "ON" switch positions
From discussion on RCGroups: https://www.rcgroups.com/forums/showthread.php?p=48896659&postcount=3976
=> Changed getSwitch* to get "One" and "ON" switch positions

radio/src/gui/128x64/view_about.cpp, radio/src/translations/de.h.txt
this will fix the about screen headline and german translation.
before:
after:
=> About screen cosmetics / translation

radio/src/storage/conversions/yaml/yaml_datastructs_funcs.cpp
Fixes #1734
- Mix data offset: convert to signed int with maximum 11 bits even if it uses 14 bits.
=> Fix YAML write issue with mix offset

radio/src/gui/colorlcd/radio_version.cpp
Fixes #1760
Presently tested on a color radio with int. MPM and CRSF.
Old behaviour:
After this PR with MPM:
=> Show internal RF module info instead of "No information"

radio/src/cli.cpp, radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/radio_hardware.cpp
Fixes #1751
- adds padding back again at the bottom of the radio hardware tab. Is an incomplete solution, as the real problem apperas to something in InternalModuleWindow not updating height properly. 
- Also resolves compile failures on NV14 if compiled with `LUA=N`, and generally removes some new UI LUA stuff if not valid
=> `LUA=N` compile fixes and radio hardware tab bottom padding (for touch)

radio/src/gui/colorlcd/radio_version.cpp, radio/src/gui/common/stdlcd/radio_version.cpp
This PR complements #1761 by displaying the module info also on black and white targets.
Tested with 4-in-1 and ELRS Zorros.
Old behaviour:
With this PR on 4-in-1 Zorro:
And on ExpressLRS Zorro:
=> Show module info for MPM and CRSF

radio/src/storage/sdcard_yaml.cpp, radio/src/storage/storage_common.cpp
- fix default VCP configuration (was not applied)
- fix internal module configuration (was always overwritten with default module)
=> fix: some radio settings were overwritten or not applied

radio/src/opentx.cpp
This bug has been mentioned a few times, but doesn't seem to have been dignified with an actual issue. 
- MPM has a delayed failsafe check, which is monitored by `checkFailsafeMulti()`. Only use this, and thus prevent STR_NO_FAILSAFE alert being shown twice. 
Has been tested on TX16S with both internal MPM and external MPM, with modules that have failsafe not set, failsafe set, and no failsafe on protocol with no incorrect behaviours.
=> Fix double "Failsafe not set" with MPM

radio/src/gui/colorlcd/model_inputs.cpp
This PR fixies the issue mentioned by @JimB40 in #1745 
Summary of changes: Keep focus on the input close to the deleted one.
=> Fix selection of the first line after deleting input.

radio/src/gui/colorlcd/radio_setup.cpp
Fixes #1795
- use `setAvailableHandler` rather than string processing which also mangled some translations
- this is colorlcd specific code, so doesn't need colorlocd conditional 
Malte, since this was your handywork... :)
=> fix: Use setAvailableHandler to filter blMode menu

radio/src/gui/colorlcd/model_inputs.cpp
- left align input names since they can vary in length
- and no, the TextButton textFlag `RIGHT`is not a typo... `LEFT` doesn't work 😆 
Before:
After:
=> colorlcd: Left align input names on Model Inputs tab

companion/src/firmwares/modeldata.cpp, radio/src/translations/cz.h.txt, radio/src/translations/de.h.txt, radio/src/translations/en.h.txt, radio/src/translations/es.h.txt, radio/src/translations/fi.h.txt, radio/src/translations/fr.h.txt, radio/src/translations/it.h.txt, radio/src/translations/nl.h.txt, radio/src/translations/pl.h.txt, radio/src/translations/pt.h.txt, radio/src/translations/se.h.txt
Fixes #1796
- update trainer modes list item availability
- standardise trainer mode Off to OFF
=> Companion trainer modes OFF and Master-Multi available for all radios

radio/src/gui/128x64/lcd.cpp, radio/src/strhelpers.cpp
Fix display of Function switches names on Inputs, Mixes, Logical SW and Special Functions screens.
Now names are used instead of SWx or Sx when a name is configured in setup screen.
Fix symbol of Function switches.
=> Fix Display Function switches names and symbol

companion/src/firmwares/curvedata.cpp, companion/src/helpers.cpp, companion/src/helpers.h, companion/src/modeledit/curves.cpp, companion/src/shared/curvedialog.cpp
Fixes #1814
The initialisation algorithm is correct so appears to be caused by Qt's event stack triggering other events in the middle of our update.
- change event refreshing to be more granular and add lock checks
- expand curves tab details column and wrap points list (Qt makes it choice about where to break lines thus the unused space)
- housekeeping
=> Companion fix custom curve edit default points

radio/src/gui/colorlcd/radio_setup.cpp, radio/src/gui/colorlcd/view_statistics.cpp
Version: 2.7.0-RC2
Classification: bug
Severity: minor
Some of the colorlcd GUI for Internal GPS was misusing `hasSerialMode()` expecting it to return a true/false, but it actually returns the port number that is set to the requested mode. Since the port numbers start at 0 for Serial Port AUX1, this means that there was some GUI that was missing if the GPS is attached to AUX1. This simply corrects the comparison to be true of `hasSerialMode(UART_MODE_GPS) != -1`
I've checked all other `hasSerialMode()` calls and they look correct, these are the only two problems.
* Radio Setup missing GPS items
* Statistics missing GPS info
=> Fix some missing colorlcd gui if GPS on AUX1

radio/src/io/multi_protolist.cpp, radio/src/io/multi_protolist.h
This prevents the MPM protocol scanning to happen in the simulation, which would not work as the FreeRTOS Software Timers are not functional until we start to use FreeRTOS in simulation as well (Posix / Windows port).
Resolves #1793
=> Use static MPM protolist on simu

radio/src/targets/common/arm/stm32/usbd_cdc.cpp, radio/src/targets/simu/simpgmspace.cpp
Inspired by @jmxp69 video: https://youtu.be/Yt79wxH4anM?t=3823 (at 1h 3min 43 sec).
Small change in label text hopefully making the "USB Virtual COM Port" (USB-VCP) more intuitive.
Old label "VCP":
New "USB-VCP":
=> Changes VCP to USB-VCP in the UI

.github/workflows/win_cpn-64.yml
To clear some confusion by users, change the Windows Companion installer package filename from `cpn-win-*` to `cpn-win-64-*` in order to more clearly denote that this is a 64-bit Windows version.
=> Use "cpn-win-64"

radio/src/targets/common/arm/stm32/bootloader/boot.cpp
Forces software controllable serial port power delivery pins off during bootloader.
Tested with TX16S mkII. W/o this change, AUX1 power remains on, AUX2 off. With this change, during init of the code, briefly AUX1 is powered up, then very early in bootloader main(), serial power is turned off again.
I have no good idea yet how to eliminate the small ca. 900ms long glitch before the bootloader main() runs. Stems likely from the underlying implementation of StdPeriphLibs.
I made this PR against SerPWR branch, due to missing SWSERIALPOWER in the main branch yet.
=> With software controllable serial port power pins, keep power delivery off in bootloader

radio/util/find_clang.py
Fix issue 1889 - find libclang on openSUSE and other systems that use /usr/lib64.
Fixes #1889
=> Find libclang on systems that use `/usr/lib64`

radio/src/stamp.cpp, radio/src/stamp.h.in, tools/build-gh.sh
Further builds on #1850, #1887
- uses proper CMake syntax to only define VERSION_TAG when it is passed in (before it was always defined, but as an empty string)
- ensures `build-gh.sh` won't unconditionally set `EDGETX_VERSION_SUFFIX` on selfbuilds
- also omits commit SHA on colorlcd (as I had already done that on B&W)
From the testing I've done so far (by overriding `EDGETX_VERSION_TAG` and `EDGETX_VERSION_SUFFIX` in `build-gh.sh`), I know the whole pipeline from `build-gh.sh` correctly showing the tag, or not showing the tag as required, will just need to do another test build with a tag once this is merged to ensure it is being picked up. 
I was tempted to also have VERSION_SUFFIX only defined on existence, but the code logic atm unconditionally expects it to exist …
=> Further tweaks to version string

.github/workflows/nightly.yml, tools/build-gh.sh
Tries to augment #1850, #1887 and #1895 by adding explicit "nightly" suffix for GitHub nightly builds.
Real-life testing possible likely only after merging and waiting for the nightly to be generated.
=> Sets explicit "nightly" suffix for GitHub nightly builds

radio/src/gui/128x64/model_setup.cpp
Fixes #1899
#1702 fixed an issue where external module setting was overwriting internal modules. I didn't take into account that `isModuleXJT()` doesn't descriminate between XJT and XJT Lite module, so it obliterates the XJT Lite type on the first change made. In doing so, the XJT Lite was not power cycled/mode changed.
=> fix: XJT Lite module type being replaced with XJT

radio/src/gui/colorlcd/radio_version.cpp
Fix issue where going SYS>VERSION>Modules / RX version , pressing  "PAGE>" or "PAGE<" while info screen being shown, and then press enter/RTN to EXIT, could result on EM immediatly, when leaving the radio settings, or shortly afterwards. 
Fixes #1582, #1878, #1901
=> fix: Radio Settings/SYS module version info lockup

companion/src/CMakeLists.txt, radio/src/targets/simu/CMakeLists.txt
- Use `install(DIRECTORY...)` instead of `install(FILES ...)`
- This allows the list of files to be resolved at the last moment versus when cmake is executed first.
=> Fix simulation plugins packaged

radio/src/gui/colorlcd/model_select.cpp, radio/src/storage/modelslist.cpp
Fixes #1897 
Summary of changes: Removed a call to update() in the changeHandler() of TextEdit.
One cannot call update()/rebuild() from TextEdit.changeHandler().
The reason is long press on ENTER sends two signals: KEY_ENTER and LONG_PRESS.
Both call changeHandler(). The first call causes update() and the screen is build().
So when te second call to changeHandler() comes the corresponding TextEdit is already deleted.
=> Fix crash in category Clear (#1897)

companion/src/storage/categorized.cpp, companion/src/storage/categorized.h, companion/src/storage/etx.h, companion/src/storage/otx.h, companion/src/storage/sdcard.cpp, companion/src/storage/sdcard.h
Fixes #1696
On B&W radios, before writing models to MODELS folder on sd card:
- delete all modelsxx.yml files
- delete models.yml file if it exists
A bit of translation housekeeping
=> Companion B&W radios clean up sd card MODELS folder before writing updated models to sd card

companion/src/modeledit/curves.cpp
Fixes #1919 for inconsistent GUI word wrap handling for nested UI objects between OSes
- merge Note column into details column to maximise space for plot points
- heading labels
- change plot points field from word wrap to fixed width max. 75 chars
Note: plot points details will be truncated if exceed max
=> Companion fix model edit curves tab plot points formatting

radio/src/targets/horus/CMakeLists.txt, radio/src/targets/horus/board.cpp
All in T16_FAMILY use the same STM32F429BIT6 and the same MCU supply voltage, so IMHO all benefit from this.
=> Set the same highest brown-out threshold level for all T16 family radios

radio/src/telemetry/crossfire.cpp, radio/src/telemetry/crossfire.h
Until now, Crossfire was only allowing for altitude as part of the GPS sensor. This PR adds barometer support as well.
See betaflight/betaflight#11070.
=> Crossfire: add barometer altitude sensor

radio/src/io/multi_firmware_update.cpp
Please note that `main` is not impacted, as the code has already been fixed because of something else.
Resolves #1764
=> fix: flashing ELRS modules would use the wrong port driver

radio/src/gui/colorlcd/model_inputs.cpp
Fixes #1934 
When the input is moved (Move/Paste - Paste Before/Paste After are not affected) the input name is also moved.
=> move input name together with input string

radio/src/gui/gui_common.cpp
Do not list OFF on VCP menu if internal RF module is set to CRSF to allow pass-through flashing.
=> No VCP off in menu with iCRSF module

companion/src/generaledit/hardware.cpp, companion/src/generaledit/hardware.h, radio/src/gui/colorlcd/radio_hardware.cpp, radio/src/gui/common/stdlcd/radio_hardware.cpp, radio/src/gui/gui_common.cpp, radio/src/storage/storage_common.cpp
Stops listing OFF as an option on USB-VCP menu, if internal RF module is set to CRSF (to allow pass-through flashing). If USB-VCP was set to OFF and internal module is changed to CRSF, changes USB-VCP automatically to CLI.
Tackles #1952 
Tested with TX16S mkII and Zorro.
=> USB-VCP no OFF if internal RF module is set to CRSF

companion/src/modeledit/colorcustomscreens.cpp
Fixes #1961
Fixes #1517
- trap and report YAML parsing errors when processing theme.yml files
- continuing loading model
Example
=> Stop Companion crashing due to malformed theme.yml files

companion/src/logsdialog.cpp
The companion log viewer lets you view aggregated series on the same graph.
By default, it uses colors in the order of their definition, but yellow is pretty bad to visualize. I just changed the order of the colors and, for me, it was much better to see with the white background of the graph.
Hope you like it. :smile:
=> Companion - Log Viewer - Reorder colors for better reading

companion/src/mdichild.cpp, companion/src/storage/yaml.cpp, companion/src/storage/yaml.h
Fixes #1958
- parse the yaml file and if successful open as a new document in a Models and Settings window
- warn the user that no radio conversion has been possible as source radio flavour unknown
- populate radio settings with default values based on current radio profile
=> Companion open individual model settings yml files

companion/src/firmwares/edgetx/yaml_modeldata.cpp, companion/src/modeledit/setup.cpp, companion/src/modeledit/setup.ui, radio/src/gui/128x64/model_setup.cpp, radio/src/gui/212x64/model_setup.cpp, radio/src/storage/storage_common.cpp, radio/src/switches.cpp
Fixes #1843
Fixes #1730
Fixes #1663
Fixes #1504
Fixes #1050
- fix Companion yaml model read and write
- B&W radios treat bit values the same as color to avoid unnecessary complication for Companion and radio conversions
- B&W radios default is therefore off for all pots and sliders
- B&W radios fix runtime warnings check
- all radios fix to save last pot or slider position when checked and mode AUTO on change of model or power off
- all radios do not display Pots Warning in model setup if no pots or sliders supported
Note: this will need a warning for B&W radio users in the release notes!!
Tested on Ubuntu 20.02 with TX16S and X9D+ libsims
=> Fix pot and slider warnings in Companion and radios

companion/src/apppreferencesdialog.cpp, companion/src/apppreferencesdialog.ui, companion/src/mdichild.cpp, companion/src/mdichild.h, companion/src/storage/appdata.h, companion/src/storage/yaml.cpp, companion/src/storage/yaml.h
Enhancement #1953
- change new model actions from series of radio buttons to dropdown list
- add new model actions template and prompt
- selecting template launches the open files dialog in the application sd card/TEMPLATES directory with a yml filter. However, there is no restriction on were you can import a template from. After selecting a model file the edit dialog is opened.
If new action Prompt is selected this dialog is displayed
Selecting Cancel will delete the temporary model.
Note: this PR includes PR 1959 as it needs to be able to open individual model files. It has been cherry picked into commits.
=> Companion add new model actions template and prompt

companion/src/mdichild.cpp
=> Companion option to insert if pasting onto existing model

companion/src/mdichild.cpp, companion/src/mdichild.h, companion/src/storage/storage.cpp, companion/src/storage/storage.h, companion/src/storage/yaml.cpp, companion/src/storage/yaml.h
Fixes #1965
- add save model(s) to models and settings menus and toolbars
- new storage functions to support single model write
- modified yml storage format write functions
- default save directory is application sd card TEMPLATES
- model name used as default file name
Note: builds upon PR 1959 and 1963 which have been cherry picked into this PR
=> Companion save individual models

companion/src/CMakeLists.txt, companion/src/storage/CMakeLists.txt, companion/src/storage/categorized.h, companion/src/storage/etx.h, companion/src/storage/otx.h, companion/src/thirdparty/miniz/CMakeLists.txt, companion/src/thirdparty/miniz/ChangeLog.md, companion/src/thirdparty/miniz/LICENSE, companion/src/thirdparty/miniz/examples/example1.c, companion/src/thirdparty/miniz/examples/example2.c, companion/src/thirdparty/miniz/examples/example3.c, companion/src/thirdparty/miniz/examples/example4.c, companion/src/thirdparty/miniz/examples/example5.c, companion/src/thirdparty/miniz/examples/example6.c, companion/src/thirdparty/miniz/miniz.c, companion/src/thirdparty/miniz/miniz.h, companion/src/thirdparty/miniz/readme.md
- replace release v1.15 with v2.2.0
- v2.2.0 introduced separate header and code files and 64-bit OS support
- move include to parent class for otx and etx storage formats and replace header guards with pragma once
- compile miniz as a library
=> Companion bump miniz to release 2.2.0

radio/src/gui/colorlcd/layouts/sliders.cpp, radio/src/gui/colorlcd/layouts/trims.cpp
Summary of changes: long type has different length on Linux and Windows.
intptr_t is the proper data type here.
Without this change Windows simulator library build fails.
=> Fix data type for Windows compilation

radio/src/gui/colorlcd/CMakeLists.txt, radio/src/gui/colorlcd/hw_inputs.cpp, radio/src/gui/colorlcd/hw_inputs.h, radio/src/gui/colorlcd/hw_intmodule.cpp, radio/src/gui/colorlcd/hw_intmodule.h, radio/src/gui/colorlcd/hw_serial.cpp, radio/src/gui/colorlcd/hw_serial.h, radio/src/gui/colorlcd/model_curves.cpp, radio/src/gui/colorlcd/model_flightmodes.cpp, radio/src/gui/colorlcd/model_gvars.cpp, radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/model_logical_switches.cpp, radio/src/gui/colorlcd/model_mixer_scripts.cpp, radio/src/gui/colorlcd/model_mixes.cpp, radio/src/gui/colorlcd/model_outputs.cpp, radio/src/gui/colorlcd/model_outputs.h, radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/colorlcd/model_telemetry.cpp, radio/src/gui/colorlcd/radio_diaganas.cpp, radio/src/gui/colorlcd/radio_hardware.cpp, radio/src/gui/colorlcd/radio_sdmanager.cpp, radio/src/gui/colorlcd/radio_setup.cpp, radio/src/gui/colorlcd/radio_theme.cpp, radio/src/gui/colorlcd/radio_tools.cpp, radio/src/gui/colorlcd/special_functions.cpp, radio/src/gui/colorlcd/tabsgroup.cpp, radio/src/gui/colorlcd/view_channels.cpp, radio/src/gui/colorlcd/view_logical_switches.cpp, radio/src/targets/simu/simpgmspace.cpp
Changes:
- use unified border on all page tabs
- dialog auto-layout improved
- moved sticks/pots/sliders/switches hardware settings to pop-ups
=> Radio hardware: layout improvements

companion/src/simulation/telemetrysimu.cpp, companion/src/simulation/telemetrysimu.h, companion/src/simulation/telemetrysimu.ui
Added a method for users to save and reload Companion Simulator Values that they have entered. Also, added defaults to all of the sensors.
When using Companion Telemetry Simulator, the user can enter values for each sensor. These values can be used to test things like low voltage alarms, etc. At this time, the values must be entered manually each time the telemetry simulator is started. If he leaves the simulator to edit these alarms, and then re-starts the simulator, he must enter the sensor values again after the telemetry simulator re-starts. My addition allows the user to save these values to a file. After re-starting the simulator he simply reloads the previously saved values. 
Also, most of the telemetry simulator sensors do not have a default value. I have entered these default …
=> Save and reload telemetry values in companion telemetry simulator

radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp
Did not commit directly to main, as I have no PWM gimbal hw to test this.
=> Initialize the PWM interrupt count to 0

radio/src/translations/cz.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h
- Fixes issue with three translations still referencing `USB Serial (Debug)` instead of `USB Serial (VCP)`
- Update all translation headers to use EdgeTX boilerplate header
=> Fix references to "USB Serial(Debug)" and use correct header text

radio/src/gui/colorlcd/radio_sdmanager.cpp, radio/src/gui/colorlcd/themes/etx_lv_theme.cpp, radio/src/gui/colorlcd/view_text.cpp, radio/src/gui/colorlcd/view_text.h
This PR is based on #2058 by @raphaelcoeffic 
Fixes #2057
Summary of changes: text viewer based on lvgl label object.
Viewer supports touch and roller interface.
txt and csv (log) files are supported. csv files are opened from the end. 
On the TXs with PGUP and PGDWN buttons long files can be viewed by loading additional pages.
=> view text functionality restored

radio/src/opentx.cpp
After all the back and forth in the other PR for this issue, I decided to do a more complete fix rather than a "minimal change" fix. Either would be fine, I believe, but I think this one is better. So, I'll create it as an actual PR vs. a draft and abandon the other if this one is accepted.
One concern I had was the scenario where you've got extended trims enabled, and you're normal trim values, and then you disable extended trims. What would the experience be, and would it wait for you to make a trim adjustment before updating the trim value to respect the new (lower) limit? Answer: no, it doesn't. As soon as you disable Extended Trims it respects the Normal Trims limits and adjusts if necessary, in the simulator. In the radio itself though it doesn't, until you move the out of bound …
=> Issue 1936 - Trim audio at max/min trim (Alternate)

radio/src/audio.h, radio/src/functions.cpp, radio/src/translations/tts_cn.cpp, radio/src/translations/tts_cz.cpp, radio/src/translations/tts_de.cpp, radio/src/translations/tts_en.cpp, radio/src/translations/tts_es.cpp, radio/src/translations/tts_fr.cpp, radio/src/translations/tts_hu.cpp, radio/src/translations/tts_it.cpp, radio/src/translations/tts_nl.cpp, radio/src/translations/tts_pl.cpp, radio/src/translations/tts_pt.cpp, radio/src/translations/tts_ru.cpp, radio/src/translations/tts_se.cpp, radio/src/translations/tts_sk.cpp
Closes #1869
- timer values longer than 10 minutes will announce time in minutes only (no seconds, no hours). 
- when timer value less than 10 minutes seconds will be announced as well
=> Long timer announce minutes only (#1869)

radio/src/fw_version.h, radio/src/gui/colorlcd/radio_version.cpp, radio/src/stamp.cpp
Remove CFGV as no longer needed
Since it related to the EEPROM config value,
which is no longer relevant.
Additionally, this (CFGV) broke after ee0c371 :laughing:
Elaboration: This (CFGV, previously EPRV) is no longer relevant since now the config version is the semver saved in the file, which will be the same as the running ETX version since it is updated automatically. 
Fixes #
=> Remove CFGV as no longer needed

radio/src/gui/colorlcd/radio_tools.h, radio/src/gui/common/stdlcd/radio_tools.cpp, radio/src/opentx.h, radio/src/pulses/pxx2.h
In my understanding the different union members of resusableBuffer should be dedicated to exactly one(!) menu-page. The _normal_ pattern should be to use a different union-member in different menu-pages. That should be safe, because two pages can't be active at the same time.
But the other way round, using two different union members in the same(!) page is false. 
Just spotted this in `*/radio_tool.cpp` and this should fix it.
=> Fixing cross-usage of union reusableBuffer

.github/workflows/macosx_cpn.yml
- `macos-11` runner (`10.15` is deprecated)
- select XCode `11.7`
See [here](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md) for details on supported tools/versions.
=> Bump macOS runner version to mac-11

radio/src/logs.cpp, radio/src/tasks.h
- adds logging of channel outputs CH1..CH32 in units of microseconds
Justification of change:
Looking at my logs the other day I noticed stick, switch and pot inputs are logged but no way of telling what the transmitters really sends to the rx (channel outputs). Only the beginning of the processing chain is logged. Example V-Tail. The only thing you see is you commanding left/right rudder. You can't see how this finally ends up commanding two rx outputs to move two servos after all the tx mix/curve/output processing.
Example 1: V-Tail. Compare rudder stick input to actual action of servos
Example 2: Channel throw limited and delayed by mixer. Servo on channel 5 controlled by switch SA, delayed by 5s by mixer and limited to 80% (1909us) and 50% throw (1244us).
=> Adds channel outputs to set of logged data

radio/src/logs.cpp
Fixes #1991
Write the "text" field for telemetry sensors that are text type.  Previously, the logic was falling through to write the sensor.value, which is 0.
=> handle text fields in log

radio/src/logs.cpp
Fixes [#2179](https://github.com/EdgeTX/edgetx/issues/2179)
adjusted pointer offset due to commit 30e3ac3.
=> fixes #2179 (partially corrupt log header)

radio/src/gui/128x64/model_setup.cpp, radio/src/gui/212x64/model_setup.cpp, radio/src/gui/colorlcd/module_setup.cpp, radio/src/translations/untranslated.h
Puts to rest the issue that started with #2079, and I then fixed and broke with 28ba80f28819c2df6140a210dd5d613b95e0b68a and 5752cf4061b85660d64b222b694d7120c409ec1e.
Essentially, the `STR_XJT_ACCST_RF_PROTOCOLS` and `STR_ISRM_RF_PROTOCOLS` should only list the protocols, and not also have "OFF" as the first entry. It seems this was done solely for 212x64 handling with ISRM radios, rather than use the same two column interface used for all other radios. 
This has been hardware tested on X9D+ (XJT), X9D+2019 (ISRM), Zorro (XJT Lite module), and TX16S (XJT module), and simu tested against X7, X7-ACCESS, X10 and X10-ACCESS (as well as TX16S, X9D+2019 and TX12 at various points). 
Last commit is automatic formatting only.
=> Fix ISRM/ACCST translation alignment

radio/src/gui/colorlcd/LvglWrapper.cpp
This adds acoustic and/or haptic feedback for touch events depending depending on radio settings.
This addresses issue [#1778](https://github.com/EdgeTX/edgetx/issues/1778)
Select "All" in radio settings/radio setup/Sound/Mode for key and touch acoustic feedback and settings/radio setup/Haptic/Mode for key and touch haptic feedback.
"NoKey" also disables touch feedback.
=> This adds acoustic and/or haptic feedback for touch events

radio/src/gui/128x64/model_setup.cpp, radio/src/gui/212x64/model_setup.cpp, radio/src/gui/colorlcd/model_setup.cpp, radio/src/translations/untranslated.h
* chore: Remove "OFF" from protocol lists
* Fix subType setting for X9D+2019
* fix: Chan start and count for ISRM, dup type set
Channel start and count wasn't being updated for ISRM.
Also remove duplicate modulke type setting, which was the
cause of an earlier bug that was worked around on 128x64
* fix(colorlcd): Shorter ACCST opts string crash
* chore: Formatting only
=> chore: Remove "OFF" from protocol lists (#2186)

.github/workflows/nightly.yml
Nightly release zips were including a subfolder, as opposed to PR and normal releases. 
Adding the `-j` flag to zip tells it to junk (drop) the paths. 
@CoderElectronics Ari, will Flasher cope with this without any changes? I know Buddy has been updated to accept either, but I would like to make the zips consistent
=> fix: Drop the path from nightly release zips

radio/src/audio.cpp, radio/src/gui/212x64/model_select.cpp, radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/theme_manager.cpp, radio/src/gui/common/stdlcd/model_notes.cpp, radio/src/opentx.h, radio/src/storage/eeprom_raw.cpp
With model dependent sound files, it was expected to have `_` in the name in place of spaces.
i.e. with a model name of `Model Name`, it should look like
`/SOUNDS/language/model_name/`
So to play the model name in English, it would like:
`/SOUNDS/en/model_name/name.wav`
However, after #645, it was looking for looking for a space, like like in the name:
`/SOUNDS/en/model name/name.wav`
It now looks for `_` instead of whitespace first (i.e. backwards compatible), and then 
checks for model name with whitespace. So both forms are now accepted.
Also, trigger postModelLoad() alarms when changing model to trigger
for checks and playing model name there. 
The second commit cleans up the file check in `theme_manager.cpp`
to also use `isFileAvailable` size it's nicer to use ;)
The third finally …
=> Use correct path for model name audio - space vs underscore

radio/src/audio.cpp, radio/src/gui/colorlcd/LvglWrapper.cpp, radio/src/gui/colorlcd/access_settings.cpp, radio/src/gui/colorlcd/color_editor_popup.cpp, radio/src/gui/colorlcd/lcd.cpp, radio/src/gui/colorlcd/radio_theme.cpp, radio/src/gui/colorlcd/view_main_menu.h, radio/src/keys.cpp, radio/src/targets/common/arm/stm32/bootloader/boot.cpp
This addresses https://github.com/EdgeTX/edgetx/issues/2194
Needs EdgeTX/libopenui#59
Changed logic from application decides if feedback has to be given (was inconsistent and inefficient) to key driver detects button down and triggers immediate feedback if radio settings allowed for acoustic and/or haptic feedback (radio settings, radio setup, sound set to All)
With this change all instances of the application calling for feedback were removed in favor of the centralized approach.
This first commit also introduces a dummy function for providing feedback on key presses in boot.cpp because keys.cpp is also used as the bootloader key driver but with no logic to determine if feedback is allowed. Using a define that indicates keys.cpp is compiled for use in the bootloader would make a much …
=> Adds audio/haptic feedback for all hard keys except trim switches

radio/src/gui/colorlcd/layout.cpp, radio/src/gui/colorlcd/menu_screen.cpp, radio/src/gui/colorlcd/view_main.cpp, radio/src/gui/colorlcd/view_main.h
Fixes #2212 (partly)
- Screen setup now starts with the tab corresponding to the active view.
- Active view is saved and restored.
=> View main fixes

radio/src/gui/colorlcd/view_text.cpp, radio/src/gui/colorlcd/view_text.h
Fix access to the Model Notes from Companion Simulator
Fixes #1378
Summary of changes: use full path instead of chdir() to test for file existence.
Only two file operations are taking care of the differences between TX and computer: f_stat() and f_open().
=> Fix full path to model notes for CP Simulator (fix #1378)

radio/src/gui/colorlcd/widget.cpp, radio/src/gui/colorlcd/widget.h
Allows #221 
Iterate the Widgets factory backward to give priority to the Lua widgets over the internal C++  Widgets.
This allows reimplementing the internal widgets with Lua without any sacrifice or `defines`.
=> Allow CPP Widgets Override with LUA

companion/src/firmwares/boards.cpp, companion/src/firmwares/boards.h, companion/src/firmwares/opentx/opentxeeprom.h, companion/src/firmwares/opentx/opentxinterface.cpp, companion/src/simulation/simulatorwidget.cpp, tools/build-companion.sh
Initial blind attempt to add TX12 MK2 support. This radio is identical to the TX12 as far as Companion is concerned, except it has two less switch options, and by currently ships with ELRS (so CRSF module protocol). 
This seems to be working so far in as far as reading and writing from a copy of my radio's settings via etx file - I'll do actual radio testing once a github build for windows is done and sleep ;)
And will then naturally be asking for a review from the Companion whisperer ;)
On another note... it looks like Companion is writing calibration data for pots/sliders that don't necessarily exist? i.e. for the TX12, with a recent `main` build of Companion, I'm seeing this for the TX12 ... a radio with standard gimbals and two pots (I would have said they were sliders but …
=> feat(cpn): Initial TX12MK2 support

radio/src/curves.cpp, radio/src/curves.h, radio/src/gui/colorlcd/CMakeLists.txt, radio/src/gui/colorlcd/bitmaps.cpp, radio/src/gui/colorlcd/bitmaps.h, radio/src/gui/colorlcd/draw_functions.cpp, radio/src/gui/colorlcd/input_mix_button.cpp, radio/src/gui/colorlcd/input_mix_button.h, radio/src/gui/colorlcd/input_mix_group.cpp, radio/src/gui/colorlcd/input_mix_group.h, radio/src/gui/colorlcd/list_line_button.cpp, radio/src/gui/colorlcd/list_line_button.h, radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/model_mixes.cpp, radio/src/gui/colorlcd/model_mixes.h, radio/src/gui/colorlcd/model_outputs.cpp, radio/src/gui/colorlcd/themes/etx_lv_theme.cpp, radio/src/gui/colorlcd/themes/flysky.cpp, radio/src/strhelpers.cpp, radio/src/strhelpers.h
After the new UI design for input, mixers, and outputs have trouble quite some people, mainly because of the reduction of the amount of information displayed at once on the screen, this PR offers more compact views that aim at finding a better compromise between touch UX and the amount of information displayed.
- Reduced margins / padding
- Live mixer monitors can be turned ON / OFF (non-persistent, OFF by default)
- Inputs, mixers, outputs use now grids into which single labels are placed rather than "on-the-fly" hard-coded drawing.
- delayed build of outputs screen to speed up tab switching (you might notice a little slow-down when scrolling the first time on the page).
The main goal is to be able to display at least 4 "simple" mixer channels on one screen:
Some …
=> More compact views for inputs, mixers and outputs

radio/src/gui/colorlcd/splash.cpp
centers the splash screen, so it does look OK when the screen resolution and the splash screen image resolution differ
=> fix: center splash screen

radio/src/telemetry/crossfire.cpp
This extends the Crossfire telemetry BARO_ALT_ID item to optionally include the VARIO item as well.
The BARO_ALT_ID item is 2 bytes of actual payload, wrapped with 4 bytes of header/crc. This makes it very inefficient to transfer due to the high overhead. The VARIO item is also only 2 bytes so these two items, which almost always exist together, can be updated from a single packet in one telemetry cycle. This is important due to the use of these items, which are to provide as real-time feedback as possible to glider pilots.
ExpressLRS will soon support native baro/vario receivers and we could split the frame on the TX module into two parts, but that doesn't get around the additional latency imposed by the half duplex eternal module connection, along with a possible low baud rate and …
=> Optionally support CRSF_VARIO in BARO_ALT telemetry

radio/src/gui/common/stdlcd/utf8.cpp
Fixes #2083
Added characters for TRANSLATIONS_SE so that Swedish special characters are displayed on B/W radios.
Thank you @gagarinlg for identifying the cause of this issue.
=> Added characters for TRANSLATIONS_SE

radio/src/gui/common/stdlcd/radio_tools.cpp
Resolves #1886
I would have sworn this was already merged in as of 8th May, but I can't find the commit or PR reference for it so I dunno.
=> feat(B&W): Lua tools list sorted alphabetically

radio/src/gui/colorlcd/splash.cpp, radio/src/targets/simu/simulcd.cpp
Fixes #2261 
- force pixel format to `RGB565` when loading splash image
=> fix: splash image pixel format

radio/src/gui/colorlcd/module_setup.cpp, radio/src/gui/colorlcd/mpm_settings.cpp, radio/src/gui/colorlcd/mpm_settings.h, radio/src/io/multi_protolist.cpp
Resolves #2203
- set field values to current option value when configuring fields
- hide sub-protocol choice if the list is empty
=> Fixes for MPM UI for colorlcd

radio/src/opentx.h, radio/src/targets/taranis/board.cpp, radio/src/targets/taranis/hal.h
I just wanted blue LEDs on my Jumper T-Pro. Instead I found a headache. 
PCBX7 STATUS_LED definitions were being used for RADIO_TPRO, resulting in incorrect GPIO pin assignments for GREEN and BLUE LED colors. LED_GREEN_GPIO_PIN would activate the blue LED, and vice versa for LED_BLUE_GPIO_PIN. 
To rectify this, a new definition for RADIO_TPRO has been created with proper GPIO pin assignments for LED_GREEN and LED_BLUE thanks to help from @pfeerick 
Yay!
=> Add correct STATUS_LEDS definitions for RADIO_TPRO

radio/src/storage/yaml/yaml_bits.cpp
Fixes #2270
No need for a bitwise OR if the value is a 32bits negative number. It's supposed to return the same value.
=> Fix 32 bits negative values YAML saving (#2270)

radio/src/gui/colorlcd/zone.h, radio/src/storage/modelslist.cpp
Allow moving labels UP and Down when there are only two labels.
Fixes #2269
Summary of changes: std::rotate() does not support two elements vectors. Use swap instead.
=> Change labels order for two labels list (#2269)

companion/src/mdichild.cpp
- move fix filenames to after new model is added AND modified
=> Companion add model with template crashes simulator

radio/src/gui/colorlcd/widget_settings.cpp, radio/src/gui/colorlcd/zone.h, radio/src/lua/lua_widget_factory.cpp, radio/src/lua/lua_widget_factory.h, radio/src/lua/widgets.cpp
Allows #221
Add the ability for Lua Widgets to display proper text in the Settings Menu as well as Display translated strings for Settings and The Widget name itself.
Backward compatibility is preserved as it adds a widget callback `translate(text, lang)` that is called if defined.
Example:
```lua
local name = "MyWidget"
local options = {
{"FirstChannel", VALUE, 1},
{"FillBackground", BOOL, 0},
{"BgColor", COLOR, COLOR_THEME_SECONDARY3},
{"TextColor", COLOR, COLOR_THEME_PRIMARY1},
{"BarColor", COLOR, COLOR_THEME_SECONDARY1}
}
local function update(widget, options)
widget.options = options
end
local function create(zone, options)
local widget = {zone = zone, options = options}
return widget
end
local function refresh(widget, event, touch)
end
local function …
```
=> Allow LUA widget translations

radio/src/gui/colorlcd/LvglWrapper.cpp
-  **Radio** - TX16S MK1
-  **Branch** - Main
I'm not sure if everyone's radio does this but it was starting to make me 😜. If you touch and slide a little up you get multiple audio beeps. This probably an underlying issue in the driver I assume, why it's sending two TE_DOWN events and causing multiple beeps.
I tried to navigate the driver and see why but didn't have much luck. I see why trace could be a super helpful tool here.
This is the **patch job** but prevents the the multiple beeping on same down event.
This after a touch and slide. Pressing and releasing in the same location won't do it.
```
222.27s: touch state = 0x81
222.27s: touch event = DOWN  ------ First Beep
222.27s: INDEV_STATE_PRESSED
222.27s: PRESSED[150|72]
222.31s: {5,50,136,231}
222.31s: {142,148,306,239}
222.57s: …
```
=> Prevent multiple audio beeps on touch

companion/src/mdichild.cpp, companion/src/mdichild.h
Feature introduced in 2.8 via #1968 however in hindsight the term Save maybe misleading as it could be interpreted as saving the selected model within the open settings whereas the function creates a new file independent to the open file.
There is no change to functionality.
=> Companion rename model Save to Export

radio/src/lua/api_colorlcd.cpp, radio/src/lua/api_general.cpp, radio/src/lua/api_model.cpp
Allows #221
Add missing LUA functions and constants to be able to recreate the C++ native widgets in LUA.
=> feat(lua): Add several Lua API funcs and constants

radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/model_select.h
Allows you to step through the labels using the page keys as discussed in issue #2285 
Hopefully someone can tell me if the keys make sense. Seems backwards on the TX16s with the PG down key on the top Pg Up on the bottom. I don't have any other color LCD's to compare with.
=> feat(color): Labels Pgup/Down keys move up down selected label

radio/src/dmafifo.h, radio/src/io/multi_firmware_update.cpp
Fixes #2310 
- fix DMA fifo `clear()`
- fix MPM update UART context reset
=> fix(mpm): update internal module

radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h
For temperature and degree units, `@C`, `@F` and `@` were being shown, rather than `°C`, `°F` and `°`. 
It seems B&W show the `°` symbol when `@` is used. 
Also, some translations were missing `dBm` as a telemetry unit.
as opposed to 
Also hoping this will also resolve the GPS sensor showing @ instead of ° as mentioned in #2163.
=> fix: Show degree symbol `°` instead of `@`

radio/src/gui/gui_common.cpp, radio/src/translations/da.h, radio/src/translations/en.h, radio/src/translations/fi.h, radio/src/translations/se.h
Fixes #1563 by ensuring Multi Trainer opt is not shown if no MPM
is enabled, as well as if MPM suport is not even compiled in.
It should only prevent `TRAINER_MODE_MULTI` being an selectable trainer mode if:
- `MULTIMODULE` support not enabled
- You don't have any modules enabled at all
- Neither of the enabled modules are MPM
It seems that having two MPMs enabled is a valid case, so I've left that case alone.
Hardware tested on TX16S and TX12-MK2, and working as expected. 
For me, this is both a bug (letting you select something that you can't) and an enhancement (don't show me stuff I can't use)... 🤷 😆
=> fix: Don't allow select MULTI_TRAINER if no MULTI

radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/model_setup.cpp
Corrects issue #2293. The menu needs to be deleted first before calling for the update. Keys work as expected now.
Also included a fix so the model bitmap updates instantly. Before you had to wait for a write to file to happen which took about 10seconds before the image was updated in the labels selector.
=> fix (color): Inability to select labels after editing them

companion/src/firmwares/modeldata.h, companion/src/firmwares/radiodata.cpp, companion/src/firmwares/radiodata.h, companion/src/labels.cpp, companion/src/labels.h, companion/src/mdichild.cpp, companion/src/mdichild.h, companion/src/modelslist.cpp, radio/src/dataconstants.h, radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/model_select.h, radio/src/gui/colorlcd/model_setup.cpp, radio/src/storage/modelslist.cpp, radio/src/storage/modelslist.h, radio/src/storage/yaml/yaml_labelslist.cpp, radio/src/storage/yaml/yaml_parser.h
- (FW) Corrects Checkall() was running twice when opening a new model. (Throttle Warning / Control Warning)
- (FW) Buffer overflow on labels too long or too many
- (CPN) Added warnings to the user if labels are too long or too many on a model in companion.
- (FW) Fix: rename create extra partial labels if a model is close to the limit
- (BOTH) Switched the commas to bullets on radio and firmware to fix #2282 
- (FW) Close model_select after making a new model
- (BOTH) Prevent YAML characters in label name. **Temporary**, will have to re-work yaml parser a bit to fully allow all characters (Will be a new PR destined for 2.9) CPN w/validator, FW, remove them.
- (FW) Limit length of text box
- (BOTH) Limit label length to 16 bytes
- (CPN) Move label up and down and rename buttons
=> fix(color): Limit label lengths, improve lbl display, prevent inv. char

radio/src/gui/colorlcd/curve_param.cpp, radio/src/gui/colorlcd/curve_param.h, radio/src/gui/colorlcd/switchchoice.cpp, radio/src/gui/colorlcd/switchchoice.h
Fixes #2312 and (indirectly) fixes #2286 
Also fixes unreported crash/emergency mode when going from Inputs tab to Edit curve screen.
Requires #EdgeTX/libopenui65 
https://github.com/EdgeTX/libopenui/pull/65
- Long press on switch button inverts the switch; e.g. SA_UP -> !SA_UP
- On the Inputs screen long press on the "curve" button bring "Edit Curve" screen.
As a side effect of removing old event handler(s) from ChoiceEx in libopneui #2286 is also fixed, but it looks like @raphaelcoeffic removed them earlier.
=> fix: Re-add Switch and Curve long press functionality

radio/src/opentx.h, radio/src/targets/taranis/board.cpp, radio/src/targets/taranis/hal.h
- Forgot to add TX12-MK2 to the list of radios prefering Blue => Green sequence
- Zorro LED G & B GPIOS were also swapped, so added to the list also
Future todo - have each radio raise a flag for blue over green status color rather than having to test for different radios. Or possibly the other way around, as quite a few radios have RGB and can do/prefer Startup Blue, Normal Green.
=> More RGB Status Led fixes

companion/src/modeledit/mixerdialog.ui, companion/src/translations/companion_sv.ts, radio/src/translations/se.h
- Some final tweaks and changes for Swedish translations, firmware and Companion, now (hopefully) ready for 2.8 release.
- One typo corrected in mixerdialog.ui, probably of little importance but corrected nonetheless.
=> fix: More Swedish translations and typo fixes 🇸🇪

radio/src/gui/colorlcd/draw_functions.cpp, radio/src/gui/colorlcd/model_curves.cpp
fix: GPS coordinates on color lcd radios now shows °, instead of @
fix: curve selector for predefined curves now shows °, instead of @
fixes part of #2163
=> fix(color): `@` displayed on radios instead of `°` 

radio/src/gui/colorlcd/view_main.h, radio/src/gui/colorlcd/widget.cpp
Related to #2182 
- disable "widget select" mode when going full screen
- prevent pop-up dialogs from passing key events to parents (thus allowing for starting ex model settings while in widget settings).
=> Some widget fixes

companion/src/firmwares/modeldata.cpp, companion/src/firmwares/rawsource.cpp, companion/src/modeledit/setup.cpp, radio/src/gui/common/stdlcd/model_inputs.cpp, radio/src/gui/gui_common.cpp
When a trainer mode is not enabled, there is no point
showing the TR# mixer sources. Once you enable a
trainer option, they will become visible again.
Tested on TX16S and TX12-MKII. TR# sources are only visible when Trainer mode not OFF.
Also fixes issue where validation of input availabliity was not happening on B&W radios :grin:
=> feat: Remove TR# mixsrc when trainer disabled

radio/src/cli.cpp, radio/src/gui/colorlcd/LvglWrapper.cpp, radio/src/targets/horus/tp_gt911.cpp, radio/src/targets/horus/tp_gt911.h
=> feat(GT911): Add CLI command to reset touch panel config

radio/src/gui/colorlcd/LvglWrapper.cpp
Depends on EdgeTX/libopenui#66
- provide better support for encoder acceleration
- applies now only to number edit and drop-down menus (those with `LV_OBJ_FLAG_ENCODER_ACCEL`)
=> feat: Use rotary encoder velocity only on specific components

radio/src/gui/128x64/lcd.cpp, radio/src/gui/128x64/model_curve_edit.cpp, radio/src/gui/128x64/radio_diaganas.cpp, radio/src/gui/128x64/radio_setup.cpp, radio/src/gui/212x64/lcd.cpp, radio/src/gui/212x64/model_curve_edit.cpp, radio/src/gui/common/stdlcd/utf8.cpp, radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h, radio/src/translations/untranslated.h
- remove translation workaround for the ° symbol
- switch every use of the @ char for a ° char to a new define
- same for ≥ and }
This also allow Lua-Scripts to use the ° character, tested with a modified iNav script
=> feature: add support UTF-8 ° symbol for B&W radios

radio/src/lua/api_general.cpp, radio/src/lua/lua_api.h, radio/src/mixer.cpp, radio/src/opentx.h
Replaces #2175 - something was messed up with the base branch
=> feat(lua): Add getSourceValue

radio/src/gui/colorlcd/radio_tools.cpp
=> fix(color): Radio tools buttons fit screen better

radio/src/gui/colorlcd/model_select.cpp, radio/src/storage/modelslist.cpp
Fixes #2386
Looks like I introduced this with removing YAML characters to prevent unwanted characters in the Label. When deleting labels, it does a rename of all the models labels to "". There was a check that was preventing this action because size was zero..
Ooops.
**Edit:** Went into autopilot on the last PR.. Should be put into 2.8
=> fix(color): Deleting empty label caused EM/Hang

radio/src/gui/colorlcd/radio_trainer.cpp
Stick labels for trainer mode should match default channel order setting
Fixes #2025
Just need to sanity check/test again before mislabeling them completely! :-O However just referred back to otx and it looks right. 
https://github.com/opentx/opentx/blob/28f67c1e9a4e949c236f576a215e9becb52fd6ec/radio/src/gui/480x272/radio_trainer.cpp#L54
=> fix(color): Trainer stick labels not correct

radio/src/gui/colorlcd/menu_model.cpp, radio/src/gui/colorlcd/menu_model.h
This PR brings back the "go to channel monitor" button, that was present in 2.7.
I would not insist on it, but I think it has some use.
For the TXs with buttons it is not really necessary, since this functionality is available with MDL button, but for the buttonless radios I think it adds some convenience.
=> Restore "go to channel monitor" Button

radio/src/gui/colorlcd/model_telemetry.cpp
Temporary fix for #2254
Fixes #2254 
Summary of changes: add extra line in the Telemetry screen to avoid text overlap on the targets with vertical screens.
=> Add extra line in telemetry screen for vertical LCD.

radio/src/gui/colorlcd/model_mixes.cpp
Fix functionality of moving and pasting mixes.
Fixes #2398 
Summary of changes: use pasteMix() for mixes rather than pasteInput(). (Kind of make sense.)
Use the relevant class member instead of global variable to detect the fact that a line was saved for Paste/Move.
=> Fix Copy/Move/Paste mixer line

radio/src/storage/modelslist.cpp
I can see a situation where a user tries to restore a model that was moved into /models/unused. If they copy models.yml as well, they will loose any changes made in the meantime. 
This PR changes the filename to models.yml.old so it has to be thought about if you want to parse again.
=> fix(color) - Change extension on models.yml to prevent second parsing

radio/src/switches.cpp
Fixes #2418
- fix one part of #2418 (switch position being missed)
Please note that the current implementation will be need more changes as it refills the menu on every auto-detected input/switch to get rid of the filtering potentially done by the toolbar. This will need a bigger effort to change the way it is done.
=> fix: auto-switch timeout raised to 1s

radio/src/gui/colorlcd/menu_model.cpp, radio/src/gui/colorlcd/menu_model.h
- Only show the "Show Channel Monitor" button on radios that are known to be touch only, since they can't access the MDL hard key shortcut.
=> fix: "Show Channel Monitor" btn only on touch only radios

radio/src/gui/colorlcd/model_select.cpp
I was still unable to reproduce #2408, but looking into the code this is one place I think there could be an issue. Making a draft pull so actions can run and hopefully users who have the issue in #2408 can test to see if it helps.
I thinking there might be a timing issue here, if there was a labels write pending and the model is changed before this happens, it may have updated to the incorrect cell in memory.
=> fix(color): Prevent false duplicate models fix for #2408

radio/src/gui/colorlcd/view_logical_switches.cpp
Fixes #2384
This patch uses styles for active and non active buttons. The style defines colors and fonts for each logical switch state.
=> fix(color): Logical switches monitor fix

companion/src/modeledit/customfunctions.cpp
For global functions in the simulator it is possible that no model is defined.
Fixes #2437 
Summary of changes: check for the model existence prior to using it.
=> Verify that model exists prior to using it in CP (Fix #2437)

radio/src/gui/colorlcd/message_dialog.cpp, radio/src/gui/colorlcd/message_dialog.h, radio/src/gui/colorlcd/model_logical_switches.cpp, radio/src/gui/colorlcd/special_functions.cpp, radio/src/gui/colorlcd/view_about.cpp
Fixes #2414 
- About: The MessageDialog constructor was extended adding the text flags. So the settings could be added at construction.
- LS & SF settings: A custom state was added with the style settings.
=> fix(color): Remove rem. `Window::setTextFlags()` font change usage

radio/src/gui/colorlcd/module_setup.cpp, radio/src/pulses/pxx2.cpp
Fixes #1585 
- do not send a sub-type for PXX2 R9M modules
=> R9M access: fix subtype

radio/src/storage/modelslist.cpp
The buffer for the name doesn't have room for the null if the full length limit.. and used strcpy, so it overwrote extra memory
Removes all strcpy's here with safer strn and terminate the strings
Fixes #2444
=> fix: Correct errors in labels.yml if modelname is full length

radio/src/gui/colorlcd/sourcechoice.cpp, radio/src/gui/colorlcd/switchchoice.cpp
Summary:
- cycling through with keys should now also allow to clear all filters
- fixed scrolling behaviour when a filter is activated (menu body window scrolled to far, thus looking empty)
- touch behaviour fixed (only one icon activate at the same time, etc)
- reset toolbar when filter is cleared by auto-source/auto-switch
- clear filter with auto-source/auto-switch only if set (#2418)
Requires EdgeTX/libopenui#71
Also addresses some of the ancillary issues mentioned in #1029
=> fix: various menu toolbar fixes

radio/src/gui/colorlcd/channel_range.cpp, radio/src/gui/colorlcd/module_setup.cpp, radio/src/gui/colorlcd/timer_setup.cpp
Like this (line scrolled to the left):
=> fix(color): some lines containing boxes could be scrolled horizontally

radio/src/gui/colorlcd/channel_bar.h, radio/src/gui/colorlcd/input_mix_group.cpp, radio/src/gui/colorlcd/input_mix_group.h, radio/src/gui/colorlcd/model_outputs.cpp
Fixes #2073
Summary of changes: add missing channel ids to mixer and output tabs
This PR currently creates those ouputs:
=> fix(gui): add missing channel IDs to mixer and output tabs. 

radio/src/gui/colorlcd/view_about.cpp
Fixes #2496
* Adjusts size of dialog to look better on NV18/EL18 - was full screeen height before
* Adjusts size of dialog content depending on the presence of version tag (on taller screen, )
I'm sure this could be done better using LVGL,
but is enough for now IMO.
Also let the auto-formatter loose on this file.
=> fix(color): Adjust about dialog size

radio/src/gui/colorlcd/model_outputs.cpp
=> fix(color): outputs in portrait mode

radio/src/gui/colorlcd/file_browser.cpp, radio/src/gui/colorlcd/file_browser.h, radio/src/gui/colorlcd/file_preview.cpp
This is an alternative implementation to the changes proposed in #2491. It does not required any `libopenui` changes.
- simple touch selects a file (including preview if available)
- touching a selected file triggers the contextual menu
=> File browser touch preview

radio/src/gui/colorlcd/draw_functions.cpp, radio/src/gui/colorlcd/fullscreen_dialog.cpp, radio/src/gui/colorlcd/page.cpp, radio/src/gui/colorlcd/tabsgroup.cpp
This prevents the main view to be redrawn if fully covered by a tab group, a page or a full screen dialog.
Prior to this, main view widgets would be redrawn in the background while visiting radio or model settings, which is obviously useless and a waste of resources.
=> fix(color): window tree preventing superfluous drawing

radio/src/pulses/afhds3.cpp, radio/src/pulses/pxx2.cpp, radio/src/telemetry/telemetry.cpp
If the module driver defines its own method, legacy telemetry polling should be prevented.
This is to prevent the S.PORT line to interfere with PXX2 telemetry reception, especially with R9M ACCESS.
Fixes #2461.
=> fix(PXX2): prevent legacy telemetry polling (S.PORT)

radio/src/gui/colorlcd/CMakeLists.txt, radio/src/gui/colorlcd/hw_intmodule.cpp, radio/src/gui/colorlcd/module_setup.cpp, radio/src/gui/colorlcd/pxx1_settings.cpp, radio/src/gui/colorlcd/pxx1_settings.h, radio/src/gui/gui_common.cpp, radio/src/gui/gui_common.h, radio/src/pulses/modules_constants.h, radio/src/storage/storage_common.cpp, radio/src/targets/horus/hal.h
Fixes #1567
- implements UI for internal/external antenna selection
And for prosperity/full transparency, I started this, but Raphael finished it ... you just can't see he finished re-writing the remainder of it due to the rebase. ;)
USE AT YOUR OWN RISK **until properly tested**! (aka have both antenna fitted until this warning removed).
=> X10/X12S: Int/Ext Antenna UI

radio/src/dmafifo.h, radio/src/pulses/pulses.cpp
De-initialising the external module while SBUS trainer is used on external module RX leads to the following sequence:
- `extmoduleStop()` is called, thus shutting down the timer DMA
- on certain targets, the timer DMA stream is the same as the external module RX DMA stream
- when this DMA stream is used by the SBUS trainer input, this leads to DMAFifo to return random bytes continuously
- thus driving `processSbusInput()` into an endless loop, which is run in the mixer task
- as the mixer task has the highest priority, it runs forever
- after some time the watchdog timer expires, and causes a reboot
- prevent de-initialising modules that have not been initialised (`NONE` protocol)
- harden `DMAFifo` to prevent endless polling from a disabled DMA stream
Fixes #1898
=> fix: prevent endless loop with SBUS trainer on model change

radio/src/targets/horus/board.cpp, radio/src/targets/horus/diskio.cpp, radio/src/targets/taranis/diskio.cpp
`g_FATFS_Obj` is located in `__DMA` section, which is not initialised, so that testing `sdMounted()` at boot relies on the fact that the bootloader linker script declares BSS in internal SRAM and not in CCM, as the firmware linker script does.
=> fix(sdcard): use init marker in initialised BSS segment

radio/src/gui/colorlcd/channel_bar.h, radio/src/gui/colorlcd/mixer_edit.cpp, radio/src/gui/colorlcd/model_flightmodes.cpp, radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/colorlcd/output_edit.cpp, radio/src/gui/colorlcd/themes/etx_lv_theme.cpp, radio/src/gui/colorlcd/view_channels.cpp
**Summary of changes:**
- text color for active LS buttons in monitor, which also affected some keyboard icons (for the better IMO)
- text color for active flight mode button
- text color for active internal/external/trainer button
- width/layout of channel monitors bars for portrait screens
- minor tweaks to alignment of channel monitor bar in relation to text, and icon layout
Before and afters
But I can't see what controls these buttons yet:
=> fix: Style/color tweaks

radio/src/switches.cpp
Fixes #1488 
- fix auto-switch for function switches
- fix matching function switch UP position
=> fix(tpro): function switches auto-switch & position matching

radio/src/storage/modelslist.cpp
Companion only opens model###.yml but radio opens all but special case .yml files. Radio should now only open the same. 
Also missing a potential file close.
=> fix(color): only open model###.yml files

.gitmodules, radio/src/gui/colorlcd/model_curves.cpp, radio/src/gui/colorlcd/model_mixes.cpp, radio/src/gui/colorlcd/model_select.cpp, radio/src/gui/colorlcd/model_setup.cpp
Fixes #2284
Speed up menu initializítion by delaying the UI update and do it in one step at the end.
Modified parts:
Requires [libopenui#77](https://github.com/EdgeTX/libopenui/pull/77)
=> Speed up bulk menu addition.

companion/src/firmwares/edgetx/yaml_modeldata.cpp
Because it seems like I managed to configure it just so
and Companion didn't like that.
Fixes #2521
- Check for inputs before just trying to reading them ;)
model1 and model23 no longer make Companion crashy crash. 
[crash-1-23.etx.zip](https://github.com/EdgeTX/edgetx/files/9762143/crash-1-23.etx.zip)
Confirmed locally against ETX file with linux cpn build, and now against Windows build and TX16s hardware. No errors on read, and settings preserved on write.
=> fix(cpn): Handle mixer scripts with no inputs def.

radio/src/targets/common/arm/stm32/intmodule_serial_driver.cpp
Otherwise, NDTR will be 0 instead of [buffer size], and thus the read index will not be set to the correct value.
Fixes #2368
=> fix: clear internal module FIFO after DMA init

radio/src/gui/colorlcd/menu_screen.cpp, radio/src/gui/colorlcd/menu_screen.h, radio/src/gui/colorlcd/screen_setup.cpp, radio/src/gui/colorlcd/screen_user_interface.cpp, radio/src/gui/colorlcd/topbar.cpp, radio/src/gui/colorlcd/topbar.h, radio/src/gui/colorlcd/widgets_setup.cpp, radio/src/gui/colorlcd/widgets_setup.h
This fixes the issue introduced in #2509 which would cause the main view to be hidden while configuring widgets.
=> fix(color): screen / widget setup

radio/src/gui/colorlcd/view_main.cpp
Prior to this fix the model settings would be opened as well when long pressing the model key.
=> fix(color): shortcut for model select

radio/src/gui/colorlcd/model_select.cpp
In a similar way as the file preview, using the ENTER key will trigger the menu, while touching a preview unselected model will just select it in the list. A second tap will then trigger the menu.
Fixes #2510
=> feat(color): single press to trigger model select menu

radio/src/gui/colorlcd/module_setup.cpp
This fixes following issue:
- switch the external module to "Multi"
- switch to something else
- check the faulty sub-types
=> fix(color): module setup sub-type after selecting MPM

radio/src/targets/common/arm/stm32/stm32_hal_adc.cpp
=> chore(adc): store constant structs in FLASH

companion/src/radiointerface.cpp
Fixes #
On MacOS 13 the EdgeTX companion will not find the radio's SD card.  The reason is that the companion app looks for volumes of type "fat", "vfat", or "msdos"; while the latest MacOS mounts the radio with type "lifs".  
This fix extends the regular expression to match that type.
=> fix(cpn): Workaround MacOS 13 filesystem type change

radio/src/gui/colorlcd/output_edit.cpp
... and not the output value. Otherwise, it will highlight min/max when the sub-trim is changed.
=> fix(color): min/max highlighting should depend on mixer channel value

radio/src/gui/colorlcd/model_select.cpp
Should only affect if you try to duplicate the current model.
If a write is pending, change of labels, etc. it wouldn't get copied into the duplicated model, but the labels still would have still been added to labels.yml until a re-scan.
Potential cause of issue #2561
=> fix(color): Duplicate model, write pending changes first

radio/src/gui/colorlcd/LvglWrapper.cpp, radio/src/lua/lua_widget.cpp
Fixes #2436
- `EVT_KEY_BREAK(KEY_EXIT)` is now mapped to `LV_EVENT_CANCEL` (previously `EVT_KEY_FIRST(KEY_EXIT)`)
- `short` and `long` `EXIT`/`RTN` work the same everywhere (`BREAK` event is generated, thus `onCancel()` is called)
- except in LUA where `long EXIT` **does not** generate a `BREAK` event.
=> fix(lua): send EVT_VIRTUAL_EXIT only on short EXIT press

radio/src/gui/colorlcd/channel_bar.cpp
Resolves #2575
- instead of omitting the percentage at 0% / center, now display it
=> feat(color): mix/output bars show '0%'

radio/src/gui/colorlcd/LvglWrapper.cpp, radio/src/gui/colorlcd/color_editor.cpp, radio/src/gui/colorlcd/gvar_numberedit.h, radio/src/gui/colorlcd/model_gvars.cpp, radio/src/gui/colorlcd/output_edit.cpp, radio/src/gui/colorlcd/timer_setup.cpp, radio/src/targets/common/arm/stm32/rotary_encoder_driver.cpp, radio/src/targets/simu/simpgmspace.cpp
Fixes #2417
Requires EdgeTX/libopenui#78
- use a more accurate / smoother implementation
- added specific acceleration factor which can be tuned for each number edit (depends on range / usage)
=> Improve rotary encoder acceleration

radio/src/io/frsky_firmware_update.cpp, radio/src/pulses/modules_helpers.h, radio/src/targets/common/arm/stm32/intmodule_serial_driver.cpp
Fixes #1552
- properly handle flashing of internal module depending internal module set in radio settings
- deactivate UART on internal serial module as the module won't reset properly otherwise
- fix a minor issue with the authentication counter not properly reset for ISRM upgrade modules
=> fix(isrm): flashing internal ISRM module

radio/src/audio.cpp
=> fix(x7): use switch indirection to fetch the proper name

radio/src/gui/colorlcd/widgets_setup.cpp, radio/src/gui/colorlcd/widgets_setup.h
Fixes #2621
Summary of changes: Disable PAG_UP and PG_DN buttons on the widgey setup scree.
The buttons were working incorrectly and there is a consensus (I feel) that they should not have any effect there.
=> fix(color): Disable invalid PG_UP and PG_DN handling on widget setup screen

companion/src/updates/updateoptionsdialog.cpp
Fixes #2634
@pfeerick note this is based on 2602 and thus why the big diff. The change for this PR is in https://github.com/EdgeTX/edgetx/compare/elecpower/cpn-fix-2634-upd-settings?expand=1#diff-565c6756adc52a80ae93eaf395cb23b75f09b37d09f4b70e53d6e175af0135c8 lines 252 - 255
=> Companion updates save component settings from Update Settings tab

.github/workflows/win-cpn-32.yml
`mingw-w64-i686-arm-none-eabi-gcc` is not actually a build dependency.
Fixes recent build failures of win32 Companion builds, which started due to this package being pulled from the MSYS package repo yesterday. 
i.e. 6b01a0c6732146c72b729937771c9e399d037795
@rotorman You may want to check your package install scripts and update them as necessary ;)
=> fix(gh): Don't install `arm-none-eabi-gcc` pkg

radio/src/storage/sdcard_yaml.cpp, radio/src/tests/conversions.cpp
Set warning/critical to default values before reading YAML model file. Otherwise, these values will be 0 if either the old or the new tags are not present, which is the case when coming from 2.7.
Fixes #2591
=> fix(yaml): RF link alarms

radio/src/lua/lua_widget.cpp, radio/src/lua/lua_widget.h
As LVGL does not support natively the gestures handled by LUA with respect to touch sensors, this PR re-implements the "tap count" instead of relying on the internal driver exporting the data.
Fixes #2617
=> fix(lua): re-implement LUA "tap" events

radio/src/telemetry/telemetry.cpp
External modules using the new module interface (direkt polling of telemetry based on driver) disabled legacy telemetry polling (S.PORT shared pin) to avoid confusing the telemetry parser. However, this fix (see #2504) was implemented poorly and removed sensor processing, which is done in the same function.
**External** modules / protocol impacted:
- `ACCESS`: `R9M ACCESS`
- `CRSF`: Crossfire, Tracer and ELRS
It would impact basically anything that is related to sensor processing:
- Vario sound (#2546)
- RF Link quality warnings (#2591)
- `Telemetry Lost` / `Telemetry Recovered` announcements
- Computed sensors (ex: Cell average)
This PR fixes the issue by only skipping the polling itself, but not the sensor processing further down in the function.
Fixes #2546
Fixes #2591
=> fix(telemetry): sensor processing with legacy polling disabled

radio/src/gui/colorlcd/hw_intmodule.cpp, radio/src/gui/gui_common.cpp
As it seems to confuse people and they are trying to set the internal module to `OFF` in the hardware settings, let's remove that possibility.
To make it clear once more:
- `Hardware Settings`: which module is installed in the radio (we don't actually support `OFF` here)
- `Model Settings`: should the internal module be turned `ON` or `OFF` for that model?
=> Prevent OFF for internal module in hardware settings

radio/src/gui/colorlcd/page.cpp, radio/src/gui/colorlcd/page.h, radio/src/gui/colorlcd/tabsgroup.cpp
... otherwise unexpected things happen.
Fixes #2595
=> fix(color): prevent event bubbling in Page and TabsGroup

radio/src/gui/colorlcd/LvglWrapper.cpp
This PR fixes an issue introduced in #2573.
What happens is the following:
- `KEY_EXIT` is pressed and released (`EVT_KEY_BREAK(KEY_EXIT)`)
- this gets translated into `[LV_KEY_ESC / LV_INDEV_STATE_PRESSED]`
- now, as the matching was wrong (`KEY_EXIT` instead of `LV_KEY_ESC`), the state would never become `LV_INDEV_STATE_RELEASED` again.
- any none LVGL key (anything apart from `ENTER` and `EXIT`) would then trigger a double `CANCEL`.
=> fix(color): EXIT key handling

radio/src/targets/nv14/extmodule_helper.cpp
Fixes #2666
extmod invert use PP output instead of OD.
=> fix(nv14): Use PP for extmod invert output, remove redundant init

radio/src/lua/lua_widget.cpp
Suppress `EVT_KEY_BREAK(KEY_PGDN)` after `EVT_KEY_LONG(KEY_PGDN)` on targets which don't have a physical `KEY_PGUP`.
This way, the sequence is now clean: no more `EVT_VIRTUAL_NEXT_PAGE` emitted after `EVT_VIRTUAL_PREV_PAGE` on these targets.
=> fix(lua): [page down long] translation to [page up]

radio/src/simu.cpp, radio/src/targets/simu/opentxsimulator.cpp
The acceleration calculation is relying on it to compute dx/dt.
Fixes #2669
=> fix(simu): rotencDt must be updated as well

radio/src/gui/colorlcd/radio_ghost_module_config.cpp, radio/src/gui/colorlcd/radio_ghost_module_config.h
This is a quick fix for Ghost module remote menu . Tested only oon TX16S, unsure of behavior on radio without rotary encoder like nv14 (but also unsure how it works today on those)
This fixes #2559
=> Fix ghost module remote menu for 2.8

.github/workflows/actions.yml, .github/workflows/linux_cpn.yml, .github/workflows/macosx_cpn.yml, .github/workflows/nightly.yml, .github/workflows/win-cpn-32.yml, .github/workflows/win_cpn-64.yml
Fixes warning starting to show in github actions:
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/upload-artifact, actions/checkout
More were present for companion builds - if they still work ~~only `maxim-lobanov/setup-xcode` remains outstanding~~. Between maxim-lobanov/setup-xcode#49 and maxim-lobanov/setup-xcode#50 this should no longer be present.
New one started showing today (update: only for the Mac Companion build, none of the other builds show it)
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more …
=> chore(github): Node.js 12 based actions deprecated

companion/src/firmwares/boards.cpp, companion/src/firmwares/edgetx/yaml_rawsource.cpp, companion/src/firmwares/opentx/opentxeeprom.cpp
Fixes #2694
- align gyro and joysticks for X10, X12S and X Lite to radios
- add yaml conversion for GYRO1 and GYRO2 to TILT-X and TILT-Y
- add bin conversion
=> cpn(fix): gyro and joystick

radio/src/translations/de.h
since the GPS button is now displayed by default (#2732), the labels for the "Alarms" and "LCD" are much too long and thus GPS is pushed into a new line. This looks unattractive and is a waste of space
Fixes #
=> de optimization

radio/src/gui/colorlcd/fullscreen_dialog.cpp
Prior to this fix, the confirmation dialog would crash because of an issue in libopenui and even then would not be displayed for the lack of the proper parent window.
Fixes #2741
- fix `libopenui` to properly check validity of pointers before passing objects to LVGL functions (`lv_obj_move_foreground`)
- use the most suitable parent when creating a confirmation dialog
=> fix(MSD): confirmation dialog properly shown

radio/src/gui/colorlcd/radio_setup.cpp, radio/src/translations/de.h
It is related to GPS telemetry, not internal GPS.
This probably needs to implemented differently in the future.
Fixes #2727
=> fix: Always show GPS button in radio setup

radio/src/gui/colorlcd/output_edit.cpp
Fixes #2757 
Summary of changes: add getDefault() to the PPM center numberEdit()
=> add setDefault() to PPM Center

cmake/toolchain/native.cmake
When compiling `simu`, `clang` complains about all the StdPeriph headers declaring assembly with invalid operand width.
=> chore(compilation): silence some warning on apple silicon

radio/src/gui/colorlcd/radio_theme.cpp
Fixes #2785 
Summary of changes: initialize pointers to nullptr for the first use.
=> initialise pointers to nullptr before the first use (fix #2785)

radio/src/lua/api_general.cpp, radio/src/lua/api_model.cpp
**Warning: this PR introduces a change in behaviour**
Prior to this change, `model.getFlightMode()` and `model.getCurve()` would return arrays with integer indexes starting at `0`, which breaks a lot of things with LUA. For instance, copying such an array removes the first element (index `0` is not copied).
**Summary of changes:**
- fixed array indexes in `model.getFlightMode()`
- fixed array indexes in `model.getCurve()`
- use array indexes to allow for incomplete table in `model.setFlightMode()`
Fixes #976
This script has been used to test the correctness of the changes.
```lua
local toolName = "TNS|TrimMode|TNE"
local lastEvent = ""
local eventTime = 0
-- String identifying events
local function evt2str(event)
if event == EVT_VIRTUAL_PREV then return "EVT_VIRTUAL_PREV"
elseif event == …
```
=> fix(lua): array indexes in some set/get functions

radio/src/gui/128x64/model_setup.cpp, radio/src/gui/128x64/radio_setup.cpp, radio/src/gui/212x64/model_setup.cpp, radio/src/gui/212x64/radio_setup.cpp, radio/src/gui/colorlcd/LvglWrapper.cpp, radio/src/gui/colorlcd/access_settings.cpp, radio/src/gui/colorlcd/input_mix_group.cpp, radio/src/gui/colorlcd/input_source.cpp, radio/src/gui/colorlcd/layouts/sliders.cpp, radio/src/gui/colorlcd/lcd.cpp, radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/model_mixes.cpp, radio/src/gui/colorlcd/model_telemetry.cpp, radio/src/gui/colorlcd/preview_window.h, radio/src/gui/colorlcd/splash.cpp, radio/src/gui/common/stdlcd/radio_sdmanager.cpp, radio/src/gui/common/stdlcd/radio_version.cpp, radio/src/gui/common/stdlcd/utf8.cpp, radio/src/gui/gui_common.cpp, radio/src/gui/screenshot.cpp, radio/src/lua/api_general.cpp, radio/src/simu.cpp, radio/src/targets/common/arm/stm32/intmodule_serial_driver.cpp, radio/src/targets/nv14/bootloader/boot_menu.cpp, radio/src/targets/simu/simulcd.cpp
fixes warning for simu and firmware for all targets
Some warnings are still in there:
colorlcd/color_edit.cpp, because I did not understand the intention of the code there
some string copy operations still create warnings in simu, because of a strict target size check
some warnings in lvgl will not be fixed
=> fix a bunch of warnings

radio/src/gui/colorlcd/model_flightmodes.cpp, radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h
Fixes #2797
Added translation for Check FM Trims button for color radios and separated the button text string for BW and color radios in the firmware translation files.
=> Check FM Trims translateable for color radios

companion/src/helpers.cpp, companion/src/helpers.h, companion/src/updates/repomodels.cpp, companion/src/updates/repomodels.h, companion/src/updates/updateinterface.cpp, companion/src/updates/updateinterface.h
Fixes #2822
- enhance SemantecVersion class
- add sort order field to release data models and populate with version if available otherwise use release creation date
Notes:
1. repositories with a mix of release tag descriptions where some tags are valid semantec versions is likely to result in a mixed up order
2. nightlies are a special case and treated as highest version
3. 32 bit compatible
Before
After
=> cpn(fix): release list order use version when available otherwise use date

companion/src/generaledit/generalsetup.cpp, companion/src/generaledit/generalsetup.h, companion/src/generaledit/generalsetup.ui
Fixes #2672
- add standard name validation
- hide label and field if radio does not support ACCESS
Note: decision required on inconsistent validation across radios
=> fix(cpn): ACCESS owner registration id validation (#2672)

radio/src/gui/colorlcd/widgets/timer.cpp
Limit length of name text drawn in small size timer widget to prevent random characters appearing.
Fixes #2807
Use 'drawSizedText' instead of 'drawText' as suggested by schnupperm in the issue description.
=> fix(color): Fix top bar timer widget names sometimes having garbage characters

companion/src/simulation/widgets/radioknobwidget.h, companion/src/simulation/widgets/radiowidget.cpp
Ensure consistent values for the TX16, 6 position switch, in the simulator.
Fixes #2827
- Round value to nearest step size in KnobWidget::setValue
- Prevent second call to 'emit valueChange()' with old 'value' in RadioWidget::setValue when value is rounded to nearest step size for 6 position switch.
=> fix(sim): Consistent steps for 6POS

companion/src/mdichild.cpp
MacOS companion does not save models if ".etx" extension not in filename.
Tested on MacOS 10, 11, 12 and 13.
Fixes #2809
Use the same filter in call to QFileDialog::getSaveFileName (in MdiChild::saveAs) for MacOS as other platforms.
=> fix(cpn): MacOS not saving unless `.etx` in filename

companion/targets/mac/MacOSXBundleInfo.plist.in
Force companion and simulator to use light mode on MacOS as workaround to make the UI more readable, when user has selected dark mode on their Mac.
Fixes #2459
Add NSRequiresAquaSystemAppearance = true to the info.plist for MacOS to force light mode UI.
=> feat(cpn): Force light mode UI on MacOS for legibility

companion/src/simulation/widgets/radioknobwidget.h
Fixes #
The default dial widget display on MacOS simulator is hard to see. This change forces the dial to use the 'fusion' style to make it display better.
Current style:
New style:
=> feat(sim): Forced style for POT/6POS knobs on MacOS for legibility

cmake/Macros.cmake, radio/src/CMakeLists.txt, radio/src/model_init.cpp, radio/src/rtos.h, radio/src/serial.cpp, radio/src/storage/rtc_backup.cpp, radio/src/targets/horus/CMakeLists.txt, radio/src/targets/nv14/CMakeLists.txt, radio/src/targets/simu/CMakeLists.txt, radio/src/targets/simu/simudisk.cpp, radio/src/targets/simu/simueeprom.cpp, radio/src/tasks.cpp, radio/src/tests/CMakeLists.txt, radio/src/tests/gtests.cpp
This PR improves the CMake files a bit, and cuts down some of the build time for commit tests.
- factorise datacopy into a macro
- use an object lib for most simu based source code (simu, Qt simulator plug-in and gtests)
TODO:
=> chore(cmake): CMake cleanup and simplifications

companion/src/simulation/widgets/radioknobwidget.h, companion/src/simulation/widgets/radioswitchwidget.h, companion/src/simulation/widgets/radiowidget.cpp
Fix 2POS switch logic in simulator. Recent change for 6POS switch broke the 2POS switches.
Fixes side-effect of #2831
The changes to the 6POS switch logic unfortunately broke the 2POS switches.
This update fixes this by making the code change specific to the 6POS switch control.
=> fix(sim): Fix for 2POS switch logic affected by 6POS switch change.

radio/src/storage/modelslist.cpp
Fixes #2844
In ModelsList::isModelIdUnique function:
- cast comparison value to int to avoid signed / unsigned comparison error if (curr - warn_buf) > 48.
Note: only tested in the simulator; but should fix issue in affected radios.
=> fix(color): EM triggered when checking if modelID unique in certain instances

radio/src/gui/colorlcd/input_mix_button.cpp, radio/src/gui/colorlcd/input_mix_group.cpp
Fixes #2703
- Adjust LVGL layout to reduce the chance of text overlap on the mixer screen for color lcd radios.
Note: it is still possible to get a small amount of overlap if input and mix names are max length using a lot of wide characters; but this change should remove overlap for most cases.
Screenshots:
Existing layout
New layout
=> Fix  for issue 2703 - mixer layout on color lcd screens

radio/src/translations/jp.h
Fixing an extra string in jp.h that was included.
(PR #2800 content transcription error)
=> Fixes an extra string that was included.

radio/src/gui/colorlcd/view_main.cpp
Fixes #2880 
check if there is a tile to access before really accessing it
=> fix(ui): check if there is an object to access before accessing it

radio/src/gui/colorlcd/radio_setup.cpp
- Limits the max value for the day field to the actual number of days in the selected month and year
- If the month or year is updated, and the day value is out of range, reset day value to max value for month & year
- Only update UI values on screen if the RTC value is different to the displayed value (assumes screen update is expensive compared to value comparison)
- Limit the range for the hour value to 0..23 (was 0..24)
=> Changes to date/time setting on color LCD radios.

radio/src/gui/colorlcd/file_browser.cpp
Changes the sort order for the SD card file browser on color LCD radios to a simplified natural ordering.
Model files will show in numerical order instead of:
model1.yml
model10.yml
model2.yml
...
=> Add a natural sort order for SD card file browser on color LCD radios.

radio/src/gui/colorlcd/color_picker.cpp, radio/src/gui/colorlcd/confirm_dialog.cpp
Change the background color of the ConfirmDialog and ColorEditorPopup dialogs.
Before:
After:
=> feat(ui) - Change dialog background color to make buttons more visible.

companion/src/firmwares/edgetx/yaml_switchconfig.h
The YamlStickConfig definition was defined and sized with CPN_MAX_SWITCHES (32) instead of CPN_MAX_STICKS (4).
When loading radio.yml this would overwrite 112 bytes past the end of the stickName array in the GeneralSettings class.
=> fix(cpn): Fix the size of the YamlStickConfig struct in companion.

radio/src/gui/colorlcd/model_outputs.cpp
Fixes #2906
Call the 'refresh' method when redrawing the Output buttons to get the updated trim value.
=> fix(ui) - UI is not updated when using the 'Add trims to subtrims' button on the Outputs page.

companion/src/helpers.cpp, companion/src/helpers.h, companion/src/mainwindow.cpp
Prevents Companion app crashing on exit while the simulator is open.
In MacOS 10 the user cannot exit the app when the simulator window is open.
On MacOS 11, 12 and 13, the user can exit the app - from the Quit menu option or by pressing Command+Q.
However the app crashes while closing, prompting the user to send a bug report to apple.
This change stops the main window from closing, allowing the quit event to just close the simulator window.
Pressing Command+Q (or selecting Quit) a second time will close the Companion app.
I suspect there is a timing issue at play; but I have so far not been able to find it. 
This change is probably not ideal; but I think is a reasonable work around for now.
Add a function to test if the simulator is running to helpers.cpp.
Ignore the …
=> fix(cpn): Ignore 'Quit' event in main window on MacOS simulator running

radio/src/gui/colorlcd/theme_manager.cpp
The ThemePersistance::scanThemeFolder method was not closing the file it opened, leaking a file handle for each theme on the SD card.
The themes are only scanned once on startup so not a huge issue on a radio. 
However, at least on MacOS, this eventually crashes the simulator / companion if the radio is reloaded in the simulator or the simulator is closed and opened multiple times.
Close the file handle in ThemePersistance::scanThemeFolder.
=> fix(color) - Fix file handle leak in theme manager.

radio/src/gui/colorlcd/curveedit.cpp
Fixes the problem described in this comment:
https://github.com/EdgeTX/edgetx/pull/2580#issuecomment-1354403082
Summary of changes: use raw input (stick) rather than detected input when such indirection exists.
=> Fix source selection for curve display

radio/src/gui/colorlcd/color_editor.cpp, radio/src/gui/colorlcd/color_editor.h, radio/src/gui/colorlcd/color_picker.cpp
I did not like the way the color picker saved changes back to the source value immediately - if you did not like the new color there was no easy way to undo changes. This version will only update the source when the 'Save' button pressed, Cancel will abort any changes.
I also added a new editor to quickly pick from the system defined theme colors.
- add title to popup window
- add Save and Cancel buttons
- Source value only updated when 'Save'' button pressed
- Add editor to select from system theme colors
=> feat(ui): Revised color picker

radio/src/gui/colorlcd/model_select.cpp
Alternate solution to the one in PR #2792
My testing on TX16S and in the simulator has no issues; but if there are reasons why doing it this way won't work please let me know.
Fixes #2722 and #2921
Close model select page before loading model so notes window is not hidden.
=> fix(color): Display of model notes when selecting model

radio/src/gui/colorlcd/output_edit.cpp, radio/src/gui/colorlcd/output_edit.h
replaces  https://github.com/EdgeTX/edgetx/pull/2902 due to my github f'up
Fixes https://github.com/EdgeTX/edgetx/issues/2859
Logic is based on mixer output for the respective channel.
Mixer 0% as reference for switching indications.
=> fix(color): Ouputs tab wrong value used for min/max highlighting

radio/src/gui/colorlcd/layouts/sliders.cpp, radio/src/gui/colorlcd/layouts/sliders.h, radio/src/gui/colorlcd/view_main_decoration.cpp
fixes https://github.com/EdgeTX/edgetx/issues/2818
https://user-images.githubusercontent.com/5615068/208301862-d9f20a91-f978-4717-ac99-a8effce8f66d.mp4
=> fix(color): Center flight mode text and 6Pos numbers

radio/src/gui/colorlcd/layouts/layout_factory_impl.cpp, radio/src/gui/colorlcd/layouts/layout_factory_impl.h, radio/src/gui/colorlcd/theme_manager.cpp, radio/src/gui/colorlcd/view_main.cpp, radio/src/gui/colorlcd/view_main.h, radio/src/gui/colorlcd/view_main_decoration.cpp, radio/src/gui/colorlcd/view_main_decoration.h, radio/src/gui/colorlcd/widgets/widgets_container_impl.h, radio/src/gui/colorlcd/widgets_container.h
Fixes #2688
Add methods to allow the theme manager to trigger updates of the main view screens after a theme is loaded or changed.
Most screen elements redraw after a theme change; but the flight mode text color is not automatically updated so has to be manually changed to the new theme color.
=> fix(ui) - Fix flight mode color on startup, or when theme is edited or active theme is changed.

radio/src/gui/colorlcd/file_browser.cpp, radio/src/gui/colorlcd/model_templates.cpp, radio/src/gui/colorlcd/radio_tools.cpp, radio/src/gui/common/stdlcd/radio_sdmanager.cpp, radio/src/gui/common/stdlcd/radio_tools.cpp, radio/src/sdcard.cpp
Fixes #2852 
Add hidden file filter to various places where the SD card files and folders are being iterated over.
=> fix(ui) - Ignore hidden file when iterating SD card contents.

radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h
Add missing entries as needed
Most of the languages have a translation for `TR_EXTERNAL_MODULE` already so I used the same translation here. 
Leaving just:
for the last entry, "External module" 
```
#define TR_AUX_SERIAL_MODES            "OFF","Telem Mirror","Telemetry In","SBUS Trainer","LUA","CLI","GPS","Debug","SpaceMouse","External module"
```
If you would like to make a suggestion for the respective short and long forms for the following I can do those also ;)
```
#define TR_INTERNAL_MODULE             TR("Int. module", "Internal module")
#define TR_EXTERNAL_MODULE             TR("Ext. module", "External module")
```
Also for DE and IT (@robustini)
```
#define TR_WIDGET_FULLSCREEN           "Full screen"
```
=> fix(translation): Add SpaceMouse/External Module and other minor translation catchups

radio/src/gui/colorlcd/layouts/layout_factory_impl.cpp, radio/src/gui/colorlcd/layouts/layout_factory_impl.h
Fixes #2961 
Add enum for the 'decorationSettings' bits to make the code more understandable.
Fix the size check in 'getMainZone'.
=> fix(ui) - Fix layout size issue (#2961) and improve code readability.

radio/src/gui/colorlcd/layouts/sliders.cpp
Fixes #2943
Summary of changes: fix mismatch in value definition between checkEvents() and paint(0 for MainView6POS.
=> Fix display of 6POS display. (#2943)

radio/src/gui/colorlcd/model_logical_switches.cpp
Fixes #2966 
Summary of changes: use proper output function for V2 value in Timer LS
=> Fix precision for V2 in TIMER LS (#2966)

radio/src/lua/api_model.cpp
Fixes #2960 
Add the switch and countdownStart properties to the getTimer and setTimer Lua functions.
=> fix(lua) - Add missing switch and countdownStart properties to timer functions

radio/src/gui/colorlcd/model_gvars.cpp, radio/src/gui/colorlcd/model_gvars.h
=> chore(ui): convert gvars window to LVGL

radio/src/FreeRTOSConfig.h, radio/src/cli.cpp, radio/src/gui/212x64/view_statistics.cpp, radio/src/opentx.cpp, radio/src/rtos.h, radio/src/tasks.cpp, radio/src/tasks.h
- enabled StackHighWaterMark in freeRTOS config
- using uxTaskGetStackHighWaterMark() for stack free status inquiry
- deleted obsolete code for stack painting freeRTOS task stacks
successfully tested with TX16s radio
=> freeRTOS task stack diagnostics using freeRTOS function

radio/src/lua/api_colorlcd.cpp
- removed an extra line at the bottom of the hud rectangle
- fixed overflowing hud rectangle for horizon outside (below) viewport (pitch > 0)
The C++ code is a direct port of my original LUA hud drawing code which had the same bug hidden by OpenTX not drawing rectangles with a negative height.
Lua code required an extra bottom line to be drawn to fill the rectangle when roll was 0 that is not necessary in C++
=> lua: fix drawHudRectangle for roll = 0

radio/src/datastructs_private.h, radio/src/gui/128x64/model_input_edit.cpp, radio/src/gui/212x64/model_input_edit.cpp, radio/src/gui/colorlcd/input_edit_adv.cpp, radio/src/gui/colorlcd/input_source.cpp, radio/src/gui/common/stdlcd/model_inputs.cpp, radio/src/lua/api_model.cpp, radio/src/mixer.cpp, radio/src/opentx.cpp, radio/src/tests/mixer.cpp
- rename the carryTrim in ExpoData to trimSource, and fix it's lua casting
- trimSource is using positive values, where carryTrim was using negative ones
This fixes https://github.com/opentx/opentx/issues/8995 also existing in EdgeTX
There is no Companion impact, as data model is untouched.
=> Fix carryTrim in LUA

radio/src/targets/horus/board.cpp
With the LED turned RED if the RTC data retrieval fails it will stay red. This will at least be an indication that the RTC startup encountered a problem. For now there is no indication that this problem occurred.
It doesn't really fix #3005, but helps in diagnostics.
Added red LED before initializing RTC and blue LED afterward.
=> Added turning the red LED before RTC data and blue LED afterwards

radio/src/gui/colorlcd/tabsgroup.cpp
Fixes #3031 
Periodically refresh header to update date/time value.
Note: header refresh also redraws all the icons. To avoid too much overhead the header is only refreshed once every 5 seconds. The time does not display seconds so this should be adequate.
=> fix(ui) - Update date & time in top bar on model and radio setup pages.

companion/src/mdichild.cpp
Fixes #3023 and same issue of no file saved if file extension not yml for model export.
Summary of changes
- enforce etx on save and save as, and yml on model export
- remove yml from save and save as filters
=> fix(cpn): Enforce file extensions on models and settings save and model export

companion/src/storage/labeled.cpp
Fixes #2817 #3011 
Make companion work the same on color LCD radios as on B&W - delete all model files from the radio before saving new models.
=> fix(cpn) - Delete old models from radio before saving new models

radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/model_inputs.h, radio/src/gui/colorlcd/model_mixes.cpp, radio/src/gui/colorlcd/model_mixes.h
Fixes #2981
The _run_popup_dialog function crashes on the model inputs and model mixes pages (I don't know why).
This change replaces the POPUP_WARNING call with a MessageDialog popup on the current window - it seems to achieve the same result without the crash.
It also uses the translated string for the warning popup title instead of a hard wired english string.
=> fix (ui) - Fix crash on model inputs and model mixes pages if limit on mixes/expos reached.

companion/src/firmwares/edgetx/yaml_logicalswitchdata.cpp, companion/src/firmwares/edgetx/yaml_rawswitch.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp
Fixes #3022 
Fixes a logic error in the timerValue2lsw function when converting YAML values for 'Edge' and 'Timer' logical switches.
The existing version will corrupt the saved values for these logical switch functions when the model is re-loaded. Unfortunately there is no way to undo this and restore the original value.
=> fix(ui,cpn) - Fix error in value conversion when loading logical switch data.

radio/src/gui/colorlcd/model_logical_switches.cpp
Fixes #3048 (#3035)
Fix to correctly update the second time value (V3) for 'Edge' switches when V2 is updated, and also display the new V3 value immediately.
=> fix(ui) - Fix update of V3 when V2 is modified whilst editing a logical switch.

radio/src/gui/colorlcd/curveedit.cpp, radio/src/gui/colorlcd/model_gvars.cpp, radio/src/gui/colorlcd/model_logical_switches.cpp, radio/src/gui/colorlcd/model_mixer_scripts.cpp, radio/src/gui/colorlcd/model_telemetry.cpp, radio/src/gui/colorlcd/radio_calibration.cpp, radio/src/gui/colorlcd/special_functions.cpp
Use 'Page' class 'header' property to display the title where possible (instead of creating a new object).
=> Cleanup title display logic on various pages.

radio/src/gui/colorlcd/special_functions.cpp, radio/src/gui/colorlcd/special_functions.h
- Convert the page to use the flex layout
- Move the function name into the button control for an active function so the entire row acts as a button
- Displays the active functions first with fixed height for each line
- Displays the inactive functions second as a grid so there is less to scroll through
=> Revised Special & Global Functions layout.

radio/src/gui/colorlcd/popups.cpp
Fixes the underlying problem with the popups from issue #2981 
PR #2985 fixed the issue by not using the POPUP_WARNING function - this change fixes the root cause in case there are any other places that might be affected.
=> fix(ui) - Prevent infinite loop and crash in popups.

radio/src/gui/colorlcd/view_main.cpp, radio/src/gui/colorlcd/view_main.h, radio/src/gui/colorlcd/view_main_menu.cpp, radio/src/gui/colorlcd/view_main_menu.h
Fixes #3087 
Close the menu popup on the main view before navigating to other pages.
=> fix(ui) - Close menu popup on main view when switching to other views.

radio/src/gui/colorlcd/model_curves.cpp, radio/src/gui/colorlcd/model_curves.h
Align with new special function and proposed logical switch UI.
Also adds titles to the menus to make it clearer what action is being performed.
Short press:
Long press:
=> feat(ui) - Add long press handler for new model curves page.

radio/src/gui/colorlcd/curveedit.cpp
Fixes #3088 
Set the alignment for the curve editor number input boxes to be center aligned.
Make the X & Y numbers align as closely as possible.
=> fix(ui) - Center align the text in the number input boxes for the curve editor.

companion/src/simulation/simulatorwidget.cpp
On my TX16S the sliders could be seen in the companion joystick setup; but would not connect to the simulator widgets regardless of the mapping option selected in the dropdown.
The index being passed to the widgetValueChanged event was incorrect.
Note: On the TX16S the LS and RS sliders should be mapped to Knob/Slider 8 and Knob/Slider 9 respectively. They will then control the simulator widgets correctly.
For some reason the companion code setup thinks the TX16S has 7 pots ???
=> fix(cpn) - Fix joystick slider mappings in companion.

radio/src/gui/colorlcd/view_main.cpp
Long press on SYS button jumps to the radio setup tab.
Partially addresses #169
=> feat(ui) - Add long press for SYS button on main screen.

companion/src/helpers.cpp, companion/src/helpers.h, companion/src/mainwindow.cpp, companion/src/mdichild.cpp, companion/src/mdichild.h
Fixes #2932
- display a static progress message whilst writing
The ideal solution would be a progress bar however the refactoring is not insignificant.
=> feat(cpn): Status dialog when writing models and settings to radio

radio/src/CMakeLists.txt, radio/src/targets/common/arm/stm32/usbd_desc.c, radio/src/targets/common/arm/stm32/usbd_storage_msd.cpp
Skips creating the "FIRMWARE" drive, when attaching radio in mass storage mode to the computer. Tested with RM TX16S.
=> feat(fw): Only attach SD card in USB storage mode

radio/src/gui/gui_common.cpp, radio/src/telemetry/multi.cpp
Fixes issues post #3032 whereby:
- protocol list was completely unusable on B&W radios
- subprotocol lists for some Frsky protocols were too long
Tested with:
- TX16, internal MPM, Frsky X and Frsky X2 receivers bound and telemetry scan. 
- TX12MK2, external MPM, same as above. 
- X9D+, external MPM, same as above. 
- NV14, external MPM, same as above.
=> fix: B&W MPM protocol offset, subprotocol lists too long

radio/src/gui/colorlcd/radio_theme.cpp, radio/src/gui/colorlcd/radio_theme.h
The theme select & edit pages probably need some work; but I'll save that for another PR as I think it could also use some design input.
The theme details edit dialog has been revised slightly.
- Changed the background colour so the buttons are visible.
- Made the input text boxes a bit larger and put the description input box on it's own line.
- Put both buttons on the same line.
=> fix(ui) - LVGL flex conversion for the theme details edit dialog.

radio/src/gui/colorlcd/model_gvars.cpp
The flight mode names were displaying incorrectly for global variables in the GV overview page.
E.G. edit GV 1 and change the option for FM1 to be FM2 instead of FM0.
On the overview page it would show FM1 as FM1 instead of FM2.
=> fix(color) - Fix flight mode name display in global variables overview.

radio/src/targets/common/arm/stm32/stm32_hal.h
Single HAL headers/modules are enabled by changing the defines in `stm32f2xx_hal_conf.h` / `stm32f2xx_hal_conf.h` rather than being directly included into this file.
=> chore: fix STM32 HAL headers

radio/src/gui/colorlcd/model_telemetry.cpp, radio/src/gui/colorlcd/model_telemetry.h
Conversion to LVGL flex layout for telemetry pages.
For portrait layout, long strings like GPS are displayed in small font in order to fit.
=> fix(ui) - LVGL conversion for telemetry.

radio/src/gui/colorlcd/model_mixer_scripts.cpp
=> fix(ui) - LVGL flex conversion for custom mixer scripts.

companion/src/firmwares/edgetx/yaml_expodata.cpp, radio/src/datastructs_private.h, radio/src/storage/yaml/yaml_datastructs_boxer.cpp, radio/src/storage/yaml/yaml_datastructs_funcs.cpp, radio/src/storage/yaml/yaml_datastructs_lr3pro.cpp, radio/src/storage/yaml/yaml_datastructs_nv14.cpp, radio/src/storage/yaml/yaml_datastructs_t12.cpp, radio/src/storage/yaml/yaml_datastructs_t8.cpp, radio/src/storage/yaml/yaml_datastructs_tlite.cpp, radio/src/storage/yaml/yaml_datastructs_tpro.cpp, radio/src/storage/yaml/yaml_datastructs_tx12.cpp, radio/src/storage/yaml/yaml_datastructs_tx12mk2.cpp, radio/src/storage/yaml/yaml_datastructs_x10.cpp, radio/src/storage/yaml/yaml_datastructs_x12s.cpp, radio/src/storage/yaml/yaml_datastructs_x7.cpp, radio/src/storage/yaml/yaml_datastructs_x9d.cpp, radio/src/storage/yaml/yaml_datastructs_x9e.cpp, radio/src/storage/yaml/yaml_datastructs_x9lite.cpp, radio/src/storage/yaml/yaml_datastructs_x9lites.cpp, radio/src/storage/yaml/yaml_datastructs_xlite.cpp, radio/src/storage/yaml/yaml_datastructs_xlites.cpp, radio/src/storage/yaml/yaml_datastructs_zorro.cpp, radio/src/storage/yaml/yaml_tree_walker.cpp, tools/generate-yaml.sh
Fixes issue with #2995 where the data model is actually changed. This is part 1 of the intended 2-part fix... to simply resolve the issue for 2.8.1 and Companion 2.8.1. Ideally, Companion 2.9 would refer to carryTime as trimSource internally to remove any confusion.
=> PR2995 carryTrim cleanup

radio/src/gui/colorlcd/radio_theme.cpp
In Radio Settings -> Themes
- Duplicate was always duplicated active theme, rather than selected theme
- Colour squares were not being refreshed if a theme was edited
=> fix(color): Duplicate selected theme, update color list

radio/src/targets/common/arm/stm32/stm32_hal.cpp, radio/src/targets/common/arm/stm32/timers_driver.cpp, radio/src/targets/common/arm/stm32/timers_driver.h
Fixes #3155 in 2.8
use a HW timer to generate a 1ms tick count instead of using the RTOS tick counter, which is not available during initialization
=> 2.8 hal tick fix

radio/src/targets/common/arm/stm32/stm32_hal.cpp, radio/src/targets/common/arm/stm32/timers_driver.cpp, radio/src/targets/common/arm/stm32/timers_driver.h, radio/src/targets/horus/board.cpp, radio/src/targets/nv14/board.cpp, radio/src/targets/nv14/hal.h, radio/src/targets/taranis/board.cpp
Fixes #3155 in main
use a HW timer to generate a 1ms tick count instead of using the RTOS tick counter, which is not available during initialization
=> Hal tick fix

radio/src/gui/colorlcd/model_telemetry.cpp
=> fix(color) - Use two rows for buttons when translation text is long (CZ)

radio/src/gui/colorlcd/radio_trainer.cpp, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h
Update the trainer setup page layout to:
- remove small amount of scroll of landscape layout
- use available space on portrait layout
=> fix(ui) - Trainer setup layout

companion/src/updates/updateinterface.cpp
Fixes #3159
Summary
- add manually maintained mapping where Companion does not match fw.json file entries
=> fix(cpn): Update firmware mapping of firmware id to repo

radio/src/gyro.cpp, radio/src/tasks.cpp, radio/src/tasks/mixer_task.cpp
- fixed a lock-up issue with touch sensor and IMU on the same I2C bus
- Please note that the HAL already handles busy I2C bus, so that we should not run into the case where the bus is used and another query is started. However, if that happens, HAL_BUSY will be returned, which leads to -1 being returned in our functions, thus increasing the error count until the sensor stops working.
- fixed a race condition between init and usage of the IMU sensor
- Init was placed in the UI task, while the sensor was queried in the mixer task.
Fixes #2786
=> fix: various issues related to IMU sensor

radio/src/targets/common/arm/stm32/stm32_i2c_driver.cpp, radio/src/targets/horus/hal.h
When building with `-DIMU=YES` and `-DIMU_LSM6DS33=YES` for TX16S, the AUX1 power was not enabled and thus easy plugging of LSM6DS33 IMU, such as [Adafruit LSM6DS33](https://www.adafruit.com/product/4480) to TX16S AUX1 port did not result in working system.
The issue with no power enabled on AUX1 with LSM6DS33 IMU, was likely introduced with #1744. This PR fixes the situation.
The power output on AUX1 was positively tested by Discord user KevTheRev.
=> fix: enable AUX1 power on TX16S with IMU_LSM6DS33

radio/src/storage/sdcard_yaml.cpp, radio/src/storage/sdcard_yaml.h
Fixes issue whereby no `RADIO/radio.yml` would trigger radio to power off rather than to initalise new files. 
The radio settings are loaded twice (i.e. B&W that show startup animation) or sometimes three times for some radios (i.e. TPro). It's only the final load that really needs to verify the checksum. The other times, checks are allowed to be ignored. 
- allow `loadRadioSettingsYaml` to skip checks, primarily when `storageReadRadioSettings` is called with the `false` flag
Was first detected on the RM Boxer after deleting the radio folder. I have tested this on this radio, and it now correctly starts and alerts if files are missing, and still performs checksum validation if the files are present. Will check behaviour on the T-Pro as that radio uniquely uses …
=> fix: `loadRadioSettingsYaml` not honoring checks flag

radio/src/targets/taranis/eeprom_driver.cpp
This was preventing conversions from EEPROM storage to work properly.
=> fix(eeprom): EEPROM address register is 16bit

radio/src/opentx.h, radio/src/targets/taranis/board.cpp
Fixes issue whereby RM Boxer is not following convention of blue during startup, green once operational in cases where radio has RGB power LED and manufacturer has not requested it be different.
=> fix(boxer): Power LED sequence

.github/workflows/macosx_cpn.yml
~~Seems that the MacOS Companion build now needs libusb before dfu-util?~ 
Seems to be a bug introduced by a new github-action runner image whereby `pkg-config` is missing
https://github.com/actions/runner-images/pull/7125
=> fix(gh): Mac Cpn action dependency reorder

radio/src/telemetry/crossfire.cpp
Looking at the code there seems something  wrong with CRSF GPS heading. I do not think it has been reported, nor do I have the necessary equipment to confirm, but looking at 
or betaflight code
/*
0x02 GPS
Payload:
int32_t     Latitude ( degree / 10000000 )
int32_t     Longitude (degree / 10000000 )
uint16_t    Groundspeed ( km/h / 10 )
uint16_t    GPS heading ( degree / 100 )
uint16      Altitude ( meter ­1000m offset )
uint8_t     Satellites in use ( counter )
*/
the current code cannot be right (and in addition, a 16bits uint cannot store 360 * 1000, so a 3 digits precision cannot work)
I would really appreciate if someone with a craft with GPS using CRSF could report
=> Fix CRSF GPS heading precision

radio/src/gui/colorlcd/widget.cpp, radio/src/gui/colorlcd/widget.h, radio/src/gui/colorlcd/widgets/widgets_container_impl.h, radio/src/lua/lua_widget.cpp, radio/src/lua/lua_widget.h, radio/src/lua/lua_widget_factory.cpp
Fixes #2598
Implements solution from @jfrickmann in issue 2598:
- Store the widget zone rectangle data in the Lua registry.
- Updates the zone data when the layout changes.
Also calls the widget 'update' function if the zone has been altered.
=> fix(lua) - Store and update the 'zone' rectangle for Lua widgets.

radio/src/lua/api_filesystem.cpp
Usage in LUA:
```lua
if del("/SCRIPTS/TOOLS/deleteme.txt") == 0 then
-- successfully deleted file
else
-- failed to deleted file
end
```
`del()` returns FRESULT:
https://github.com/EdgeTX/edgetx/blob/60cdb897ee8fe8d7fd4a44a5c4fef7e969ccac63/radio/src/thirdparty/FatFs/ff.h#L251-L272
Tested with simulator under Win10.
=> feat(LUA): adds delete command to filesystem API

radio/src/gui/colorlcd/str_functions.h
Fixes #3222.
Addressing
```
In file included from /builddir/build/BUILD/edgetx-2.8.1/radio/src/gui/colorlcd/str_functions.cpp:25: /builddir/build/BUILD/edgetx-2.8.1/radio/src/gui/colorlcd/str_functions.h:30:42: error: 'uint32_t' has not been declared
30 | extern std::string wrap(std::string str, uint32_t width);
|                                          ^~~~~~~~
```
The change helps compilation with gcc 13 while does not negatively affect gcc 12.
=> Addressing error: 'uint32_t' has not been declared

.github/workflows/win-cpn-32.yml, .github/workflows/win_cpn-64.yml, companion/src/CMakeLists.txt
Fixes #2929 #2758
- modify the github workflows including installing Qt tools openssl for each OS
- change the Companion installer processes to bundle the Qt versions of the openssl libs
Dependencies:
For linux builds https://github.com/EdgeTX/build-edgetx/pull/14 needs to be merged
TODO:
=> fix(build): packaged openssl files

radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/model_mixes.cpp, radio/src/gui/colorlcd/model_outputs.cpp
Fixes #3186
- Move button creation on inputs and mixes pages so the '+' button is not the first selected button.
- Force line height on outputs page so initial scroll height works.
=> fix(color) - Fix scroll wheel behaviour on inputs, mixes and outputs pages.

radio/src/telemetry/spektrum.cpp
Fixed DSM telemetry to allow LUA scripts to request the RAW DSM telemetry raw data.  This will enable the use of TextGen
Fixes #3125
Change the DMS telementry processing if I2C_TEXTGEN to make work, and make it more generic in general for other uses.
the LUA script can request to monitor an specific DSM telemetry message (I2C address), and will get the RAW data.
Here is the working firmware and lua script using this change:
https://www.youtube.com/watch?v=yrAqV4b9Li4
Attached is the 1 file LUA script to test it (will be added to the Multi-Module release, or I can add it to the EdgeTX Lua Scripts)
[DSM_SmartRX_Tel.zip](https://github.com/EdgeTX/edgetx/files/10529218/DSM_SmartRX_Tel.zip)
=> #3125 Changes to DSM Telemetry to allow LUA scripts to do TextGen

radio/src/gui/colorlcd/model_select.cpp
Currently a long press on the touch screen on  any model other than the selected one does nothing.
With this change, a long touch press on any model will select it and open the menu.
=> feat(color) - Update long press handler on model select page.

radio/src/tasks/mixer_task.cpp
=> fix(color) - Fix telemetry checks not running in simulator due to inverted logic.

companion/src/companion.cpp
This fixes some issues on MacOS Companion startup.
1. Show the main window before showing the splash screen:
- Fixes MacOS issue where the main window size and position is not restored if the splash screen is displayed first.
- Splash screen can be dismissed before the timeout (click on splash) and the main window can be used without having to wait for the timeout to finish.
2. Delay showing splash until after app.exec() started:
- Prevents lockup due to splash->show() call not returning. Note this only happen on my self-build versions; but happens on both Big Sur and Monterey.
4. Don't create splash objects unless needed (general optimisation).
=> feat(cpn) - Companion startup changes

radio/src/gui/colorlcd/confirm_dialog.cpp, radio/src/gui/colorlcd/listbox.cpp, radio/src/gui/colorlcd/listbox.h, radio/src/gui/colorlcd/page.cpp, radio/src/gui/colorlcd/page.h, radio/src/gui/colorlcd/radio_theme.cpp, radio/src/gui/colorlcd/radio_theme.h, radio/src/gui/colorlcd/tabsgroup.cpp, radio/src/gui/colorlcd/tabsgroup.h, radio/src/gui/colorlcd/theme_manager.cpp, radio/src/gui/colorlcd/theme_manager.h, radio/src/translations.cpp, radio/src/translations.h, radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h
Changes to theme related pages:
- Convert theme select, theme edit and color edit pages to LVGL flex.
- Add 'Edit Color' string to language files (requires translations).
- Simplify theme edit 'onCancel' logic.
- Replace strncpy and strncat in theme manager with strAppend - avoid possible unterminated strings and string overrun.
- Truncate display of long name and author strings in theme pages.
Change to other files to fix issues found:
- Fix size of buttons in ConfirmDialog for portrait layout.
- Truncate item strings in ListBox to fit available space.
- Set window background color on Page and TabsGroup classes instead of using 'paint' function.
=> fix(color) - Fixes and layout updates for theme pages.

radio/src/translations/fr.h
=> fix(color,fr) - Fix missing comma in FR translation.

companion/src/firmwares/boards.h, companion/src/firmwares/eeprominterface.h, companion/src/firmwares/generalsettings.cpp, companion/src/firmwares/generalsettings.h, companion/src/firmwares/opentx/opentxinterface.cpp, companion/src/generaledit/hardware.cpp, companion/src/generaledit/hardware.h, companion/src/modeledit/setup.cpp
Fixes #2383
- align Companion with #1765
- hardware
-- move antenna to within Internal RF section
-- code housekeeping
- model setup
-- Internal module fix when to display antenna parameter
-- fix antenna dropdown list sequence
- boards fix external antenna
Tested on a few libsims
=> fix(cpn): hardware and internal module antenna parameters

radio/src/pulses/afhds3.cpp, radio/src/pulses/afhds3_transport.cpp, radio/src/pulses/afhds3_transport.h
=> Added support for FRM303, enhancement 2863

radio/src/strhelpers.cpp
Fixes #3301
subtract 10 instead of 9 in case hex value is in [0xa..0xf]
=> fixes hex2char() returning wrong characters for 0xa..0xf

radio/src/gui/colorlcd/file_carosell.cpp, radio/src/gui/colorlcd/file_carosell.h, radio/src/translations.cpp, radio/src/translations.h, radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h
Use StaticText instead of 'paint' function for 'loading' message in theme file carousel.
Add message strings to translation files.
=> chore(color) - LVGL update and translation strings for theme file carousel.

radio/src/gui/colorlcd/channel_range.cpp
=> fix(color) - Fix update of 'end' value in ChannelRange class.

radio/src/targets/common/arm/stm32/f4/system_stm32f4xx.c, radio/src/targets/nv14/backlight_driver.cpp, radio/src/targets/nv14/board.h, radio/src/targets/nv14/bootloader/boot_menu.cpp
Fixes #3199
Because the resistance value of the pull-down resistor(R5) of the backlight pin is too large, the backlight will be turned on when the pin is not initialized at power-on.
=> fix:EL18 power-on backlight before screen content.

companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/generalsettings.h, companion/src/firmwares/opentx/opentxeeprom.cpp, companion/src/generaledit/generalsetup.cpp, companion/src/generaledit/generalsetup.h, companion/src/generaledit/generalsetup.ui
Fixes #3331 
- Change Companion logic for the splash screen settings to match the firmware logic.
- Only save/load splash screen settings for b&W radios.
=> fix(cpn) - Fix handling of the 'show splash' setting for B&W radios in Companion.

radio/src/gui/colorlcd/preflight_checks.cpp, radio/src/gui/colorlcd/radio_setup.cpp, radio/src/gui/colorlcd/throttle_params.cpp, radio/src/gui/colorlcd/trims_setup.cpp, radio/src/translations.cpp, radio/src/translations.h, radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/tw.h
Fixes #2534 
Also made the button size consistent and display better pot/slider name in the center beeps buttons in the pre-flight checks page.
=> fix(color) - Adjust page padding for pre-flight checks, trims and throttle setup pages.

radio/src/gui/colorlcd/tabsgroup.cpp
A small change that improves the performance when switching tabs in the radio and model setup views.
=> fix(color) - Make radio and model setup UI more responsive when switching tabs.

radio/src/gui/colorlcd/layouts/trims.cpp, radio/src/gui/colorlcd/layouts/trims.h
=> feat(color) - Implement DISPLAY_TRIMS_CHANGE option for color LCD trim widget.

radio/src/gui/gui_common.cpp
Fixes radio part of #3086
- make gvars available in source list
Tested on X9D+ libsim and does not appear to break other source lists.
Regression tested TX16S libsim
=> fix(B&W): Include gvars in input sources

companion/src/apppreferencesdialog.cpp, companion/src/apppreferencesdialog.ui, companion/src/simulation/simulatorwidget.cpp, companion/src/storage/appdata.h
Made the following changes to the Companion preferences:
- Don't wipe the user joystick settings if preferences dialog opened when radio is not connected as a joystick.
- Add an option to disable the alert popup when starting the simulator with no joystick connected.
- Remove reference to the "Ubuntu" font family for the 'Radio Type' label (showed a warning on MacOS).
=> fix(cpn) - Joystick preferences in Companion.

radio/src/mixer.cpp
=> fix(radio) - Change output value calculation to 'round away from 0' instead 'floor'.

companion/src/firmwares/edgetx/yaml_moduledata.cpp, companion/src/modeledit/setup.cpp, radio/src/gui/colorlcd/access_settings.cpp, radio/src/pulses/modules_helpers.h, radio/src/storage/storage_common.cpp
fixes https://github.com/EdgeTX/edgetx/issues/3273
The reason Companion doesn't show any registered ACCESS receivers is simply because color LCD radios don't populate the pxx2.receivers bit field after successfully binding receivers. Companion checks the bit field in yaml tag receivers: and as the bit filed results to no bit set it doesn't show the receiver names. Which in turn leads to the situation that all receivers are lost when playing back the model.yml file to the radio, forcing users to bind their receivers again.
Changes:
1. Color LCD (and simu) now set the correct bit in the pxx2.receivers bit field after a successful (or simulated) bind
2. Companion and radio firmware check after loading model.yml if pxx2 receiver names are given. If so it updates the pxx2.receivers bit field …
=> fix: Companion X10s Express, ISRM receiver name missing

radio/src/gui/colorlcd/model_telemetry.cpp
Fixes https://github.com/EdgeTX/edgetx/issues/3327
The problem is due to a classical race condition. `void ModelTelemetryPage::checkEvents()` is called cyclically and uses `int availableTelemetryIndex()` to determine if the model telemetry screen needs to be rebuilt due to a changed list of telemetry sensors using `void ModelTelemetryPage::rebuild()`. 
The last known index into the the telemetry sensor list memorized `int ModelTelemetryPage::lastKnownIndex` is compared to the number of available sensors. If different the screen needs to be updated (rebuilt). But `rebuild()` updates `lastKnownIndex` by calling `availableTelemetryIndex()` again when finished redrawing the screen. In time frame between the comparison if a rebuild is necessary until rebuild() finishes and …
=> fix: UI - not all detected sensors displayed at detection time

companion/src/simulation/widgets/virtualjoystickwidget.cpp
I missed one change after fixing the vertical axis logic in PR 3111
The throttle initial position needs to be set to -1 (down).
=> fix(cpn) - Fix throttle initialisation in Companion after changes in PR 3111.

radio/src/telemetry/spektrum.cpp
Fix for #3290
1. The BCD conversions was totally wrong.  The only code that used BCD was  for JETCATS sensor. I don't think that it ever worked with that BCD conversion.
2. Added support for the Spektrum GPS sensor 
3. Populated the Flight Mode sensor based on AS3X/SAFE information (AR631,etc)
4. Populated the Flight Mode sensor based on Alpha6 information (Blade Heli Controllers based on AR636)
=> fix(DSM Tel) Fix for Spektrum GPS Sensor

radio/src/pulses/afhds3.cpp
Fixes #3384
The configuration can only be obtained after switching the INRM301 model successfully, and the configuration should also be obtained after manually exiting binding.
=> Fix the BUG when switching models in EL18.

radio/src/gui/colorlcd/model_outputs.cpp
This does not speed up the overall page build/display time; but it prevents the UI from blocking while the outputs page is loading making navigation more responsive.
=> fix(color) - Improve responsiveness of the model outputs tab.

radio/src/gui/colorlcd/curveedit.cpp, radio/src/gui/colorlcd/curveedit.h, radio/src/gui/colorlcd/input_edit.cpp, radio/src/gui/colorlcd/model_curves.cpp, radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/model_inputs.h, radio/src/gui/colorlcd/model_logical_switches.cpp, radio/src/gui/colorlcd/model_mixer_scripts.cpp, radio/src/gui/colorlcd/model_mixes.cpp, radio/src/gui/colorlcd/model_mixes.h, radio/src/gui/colorlcd/model_outputs.cpp, radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/colorlcd/model_telemetry.cpp, radio/src/gui/colorlcd/module_setup.cpp, radio/src/gui/colorlcd/preflight_checks.cpp, radio/src/gui/colorlcd/radio_hardware.cpp, radio/src/gui/colorlcd/radio_sdmanager.cpp, radio/src/gui/colorlcd/radio_setup.cpp, radio/src/gui/colorlcd/radio_theme.cpp, radio/src/gui/colorlcd/radio_tools.cpp, radio/src/gui/colorlcd/screen_setup.cpp, radio/src/gui/colorlcd/screen_user_interface.cpp, radio/src/gui/colorlcd/special_functions.cpp, radio/src/gui/colorlcd/tabsgroup.cpp, radio/src/gui/colorlcd/timer_setup.cpp
WIP - add scroll bars to views with more content than will fit on a single screen.
Part 1 - Radio Settings:
- Tools
- SD Card
- Radio Setup
- Themes
- GLobal Functions
- Hardware
=> feat(color) - Add LVGL scroll bar where needed.

radio/src/targets/common/arm/stm32/extmodule_driver.cpp, radio/src/targets/common/arm/stm32/stm32_pulse_driver.cpp, radio/src/targets/taranis/intmodule_pulses_driver.cpp
This PR fixes some timing issues for the pulse drivers that might otherwise causes trouble with picky PXX1 modules. The issue is probably that the timing have been tuned to work with older radios, which had much slower raise time on the inverters. Newer harder has inverters with a faster raise time (to support higher bitrates).
- X10 (the old one, not the Express):
- X9D+ (legacy):
- TX16S MKII:
- RM Boxer:
Please note that the measurements above have been done with a pulse length set to `8 us`.
=> fix: more precise pulse timings

radio/src/opentx.cpp, radio/src/storage/storage_common.cpp, radio/src/targets/common/arm/stm32/bluetooth_driver.cpp, radio/src/tasks/mixer_task.cpp, radio/src/tasks/mixer_task.h
I must admit I'm not quite sure why this is an issue at this point, but we used to have the mixer (and thus sending stuff to modules / initialising telemetry, etc) running at a later point than today. This PR re-establishes the *status quo ante*.
=> Fix attempt for boot issue

radio/src/io/multi_firmware_update.cpp, radio/src/targets/common/arm/stm32/stm32_pulse_driver.cpp, radio/src/targets/common/arm/stm32/stm32_softserial_driver.cpp, radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp
- fixes for sending pulses/soft-serial using 32bit timers (X10E; mostly impacting MPM, DSM and similar)
- fixes for soft-serial RX (mostly X10E; caused by coupling btw. PPM & S.PORT lines)
- fix for USART driver RX side
=> Various soft serial fixes

radio/src/gui/colorlcd/model_gvars.cpp
Getting rid of the StaticText labels and using LVGL labels instead also improves the load time.
=> Replace StaticText with LVGL labels.

companion/src/firmwares/opentx/opentxinterface.cpp, radio/src/gui/colorlcd/model_flightmodes.cpp, radio/src/gui/colorlcd/model_flightmodes.h, radio/src/gui/gui_common.h
Fixes #2062 
- Move trim setup to FM edit page instead of being a popup
- Add trim value display/edit box to FM edit page (only displayed if enabled)
- Display FM list like logical switches, show all FM data for each mode
- Update the trim value range limits in Companion to match the radio
The list view layout is a bit messy; but I'm not sure how to do it any cleaner.
The list view can only handle 6 trim switches at the moment - I hope there aren't any radios with more.
The trim values in the list view will update automatically if the trim is altered via the trim switches (probably need to do this in the edit page as well).
I left the 'Check FM Trims' button at the bottom, although I don't really understand it's purpose. It will however now turn off automatically when …
=> feat(color) - Change Flight Mode list and edit views.

companion/src/apppreferencesdialog.ui, companion/src/mdichild.cpp, companion/src/mdichild.h, companion/src/modelslist.cpp, companion/src/modelslist.h
Fixes #3370
- fix paste
- housekeeping remove traces of old categories code
=> fix(cpn) - paste model to empty slot on B&W radios

radio/src/gui/gui_common.cpp
All credit goes to @philmoz  - thanks dude!
Fixes #https://github.com/EdgeTX/edgetx/issues/3423
- corrected wrong number of items in FrSky R9 protocol subtype list
=> fix (cpn):  fw simulator crashes on loading MPM protocol list

radio/src/targets/common/arm/stm32/stm32_pulse_driver.cpp
Fixes #3418 
- revert changes made to pulse driver in commit e016598
- tested successfully on X10access
Notes:
I suspect the change was made under a wrong assumption. Struct `LL_TIM_InitTypeDef` member `.Autoreload ` is of unsigende 32 bit (uint32_t) type . Setting `.Autoreload` to `STM32_DEFAULT_TIMER_AUTORELOAD` which is defined as value 65535 (= 0xffff) most likely tricked the author into thinking of 0xffff as a signed value. Hence the author extended the initialization code to distinguish between 16 and 32 bit timers and setting .Autoreload to 0xffffffff in case the timer is a 32bit timer. 0xffff is not a signed value so 32 bit timers should also be initialized with 0xffff to load the same countdown value as for 16 bit timers. This is what the original code did. …
=>  fix: X10access - no PPM output on CPPM pin

radio/src/pulses/afhds3.cpp
=> Fixed IRM301/FRM303 channels scaling problem.

companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/generalsettings.h, radio/src/dataconstants.h, radio/src/datastructs.h, radio/src/datastructs_private.h, radio/src/gui/colorlcd/radio_theme.cpp, radio/src/gui/colorlcd/theme_manager.cpp, radio/src/gui/colorlcd/theme_manager.h, radio/src/storage/yaml/yaml_datastructs_nv14.cpp, radio/src/storage/yaml/yaml_datastructs_x10.cpp, radio/src/storage/yaml/yaml_datastructs_x12s.cpp, radio/src/storage/yaml/yaml_labelslist.cpp, radio/src/storage/yaml/yaml_modelslist.cpp, radio/src/storage/yaml/yaml_parser.cpp, radio/src/storage/yaml/yaml_parser.h, radio/src/storage/yaml/yaml_tree_walker.cpp, radio/src/storage/yaml/yaml_tree_walker.h
- Remove hard wired code and use YAML parser for theme files.
- Fix handling of empty input lines in YAML parser.
- Increase size of YAML parser variables to handle theme 'info' property length.
=> feat(color) - Use generic YAML parser to save/load Theme yaml files.

radio/src/gui/colorlcd/widget.cpp
Fixes #3412 
The Menu popup dialog tries to find the parent full screen window to display the modal window over which should block all the other on-screen buttons.
The widgets are displayed on a child full screen window which sits under the main view menu bar, so the widget Menu popup does not block the top bar buttons.
This change tries to find the real top level full screen window to prevent this problem.
=> fix(color) - Fix issue where top menu bar still active when widget popup menu is opened

companion/src/firmwares/customfunctiondata.cpp, companion/src/firmwares/customfunctiondata.h, companion/src/firmwares/edgetx/yaml_customfunctiondata.cpp, companion/src/modeledit/customfunctions.cpp, companion/src/modeledit/customfunctions.h, radio/src/gui/128x64/model_special_functions.cpp, radio/src/gui/212x64/model_special_functions.cpp, radio/src/gui/colorlcd/special_functions.cpp, radio/src/lua/interface.cpp, radio/src/myeeprom.h, radio/src/storage/yaml/yaml_datastructs_funcs.cpp
Fixes #3321 
Adds the 'repeat' option to the 'Lua Script' special function.
The options are:
- 'On' = current functionality where script runs repeatedly while SF switch is active.
- '1x' = script is run only once for each activation the SF switch
Companion, Color and B&W radios supported.
Some minor layout adjustment needed for 128x64 B&W radios.
=> feat(radio) - Add 'repeat' option to 'Lua Script' special function.

radio/src/gui/212x64/model_setup.cpp
Fixes #3458 
Add missing test for empty 'title' value.
=> fix(radio) - Fix crash when editing multi module type on 212x64 LCD B&W radios.

radio/src/storage/storage_common.cpp
Fixes #3434
This fixes the shortcomings of [PR #3355](https://github.com/EdgeTX/edgetx/pull/3355) where ACCESS receiver name data was corrected to fix https://github.com/EdgeTX/edgetx/issues/3273
Added checking module types of the currently loaded model. If there is no PXX2 module selected there is nothing to correct. 
The problem finder confirmed this to fix his problem.
Note of shame:
Dummy me created a major mess with https://github.com/EdgeTX/edgetx/pull/3355 which showed it's ugly face in 2.8.2 (https://github.com/EdgeTX/edgetx/issues/3434) and is also present in 2.9. My fudge up causes under very specific conditions (which makes it look random) an index shift to Multi protocols (firmware and simulator). The reason is writing to the PXX2 module data struct via …
=> fix: undesired MPM protocol selection changes

radio/src/gui/128x64/model_failsafe.cpp, radio/src/gui/128x64/widgets.cpp, radio/src/gui/common/stdlcd/model_receiver_options.cpp
It seems the display used on these TX doesn't like too many horizontal lines.
Fixes #3450
- Apply X7/X9 Lite S fix to X9 Lite also, consistently
=> fix(X9lite): Chan. monitor, other display glitches

radio/src/gui/colorlcd/custom_failsafe.cpp
Fixes #3462 
Add missing calls to SET_DIRTY() when values changed.
=> fix(color) - Fix for custom failsafe settings not being saved to SD card on color LCD radios.

radio/src/cli.cpp
Update code to exclude code the is not relevant when INTERNAL_MODULE_PXX2=OFF.
=> chore(color) - Fix TX16S firmware build when DEBUG=YES and INTERNAL_MODULE_PXX2=OFF.

radio/src/gui/colorlcd/themes/480_default.cpp
When USB is connected in SD card mode, everything is shut down.
When USB is disconnected, everything is re-loaded including the background image.
The background image name had not been changed, so the old bitmap buffer was not deleted, even though the image was re-loaded into a new bitmap buffer.
The old buffer is now always deleted.
The user may have copied a new image file to the SD card so can't just assume the old buffer is valid.
=> fix(color) - Fix memory leak when disconnecting USB in SD card mode.

radio/src/hal/module_port.cpp, radio/src/pulses/afhds3.cpp, radio/src/pulses/pulses.cpp, radio/src/serial.cpp, radio/src/targets/horus/CMakeLists.txt
Fixes #3337
Fixes #3413
1. Fix configurable port problems
2. Resolved R9M Access MOD unusable
3. Support FRM303 in TX16S via AUX1 mod (similar to R9M mod but no need inverters.
Documentation for mod: https://github.com/EdgeTX/edgetx/wiki/Flysky-FRM303-Mod-for-TX16S
=> Fix configurable port, solved R9M Access problem and support FRM303 via mod

radio/src/gui/colorlcd/widget.cpp
It always annoys me when selecting widgets that the list is not sorted so I have to scroll around to find the one I want.
This PR sorts the list of widgets by the display name.
=> feat(color) - Sort the widget list by display name.

radio/src/opentx.cpp
Add haptic startup buzz for radios with no startup animation, which may or may not be just colorlcd radios?
It is difficult to tell when my TX16S finally turns on after holding the power button when outdoors. The LED is not visible in direct sunlight and my polarized sunglasses make the LCD itself completely black when held in the normal orientation (both my head and the radio in their respective normal orientations). B&W radios such as the Zorro give a satisfying buzz as they power on so why not everyone else?
Hardware with physical on/off switches may also buzz with this? Not sure if this is a good or a bad thing or if this code path runs for those fancy snowflakes.
TX16S with 2.8.2 + this line, also tested compiling `main` with it as well, as this patch is against main
Zorro with 2.8.2 …
=> feat(color) Add haptic startup buzz for radios with no startup animation

radio/src/gui/colorlcd/LvglWrapper.cpp
Fixes #3428 
Only tested on TX16S Mk2 so far; but this seems to work better in my testing.
=> fix(color): Rework rotary encoder acceleration calculation removing double handling

radio/src/gui/colorlcd/popups.cpp, radio/src/gui/colorlcd/popups.h, radio/src/gui/common/stdlcd/popups.h, radio/src/main.cpp, radio/src/telemetry/telemetry.cpp
Fixes #3424 
The antenna warning from the telemetry task is handed off to the UI task for display.
Also fixes an issue where the simulator does not close cleanly if a popup is showing.
=> fix(color) - Fix issue where popup telemetry warning can crash radio.

radio/src/thirdparty/Lua/src/luaconf.h
Fixes https://github.com/EdgeTX/edgetx/issues/3468
- use debugPrintf (through TRACE_DEBUG_WP) for LUA print function
=> fix CPN: LUA no debug printout possible

radio/src/storage/storage_common.cpp
There is a 200ms delay built in when switching models to ensure the RF module initialises properly when stopped and restarted.
This is not needed on radio startup so this PR skips it to reduce startup time.
=> feat(color) - Skip model switch delay if mixer not running (e.g. on startup).

radio/src/gui/colorlcd/flysky_settings.cpp, radio/src/gui/colorlcd/flysky_settings.h, radio/src/hal/module_port.h, radio/src/pulses/afhds3.cpp, radio/src/pulses/afhds3_transport.cpp
Fixes #3477 
Also fix simulator crash issues related to FlySky module.
=> fix(color): Scroll order for 'FlySky' module options

radio/src/targets/common/arm/stm32/stm32_hal_adc.cpp
Increases code readability by explicitly listing the used ADC resolution.
=> fix: Explicitly list 12-bit ADC resolution

radio/src/mixer_scheduler.h, radio/src/targets/common/arm/stm32/heartbeat_driver.cpp, radio/src/targets/common/arm/stm32/mixer_scheduler_driver.cpp, radio/src/targets/horus/hal.h, radio/src/targets/taranis/hal.h
Fixes https://github.com/EdgeTX/edgetx/issues/3285
Summary of changes after discussion with @raphaelcoeffic:
This sets the bit start detection IRQ priority to the value used before the major serial/port API change. Tested on TX16s and 
X10express. Logic analyzer confirms great performance and spot on timing of the soft serial driver introduced with the serial/port API change.
TODO: the same or similar fix must be applied for targets Taranis and NV14 as at least external telemetry protocol LemonDSP uses soft serial. Need discussion how to go about this in a follow up PR.
=> fix: corrupt data using soft serial driver

companion/src/apppreferencesdialog.cpp, companion/src/simulation/joystick.cpp, companion/src/simulation/joystick.h, companion/src/simulation/joystickdialog.cpp, companion/src/simulation/joystickdialog.h, companion/src/simulation/simulatorwidget.cpp, companion/src/storage/appdata.cpp, companion/src/storage/appdata.h, radio/src/datastructs_private.h, radio/src/usb_joystick.cpp
Reduce RAM usage for advanced joystick system on radio:
- Don't allocate memory blocks unless joystick mode is actually being used.
Support multiple radio joystick configurations in Companion:
- Save configured joystick settings by joystick name in Companion settings.
- Save last joystick name used in each profile.
- Reload joystick settings by name when profile is changed.
This allows the configuration for multiple radios to be saved individually in the Companion settings, and stores the radio that was last used for each profile. On profile load/switch the appropriate joystick settings are restored.
Previously only one configuration was available so switching radios required redoing all the configuration settings.
=> feat(radio,cpn) - Updates for new joystick system.

radio/src/serial.cpp
fixes #3509
This problem shows for target bootloader and is caused by CONFIGURABLE_MODULE_PORT including header files into `radio\src\gui\colorlcd\mpm_settings.cpp` which are not meant to be part of bootloader code.
Changes:
- include CONFIGURABLE_MODULE_PORT code only if compiled not for bootloader
=> fix: Building TX16s firmware with -DDEBUG=YES -DCMAKE_BUILD_TYPE=Debug fails

radio/src/gui/colorlcd/special_functions.cpp
Fixes #3519 
Fix incorrect minimum value for repeat option edit box on color LCD radios.
Checked B&W and they are not affected.
=> fix(color) - Fix '!1x' repeat option broken in PR 3338.

radio/src/targets/horus/stm32f4_flash.ld, radio/src/targets/taranis/stm32f2_flash.ld, radio/src/targets/taranis/stm32f4_flash.ld
Prior to this PR, FLASH overflow detection would fail if `.text` segment would be small enough, but the firmware would overflow once `.data` is added.
- explicitly locate `.data` segment in `FLASH` instead of using `_sidata` marker.
=> fix: FLASH overflow detection

radio/src/gui/common/stdlcd/radio_sdmanager.cpp, radio/src/sdcard.cpp, radio/src/sdcard.h, radio/src/translations.cpp, radio/src/translations.h, radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h
Reduce risk AND reduce flash size by 1928 bytes
=> Formating the sd card is a bad idea with EdgeTX

radio/src/targets/horus/stm32f4_flash.ld, radio/src/targets/taranis/stm32f2_flash.ld, radio/src/targets/taranis/stm32f4_flash.ld
Prior to this PR, FLASH overflow detection would fail if `.text` segment would be small enough, but the firmware would overflow once `.data` is added.
- explicitly locate `.data` segment in `FLASH` instead of using `_sidata` marker.
=> [2.8] fix: FLASH overflow detection

radio/src/pulses/multi.cpp, radio/src/pulses/ppm.cpp, radio/src/targets/common/arm/stm32/module_timer_driver.cpp, radio/src/targets/common/arm/stm32/stm32_pulse_driver.cpp, radio/src/targets/common/arm/stm32/stm32_softserial_driver.cpp
✅ Tested side-by-side with TX16S & Boxer for all external module protocols.
Fixes #3413
=> fix: signal polarity for soft-serial & timer based protocols

radio/src/lua/api_general.cpp
fixes #3525
changes:
- calculate LUA return value for GVARS taking precision into account
=> fix: LUA ignoring GVAR precision

radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h
Fixes #3533 
Update translation files - use same key names as Zorro.
=> fix(radio) - Fix key names for Boxer.

radio/src/storage/yaml/yaml_labelslist.cpp
Fixes #3518 
The hash value stored in the labels.yml file does not get updated when model files are saved.
On restart the values stored in labels.yml are ignored because the hash is not correct.
This workaround forces loading of the 'lastopened' value regardless of the hash. All other ignored values are re-created correctly.
This is a quick and dirty workaround to fix the issue.
=> Workaround for 'lastopened' value not loaded on startup if stored hash not up to date.

radio/src/opentx.cpp, radio/src/opentx.h
The current implementation of 'availableMemory' only returns the free heap space.
Memory already allocated from the heap by the 'malloc/new' memory management system is not considered.
This change adds the amount of free memory already taken from the heap; but not used, to the total.
=> feat(color) - Return actual free memory available from 'malloc/new' calls in the 'availableMemory' function.

radio/src/gui/colorlcd/view_statistics.cpp
Remove x10 multiplier on memory usage values for scripts and widgets on the statistics debug page.
=> fix(color) - Fix incorrect Lua memory usage values.

companion/src/firmwares/eeprominterface.h, companion/src/firmwares/opentx/opentxinterface.cpp, companion/src/firmwares/opentx/opentxinterface.h, companion/src/helpers.cpp, companion/src/simulation/simulator.h, companion/src/simulation/simulatorinterface.cpp, companion/src/simulation/simulatorinterface.h, companion/src/simulation/simulatormainwindow.cpp, companion/src/simulation/simulatormainwindow.h, companion/src/simulation/simulatorstartupdialog.cpp, companion/src/simulation/simulatorstartupdialog.h, companion/src/simulation/simulatorstartupdialog.ui, companion/src/simulation/simulatorwidget.cpp, companion/src/simulator.cpp, companion/src/updates/updateinterface.cpp, radio/src/targets/simu/opentxsimulator.cpp
- add ability for a radio type to reference any simulator when registering radio types eg T-Lite F4 can reference T-Lite sim (USE WITH EXTREME CAUTION as there are no checks that the manually selected simulator is compatible - all hell is likely to break loose if you get it wrong)
- add ability for mapping of cpn firmware id to repo firmware id when registering radio types (keeps in most logical place)
- remove mapping from updateinterface
- standalone simulator fix B&W simulator crash when saving settings file on simulator close (bug introduced in move of B&W radios to yaml)
- housekeeping
The Simulator field is auto filled based on displayed Radio Type. Note: it is a combo box widget since it is populated by a filtered data model.
I have performed numerous regression …
=> feat(cpn) Radio types can reference any libsim and/or firmware download id

radio/src/targets/taranis/board.h
Fixes #3455
Just added default contrast settings for Radiomaster Zorro
=> Added default contrast settings for Zorro

radio/src/gui/colorlcd/sourcechoice.cpp
The min and max values for the 'Custom Mixer Scripts' filter were reversed so the filter was not shown in the source selection menu popup.
=> fix(color) - Fix 'Custom Mixer Scripts' filter not shown is source selection menu.

radio/src/functions.cpp
Fixes #2967 
Remove the check on the audio queue state from the 'Play Sound' code.
=> fix(radio) - Fix SF 'Play Sound' not working on startup.

companion/src/modeledit/customfunctions.cpp, radio/src/functions.cpp, radio/src/lua/interface.cpp, radio/src/myeeprom.h, radio/src/storage/yaml/yaml_datastructs_funcs.cpp
Make 'active' flag work for all functions.
Fix loading and saving of 'active' flag and 'repeat' param in YAML file.
Add missing logic for 'Lua Script' repeat param.
Remove redundant HAS_ENABLE_PARAM macro.
Remove empty column from Companion special/custom functions page.
=> Fixes for various issues (3038-rebase).

radio/src/telemetry/telemetry.cpp
- added rx stat type Rqly % for PPM MLINK telemetry protocol
Tested ok on TX16s
=> RX stat type "Rqly %" for PPM MLINK

radio/src/gui/colorlcd/themes/480_default.cpp, radio/src/thirdparty/Lua/src/lstate.c
Fixes two memory leaks totalling ~46K when using USB storage connection:
- Lua state 'cache' was being allocated to both lsScripts and lsWidgets; but only one was being released.
- Default theme bitmaps were being reloaded without releasing previously allocated memory.
There is still a small (<1K) leak that I have not managed to track down yet.
=> fix(color) - Fix memory leaks when using 'USB Storage (SD)' connection.

radio/src/datastructs_private.h
=> fix(radio) - Include internal module type in backup data for EM so radio re-connects to receiver.

radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/pl.h, radio/src/translations/se.h, radio/src/translations/tw.h
Changes to less daunting label "Missing or bad radio data" if \RADIO folder on SD card is non-existent:
Previously "Bad radio data" was used, causing unnecessary negative emotions on many users, who created a clean SD card content.
Needs translation of the TR_BAD_RADIO_DATA string. I am herewith pinging directly - thx!
Please feel to use the phrase in your language what makes most sense - does not need to be a direct translation.
=> feat(ui): "Missing or bad radio data"

radio/src/gui/colorlcd/mpm_settings.cpp, radio/src/io/multi_protolist.cpp, radio/src/io/multi_protolist.h
Fixes #2713, fixes #3046 (partly #3500), and fixes #1470
- use getMultiOptionTitle() instead of rfproto->getOptionStr() as getMultiOptionTitle() takes updated MPM status in account
- changes to mpm_settings.cpp to check for MPM changing subtype for DSM auto
=> fix: MPM protocol options missing in various protocols

radio/src/CMakeLists.txt
- Re-enable HELI by default as can now be turned off at runtime thanks to #3484
Woohoo... X9D+2019 still has 12kb free flash!
=> chore: Re-enable HELI since now runtime option

radio/src/gui/colorlcd/mixer_edit.cpp, radio/src/gui/colorlcd/model_usbjoystick.cpp, radio/src/gui/colorlcd/output_edit.cpp, radio/src/gui/colorlcd/view_channels.cpp
Fixes two issues where the channel bar is being used:
- The header height on the mixes, outputs and USB joystick edit pages is incorrect, allowing the header to be scrolled up and down by a few pixels.
- The height for each row in the channel monitor window is too small truncating the channel bar (and again allowing scrolling).
=> fix(color) - Fix window sizes where the ComboChannelBar is displayed.

radio/src/gui/colorlcd/model_flightmodes.cpp, radio/src/gui/colorlcd/model_gvars.cpp, radio/src/gui/colorlcd/model_gvars.h, radio/src/gui/colorlcd/model_telemetry.cpp, radio/src/gui/colorlcd/themes/480_default.cpp
The change to fix memory leaks in PR #3547 broke changing themes/colors - the icon colors did not get updated.
This PR fixes the problem by splitting the icon creation (memory allocation) from the icon loading (setting theme color).
=> fix(color) - Fix colors when theme is changed.

companion/src/firmwares/edgetx/edgetxinterface.cpp, companion/src/firmwares/edgetx/edgetxinterface.h, companion/src/firmwares/radiodata.cpp, companion/src/firmwares/radiodata.h, companion/src/labels.cpp, companion/src/storage/labeled.cpp
Fixes #2899
- based on work by @dlktdr 
- extend radio data structures
- read and write sort order and selected labels
Note: This PR does not support changing these within Companion. That will be included in a separate PR along with some other features. The primary objective here is for Companion not to lose settings.
=> fix(cpn): write sort order and selected labels

radio/src/targets/common/arm/stm32/module_timer_driver.cpp, radio/src/targets/common/arm/stm32/stm32_pulse_driver.cpp
fixes #3597
PPM settings for external module:
PPM stream with internal RF set to OFF and external RF set to PPM with above settings - `OK`
All sticks at neutral except CH1 set to Min. Channel monitor confirms all channel 1 at 988us, channels 2 to 8 at 1500us. Notice  all 8 channels correctly transmitted, timing as expected.
PPM OFF to PPM ON without glitches -  - `OK`
=> Fix: first channel omitted in PPM stream

radio/src/telemetry/spektrum.cpp, radio/src/translations/untranslated.h
Fixes:
1. Filter invalid values for "uint8" datatype.. This created sensors with no valid data.
2. Smart ESC:  Fix RPM, Current, Power %, BEC Voltage was not properly computed (many needed x10, or x100)
3. Filter Telemetry NO-DATA ID to avoid creating fake 0000,0001  sensors  (Telemetry "Ping")
4. Fix renaming of ESC Rpm sensor.  Was "Erpm" up to EdgeTX 2.8.x, but  during 2.9 development, it changed to "EscR". Will keep it backward compatible for now (i.e, name "Erpm"),  Will create sepatate ticket to normalize a few of this Spektrum only names to FrSky+other standards
Improvements
1. Binary GPS sensor support
2. Dual Receiver Battery  monitor support  (ID 0x18)
3. Make the code more CPU efficient when processing sensors.
4. Move big blocks of code into functions to make the code more …
=> fix (telemetry):  DSM Telemetry fix for ESC sensor, Binary GPS, RX Battery Sensor Capacity metter

radio/src/gui/128x64/model_setup.cpp, radio/src/gui/212x64/model_setup.cpp, radio/src/gui/colorlcd/channel_range.cpp, radio/src/gui/colorlcd/channel_range.h, radio/src/gui/colorlcd/module_setup.cpp, radio/src/gui/colorlcd/ppm_settings.cpp, radio/src/gui/colorlcd/ppm_settings.h, radio/src/gui/colorlcd/trainer_setup.cpp, radio/src/pulses/modules_helpers.h
- adjusts PPM frame length if channel count > 8
- channel count in [1;8] -> frame length = 22.5 ms
- channel count in [9,16] -> frame length = 22.5ms + (channel count - 8)  * 2ms
- example channel count 9 -> frame length = 24.5ms
- example channel count 16 -> frame length = 38.5ms
- auto adjusted value can be manually overriden
=> fix: Auto adjust PPM frame length

radio/src/gui/colorlcd/model_telemetry.cpp, radio/src/gui/colorlcd/model_telemetry.h
Change the telemetry page to dynamically show or hide the 'Delete All' button based on sensor count.
Currently the button state is set on page load and does not change.
=> fix(color) - Show/hide the 'Delete All' button on the telemetry page.

radio/src/gui/colorlcd/mpm_settings.cpp
Fixes the weird layout scroll behaviour for the 'RF Freq. fine tune' option (reported on Discord).
=> fix(color) - Fix layout scroll issue with MPM protocol option settings.

radio/src/gui/colorlcd/theme_manager.cpp
- If the `THEMES` directory is missing, create it on creating (although at this point it is really when duplicating, but that is probably splitting hairs) a new theme. 
- Prior to this, it would fail silently with no theme created.
=> fix: Create `THEMES` dir if missing when creating a new theme

radio/src/telemetry/hott.cpp
Fixes #3648
- missed resetting sign of decimal latitude after initial data received from GPS
=> Robustness measure: HoTT telemetry gps latitude sign may be wrong

radio/src/targets/taranis/board.cpp
Solve the redundant cluttered display on the screen after Boxer is shut down.
=> Solve the messy display after Boxer shutdown

radio/src/gui/common/stdlcd/radio_hardware.cpp, radio/src/gui/gui_common.cpp, radio/src/gui/gui_common.h
Add (back) Sport power handling
This fixes #3635
=> SPORT power handling

radio/src/pulses/sbus.cpp
Fixes #3680
- checks function ptr for nullptr before accessing it (simu doesn't implement function)
=> fix CPN: simulator crashes on selection of SBUS external module

radio/src/bluetooth.cpp
In FrSky BT protocol, 0x7D and 0x7E are forbidden values that acts as frame delimiters. While the data part of the frame is currently protected using byte stuffing, the crc bytes aren't, resulting in rejected frames on receiveing device when crc value is 0x7D or 0x7E.
This fixes the issue
=> Fix BT sending crc non "byte stuffed"

radio/src/gui/colorlcd/special_functions.cpp
Don't reset Lua for PLAY TRACK, or BACKGND MUSIC functions.
Fixes #3692
=> fix(color) - Only reset Lua if changing PLAY SCRIPT special function

companion/src/firmwares/edgetx/yaml_generalsettings.cpp
=> fix(cpn): Add read/write for trainer multiplier in radio.yml

radio/src/telemetry/spektrum.cpp
Fix the Flight Pack sensor processing.  
TESTED WITH THE REAL SENSOR up to 5000mAh packs
Sensor:  Capacity Sensor SPMA9605
The main problem was that we expected the data to come in big-endian encoding, but in reality, the sensor send it in little-endian.   This was causing the 1st byte to change much faster, and eventually move into the negative value (16 bit integer)
Added more validations to handle little-endian values, and recognize NO-DATA scenarios for little-endian.
Fixes #1649
=> fix(telemetry-DSM): Fix for Flight Pack Monitor Sensor

radio/src/io/multi_firmware_update.cpp, radio/src/targets/common/arm/stm32/stm32_pulse_driver.cpp
- specific pulse timer inits for and pwm toggle mode
- set correct RX/TX polarity for MPM bootloader
- extended flash process timeout from 12.5ms to 100ms as robustness measure
=> fix: external MPM flash

radio/src/lua/api_model.cpp
Currently LUA model.setModule() cannot change module type. I want to change that to enable scripts that switch between internal and external module.
User scenario 1 is using same EdgeTX model with multiple craft on multiple receiver types; currently you either need to clone the model (making modifications cumbersome, since you need to keep them in sync), or manually switch modules in the menu.
User scenario 2:  this can be used to enable 'check antenna' warning for radios with removable internal module antennas - they can burn out the transmitter if the antenna isn't connected, so the user would be able to have LUA remind them to put on the antenna after the radio boots, and only enable the module (via model.setModule) once the user acknowledges the antenna is on by flipping a switch.
=> Support changing module type from LUA model.setModule()

radio/src/targets/horus/hal.h
Based on feedback received from Radiomaster customers, they would prefer to re-enable mute for TX16S.
I'll do later a user configurable version, but for 2.10
Would be nice if this one could be part of 2.9
=> (re)enable mute for TX16S based on RM feedback

radio/src/switches.cpp, radio/src/targets/taranis/board.h
Fixes #3560
The ultimate fix is https://github.com/EdgeTX/edgetx/pull/2631 in milestone 2.10.0
=> fix: 3POS switches on certain radios not detecting all switch positions

companion/src/firmwares/radiodata.cpp, companion/src/firmwares/radiodata.h, companion/src/mdichild.cpp, companion/src/mdichild.h, companion/src/modelslist.cpp, companion/src/modelslist.h
Fixes #3033 #3546
- add support for editing radio sort order (color radios only) Note: independent of models list sort order
- add support for sorting models list by any column in ascending or descending order
- housekeeping:
replace depreciated macro Q_DECL_OVERRIDE with override keyword
replace NULL with nullptr
stubs for model list label filtering (separate PR)
New color radio model list
Sort by RX# indicator
New B&W radio model list
Sort by name indicator
=> feat(cpn): Add radio sort order edit and sorting models list by any column

companion/src/datamodels/compounditemmodels.cpp, companion/src/datamodels/compounditemmodels.h, companion/src/firmwares/edgetx/yaml_modeldata.cpp, companion/src/modeledit/modeledit.cpp, companion/src/modeledit/telemetry.cpp, companion/src/modeledit/telemetry.ui, radio/src/gui/128x64/model_telemetry.cpp, radio/src/gui/212x64/model_telemetry.cpp, radio/src/storage/storage_common.cpp, radio/src/telemetry/frsky_sport.cpp
Fixes #2552 
For justification please refer to discussion in #2552 
- force rssi source to default yaml value ("rssiSource: none") at model load if not already set to default
- remove rssi source selection from Companion and b&w UI (color LCD never implemented this option)
=> UI: remove rssiSource and use default value 

companion/src/constants.h, companion/src/simulation/simulatorstartupdialog.cpp, companion/src/simulation/simulatorstartupdialog.ui
Fixes #3709
After closing the message box the OK button is disabled to prevent attempting to launch the simulator.
=> Simulator: do not allow launching if no radio profiles found

radio/src/hal/adc_driver.cpp
Fixes #3711 
Tested in simulator and on TX16S Mk2.
=> fix(radio) - Fix rounding errors in ADC value calculation for 6POS switch.

companion/src/firmwares/boards.cpp, companion/src/firmwares/boards.h, companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/generalsettings.h, companion/src/generaledit/hardware.cpp, companion/src/translations/companion_cs.ts, companion/src/translations/companion_da.ts, companion/src/translations/companion_de.ts, companion/src/translations/companion_en.ts, companion/src/translations/companion_es.ts, companion/src/translations/companion_fi.ts, companion/src/translations/companion_fr.ts, companion/src/translations/companion_he.ts, companion/src/translations/companion_it.ts, companion/src/translations/companion_ja.ts, companion/src/translations/companion_nl.ts, companion/src/translations/companion_pl.ts, companion/src/translations/companion_pt.ts, companion/src/translations/companion_ru.ts, companion/src/translations/companion_sv.ts, companion/src/translations/companion_zh_CN.ts, companion/src/translations/companion_zh_TW.ts
Adds user configurable audio mute in CPN's radio setting. Supports PR #3703
=> CPN: user configurable audio mute in radio settings. Supports PR #3703

radio/src/targets/taranis/bootloader/boot_menu.cpp, radio/src/translations/cn.h, radio/src/translations/cz.h, radio/src/translations/da.h, radio/src/translations/de.h, radio/src/translations/en.h, radio/src/translations/es.h, radio/src/translations/fi.h, radio/src/translations/fr.h, radio/src/translations/he.h, radio/src/translations/it.h, radio/src/translations/jp.h, radio/src/translations/nl.h, radio/src/translations/pl.h, radio/src/translations/pt.h, radio/src/translations/se.h, radio/src/translations/tw.h
Fix centering of "USB connected" on B&W bootloader
Introduced in 2.9 thorugh #2946
=> fix(b&w): Bootloader "USB Connected" alignment

radio/src/gui/colorlcd/radio_diaganas.cpp
This displays only configured POT/Sliders in colorlcd diaganas, so that unpopulated extra entries aren't displayed
While it started as a workaround for a curent issue handling EXT3/EXT4 in ADC refactor, it is also I guess a logical thing to do
=> Show only defined entries in diaganas

radio/src/gui/colorlcd/radio_sdmanager.cpp, radio/src/gui/colorlcd/radio_sdmanager.h
Fixes #2147 
The OTA flash code are basically copied from stdlcd, rewrite UI part based on the new implementation for color screens.
The UI part cost me some time. My finding is to close dialogs & menus programmatically, they needs to be deleteLater() in stack order, from latest widget to older widget. If the order is wrong the UI will crash immediately. After fix the order of deleteLater(), the UI works fine.
I run several tests in my X10s, click no and yes, flash by OTA several times. Seems working well in my device. It should also work in X12s, but I don't have a device to test.
=> Add RX OTA flash for frsky X10s & X12s.

radio/src/translations/it.h
Fixes #
Missing line in recent commit, so for IT you can't compile it.
Please when posting commits that contemplate a new translation ping the translators, thank you!
Line 842
#define TR_FS_BTN                       BUTTON(TR("Fun. Inter.", "Funzione interruttori"))
=> Missing translated line for IT in recent commit

companion/src/firmwares/boards.cpp, companion/src/firmwares/boards.h, companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/generalsettings.h, companion/src/generaledit/hardware.cpp, companion/src/translations/companion_cs.ts, companion/src/translations/companion_da.ts, companion/src/translations/companion_de.ts, companion/src/translations/companion_en.ts, companion/src/translations/companion_es.ts, companion/src/translations/companion_fi.ts, companion/src/translations/companion_fr.ts, companion/src/translations/companion_he.ts, companion/src/translations/companion_it.ts, companion/src/translations/companion_ja.ts, companion/src/translations/companion_nl.ts, companion/src/translations/companion_pl.ts, companion/src/translations/companion_pt.ts, companion/src/translations/companion_ru.ts, companion/src/translations/companion_sv.ts, companion/src/translations/companion_zh_CN.ts, companion/src/translations/companion_zh_TW.ts
Port of  https://github.com/EdgeTX/edgetx/pull/3710 to compliment https://github.com/EdgeTX/edgetx/pull/3719
Translations sourced from #3719, to be pushed over to 2.9 also as the feature exists there.
=> feat(cpn): User configurable audio mute in radio settings

radio/src/mixer.cpp, radio/src/opentx.cpp, radio/src/switches.cpp
This fixes throttle timer not picking up the right channel by default after adc refactor
=> Fix thottle timer

radio/src/gui/gui_common.h, radio/src/targets/common/arm/CMakeLists.txt, radio/src/telemetry/frsky_defs.h, radio/src/telemetry/spektrum.cpp, radio/src/telemetry/telemetry.cpp, radio/src/telemetry/telemetry_sensors.cpp
Since we are getting real low on flash on some radio, it may be needed to exclude multi for special purposes (make room for DEBUG for exemple).
This fixes current compilation issues when MULTIMODULE is not define. 
No end user impact
=> Allow compile without multimodule support

radio/src/gui/colorlcd/special_functions.cpp
fixes #3751
changes:
- use stored value if SF exists otherwise initialize with default value
=> fix: SD Logs interval shown as default value when entering SF edit window

radio/src/targets/nv14/bootloader/boot_menu.cpp, radio/src/targets/nv14/hal.h, radio/util/hw_defs/hal_keys.py, radio/util/hw_defs/stm32_keys.jinja
- add `active_low` boolean attribute for trims and keys
- init pins separately to allow for different pull-up/-down settings based on `active_low`
- read pins according to `active_low`
- activate *"trims as buttons"* in bootloader
=> fix: NV14 uses active-high for keys and trims

radio/src/gui/128x64/view_statistics.cpp, radio/src/mixer_scheduler.h
This make the mixer run at 1000Hz when in Joystick mode (Needed for F.Sim competitors), also displays mixer run time in statistic/debug screen.
BOTH MODULE need to be off on model setup page to get that speed
Result of work with TDog on discord
(Windows may require special drivers to reach that speed)
=> 1khz update rate for F.Sim competitions

radio/src/gui/colorlcd/preflight_checks.cpp
=> fix(color): Names and number of buttons on Preflight checks screen

radio/src/gui/colorlcd/gvar_numberedit.cpp
Fixes #3768 
Add missing '#if defined(GVARS)' check.
=> chore: Fix build when GVARS=NO

radio/src/targets/horus/diskio.cpp, radio/src/targets/horus/lcd_driver.cpp, radio/src/targets/nv14/diskio.cpp
Fixes: having do comment out those TRACE() calls every time you start debugging using traces
- commented out misleading TRACE() call for bad alignment if writing stack allocated buffers to SD card
- commented out trace flooding TRACE() call in lcd driver
If it was Xmas I'd wish for this to be in 2.9 too.
=> chore: Comment out the top two trace flooding calls

radio/src/io/multi_protolist.cpp
... if timer already exists (from previous scan)
fixes #3084
changes:
Protocol scans use software timers to fetch the MPM protocol list at 100ms rate but with an initial rate of MULTI_PROTOLIST_START_TIMEOUT (3000ms) for the first poll to allow the MPM to finish its startup sequence after power on. Switching models back and forth power cycles the MPM. As the software timer already exists it is not instantiated again but reused. but with the rate it was left, i.e. 100ms, not the required 3000ms to allow the MPM to settle. Resetting the timer rate to MULTI_PROTOLIST_START_TIMEOUT solves the problem.
Note: the current implementation will under certain circumstances (e.g. model change back and forth) poll the MPM at 100ms with every poll failing and rebuilding the fallback list because the …
=> fix: reset proto scan software timer to MULTI_PROTOLIST_START_TIMEOUT

radio/src/gui/colorlcd/model_inputs.cpp, radio/src/gui/colorlcd/model_mixes.cpp
Fixes #3774 
Change layout build code to match 2.8 so that scroll order works correctly when new inputs/mixes added.
Add logic to set focus to first input/mix line if present as per 2.9 changes.
=> fix(color): Fix inputs and mixes scroll order

radio/src/opentx.cpp, radio/src/targets/common/arm/stm32/bluetooth_driver.cpp, radio/src/targets/simu/bt_driver.cpp
=> Add X7S BT detection

companion/src/apppreferencesdialog.cpp, companion/src/apppreferencesdialog.ui, companion/src/firmwares/boards.cpp, companion/src/firmwares/boards.h, companion/src/firmwares/moduledata.cpp, companion/src/mainwindow.cpp, companion/src/modeledit/setup.cpp, companion/src/storage/appdata.h
- provide support for #3624
- add setting External Module to Radio Profiles
- the setting default value is based on the radio type (None, Standard, Small, Both)
'None' can be a hardware limitation or it is never used so force protocol to OFF
'Both' if factory or custom mods to hardware. All protocols will be available.
- existing profiles will have the value of 'Standard' set on first use (see RELEASE NOTE below). It is not practical to code the default for each profile as app settings are loaded prior to firmware/board objects
- available external module protocols are based on the new setting (complete change to logic so high importance for regression testing)
- new warning message when opening a model for editing if external module protocol is not supported by …
=> feat(cpn): External module form factor set in Radio Profile to allow aligning with firmware compile option

companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/generalsettings.h, companion/src/generaledit/CMakeLists.txt, companion/src/generaledit/generalsetup.cpp, companion/src/generaledit/generalsetup.h, companion/src/generaledit/generalsetup.ui, companion/src/generaledit/timezoneedit.cpp, companion/src/generaledit/timezoneedit.h, companion/src/thirdparty/maxlibqt/src/widgets/TimerEdit.h, radio/src/datastructs_private.h, radio/src/gui/128x64/radio_setup.cpp, radio/src/gui/212x64/radio_setup.cpp, radio/src/gui/colorlcd/radio_setup.cpp, radio/src/rtc.cpp, radio/src/storage/yaml/yaml_datastructs_128x64.cpp, radio/src/storage/yaml/yaml_datastructs_nv14.cpp, radio/src/storage/yaml/yaml_datastructs_t20.cpp, radio/src/storage/yaml/yaml_datastructs_tpro.cpp, radio/src/storage/yaml/yaml_datastructs_x10.cpp, radio/src/storage/yaml/yaml_datastructs_x12s.cpp, radio/src/storage/yaml/yaml_datastructs_x9d.cpp, radio/src/storage/yaml/yaml_datastructs_x9e.cpp, radio/src/storage/yaml/yaml_datastructs_x9lite.cpp, radio/src/storage/yaml/yaml_datastructs_xlites.cpp, radio/src/strhelpers.cpp, radio/src/strhelpers.h, radio/src/telemetry/spektrum.cpp
Add support for all current timezones to radios and Companion.
Fixes #3398 
- Add a 'timezoneMinutes' field to the radio settings to store the minutes offset.
- Add +13:00 and +14:00 timezones.
- Update the radio and Companion UI to allow selection of any valid timezone.
=> feat(radio,cpn): Support all current timezones.

radio/src/targets/common/arm/stm32/CMakeLists.txt, radio/src/targets/common/arm/stm32/flysky_gimbal_driver.cpp, radio/src/targets/common/arm/stm32/flysky_gimbal_driver.h, radio/src/targets/common/arm/stm32/stm32_adc.cpp, radio/src/targets/common/arm/stm32/stm32_adc.h, radio/src/targets/common/arm/stm32/stm32_dma.cpp, radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp, radio/src/targets/horus/board.cpp, radio/src/targets/horus/hal.h, radio/src/targets/nv14/board.cpp, radio/src/targets/nv14/hal.h, radio/src/targets/taranis/board.cpp
As Flysky Gimbals use only 1 pin instead of 4 for analog gimbals, and 2 of these are re-used, it is not enough to mask used pins. This PR adds support in the ADC driver to manually mask inputs which will then be ignored / left untouched by the ADC driver.
=> fix(flysky gimbals): mask first 4 channels when FS gimbals are detected

companion/src/firmwares/curvedata.h
=> fix(cpn): reduce curve name length to match firmware

companion/src/mainwindow.cpp
- disable backup and restore for all radios until time can be found to rework
- completely broken with the move to yaml for B&W radios
- does not impact read and write models and settings
=> chore(cpn): disable backup and restore for all radios

companion/src/firmwares/edgetx/yaml_generalsettings.cpp
- compare radio.yml semver to Companion version
- warn user that proceeding may result in corrupted radio and/or model settings
Related to but DOES NOT resolve
#3758
The purpose of this PR is to link to the commits that can be cherry picked into 2.8.5 and 2.9 RC and merged into main.
=> feat(cpn): warn if radio settings version not supported

radio/src/targets/common/arm/stm32/bootloader/CMakeLists.txt
Bootloader build fails when DEBUG=YES on TX16S due to missing source file.
=> chore(build): Add missing source for bootloader debug build.

companion/src/firmwares/boards.cpp, companion/src/firmwares/moduledata.cpp
=> fix(cpn): add missing module types to module size lists

radio/src/opentx.cpp, radio/src/targets/taranis/board.h
Revert a change introduced in https://github.com/EdgeTX/edgetx/pull/3575
With settings introduced in 3575, author custom splash with a lot of black pixels looks better, but default EdgeTX and many other look worse. Suggesting reverting to initial value
This fixes #3830
Recommend applying to 2.9
=> fix: revert Zorro default contrast

radio/src/gui/128x64/model_telemetry.cpp, radio/src/gui/212x64/model_telemetry.cpp
This is a small qualilty of life PR that automaticaly expand sensor list when discovering sensor (basicaly, you want to see sensors poping when you launch that function).
=> feat: auto expand sensor list when discovering sensors

radio/src/gui/colorlcd/widgets_setup.cpp
Prevents recursive loading of widget setup page.
Fixes #3842
=> fix(color): Change behaviour of TELE button on widget setup page to work like RTN button.

companion/src/firmwares/edgetx/yaml_modeldata.cpp, companion/src/helpers.cpp, radio/src/targets/simu/opentxsimulator.cpp, radio/src/targets/simu/simpgmspace.cpp
Fixes #3724
- incorporate 3djc PR #3727
- calculate sliders offset in adc
- fix trims credit to @philmoz 
- 6POS calculation using calibration data if exists credit to @philmoz
- fix yaml to convert between pre and post adc refactor
TODO:
=> Companion simulator pots and sliders adc refactor fixes

radio/src/targets/taranis/hal.h
Fixes #3853
- make definitions consistent between `ADC_GPIO_PIN_STICK_XX` and `ADC_CHANNEL_STICK_XX`
- fixed `STICK_PWM_CHANNEL_XX` definitions
=> fix(x-lite): ADC channel definition

radio/src/gui/colorlcd/radio_diaganas.cpp
On portrait layout LCD screen the analog diagnostic page is clipped to the content height so the touch screen cursor gets clipped halfway down.
This PR resizes the page to full height so the crosshair is not clipped.
=> fix(color): Expand analog diagnostic page to full height

radio/src/opentx.cpp
Radiomaster as asked to default their radio with mute on (they are doing it on production lines, but if you wipe your sd, it default cxurrently to disabled)
=> feat: Default audio mute on for RM radios

radio/src/gui/128x64/lcd.cpp
Resolves #3836
Swaps the model name for timer1 if it is defined. I was tempted to make it so if no RTC, the timer is drawn where the time would be, but that will then create a "if this handset, looks like this, if that handset, looks like that" documentation/tutorial issue. 
Timer 1 defined
No timer 1 (i.e. like before, minus timer)
=> feat(128): Swap modelname for timer1 if defined

radio/src/gui/colorlcd/model_flightmodes.cpp
Fixes #3873 
Needs to be applied to 2.9 as well as 2.10.
=> fix(color): Fix switch selection when physical switch moved in Flight Mode edit page.

radio/src/gui/128x64/lcd.cpp, radio/src/gui/212x64/lcd.cpp
While @pfeerick was couting sheeps, request : https://github.com/EdgeTX/edgetx/pull/3856#issuecomment-1655569858
Handles remaining/elapsed display on BW telemetry screen topbar and move to HH:MM:SS format
=> fix: Add remaining/elapsed display on BW telem topbar

radio/src/targets/common/arm/stm32/sdio_sd.c
Reduce the number of retries of SD_MAX_VOLT_TRIAL to solve the problem that the card owner cannot enter the system during the boot process of TX16S.
=> Solve the problem that TX16S is stuck and unable to start

radio/src/pulses/afhds3.cpp, radio/src/pulses/afhds3_config.h
=> fix(AFHDS3): V0 ibus option and failsafe malfunction

radio/src/gui/colorlcd/input_mix_group.cpp, radio/src/gui/common/stdlcd/radio_version.cpp
Fix an issue reported by Radiomaster and introduced in #2748
This allow proper compilation with current arm compiler and also prevent the casting warning when compiled on 64bit platfrom.
Also the display of "0 Err" has been removed as it is quite misleading, but code is left in place in a hope that telemetryErrors is going to come back... one day :D
=> fix: unsuported %zu in arm compiler

radio/src/gui/colorlcd/view_text.cpp, radio/src/gui/colorlcd/view_text.h
Move checklist logic to sub-class.
Show model name instead of file name in title, show 'Preflight checks' in title2 for checklist. 
Handle long line wrapping of text.
Don't indent lines without checkbox.
Add 'RTN' button when done.
=> Some re-work of the color lcd checklist code.

radio/src/datastructs.h, radio/src/gui/colorlcd/layouts/topbar_impl.cpp, radio/src/gui/colorlcd/layouts/topbar_impl.h, radio/src/gui/colorlcd/preview_window.h, radio/src/gui/colorlcd/topbar.h, radio/src/gui/colorlcd/widgets/radio_info.cpp, radio/src/gui/colorlcd/widgets_container.h, radio/src/gui/colorlcd/widgets_setup.cpp, radio/src/storage/storage_common.cpp, radio/src/storage/yaml/yaml_datastructs_nv14.cpp, radio/src/storage/yaml/yaml_datastructs_x10.cpp, radio/src/storage/yaml/yaml_datastructs_x12s.cpp, radio/src/targets/horus/libopenui_config.h, radio/src/targets/nv14/libopenui_config.h
Change radio info (USB, volume, signal strength), date/time and internal GPS display from top bar into widgets.
The entire top bar (except EdgeTX icon on the left) is now just widgets.
There are 6 widget slots on landscape layout and 4 on portrait screens.
The rightmost widget is slightly smaller than the others however.
The widgets can be moved, or deleted as required by the user. The color of the date/time display can be changed.
The radio info, date/time and internal GPS widgets will be automatically loaded if the slots are empty when a model is loaded. If they are manually removed, they will not get reloaded.
I am thinking of adding layout styles for the top bar widgets like the main view - e.g. different number and size of widgets. Possibly a single widget the full size of the top …
=> feat(color): Convert top bar display in main view into widgets.

radio/src/telemetry/flysky_ibus.cpp
Fixes (partially) #3543 
Fixes #3583
=> fix: Some AFHDS2A/AFHDS3 GPS/ALT telemetry handling issues

radio/src/tasks/mixer_task.cpp
PR #3451 moved the start of the mixer task to a point in time where the task scheduler is already started (UI task). Before that change, the mixer task would be created *before* and effectively started *after* the task scheduler started.
This introduces a race condition on `mixerTaskId.rtos_handle`, as the mixer scheduler might trigger before `xTaskCreateStatic` returns and the task handle is assigned.
This PR fixes the issue by delaying the start of the mixer scheduler until `xTaskCreateStatic` returned and the task handler has been properly assigned.
=> fix: race condition on mixer task handle

radio/src/targets/common/arm/stm32/CMakeLists.txt, radio/src/targets/common/arm/stm32/ads79xx.cpp, radio/src/targets/common/arm/stm32/stm32_spi.cpp, radio/src/targets/common/arm/stm32/stm32_spi.h
#3790 removed `ADC_RCC`, so that peripheral clocks for ADC driver must now be initialised properly within the driver.
- initialise GPIO peripheral clock
- initialise SPI peripheral clock
=> fix(x12s): init periph clocks in ads79xx driver

radio/src/gui/colorlcd/model_setup.cpp, radio/src/gui/colorlcd/themes/etx_lv_theme.cpp, radio/src/thirdparty/libopenui/src/widgets/etx_obj_create.h
Makes the buttons on the model setup page consistent height (matches the radio setup -> Tools page buttons).
Cleanup the code.
=> chore(color): Model setup page cleanup

radio/src/bluetooth.cpp, radio/src/gui/212x64/view_main.cpp, radio/src/gui/colorlcd/radio_trainer.cpp, radio/src/gui/common/stdlcd/radio_trainer.cpp, radio/src/hal/trainer_driver.h, radio/src/mixer.cpp, radio/src/opentx.cpp, radio/src/sbus.cpp, radio/src/targets/common/arm/stm32/trainer_driver.cpp, radio/src/targets/simu/module_drivers.cpp, radio/src/targets/simu/opentxsimulator.cpp, radio/src/targets/taranis/board.cpp, radio/src/telemetry/multi.cpp, radio/src/tests/mixer.cpp, radio/src/trainer.cpp, radio/src/trainer.h
For some time already, the jack detection pin on Taranis platform has been left uninitialized (good catch @raphaelcoeffic). This did not have too much impact because another level of trainer signal detection is in place, but fixing makes sense anyway.
While at it, renamed misleading ppm instead of trainer.
The system as it is currently works ok on master, but does not make pertinent use of trainer detect pin. On slave side, there is nothing. maybe in case of wired trainer we could leverage that pin and let the slave know the trainer cable has been disconnected ?
=> fix: fix and clean trainer driver

radio/src/targets/taranis/hal.h
PCBREV detection for X7 was disabled as part of early 2.10 work. It leads to SPORT port not been  available on X7
Once enable, option is back, tested flashing a receiver ok
=> fix: PCBREV detect not working

companion/src/simulation/simulateduiwidgetJumperTPRO.cpp
Fix menu key not working in libsimu for T-Pro
=> fix: TPRO libsimu menu key

companion/src/mainwindow.cpp
Prevents pasting clipboard data from one profile to another possibly incompatible one which could result in corrupted models and settings
=> feat(cpn): Clear clipboard on profile change

radio/src/opentx.cpp
This revert a minor change part of #2994, which cause very bad EM when trying to power off the radio and a LUA script is running (a wizard for example).
At the time of writing, I have not been able to gather why the change was made in #2994, so it may introduce another issue I'm not aware off, but it does fix the EM issue (tested on TX16S and Zorro).
This fixes #3919
While 2.9 is timing wise the most critical, 2.10 needs it too
=> fix: EM when LUA script is running and radio is turned off

companion/src/simulation/simulateduiwidgetTX12.cpp, companion/src/simulation/simulateduiwidgetZorro.cpp
Fixes #2593
- remove duplicate  left and right arrow keys from roller
=> fix(cpn): TX12 MKII and Zorro sims key mapping

radio/src/sdcard.cpp
Following recent sdcard changes, simu could not be run (NoSD cards error)
=> fix: simu sd detection

companion/src/constants.h, companion/src/firmwares/boards.cpp, companion/src/firmwares/boards.h, companion/src/firmwares/datahelpers.cpp, companion/src/firmwares/datahelpers.h, companion/src/firmwares/edgetx/yaml_calibdata.cpp, companion/src/firmwares/edgetx/yaml_generalsettings.cpp, companion/src/firmwares/edgetx/yaml_modeldata.cpp, companion/src/firmwares/edgetx/yaml_ops.cpp, companion/src/firmwares/edgetx/yaml_ops.h, companion/src/firmwares/edgetx/yaml_switchconfig.cpp, companion/src/firmwares/edgetx/yaml_switchconfig.h, companion/src/firmwares/eeprominterface.h, companion/src/helpers.cpp, companion/src/helpers.h
Repeat of https://github.com/EdgeTX/edgetx/pull/3777 so that Github recognises it
Fixes #3758
- continue support for pre adc settings
- support adc settings remapping to pre adc sequences
- remap internal settings on encoding to adc format
- add version check for unsupported settings versions refer #3766
- fix pots and sliders refer #3731
- fix calibration
- fix pots and sliders config
- add global yaml radio and model settings versions variables to assist in data conversion
=> fix(cpn): radio settings yaml for adc refactor

radio/src/lua/api_model.cpp
When using telemetry as an input, the scale field is used to convert from a value with units (like volts or meters) to a percentage. I'd like to modify an input's scale via Lua script. However this field does not seem to be supported by the Lua API. This seems like an oversight, so I added it.
Modify model.getInput and model.insertInput API to add the "scale" field.
=> Include scale in getInput and insertInput

companion/src/datamodels/compounditemmodels.cpp, companion/src/firmwares/customfunctiondata.cpp, companion/src/firmwares/customfunctiondata.h, companion/src/firmwares/edgetx/yaml_rawsource.cpp, companion/src/firmwares/rawsource.cpp, companion/src/firmwares/timerdata.cpp, companion/src/firmwares/timerdata.h, companion/src/modeledit/setup.cpp, companion/src/modeledit/setup.h
Fixes #3952
- add mode filter to source lists
- trigger update to source lists and cross references when mode changed in model edit
- fix mode off test
- add mode filter to Set functions and Reset function parameter
- support new yaml format for timers
MERGE NOTE: partner for #3949
=> fix(cpn): only timers with active modes should be included in lists

companion/src/firmwares/customfunctiondata.cpp, companion/src/firmwares/rawsource.cpp
Fixes #3977
Bug in global functions when building lists containing timer related entries introduced by #3956
- test for existence of a model pointer in function parameters before calling model functions
=> fix(cpn): Edit radio settings application crash

radio/src/boards/generic_stm32/module_ports.cpp, radio/src/targets/common/arm/stm32/stm32_softserial_driver.cpp, radio/src/targets/common/arm/stm32/stm32_softserial_driver.h
Over the course of the previous months, a series of changes have been made to clean pulse generation. Part of it has broken external R9M (and likely XJT).
Bottom line is the software is trying to generate a 8µS/8µs pulse (and the MCU does it correctly), but after the inverters, you have basicaly 7µS/9µS, and the module does fail.
(red is MCU output pin, white is inverter out)
This introduces a compensation for the slow inverters. This has been successfully tested on TX16S and X7S. X10 Express does have (because of ACCESS support) fast inverters, so the compensation is not needed.
It needs to be noted that this also affect internal module PXX1 used by X7 and X9(D/D+/E), but they also have an inverter inside
=> fix: PXX1 external module timings

companion/src/firmwares/rawsource.cpp, companion/src/modeledit/mixes.cpp, companion/src/modeledit/mixes.h
Fixes #3958
- add active test to channels in source lists
- update shared dynamic data models when changes to mixes
Note: active test not applied to Override Channel functions as these bypass the mixes
=> feat(cpn): Only show active channels in source lists

radio/src/datastructs_private.h
Since the USB joystick doesn't get re-enabled on EM start there is no point having the joystick configuration in the backup data.
=> chore(radio): Don't save joystick configuration data to the EM backup storage

companion/src/updates/chooserdialog.cpp, companion/src/updates/chooserdialog.h, companion/src/updates/chooserdialog.ui, companion/src/updates/updateinterface.cpp, companion/src/updates/updateinterface.h, companion/src/updates/updatesounds.cpp, companion/src/updates/updatesounds.h, companion/src/updates/updatestatus.cpp
Fixes #3841
- refactor asset filtering to not use sounds.json file but instead filter the release assets
- only 1 pack can be downloaded per run as all language variants share the same destination directory
- supporting functions
- housekeeping
Due to a change to the asset filter a release note is required as only 1 zip file will be found for each language with the old filter:
Steps:
1. Launch Companion
2. Select Settings
3. Select Update Settings tab
4. Click Sounds component Options button
5. Edit the Filter pattern by DELETING the trailing hypen
6. Click OK to save the change
7. Click OK to exit the Settings
=> fix(cpn): selection of sound packs in update process

radio/src/storage/yaml/yaml_parser.cpp, radio/src/tests/yaml.cpp
Fixes #3760 
Better handling of blank lines in YAML files in the case where the blank line was at the start of the parse buffer after a newline ended the previous buffer.
=> fix(color): Fix handling of blank lines in YAML files.

radio/src/gui/212x64/radio_setup.cpp
fix issue #4039, compile error if X9D and USE_RTC_CLOCK=OFF
Added ifdefs to missing enums
=> fix: compile error if X9D and USE_RTC_CLOCK=OFF

radio/src/targets/horus/hal.h
=> fix: T18 has no power switch on AUX2

radio/src/telemetry/telemetry_sensors.cpp
Fixes #4070 
Save hash of string for text telemetry sensor so Value widget can detect updates.
=> fix(color): Detect changes to telemetry sensors that return strings

radio/src/storage/yaml/yaml_datastructs_funcs.cpp
Note: this probably does not affect `2.9`.
=> fix: use SWRC_NONE if switch cannot be found

radio/src/gui/colorlcd/popups.cpp, radio/src/gui/colorlcd/popups.h, radio/src/gui/colorlcd/themes/etx_lv_theme.cpp, radio/src/thirdparty/libopenui/src/mainwindow.cpp, radio/src/thirdparty/libopenui/src/widgets/etx_obj_create.h, radio/src/thirdparty/libopenui/src/window.h
As requested for the NV14/EL18 hat trims PR #3894 .
Initial styling is high contrast (black & white) with a thicker border.
Displays at the bottom of the screen, above all other windows, and closes automatically after a configurable timeout.
User can still interact with the other windows/controls.
=> feat(color): Add information bubble popup window.

radio/util/find_clang.py, radio/util/generate_yaml.py
This fixes an issue causing `generate_yaml.py` to bypass the `libclang` found automatically by the Python `clang` package.
=> fix: yaml generator for clang 15 and up

radio/src/usb_joystick.cpp
=> chore(radio): Use existing 'hash' function for detecting settings change in USB joystick

fw.json
Per https://github.com/EdgeTX/edgetx/issues/4002#issuecomment-1704986318 removing the option for T-Lite F4 since it will only confuse.
=> chore: Remove TLite F4 from Buddy

radio/src/pulses/ppm.cpp, radio/src/pulses/sbus.cpp
Fixes #3877 
- Enable S.PORT telemetry by default for SBUS and PPM modules.
=> feat: enable S.PORT telemetry by default for SBUS and PPM modules

radio/src/gui/colorlcd/special_functions.cpp
Fixes #4089 
Fix incorrect offset when populating the menu.
=> fix(color): Fix the popup menu entries when selecting the value for the Trainer special function.

radio/src/gui/colorlcd/view_about.cpp, radio/src/gui/colorlcd/view_about.h
Missed when converting the QR code to LVGL.
=> chore(color): Remove unused code from 'About EdgeTX' popup.

radio/src/gui/colorlcd/sourcechoice.cpp, radio/src/gui/colorlcd/switchchoice.cpp, radio/src/gui/colorlcd/themes/etx_lv_theme.cpp, radio/src/targets/horus/libopenui_config.h, radio/src/targets/nv14/libopenui_config.h, radio/src/thirdparty/libopenui/src/choice.cpp, radio/src/thirdparty/libopenui/src/menutoolbar.cpp, radio/src/thirdparty/libopenui/src/menutoolbar.h
- Fix missing GV filter in source select
- Ensure all available options are also included in one of the filters
- Add misc filter to switch select (for TELE and ACT options)
- Show inverted and no-selection options when a filter is selected
- Make menu line height consistent.
=> fix(color): Fixes for switch and source select popup menus.

radio/src/opentx.cpp
=> fix: invert TPro V2 default roller handling to match previous version

radio/src/bluetooth.cpp
For years I had trouble with bluetooth range and reliability on my modded TX16S with X10S module until I now finally discovered that EdgeTX sets the BT transmission power to -23dBm by default. This did not allow any connection with more than 2-3m range and even then it is unreliable with the slightest interference. I changed the power level to the CC2540/CC2541 default power level 2 (0dBm) and now I have perfect range and a reliable connection that goes through 2 rooms of my apartment. 
1mW power should not interfere with any RC link but might need testing. Maybe add a option to configure the power in the GUI.
=> Fix BT power level

radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp
=> fix: prevent enabling USART IRQ if not supported

radio/src/gui/colorlcd/radio_version.cpp
=> fix(color): Allow scrolling of the version info dialog popup with the rotary encoder wheel.
